### ISSUE TITLE
iBeacons flapping

### ISSUE THREAD

**Issue by wnagele** [owntracks/ios#102]
When using iBeacons I noticed that the current implementation is flapping a lot. It seems that if it misses a beacon for a short period it immediately sends a 'leave' event. I think for 'leave' events a hold-down timer would be good to have to avoid these. Otherwise you end up getting lots of 'enter' and 'leave' events in short order without actually having left the iBeacon area.

**Comment by ckrey** [comment]
When woken up b/c an `enter`or `leave`event, IOS gives the app only about 10 seconds to finalize it's work. We could only implement a hold down timer within such time frame. Do you think this would help?

**Comment by wnagele** [comment]
I couldn't say for sure without being able to test. The problem is that it only occurs when the app is in the background. To be able to test, a version with some logging of the gaps between beacon announcements would help to narrow down the problem.

**Comment by ckrey** [comment]
@wnagele if you share your apple-id with me via direct message, I could provide you with a test version

**Comment by ckrey** [comment]
enter leave events for beacons have already a meaningful timestamp for debugging (see below)
```
{"cog":-1,"lon":"6.x","acc":"65","vel":-1,"_type":"location","batt":"50","vac":10,"lat":"51.x","t":"u","tst":"1421688779","alt":40,"tid":"5c"} {"cog":-1,"lon":"6.x","acc":"200","vel":0,"_type":"location","batt":"51","vac":16,"lat":"51.x","t":"p","tst":"1421688888","alt":70,"tid":"5c"}
{"cog":-1,"lon":"6.x","acc":"65","vel":-1,"_type":"location","event":"leave","vac":10,"lat":"51.x","batt":"52","t":"b","tst":"1421689134","desc":"iBeacon1","alt":39,"tid":"5c"}
{"cog":-1,"lon":"6.x","acc":"65","vel":-1,"_type":"location","event":"leave","vac":10,"lat":"51.x","batt":"52","t":"b","tst":"1421689136","desc":"-iBeacon2","alt":39,"tid":"5c"}
{"cog":-1,"lon":"6.x","acc":"65","vel":-1,"_type":"location","event":"enter","vac":10,"lat":"51.x","batt":"52","t":"b","tst":"1421689145","desc":"-iBeacon2","alt":39,"tid":"5c"}
{"cog":-1,"lon":"6.x","acc":"65","vel":-1,"_type":"location","event":"enter","vac":10,"lat":"51.x","batt":"52","t":"b","tst":"1421689147","desc":"iBeacon1","alt":39,"tid":"5c"}```

**Comment by ckrey** [comment]
intermediate testing version holds `leave` events for 3 seconds if waypoint name starts with `-` (see example above). If iBeacon creates an `enter` event within the 3 seconds, no messages are published.

**Comment by wnagele** [comment]
It seems that this instability is not an issue anymore. Wondering if any changes were made in the latest OwnTracks app that might have helped? I haven'd used the testing version yet so it must be something in the main codebase or iOS has improved.

**Comment by ckrey** [comment]
Good to hear, I will keep the hold-down code in.

When I was testing iBeacons intensively earlier in 2014, I noticed the same phenomenon. Recent retests had the same results as you experienced.
My guess is that IOS 8.1.x added some holddown in iBeacon event processing. The app code did not change since.
