### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by bluewindthings** [owntracks/ios#104]
I have a suspect that timestamps are not correct, but can't determine the exact rationale. I'm building a very simple example, light that indicates someone leaving / approaching house.
As an example of a strange situation:
- I have an event this morning "Leave" (home) that was for sure originated at 7:45 (between 7:45 and 7:50 depending on GPS position update, walking away from home, radius 50mt)
- The message contains: "tst":"1418365802" which translates to 07:30:02 (earlier it seems...)
- The message reached the broker at 7:59:12 (recorded in our database and confirmed by the associated light switching off at that hour exactly).

App is wiped out (only events are being sent), iOS v. 8.1.2 on iPhone 5. Cellular tower is 200mt from home, field is very high. Again I often see events (as popups on iPhone) that accumulate and are shown as soon as connection changes between Wifi and Cellular (both directions) don't know if this is related somehow.
Hope this is helpful.

**Comment by bluewindthings** [comment]
Tested during several days with manual mode, backgrounded or swiped and behaves the same: no extra enter/leave anymore, lwt (disconnect while publishing) fairly often. Erroneous tst and other strange things are all related to leaving move mode while swiped, it seems.
Again: I'm not sure if this is interesting for other users, but I'd like to understand the reason for so many fails while publishing events from background, isn't this potentially a limitation of any iOS messaging app? When lwt is detected then only a new event will trigger sending also the pending ones.

**Comment by ckrey** [comment]
Will be fixed with 7.4
