### ISSUE TITLE
Update location while app terminated

### ISSUE THREAD

**Issue by kieranoshea** [owntracks/ios#105]
Both the Latitude (when it existed) and Google+ apps seem to continue to update location even when the app is terminated. Not knowing anything about how iOS works, I'm not sure why/how this happens, but I know it does because the app can be closed for weeks and I still see the location icon on the home screen and see the location history for that period in Google location history.

Is there a reason OwnTracks does not do this too? With the app terminated I do still see the location icon on the home screen visible permanently, but no updates to my MQTT server.

**Comment by jpmens** [comment]
OwnTracks does this on iOS unless you've swiped the app away. I.e. just press the home button to return to iOS launchpad leaves the app running in the background, where it will wake up periodically to publish location. This, however, happens only when the app is set to publish on _significant changes_ (play symbol on top) or in _move mode_ (which reports much more frequently, but also quickly drains battery -- best used in, say, car when connected to charger).

Are you quite sure the app isn't set to _manual_ which effectively disables publishes?

**Comment by kieranoshea** [comment]
It works fine if I just press the home button and keep the app in the background (I'm using significant changes). I was more wondering why other apps (Google) can still update when you've swiped away and OwnTracks doesn't

**Comment by jpmens** [comment]
Maybe @ckrey will help us to understand that. However, there's really [no reason](http://www.howtogeek.com/204552/no-closing-background-apps-on-your-iphone-or-ipad-wont-make-it-faster/)  to swipe [apps away](http://lifehacker.com/quitting-apps-in-ios-actually-worsens-battery-life-1560086834) :-)

**Comment by ckrey** [comment]
IOS re-launches the app after being terminated (swiped out) when
a) in `significant changes mode` and a move of more than 500m happens

IOS re-starts the app after being backgrounded when
a) same as above
b) after 500-1000 seconds and battery level is > 20% when not in `manual mode`

In `move mode` the app stops reporting changes when backgrounded except b).

In the case of a) or b) the active time of the app is limited by IOS. This means depending on the connection quality, some messages might not be published or received and acknowlegded during this period. The app and the MQTT broker make sure that all messages are transferred according to the QoS level, but do not guarantee immediate transmission.
