### ISSUE TITLE
Enter/leave without desc

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#106]
I'm seeing the following event:

```
{
  "tid": "I6",
  "_type": "location",
  "alt": 2175,
  "tst": "1420815620",
  "t": "c",
  "cog": -1,
  "batt": "74",
  "lon": "xx",
  "acc": "5005",
  "vel": -1,
  "event": "enter",
  "vac": 23,
  "lat": "yy"
}
```

It doesn't contain a `desc`ription, so I had assumed it was a non-shared waypoint. [Our documentation](https://github.com/owntracks/owntracks/wiki/Waypoints) says:

> For waypoints with disabled sharing, no waypoint message is published. These can be used to note down locations privately. But note that entering or leaving a waypoint will be published as a location message as described above.

I interpret that as meaning: if it isn't shared, a simple location (i.e. *without* `event`) will be published.

So, the question is: is our documentation unclear or has this user really been able to create a shared waypoint with a null description (which I cannot reproduce)?

**Comment by ckrey** [comment]
There are 2 kinds of locations:
a) an `automatic location` created when IOS detects a change of location
b) a `manual location` created by the user

A `manual location` has with a non-zero length remark (description) is a `waypoint`.

If a `waypoint` is `shared`, its attributes are published when created or changed.

If a `waypoint` specifies a radius, a `circular region` is monitored for `enter/leave events`.

If a `waypoint` is not a `circular region` and the `waypoint`'s description contains a valid `iBeacon` specification, a `beacon region` is monitored for `enter/leave events`.

If an `enter/leave event` occurs an event message is published with the `type` attribute set to `c`or `b`for (`circular region`or `beacon region`). The message contains an `event`attribute specifying either `enter`or `leave`.

If the `waypoint`is `shared`, the description of the `waypoint`is added to the published `event`message.

Automatic | Description | iBeacon | Radius | Shared | Event Message | /w Description | Waypoint Message | 
---|---|---|---|---|---|---|---|---|
Y | n/a |  n/a |  n/a |  n/a | N | N | N |
N | N   | n/a |   n/a |  n/a | N | N | N |
N | Y | N | N | N | N | N | N |
N | Y | N | N | Y | N | N | Y |
N | Y | N | Y | N | `c` | N | N |
N | Y | N | Y | Y | `c` | Y | Y |
N | Y | Y | N | N | `b` | N | N |
N | Y | Y | N | Y | `b` | Y | Y |
N | Y | Y | Y | N | `c` | N | N |
N | Y | Y | Y | Y | `c` | Y | Y |

**Comment by jpmens** [comment]
Thanks for the clarification. Copied your description to [the documentation on Wiki](https://github.com/owntracks/owntracks/wiki/Location).
