### ISSUE TITLE
Not buffering GEO Data when no connection to Network

### ISSUE THREAD

**Issue by edgarjung** [owntracks/ios#110]
Yesterday I started in switzerland, tracking on IPHONE 4. While within der primaray Gridoperator (swisscom), OWNTRACKS sends "SIGNIFICANT CHANGES" to mqtt SERVER. When changing borders to (mobile Austria or German telekom - Dataroaming is set off), OWNTRACKS started reporting 5 undelivered Messages up to 40 Messages.

I came back to swisscom, hoping OWNTRACKS is now sending all buffered Locations (in germany or austria). But owntracks shows nothing more to deliver the mqtt Server received nothing. So I assume, OWTRACKS withdraws all buffered locations.

**Comment by jpmens** [comment]
Generally speaking, OwnTracks for iOS buffers updates it cannot deliver (which you confirm by saying it reported up to 40 undelivered messages). As soon as it can contact the MQTT broker it will typically publish these, and this is quite reliable.

What would be important is: what kind of broker are you using? Is this something private, is it a public broker, how is it configured, etc. When using Mosquitto for example, care must be taken to increase the inflight message buffers; set too low can cause Mosquitto to drop incoming (or outgoing) messages.

For the record: I've updated your comment above to _remove_ the credentials you displayed; this tracker is public and we wouldn't want anybody to abuse your service now, would we? ;-)

**Comment by ckrey** [comment]
In fact, you are both right.

OwnTracks for IOS does queue messages when not connected and starts transmitting as soon as the connection is established again. But:

It keeps track of unsent messages in volatile memory. This means if the app is terminated (swiped out) or cancelled by IOS, the remaining messages in the queue will be lost. In both cases, you will see a `App terminated. Tap to restart` notification.

@edgarjung I will take your issue as an enhancement request to make OwnTracks useful as long term tracking device too.

We had other inquiries e.g. to cover hiking trips in remote areas too

**Comment by edgarjung** [comment]
I am using mosquitto with 2 extra settings only:

max_inflight_messages 150
max_queued_messages 250

thank you for removing the credientials – they has been temporary only -

Von: JP Mens [mailto:notifications@github.com]
Gesendet: Samstag, 7. Februar 2015 14:13
An: owntracks/ios
Cc: Edgar Jung
Betreff: Re: [ios] Not buffering GEO Data when no connection to Network (#110)


Generally speaking, OwnTracks for iOS buffers updates it cannot deliver (which you confirm by saying it reported up to 40 undelivered messages). As soon as it can contact the MQTT broker it will typically publish these, and this is quite reliable.

What would be important is: what kind of broker are you using? Is this something private, is it a public broker, how is it configured, etc. When using Mosquitto for example, care must be taken to increase the inflight message buffers; set too low can cause Mosquitto to drop incoming (or outgoing) messages.

For the record: I've updated your comment above to remove the credentials you displayed; this tracker is public and we wouldn't want anybody to abuse your service now, would we? ;-)

**Comment by jpmens** [comment]
I think we've noticed (if we're asking the right machine :) that you're using a very old version of Mosquitto:

```
$SYS/broker/version mosquitto version 1.2.3
```

I would like to strongly recommend that you upgrade. Currently 1.3.4 (or .5) is the released version; quite a number of stability issues were solved in that. (An upgrade ought to be quite simple for you: mosquitto.org has links to pre-built packages for a number of OS versions.)

**Comment by edgarjung** [comment]
Yes, I’am using mosquitto version 1.2.3 due to centOS 6. I used the automatic yum update process. I think, I have to update to CentOS 7 before I am able to autoupdate to higher mosquito  version

Von: JP Mens [mailto:notifications@github.com]
Gesendet: Samstag, 7. Februar 2015 17:26
An: owntracks/ios
Cc: Edgar Jung
Betreff: Re: [ios] Not buffering GEO Data when no connection to Network (#110)


I think we've noticed (if we're asking the right machine :) that you're using a very old version of Mosquitto:

$SYS/broker/version mosquitto version 1.2.3

I would like to strongly recommend that you upgrade. Currently 1.3.4 (or .5) is the released version; quite a number of stability issues were solved in that. (An upgrade ought to be quite simple for you: mosquitto.org has links to pre-built packages for a number of OS versions.)

**Comment by jpmens** [comment]
Not at all: you can install the repo configuration [from here](http://mosquitto.org/download/), then run `yum update mosquitto`. Should work like a charm, and those packages are built by the Mosquitto project so they work.

**Comment by edgarjung** [comment]
Thanks,
I used this installation inststructions for centOS 6 (you sent), which automatically installed mosquito 1.2.3 and not 1.3.4 – I think this depends on cent version

Von: JP Mens [mailto:notifications@github.com]
Gesendet: Samstag, 7. Februar 2015 17:55
An: owntracks/ios
Cc: Edgar Jung
Betreff: Re: [ios] Not buffering GEO Data when no connection to Network (#110)


Not at all: you can install the repo configuration from here<http://mosquitto.org/download/>, then run yum update mosquitto. Should work like a charm, and those packages are built by the Mosquitto project so they work.

**Comment by jpmens** [comment]
You're not using that repository, Edgar.

It definitely contains Mosquitto version 1.3.5, as you can see [http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-6/x86_64/](http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-6/x86_64/)

**Comment by edgarjung** [comment]
Thank you. There was an error in my yum config. Now it worked. Will keep on testing…

Von: JP Mens [mailto:notifications@github.com]
Gesendet: Sonntag, 8. Februar 2015 08:54
An: owntracks/ios
Cc: Edgar Jung
Betreff: Re: [ios] Not buffering GEO Data when no connection to Network (#110)


You're not using that repository, Edgar.

It definitely contains Mosquitto version 1.3.5, as you can see http://download.opensuse.org/repositories/home:/oojah:/mqtt/CentOS_CentOS-6/x86_64/

**Comment by ckrey** [comment]
IOS app working so much better now!!! No duplicates anymore, no lost messages when restarted.

Anybody likes to participate in beta-test?
Let me know your Apple-ID (for Testflight) if I don't have it already.

**Comment by edgarjung** [comment]
Yes please.
U should have my ID

Von: Christoph Krey [mailto:notifications@github.com]
Gesendet: Dienstag, 10. Februar 2015 12:04
An: owntracks/ios
Cc: Edgar Jung
Betreff: Re: [ios] Not buffering GEO Data when no connection to Network (#110)


IOS app working so much better now!!! No duplicates anymore, no lost messages when restarted.

Anybody likes to participate in beta-test?
Let me know your Apple-ID (for Testflight) if I don't have it already.

**Comment by bluewindthings** [comment]
On 10/02/2015 12:03, Christoph Krey wrote:
> IOS app working so much better now!!! No duplicates anymore, no lost
> messages when restarted.
>
> Anybody likes to participate in beta-test?
> Let me know your Apple-ID (for Testflight) if I don't have it already.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owntracks/ios/issues/110#issuecomment-73681782>.
>


mine still working I guess? Already upgraded to latest beta?

-- 
   Stefano Costa, Managing Director R&D

   M +39 335 6565749
   Skype stefanocosta.bluewind
   Twitter @stefanobluewind
   http://www.bluewind.it

**Comment by heziegl** [comment]
@edgarjung I would be interested in beta testing. How can I send you my AppleID?

**Comment by ckrey** [comment]
@heziegl send it to me via mail
<krey.christoph@gmail.com> BA7E 0B5B 965C A5C3 FC4F  83E6 21D0 C720 631F 0F77

**Comment by ckrey** [comment]
Implemented, will be in 7.4

**Comment by ckrey** [comment]
A few days of skiing: Capturing off-line, unload in the evening via WiFi (visualisation by pista):
![bildschirmfoto 2015-03-12 um 18 08 24](https://cloud.githubusercontent.com/assets/4027289/6623501/a72c6e3a-c8e3-11e4-8285-3a011b815fcc.png)

**Comment by jpmens** [comment]
Nice!

**Comment by matbor** [comment]
@ckrey Good work, roughly how much cached msg's will it keep? I think you haven't got me in the beta test anymore, will send you an email.

**Comment by ckrey** [comment]
The cache is unmlimited (stored in sqlite). As soon as MQTT signals message delivered in QoS 1 and 2, the cache is cleared. The # of items in the cache is displayed on the map screen.

**Comment by jpmens** [comment]
Unlimited being 128GB (iPhone 6) minus apps, minus music, minus videos, minus photos, minus OS, minus a bit. ;-) (Sorry: I couldn't resist. :-)

**Comment by edgarjung** [comment]
Will update be available for IOS 7.X – sorry do have IPHONE 4.. current update shows 7.3.8.

Von: JP Mens [mailto:notifications@github.com]
Gesendet: Freitag, 13. März 2015 10:10
An: owntracks/ios
Cc: Edgar Jung
Betreff: Re: [ios] Not buffering GEO Data when no connection to Network (#110)


Unlimited being 128GB (iPhone 6) minus apps, minus music, minus videos, minus photos, minus OS, minus a bit. ;-) (Sorry: I couldn't resist. :-)

**Comment by ckrey** [comment]
yes, the upcoming update will run even on iPhone 3GS and IOS 6.1
