### ISSUE TITLE
Slow pan/zoom

### ISSUE THREAD

**Issue by bluewindthings** [owntracks/ios#111]
After startup for a few seconds (10-60) panning ang zooming the map is too slow, if not impossible. This usually recovers after seconds, or stays forever.
The same does not apply to OwntracksCTRL, always smooth.
Seems related to app sending events waiting in queue.

**Comment by ckrey** [comment]
You are correct:

OwnTracks was not designed to cope with a large number of incoming messages. This causes the display to "freeze" at startup if a large number of messages is published by the broker.

OwnTracks subscribes with CleanSession=NO and QoS=1 by default. The reason for this is not to miss any enter/leave events sent by friends.

On the other hand if you have a number of devices sending frequent position updates this causes the observed behavior.

If you do not mind missing enter/leave events, you may change CleanSession to YES for the subscrption.

---

For Greenwich/OwntracksCTRL the app does
a) subscribes to position updates with CleanSession=YES and 
b) processes incoming messages in a separate thread

I will consider to change OwnTracks to b) too

**Comment by bluewindthings** [comment]
On 25/02/2015 11:08, Christoph Krey wrote:
>
> On the other hand if you have a number of devices sending frequent
> position updates this causes the observed behavior.

The topic tree I OwnTracks is configured to subscribe to contains 20 
persistent messages from a couple of devices and I suppose these are the 
messages that OwnTracks is slow to process at startup. Then the traffic 
is very limited (ten messages sent by a greenwich every a few minutes or 
so). Do you think this can be the reason?


> If you do not mind missing enter/leave events, you may change
> CleanSession to YES for the subscrption.

Already CleanSession=YES, if I switch to NO seems to slow down even more

**Comment by bluewindthings** [comment]
This seems solved with 7.4.2 but see #117

**Comment by ckrey** [comment]
With 8.0.6, processing of incoming messages is happening in separate background thread. 
Response is much better now but if high volume of queued messages are processed still visible.
