### ISSUE TITLE
Slow updates

### ISSUE THREAD

**Issue by mabnz** [owntracks/ios#112]
Hi,

Are there any tips to having the iOS app update more frequently than once a day? My wife's phone only seems to update in the morning each day, nothing more. 

It feels as though the app doesn't want to update in the background.

Mike.

**Comment by jpmens** [comment]
Please show us the settings configured for OwnTracks on that device, and tell us which version device/iOS/OwnTracks you're running.

There are no known issues with iOS not sending updates, in particular when the device moves significantly. We'll need more information to help you.

**Comment by ckrey** [comment]
Location monitoring works different in IOS than on Android. Please refer to our wiki https://github.com/owntracks/owntracks/wiki/Location

In your special case described in owntracks/android#86 setting `iOS 7.0. Location distance/time set to 25m/2 minutes respectively.`does not trigger background reporting. Please set the mode to `SIGNIFICANT LOCATION CHANGE`

**Comment by ckrey** [comment]
@mabnz did it help to switch to `SIGNIFICANT LOCATION CHANGE`?

**Comment by bluewindthings** [comment]
Maybe this is related to the problems I observe for the application to connect and send updates while in background? I recently reached as many as 100 messages not delivered in days, when the app resumes they start flowing again.

**Comment by mabnz** [comment]
Yes,  well sort of. Once I understood the difference between significant changes and move mode I settled on move mode and it's working well. Much better than significant changes. 
Mike.

----- Reply message -----
