### ISSUE TITLE
Enhancement -> Future: Notification Center widget. 

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#113]
I was playing with an app called 'today steps' and it has an excellent 'Notification Center widget' and I was thinking that owntracks for iOS could have something similar. 

Whereby it lists the friends you follow and next to that it displays the following information.
(You would tap to change between each item.)

* suburb/town/city
* distance from you
* last updated

Just an idea, which would require a bit of coding, but something for the future versions.

**Comment by ckrey** [comment]
You mean to put this here?:
![ios simulator screen shot 07 03 2015 11 52 00](https://cloud.githubusercontent.com/assets/4027289/6541118/74dbdcd0-c4c0-11e4-932d-69507ea832eb.png)

**Comment by matbor** [comment]
Forgot to mention that part, you would need to favourite the ones that you want to see in the list first. Obviously you wouldn't want to see everything.

**Comment by jpmens** [comment]
I agree that you'd need to favorite the friends you want to see to avoid clutter. Last update could be HH:MM with an indicator whether recent (i.e today) or older to save space (no full date required).

**Comment by matbor** [comment]
Maybe put the time if it is the same day that it was last updated and if it
is more than a day just start counting the days.

ie.

For same day;
15:34

If no contact for more than a day;
+2 days (or +2d)

And to favourite a contact within each contact would you just use the
'heart' symbol like the camera roll uses? Or a 'star' like Dropbox.

**Comment by ckrey** [comment]
Anyone wants to sponsor an AppleWatch for testing? ;-)

**Comment by matbor** [comment]
Everyone chip in for the gold version?

**Comment by ckrey** [comment]
Getting there:

![bildschirmfoto 2015-03-17 um 13 41 06](https://cloud.githubusercontent.com/assets/4027289/6687441/5b53f840-ccab-11e4-8c66-fd104e0d918c.png)

**Comment by jpmens** [comment]
Gorgeous!

**Comment by jpmens** [comment]
If you need space, you could use `tid` instead of full name ...

**Comment by ckrey** [comment]
And here comes your AppleWatch:
![bildschirmfoto 2015-03-17 um 21 58 06](https://cloud.githubusercontent.com/assets/4027289/6697423/b619515e-ccf0-11e4-827d-cb0ef8865847.png)

**Comment by matbor** [comment]
Looking good.

Suggestion, display just the time last updated first and then if you tap it
display the distance and then another tap will display the
suburb/town/country (or vice versa).  Makes it cleaner.

**Comment by ckrey** [comment]
Now it looks exactly as you wished. Get the next test version in Testflight soon

**Comment by ckrey** [comment]
postponed until after the solution to urgent problems

**Comment by matbor** [comment]
Good work, No hurry.

**Comment by matbor** [comment]
@ckrey notification widget looks awesome, maybe lose the lines in between friends ? Will look similar to other widgets then.

**Comment by jpmens** [comment]
The notification widget is gorgeous, yes, and I don't think I'd change anything on it -- it's optically beautiful.

Matt: have you tapped on one of the friends? Tap once and you get last PUB times. Tap again, and you get addresses of location of last PUB. Tap again, and you're back where you started.

Once again: gorgeous, @ckrey! Now, about that Apple Watch ... ;-)

**Comment by matbor** [comment]
@jpmens yep, works nicely.

Just having a few problems with the addressbook atm. Strange owntracks has me listed twice, but I can only see me once in the actual ios addressbooks.

**Comment by stefanoco** [comment]
Sounds really awsome @ckrey!!! How do I select friends for whom to get notifications?

**Comment by jpmens** [comment]
You currently cannot. The first 4 listed will be shown. (And: this will remain like this for a bit, as we're working on a lot of stuff at this moment. :-)

**Comment by stefanoco** [comment]
Aha ok I understand. I'm not getting notifications at the moment, what should I check first? I have Notification Center enabled for OwnTracks, one friend sending waypoints every 20s correctly shown on map.
BTW I think this makes OwnTracks really one step forward for many users! Could think of so many use modes.

**Comment by jpmens** [comment]
Not notifications. It's a swipe-down thing from the home screen which you have to add first (I assume you're running 8.0.4?) Sipe down, show "Today" view, at bottom is "Edit". Add Owntracks.

**Comment by stefanoco** [comment]
Now I see, didn't know about this. OwnTracks (8.0.4) is not an option in the "Edit" menu should I also upgrade iOS to 8.2 (currently 8.1.3)?

**Comment by jpmens** [comment]
Today Widgets are in iOS > 8.0.0 iirc.
Look around a bit

**Comment by ckrey** [comment]
I think 8.1.3 should support this:
![ios simulator screen shot 05 04 2015 17 18 03](https://cloud.githubusercontent.com/assets/4027289/6997358/d3be0912-dbb8-11e4-8fd3-9bfabd2d8379.png)
![ios simulator screen shot 05 04 2015 17 17 56](https://cloud.githubusercontent.com/assets/4027289/6997359/d6569784-dbb8-11e4-9cad-a7aacce81efd.png)

**Comment by ckrey** [comment]
Currently the widget for today will display up to 4 friends. The friends to be shown are the ones which are linked to your address book.

**Comment by ckrey** [comment]
Implented forward/backward scrolling
![bildschirmfoto 2015-04-05 um 18 09 42](https://cloud.githubusercontent.com/assets/4027289/6997540/065d2898-dbbf-11e4-9f95-01ed3633fab0.png)

**Comment by stefanoco** [comment]
It does not show as an option in the "do not include" list, I'm upgrading to 8.2 and check again

**Comment by stefanoco** [comment]
Done iOS 8.2 - works now! Great job @ckrey.

I realized too late that a restart of the iPhone could have been also a solution, didn't restart since last upgrade of OwnTracks.

**Comment by jpmens** [comment]
A restart would not have been required. This must have been some other quirk, maybe OS version. Anyway, good that it works for you.

**Comment by stefanoco** [comment]
I'm finding this feature really amazing. Example: add your home location as a "friend" with a single retained mqtt msg and you will have your distance from home constantly updated with a swipe down.

**Comment by matbor** [comment]
Good idea.

**Comment by ckrey** [comment]
Wait for 8.0.6:
![bildschirmfoto 2015-04-08 um 11 27 11](https://cloud.githubusercontent.com/assets/4027289/7042528/d4fd1648-dde2-11e4-973c-29ca24c15335.png)
And Watch:
![bildschirmfoto 2015-04-08 um 11 28 33](https://cloud.githubusercontent.com/assets/4027289/7042536/e41e72de-dde2-11e4-899e-87d24fb60745.png)
