### ISSUE TITLE
OwnTracks stops when crossing borders?

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#114]
Stopping does not mean transmitting (due to not roaming data plan), but stop recording locations? Need to investigate further...
![bildschirmfoto 2015-03-13 um 18 20 47](https://cloud.githubusercontent.com/assets/4027289/6643600/bdc02bf8-c9ad-11e4-8603-0c58531cce81.png)

**Comment by ckrey** [comment]
Not related to crossing borders:


![img_3329x](https://cloud.githubusercontent.com/assets/4027289/6664858/a6e28d86-cbd3-11e4-8a6b-7d8adffad42b.png)

**Comment by ckrey** [comment]
Happened again when travelling from Germany via the Netherlands to Belgium, but not on the return!?

**Comment by ckrey** [comment]
This might well be related to ckrey/MQTT-Client-Framework#41.
Updated to fixed version in 8.2.9

**Comment by jpmens** [comment]
So I'll have to re-do the 3000 km tour I just did?!? :-)

**Comment by ckrey** [comment]
Testing is hard :wink:

**Comment by ckrey** [comment]
It stopped b/c locations services were not correctly restarted after crash/restart of the app
