### ISSUE TITLE
trying to open address book crashes app

### ISSUE THREAD

**Issue by brunkj** [owntracks/ios#115]
I am running owntracks 7.4.2

ios 8.1.3
iphone 5

My default addressbook is my gmail address book.  I have 4 accounts on my phone that have address books associated.

When i go into own tracks and go to any of my friends and try to assign them to a contact, it crashes the app.  I have no problem opening the app again, but it never opens the address book.  I have tried to reset privacy permissions but it still crashes.

**Comment by jpmens** [comment]
If `Update Addressbook` is on in your app settings, would you please switch it off, relaunch the app and try again?

**Comment by brunkj** [comment]
Turned off update address book.  terminated the app.  restarted it.  confirmed setting off.  went to the friends tab and tried to click the addressbook and it crashed again.  

Is there a debug log or anything i can pull for you?

**Comment by ckrey** [comment]
After you connect the iPhone to iTunes, you find the crash logs in
OSX (Mac): /Library/Logs/CrashReporter/MobileDevice/<devicename>/
Windows: C:\Users\<username>\AppData\Roaming\Apple computer\Logs\CrashReporter\MobileDevice\<devicename>
Please pick the most recent one

**Comment by brunkj** [comment]
strange.  i do not have any owntracks crashlogs from today even though i have watched it exit a dozen times.

**Comment by ckrey** [comment]
Which kind of other address books do you have?

**Comment by brunkj** [comment]
i have a gmail, an owncloud and an exchange

**Comment by ckrey** [comment]
@brunkj in the next major version, we will include a crash logger. I hope this will give us some hints

**Comment by brunkj** [comment]
That's great news!  Is there an eta for that release?

**Comment by ckrey** [comment]
@brunkj if you share your email address with me (krey.christoph@gmail.com) I will invite you as a beta tetster

**Comment by ckrey** [comment]
@brunkj thanks for testing. I see the new version still crashes when using the address book. The good thing is: we now have a crash dump to analyze

**Comment by ckrey** [comment]
crash recorded in #202

**Comment by brunkj** [comment]
haha, glad you are looking out :)

Jason

**Comment by ckrey** [comment]
Thanks, I found the problem. I used a method which interprets a leading `@` in the name of a person in a special way which causes the crash.

Will fix in the next version.

If you have only very few persons with leading `@` in their names, you may change the names until the bug fix version becomes available.

**Comment by brunkj** [comment]
oh wow thats awesome.  i will check my address book now, i can't imagine
its many.  Nice job!
