### ISSUE TITLE
Not sending events after upgrade

### ISSUE THREAD

**Issue by bluewindthings** [owntracks/ios#117]
After upgrade to 7.4.2 (on iOS 8.1.3) not sending enter and leave events any more (and no iOS notification). Trying with existing waypoints, restored from a file, created again. Should delete all waypoints and create again? Wait doing this in case developer needs more details.

**Comment by bluewindthings** [comment]
Sorry 7.4.3 actually

**Comment by ckrey** [comment]
Similar issue reported by Marianne
![bildschirmfoto 2015-03-20 um 10 29 22](https://cloud.githubusercontent.com/assets/4027289/6748988/1a6173c4-ceec-11e4-8915-3972595e1ac4.png)

**Comment by bluewindthings** [comment]
News:  today one of the waypoints started reporting events. Is the one I added on 18/3 (h22:00) and didn't work until an hour ago. It's my home so stressed frequent... I have four more waypoints from previous installation, not working. I'll add another now ("Work") and see.

**Comment by bluewindthings** [comment]
...stopped sending Events again. Just tell me in case you need any details.

**Comment by sysadmama** [comment]
With the previous version I also got no events. In move mode I got two "enter" events yesterday, but no "leaves" (poor OpenHAB ;) ). But it's not reliable, and anyway - I don't want to stay in "movement mode" all time.

**Comment by jpmens** [comment]
Please note we've discovered a bug which was introduced a while ago and still exists in 7.5: waypoints are not handled unless the app is restarted and kept on the Map. Alternatively edit a waypoint, go back to the friends list (*but not back to the map*) and hit Home. That should re-activate said waypoint and enter/leave events then work.

A fix is in progres.

**Comment by bluewindthings** [comment]
On 23/03/2015 15:15, JP Mens wrote:
> Please note we've discovered a bug which was introduced a while ago and
> still exists in 7.5: waypoints are not handled unless the app is
> restarted and kept on the Map. Alternatively edit a waypoint, go back to
> the friends list (/but not back to the map/) and hit Home. That should
> re-activate said waypoint and enter/leave events then work.
>

Ok thanks I'll try this in a few hours

**Comment by jpmens** [comment]
(confirmed working by Stefano)
