### ISSUE TITLE
Add "Request refresh"

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#121]
as discussed during coffee

**Comment by ckrey** [comment]
The new feature will become available with the next major release (probably 8.0).

A request request is queued to the friend's device. The actual update may be visible almost immediately or will happen later when your friend's device receives and responds to your request.

There are two ways to initiate the `reportLocation` command to a friend's device: 

1: Navigate to your friend's location screen and pull down the table view cells. A refresh indicator will show until the request is sent out.

![ios simulator screen shot 25 03 2015 06 24 37](https://cloud.githubusercontent.com/assets/4027289/6818953/7d2bad46-d2b9-11e4-85e5-58f930edcec7.png)

2: Select your friend's marker on the map screen. A refresh button is shown on the left hand side of the callout.
![ios simulator screen shot 25 03 2015 06 25 10](https://cloud.githubusercontent.com/assets/4027289/6818965/d3c5da46-d2b9-11e4-8b03-8aa9a4045744.png)

**Comment by jpmens** [comment]
That looks excellent!

**Comment by matbor** [comment]
Awesome, have been waiting for the pull down refresh #Num: #68
