### ISSUE TITLE
Crash when clicking '+' icon (top right) when viewing an existing waypoint

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/ios#128]
Click the (i) icon for an existing waypoint, to view details, and then click the '+' in the top right. Crashes every time on my wifes 4S with iOS 8.

**Comment by jpmens** [comment]
No crash on 5S with iOS 8.2

**Comment by jpmens** [comment]
No crash on 4S with iOS 7.1.2

**Comment by ckrey** [comment]
No crash on 5C with iOS 8.2.
I found some concurrency issues which will be solved in OwnTracks 8.0. The crash might be related.

**Comment by sumnerboy12** [comment]
No crash on iPad 2 w/ iOS 8.2 (running 8.0.4 via TestFlight)

**Comment by ckrey** [comment]
will track in #107
