### ISSUE TITLE
CoreData.m line 92

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#131]
#### in +[CoreData saveContext]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5525aeb35141dcfd8f62c685](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5525aeb35141dcfd8f62c685)

**Comment by ckrey** [comment]
will track in #107
