### ISSUE TITLE
Leading `/` is dropped from remote cmd publish topic

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/ios#143]
I use the un-orthodox topic structure of (i.e. no device name);

`/owntracks/user1`
`/owntracks/user2`

I have the apps setup to pub locations to these topics on each device, and have them configured to subscribe to `/owntracks/+' for receiving messages. This works fine for location pubs and each device can see the others no problem.

When user1 hits the refresh option for themself I see a pub on `/owntracks/user1/cmd` as expected. However if I try for user2 (from the app on user1) I see a pub on `owntracks/user2/cmd`. I.e. missing the leading slash.

**Comment by ckrey** [comment]
Found the bug:
leading `/`was dropped for incoming messages from topic
