### ISSUE TITLE
UI unclear (Check/Mode)

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#145]
![zz7e6aeb4f](https://cloud.githubusercontent.com/assets/4027289/7219494/ab1c94d8-e6a3-11e4-8f8c-627d62d3433b.jpg)

**Comment by ckrey** [comment]
So much clearer - thanks guys:

![bildschirmfoto 2015-04-19 um 14 53 45](https://cloud.githubusercontent.com/assets/4027289/7219497/ec146dc6-e6a3-11e4-91a0-5d15096d4ced.png)

**Comment by jpmens** [comment]
Much clearer!
