### ISSUE TITLE
PUB on switching modes / changing TID?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#148]
When switching modes from _public_ to _hosted_, and maybe when changing _TID_, would it be good to immediately publish current location even though mode switch is a pretty stupid thing to do?

I'm thinking along the lines of somebody trying that and complaining that the marker isn't updated with TID on it. Same goes for changing TID in public and hosted mode: the map is updated on next publish only which could be a disappointing experience.

**Comment by ckrey** [comment]
Done. When reconnecting (switching modes or manually), a `publish now`is initiated.
