### ISSUE TITLE
Add a waypoint by dropping a pin, enhancement. 

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#155]
Navigate to a point on the map and then drop a pin and create a waypoint. Pin can also be moved this way if needed.

**Comment by ckrey** [comment]
Implemented:
* Set a new waypoint by navigating the a point on the map (center) and press* long on the map.
* Waypoints can be dragged

**Comment by ckrey** [comment]
long press on map with 3 fingers will publish the current location immediately
