### ISSUE TITLE
New auth settings not picked up by auto-reconnect

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/ios#157]
If I enter bad auth settings in Hosted mode the app will fail to connect (as expected). The app will keep attempting to connect, and keep failing.

If I then enter good auth settings, the re-connect attempts continue, and continue failing. This can be a little confusing as the auth settings are now correct but the app is obviously still using the old settings.

Manually hitting `Check` forces a reconnect attempt using the new settings and everything is fine.

As soon as any of the auth settings are changed, any subsequent connection attempts should use these new settings without requiring a manual `Check`.

**Comment by ckrey** [comment]
I understand what you are aying. But I would like to avoid trying to connect after every keystroke

**Comment by sumnerboy12** [comment]
Fair enough - what about just updating the connection settings on each key stroke? Then leaving the re-connect logic as is?

**Comment by ckrey** [comment]
Connection is reconnected when closing keyboard
