### ISSUE TITLE
DDTTYLogger.m line 1266

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#162]
#### in -[DDTTYLogger logMessage:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/553e5cc75141dcfd8f98562c](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/553e5cc75141dcfd8f98562c)

**Comment by ckrey** [comment]
During development testing
