### ISSUE TITLE
Publish Now via 3-finger long tap publishes twice

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#168]

**Comment by matbor** [comment]
I am noticing that as well, sometimes even more than 2, maybe some dialog
box needs pop up to tell you once it has published.

**Comment by jpmens** [comment]
Is 3-finger long tap supposed to work on iPhone? I've been tapping in all directions I can think of, short, long, whatever: no PUB. 

What I did notice was a total freeze of the app for several seconds; tab switching (map, friends, settings) not possible during that time. I seem to be able to reproduce this. (8.0.18)

**Comment by ckrey** [comment]
@jpmens iPhone issue now in #174 
@jpmens freeze issue now in #175 

double publish fixed
