### ISSUE TITLE
Events not publishing description. 8.0.18

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#170]
waypoints in config file (lat/lon blanked out by me);
```
"waypoints" : [
    {
      "_type" : "waypoint",
      "tst" : 1430275774,
      "lat" : xxx,
      "lon" : xxx,
      "rad" : 200,
      "desc" : "shops"
    },
    {
      "_type" : "waypoint",
      "tst" : 1430275810,
      "lat" : xxx,
      "lon" : xxx,
      "rad" : 200,
      "desc" : "home"
    },
    {
      "_type" : "waypoint",
      "tst" : 1430275665,
      "lat" : xxx,
      "lon" : xxx,
      "rad" : 250,
      "desc" : "work"
    }
```

What is getting published on event trigger, notice he 'desc' field is missing;
```
owntracks/matthew/iphone/event {"tst":1430345127,"acc":65,"_type":"transition","event":"enter","lon":xxx,"lat":-xxx,"wtst":1430275774,"tid":""}
owntracks/matthew/iphone/event {"tst":1430345834,"acc":65,"_type":"transition","event":"leave","lon":xxx,"lat":-xxx,"wtst":1430275774,"tid":""}
oowntracks/matthew/iphone/event {"tst":1430348743,"acc":165,"_type":"transition","event":"enter","lon":xxx,"lat":-xxx,"wtst":1430275665,"tid":""}
```

**Comment by jpmens** [comment]
Did you configure the waypoints to be `Shared`? If they're not shared, we don't pub the `desc`ription for privacy reasons.

**Comment by matbor** [comment]
Will try it.

Has that changed?

Pretty sure I didn't have shared selected in previous (AppStore) version.
It would just publish to the main topic.

**Comment by ckrey** [comment]
If not marked as `shared`it did not publish the `desc` even in older versions - at least not intentionally

When imported, waypoints are set to `shared`

**Comment by matbor** [comment]
thx. worked.

I have noticed however that sometimes it will say 'entering -> work' for example in the ios notifications, but the broker never receives that event message. Will monitor it.
