### ISSUE TITLE
events when published not set to retain - 8.0.18

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#171]
I believe that when the events are being published they are not set to retain?

If it is by design, maybe we need to add the info to the wiki, https://github.com/owntracks/owntracks/wiki/JSON#topics

**Comment by jpmens** [comment]
It is by design so that it really is an `event`; otherwise a client would constantly see me _entering favorite restaurant_ when it connects... ;-) 

I'll update the JSON spec. Thank you.

**Comment by matbor** [comment]
Figured that.

The retain setting (settings -> reporting -> retain ) might need a
explanation icon on what is being retained.

A shame you can't just link the wiki articles to each setting.
