### ISSUE TITLE
Messages queued and not delivered although in Wifi environment

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#173]
![fullsizerender](https://cloud.githubusercontent.com/assets/4027289/7430538/0a6b4e1e-f015-11e4-819a-09e40ae9ab47.jpg)

**Comment by ckrey** [comment]
Build in logging to fabric.io

please intentionally force crash next time you experience this (Settings tab, button beside Version)

**Comment by jpmens** [comment]
This may be hard to do ... I noticed that when I entered app, the messages were quickly transmitted out..

**Comment by ckrey** [comment]
No problem, logging is done always. The forced crash just transmits them

**Comment by ckrey** [comment]
Found performance issue when processing a bunch of incoming queued messages after reconnect.

**Comment by ckrey** [comment]
Problem can be reproduced by:
- open app
- disconnect manually
- publish now
> message will be sent after 20 seconds (dup timeout)

**Comment by ckrey** [comment]
Fixed in MQTT-Client
