### ISSUE TITLE
3-finger long tap to trigger publish now does not work on iPhone

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#174]

**Comment by ckrey** [comment]
It does work, but the user feedback is poor mainly because of #175 

On an iPhone, the same functionality is still available under "Modes/Publish now"

**Comment by jpmens** [comment]
I think the freezing in #175 really is the cause, yes. Also, I wouldn't invest too much in this -- I personally think Modes/Publish now is more than sufficient. Actually, perhaps you may consider removing the 3-finger tap completely to avoid people complaining? ;-)
