### ISSUE TITLE
User with card but no retained location (public)

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#177]
Jane has a retained card on public, but no retained location published, so Friends list shows ???.
I don't consider this a bug because it can't really happen in real-life, but I do want to point it out. 
Please close when you've seen it.

![image](https://cloud.githubusercontent.com/assets/60706/7446289/c4033278-f1d3-11e4-8a37-37ebba92a368.jpg)

**Comment by ckrey** [comment]
Maybe I should show "no location data available yet" instead of "???"

**Comment by jpmens** [comment]
Leave it as is; it's fine. (Closing now.)
