### ISSUE TITLE
PUB on enter WiFi?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#178]
Does iOS have an API which would make this possible?

We added this as a feature request [for Android](https://github.com/owntracks/android/issues/157) and it ocurred to me this would also be really nice for iOS.

In the very unlikely even you are bored, @ckrey :smile:

**Comment by ckrey** [comment]
The good news is: Yes, iOS has an API to get reachability status and it can even be run asynchronously. Works well and reliable.

The bad news is: This is not a supported background mode function. So it won't fire when the app is inactive.

**Comment by jpmens** [comment]
It was too good to be true. ;-)
