### ISSUE TITLE
Warn when switching from Private mode?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#182]
Can we, without too much trouble, warn a user when she taps from Private mode to one of the other modes? I''m thinking what's going to happen to users who have configured their Private environment, everything works, and then maybe erroneously tap on Hosted or  Public. They won't be pleased to lose all their settings.

A warning dialog which, if answered negatively, preserves settings would be a valuable enhancement.

**Comment by ckrey** [comment]
![ios simulator screen shot 07 05 2015 15 10 36](https://cloud.githubusercontent.com/assets/4027289/7515889/55828ee8-f4cb-11e4-8da9-e54a3ab2b8ff.png)

**Comment by jpmens** [comment]
Grand. Can you add something to the effect that configuration is wiped as well?

**Comment by ckrey** [comment]
But it isn't. Once setup, you can switch back and forth between modes.
