### ISSUE TITLE
Crash on Export (8.0.23)

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#184]
1. Open app
2. Click Settings
3. Tap `Export`

**Comment by jpmens** [comment]
> Crash is probably linked to export in Hosted mode where some parameters are not set/defined.

I confirm: does not crash on iPhone in Private mode.

**Comment by ckrey** [comment]
Fixed

**Comment by ckrey** [comment]
Crash report in #183 is linked

**Comment by jpmens** [comment]
I confirm it now works.
