### ISSUE TITLE
Found no location (8.0.27)

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#192]
![image](https://cloud.githubusercontent.com/assets/60706/7542482/57698066-f5bd-11e4-938d-71772d85ef3b.jpg)

**Comment by ckrey** [comment]
Some sources indicate that CLLocationmanager does not always provide a location.

This explains why sometimes hitting Publish Now or requesting an update via the 'reportLocation' command does not send any response.

The fix avoids the problem by using the last valid location reported.
