### ISSUE TITLE
Crash if friends are linked to address book, but no contact image is set

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#196]
#### in -[OwnTracksAppDelegate share]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55584805f505b5ccf0d9cdec](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55584805f505b5ccf0d9cdec)

**Comment by ckrey** [comment]
Fixed: Default image was missing in Application Bundle
