### ISSUE TITLE
type "p" should use real tst

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#197]
Publishes of `"t" : "p"` appear to use timestamp of last location publish which makes them appear as duplicates when they are published.

Should we use _now_ as `tst` for these?

**Comment by ckrey** [comment]
Publishes of "t" : "p" use timestamp of last location **reported by iOS** which makes them appear as duplicates when they are published.
Rather than using `now` instead of `tst`, we may add "now" as a secondary timestamp, similar to "wtst"

**Comment by jpmens** [comment]
I don't think we should add a second element to the JSON for now: it would a) complicate the issue and b) cause incompatibilities with Android. 

Instead, I will document this. Closing.

**Comment by jpmens** [comment]
I would like to bring this up again. Publishes of `"t":"p"` use last location reported by iOS (which is fine) and its timestamp.

Is it *possible* to replace the `tst` of those publishes by `now()` without adding a separate JSON element?

The reason I ask (again) is that I find it quite confusing to see a location report with an old `tst` in it, and I can imagine this will confuse others as well, in spite of our documenting it. :-) 

If we can replace the `tst` by `now()`, I propose we should do so.

**Comment by ckrey** [comment]
done

**Comment by jpmens** [comment]
Thank you, Christoph.

**Comment by dmikester1** [comment]
Came on here looking for answers.  The tst for each of the pubs is the same.  I can see from reading this thread why that is.  What's holding up getting this change committed?  I'd love to have a realtime timestamp on my pubs.
