### ISSUE TITLE
Show MQTT topic name somewhere?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#198]
We currently don't show the MQTT topic name associated with a friend anywhere, I think, and this has been fine so far as address-book associations or plain TID display takes care of that very nicely.

However, in _Hosted_ mode, when somebody creates a new device for herself, she suddenly appears twice in Friends. I think this could confuse people in spite of the face having a different-coloured ring around it.

Would it be worth adding the MQTT topic name into the user details page somewhere so that people can differentiate?

**Comment by ckrey** [comment]
Can't do much on the 'Friends' page
![ios simulator screen shot 18 05 2015 22 08 29](https://cloud.githubusercontent.com/assets/4027289/7689200/d8ab88f0-fdaa-11e4-92b0-537d3cfef27d.png)

**Comment by ckrey** [comment]
But I can do it on the `Locations`page
![ios simulator screen shot 18 05 2015 22 08 49](https://cloud.githubusercontent.com/assets/4027289/7689238/10554368-fdab-11e4-9287-ead58796693f.png)

**Comment by ckrey** [comment]
And on the `Details`page
![ios simulator screen shot 18 05 2015 22 13 53](https://cloud.githubusercontent.com/assets/4027289/7689256/2f2c655a-fdab-11e4-826f-0a45d43ea76f.png)

**Comment by jpmens** [comment]
I think putting the topic on the Details page is fine.
