### ISSUE TITLE
LocationTVC.m line 135

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#200]
#### in -[LocationTVC tableView:commitEditingStyle:forRowAtIndexPath:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5563450df505b5ccf0ef4aaa](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5563450df505b5ccf0ef4aaa)

**Comment by ckrey** [comment]
concurrency issue
