### ISSUE TITLE
OwnTracks not sending enter/leave events for waypoints

### ISSUE THREAD

**Issue by daniellueddecke** [owntracks/ios#201]
Hi there,

Im struggling with enter and leave events of waypoints and I think there might be a bug within OwnTracks for iOS.

Here is what I've done so far:
- setup OwnTracks to talk with my private MQTT server (Mosquitto as server, TLS enabled, Authentication enabled, set custom client ID, set custom device ID, all other options left to default)
- subscribing to "owntracks/#" on that server using mosquito_sub
- setting two shared waypoints in OwnTracks (home and work) with a radius of 200m and 2000m respectively

What I've observed so far:
- I see announcement of waypoints appearing on "owntracks/#"
- I see manual location updates sent from my iPhone
- I see location updates if in Move Mode
- if in "Significant Changes" mode I see location updates my phone is sending during the day

What I'd expect:
- OwnTracks should also send enter and leave events for my two waypoints no matter which mode I'm using

Some meta info:
- iPhone 6 / iOS 8.3
- OwnTracks 7.5.1

Please let me know if you need more details.

Thanks and best regards,
Daniel

**Comment by jpmens** [comment]
Thank you very much for your very detailed report.

You will be glad to hear that we've probably fixed this issue a while ago, and we're releasing a new version of the iOS app within the next few days, pending approval by Apple. We've been *very* busy with new things and we've applied a *ton* of fixed (really!).

I'll leave this open for the moment, and I hope you'll be voluntarily closing this issue in just a few days. :-)

**Comment by jpmens** [comment]
I forgot to say: the reason this has taken a while to be released is that we've decided to test in a closed-alpha group before going live.

**Comment by daniellueddecke** [comment]
Thanks for your reply. Indeed, I'm glad to hear this issue might be fixed by the new version :)
I'll close this ticket by myself as soon as I can approve it's working correctly.

Assuming your are using Apple's Test Flight for Alpha/Beta Tests, I'd be happy to also support you in doing so. So if your looking for new testers I'd like to send you my Apple ID and you may put me on your list :)

**Comment by jpmens** [comment]
@ckrey would you please take Daniel into TestFlight!?

**Comment by ckrey** [comment]
@daniellueddecke I need an email of you (not necessarily your Apple-ID) to include you in beta testing

**Comment by ckrey** [comment]
@daniellueddecke we clarified the situation in #209 

If in manual mode, no locations will be published except manually via `publish now`
