### ISSUE TITLE
Waypoints import message on incorrect JSON

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#206]
Can we make this more explanatory? JSON was incorrectly formatted and couldn't be parsed. (User error of course, but maybe we can say so in the popup.)
![file 28 05 15 15 22 55](https://cloud.githubusercontent.com/assets/60706/7860985/b381370a-054d-11e5-95ef-40ec9ea4472d.png)

**Comment by ckrey** [comment]
Added user info
![bildschirmfoto 2015-05-29 um 13 03 40](https://cloud.githubusercontent.com/assets/4027289/7881436/3362b628-0603-11e5-8ac3-b119eaf41f71.png)
