### ISSUE TITLE
crash if address book relationships corrupt - Friend+Create.m line 213

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#207]
#### in recordWithTopic

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/556d84f4f505b5ccf002c296](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/556d84f4f505b5ccf002c296)

**Comment by ckrey** [comment]
There is something strange within the relation section of the address book:

>                        CFStringRef label = ABMultiValueCopyLabelAtIndex(relations, k);
>                        if (CFStringCompare(label, RELATION_NAME, kCFCompareCaseInsensitive) == kCFCompareEqualTo) {

fails b/c label is NULL in CFStringCompare.

Will add defensive checks
