### ISSUE TITLE
if no deviceid is specified, it doesn't publish

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#211]
I have noticed that if you don't have any DeviceID in settings it will not publish anything, no warning appears to say it is required or missing.

**Comment by ckrey** [comment]
Good point!

We suppressed the publish unless all necessary settings are made to avoid random publishes during setup.

Will give clear hints on settings tab in the next version

**Comment by matbor** [comment]
Out of interest, was this  'enforced' more recently?

**Comment by ckrey** [comment]
Yes, see #180 
We found the problem with random publishes while testing and switching back and forth between modes

**Comment by matbor** [comment]
thx, think that is what has been causing my problems recently then, never had a deviceid set in the past.

**Comment by ckrey** [comment]
I see this from the crash dump you produced :sigh: #210 

If the location updates received from other devices have "shorter" topics than your base topic, the receiving app crashes.

"shorter" means haven less topic levels

**Comment by matbor** [comment]
Forgot to mention it will still publish waypoint enter/leave events if no
deviceid. Which is why I assumed something else was wrong.

**Comment by ckrey** [comment]
Fixed:
- Now all publishes are blocked until userID + clientID are set
- A warning is issued when the app enters foreground

![bildschirmfoto 2015-06-10 um 12 17 44](https://cloud.githubusercontent.com/assets/4027289/8080203/c02a634c-0f6a-11e5-9340-e7d031fafbc0.png)
