### ISSUE TITLE
GLEngine

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#212]
#### in gliCreateContextWithShared

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55725c7ff505b5ccf00d0082](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55725c7ff505b5ccf00d0082)

**Comment by ckrey** [comment]
does not seem to be related to app
