### ISSUE TITLE
location publishes with "t":"b"

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#213]
I'm seeing a few location publishes with `"t":"b"` in their payload. These are being published to the base topic.

```json
{
    "_type": "location", 
    "acc": 65, 
    "alt": 170, 
    "batt": 100, 
    "cog": -1, 
    "lat": 99, 
    "lon": 88, 
    "t": "b", 
    "tid": "jp", 
    "tst": 1433686481, 
    "vac": 10, 
    "vel": -1
}
```

IMO this should not be possible? The documentation specifies that `"b"` is for Beacon transition events. This is on 8.0.32 (retail & Testflight).

**Comment by ckrey** [comment]
When we introduced transition events we initially lost
a) the `"t":`trigger information and
b) the location message published to the base topic.

a) was remediated in #199
b) was re-implemented in #159

Use case:
If somebody leaves and enters his home without leaving the radius of detection for significant changes, a subscriber to his main topic would not get notified of any location change although beacon or circular region enter and leave transitions were generated
