### ISSUE TITLE
crash when upgrading db on iPhone4S - OwnTracksAppDelegate.m line 101

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#214]
#### in -[OwnTracksAppDelegate application:didFinishLaunchingWithOptions:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5576e773f505b5ccf0153603](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5576e773f505b5ccf0153603)

**Comment by ckrey** [comment]
timing issue upgrading sqlite db on iPhone4S. Fixed
