### ISSUE TITLE
crash remove called after [super will disappear] - StatusTVC.m line 124

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#215]
#### in -[StatusTVC viewWillDisappear:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5576f401f505b5ccf01558d7](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5576f401f505b5ccf01558d7)

**Comment by ckrey** [comment]
Fixed
