### ISSUE TITLE
location.timestamp == nil - OwnTracksAppDelegate.m line 914

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#217]
#### in -[OwnTracksAppDelegate share]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55789afdf505b5ccf018f8fd](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55789afdf505b5ccf018f8fd)

**Comment by ckrey** [comment]
location.timestamp was nil --- which should never happen.
Anyhow, put some protective code around it
