### ISSUE TITLE
crash Deleting a waypoint - LocationTVC.m line 143

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#219]
#### in -[LocationTVC tableView:commitEditingStyle:forRowAtIndexPath:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/557c9674f505b5ccf0214a6f](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/557c9674f505b5ccf0214a6f)

**Comment by ckrey** [comment]
I thought I fixed that in #215 ...

**Comment by ckrey** [comment]
put waypoints into separate table
