### ISSUE TITLE
crash when entering region before first location publish - OwnTracksAppDelegate.m line 333

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#220]
#### in -[OwnTracksAppDelegate regionEvent:enter:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/557df816f505b5ccf023ac49](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/557df816f505b5ccf023ac49)

**Comment by ckrey** [comment]
fixed
