### ISSUE TITLE
owntracks no longer seems to publish name of geofence

### ISSUE THREAD

**Issue by cpcowart** [owntracks/ios#223]
I use owntracks to geofence my home with the openhab mqtt binding for creating presence rules in home automation.

After upgrading to the current version (8.0.32), I stopped seeing geofence events in openhab. I updated the binding to subscribe to the new .../event topic, but still had no luck. 

Using mosquitto_sub, I captured the messages when entering a geofenced area:
Client mosqsub/6252-jayne.time received PUBLISH (d0, q0, r0, m0, 'owntracks/chris/event', ... (140 bytes))
owntracks/chris/event {"tst":1434572296,"acc":65,"_type":"transition","event":"enter","lon":-122.X,"lat":37.Y,"wtst":1434565884,"tid":""}
Client mosqsub/6252-jayne.time received PUBLISH (d0, q0, r0, m0, 'owntracks/chris', ... (160 bytes))
owntracks/chris {"cog":-1,"batt":85,"lon":-122.X,"acc":65,"vel":-1,"vac":10,"lat":37.Y,"t":"c","tst":1434572298,"alt":17,"_type":"location","tid":"IS"}

I don't see any mention of the geofence's name ("work") as specified in the description field for the location. I never looked at this debug subscription before the issue began occurring, so I can't say for sure, but I don't know how my openhab binding can tell between the "work" and "home" geofences without the messages including the name of the location.

Please let me know if I'm misreading something or if there's any additional info I can provide. Thanks.

**Comment by ckrey** [comment]
@cpcowart the name of the waypoints aka geofences are send out only if the `share` option is set on the waypoint. Could you please check if this is the case in your setup?

**Comment by cpcowart** [comment]
Thank you, that fixed it!
