### ISSUE TITLE
iOS 6 users crash - LocationManager.m line 273

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#224]
#### in -[LocationManager showError]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5585241ef505b5ccf0331f09](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5585241ef505b5ccf0331f09)

**Comment by ckrey** [comment]
IOS6 should not be supported anymore

**Comment by ckrey** [comment]
Updated last supported iOS version settings in app store
