### ISSUE TITLE
iOS 6 users crash - OwnTracksAppDelegate.m line 506

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#225]
#### in -[OwnTracksAppDelegate processFace:dictionary:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55852461f505b5ccf0331f8a](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55852461f505b5ccf0331f8a)

**Comment by ckrey** [comment]
IOS6 should not be supported anymore

**Comment by ckrey** [comment]
Updated last supported iOS version settings in app store
