### ISSUE TITLE
iOS 6 users crash - CoreFoundation

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#226]
#### in _outputStreamCallbackFunc

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5585248df505b5ccf0331fcb](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5585248df505b5ccf0331fcb)

**Comment by ckrey** [comment]
IOS 6 should not be supported any longer

**Comment by ckrey** [comment]
Updated last supported iOS version settings in app store
