### ISSUE TITLE
Waypoint events doesn't send out MQTT message

### ISSUE THREAD

**Issue by giorgiocanale** [owntracks/ios#234]
Hi I've the following scenario:
- a rPI with a MQTT server 3.1.1 version, published with a static IP, and with a DNS name 
- MQTT server is configured with SSL and a cert issued from a public, trusted CA 
- 1 iphone4 with IOS 7.1.2
- owntracks 8.0.32 on the phone
- I've a couble of waypoint defined, and owntracks set in manual mode, so to have just the transition events. I'm implementing some authomation when leaving and entering home, work, and so on

Sometimes all goes fine, when I leave home i got a notification on the iphone screen, and 2 messages on my mqtt server (with log them all and send me an email for debugging purposes), one of transition type and leave and another one of "location" type

After a couple of successful iterations of this the phone start giving just the notification on the screen (aka leaving home) but no MQTT message published on my server. 
Some other time it gives me the notification on screen, the "location" MQTT message but not the transition one, so I would rule out MQTT server reachability 

Is there something obvious I'm missing or am I hitting some bug?

Thanks

**Comment by ckrey** [comment]
please have a look at #213 
We made the decision not to publish any location updates when monitoring is "manual" to ensure privacy.
In earlier versions, this was not strictly checked.

**Comment by giorgiocanale** [comment]
Ok' I'll try to set it to "significant change" to see it it behave with
more reliability.
What fools me was that it works half of the times, and this is the reason I
thought of a bug.

If I understand you correctly the only way to have a reliable notification
regarding the transition event in and out the shared waypoint (geofencing)
is to leave in "Significant change" mode, am I right?
What do you think of a 4° settings ( Move mode, Significant Changes, Manual
mode, Disable)? This way if someone (like me) is just interested in
geofencing-waypoint feature this could be achieved without using the GPS
feature of the device at full power ( if I recall correctly GPS drain more
battery than GPS geofence on IOS), and without compromise on the privacy.

Thanks for your attention, I'll keep you posted of my findings either way.
A bit of information I've found in the meantime: it seems that owntracks
publish the location messages, but if you restart the device you got just
the oinscreen notification for the waypoint until you manually start the
app (and then all the gathered events are sent out at once as MQTT message
to the server)


Thanks again
Giorgio

2015-07-06 14:01 GMT+02:00 Christoph Krey <notifications@github.com>:

**Comment by ckrey** [comment]
closed. The enhancement in #274 picks up the additional mode suggestion
