### ISSUE TITLE
Waypoint with null desc

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#236]
It seems to be possible to create a shared waypoint with an empty description. I'm not sure that is particularly useful ... :-)
![image](https://cloud.githubusercontent.com/assets/60706/8507552/a8043888-2248-11e5-88e5-2154f5d2fdd3.jpg)

**Comment by ckrey** [comment]
No, it is a waypoint with a description which is not shared.
This makes sense if you want to trigger location updates.
It does not make sense to send enter/leave events in such a situation

**Comment by ckrey** [comment]
Fixed
