### ISSUE TITLE
CFNetwork

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#238]
#### in CoreStreamBase::_streamSetEventAndScheduleDelivery(unsigned long, unsigned char)

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55995a90f505b5ccf05c82c1](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55995a90f505b5ccf05c82c1)

**Comment by ckrey** [comment]
Testing artefact
