### ISSUE TITLE
Crash when incorrect face data received - OwnTracking.m line 165

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#240]
#### in -[OwnTracking processFace:dictionary:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a11cb1f505b5ccf06e0c82](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a11cb1f505b5ccf06e0c82)

**Comment by ckrey** [comment]
checks for incoming data added
fixed in 8.2.1
