### ISSUE TITLE
MessageTVC.m line 135

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#243]
#### in -[MessageTVC fetchedResultsController]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a15303f505b5ccf06e91c2](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a15303f505b5ccf06e91c2)

**Comment by ckrey** [comment]
Testing artefakt
