### ISSUE TITLE
crash due to memory leak - Friend+Create.m line 189

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#246]
#### in recordWithTopic

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a28ac6f505b5ccf070c620](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a28ac6f505b5ccf070c620)

**Comment by ckrey** [comment]
memory leak fixed
