### ISSUE TITLE
Waypoints deleted on update. 

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#248]
From 8.2.0 -> 8.2.1

**Comment by matbor** [comment]
FYI, upgrading to 8.2.7 lost waypoints again.

**Comment by jpmens** [comment]
That didn't happen here; waypoints still configured.

**Comment by ckrey** [comment]
@matbor did you upgrade from 8.2.6 to 8.2.7?

I have no idea how this can happen. What did you do after the upgrade?

The loss of waypoints coming from 8.0.32... to 8.2.x was clear and I added a conversion routine. 
I tested the conversion by installing 8.0.32 from the app store and then upgraded to the recent version.

**Comment by matbor** [comment]
My mistake, just worked out what I did. Changing modes private -> hosted -> public clears the waypoints. 

 You may close. 

Not sure if by design but going back to private I get all my settings back but not waypoints.

**Comment by jpmens** [comment]
That is correct: waypoints are deleted intentionally so as not to pollute eg. public with data which is basically private. This works as defined. :-)

**Comment by matbor** [comment]
@jpmens lol, I remember clicking the box now ;)
