### ISSUE TITLE
Use more general tab bar icon for regions (regions are both geofences and beacons)

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#249]
![bildschirmfoto 2015-07-13 um 15 16 33](https://cloud.githubusercontent.com/assets/4027289/8650311/305f2a6e-2972-11e5-9bc5-1809075e91af.png)

**Comment by ckrey** [comment]
Done, including equally heavy symbols and lighter background color

![bildschirmfoto 2015-07-13 um 15 28 08](https://cloud.githubusercontent.com/assets/4027289/8650553/cb9a15ce-2973-11e5-8ea3-9d2bdbb89b5e.png)

**Comment by matbor** [comment]
Prefect. Thx.
