### ISSUE TITLE
Double taping owntracks when red

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#252]
Power user feature request, long press or double  taping the red owntracks will bring up the Matt connection status error window

![image](https://cloud.githubusercontent.com/assets/1978503/8660996/000200d6-29f8-11e5-8615-58591f09790a.jpg)

**Comment by ckrey** [comment]
I cannot make the Lable become a Button, but we have Info now on all Navigatiion bars:

![bildschirmfoto 2015-07-14 um 13 46 59](https://cloud.githubusercontent.com/assets/4027289/8672480/03bd96ea-2a2f-11e5-8f3b-c45d87bd7cb3.png)

![bildschirmfoto 2015-07-14 um 13 49 20](https://cloud.githubusercontent.com/assets/4027289/8672492/2711b432-2a2f-11e5-8e88-8a9ce8c67b0b.png)
