### ISSUE TITLE
Location+Create.m line 234

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#255]
#### in __37-[Location(Create) getReverseGeoCode]_block_invoke

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a800a82f038749478f9071](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55a800a82f038749478f9071)

**Comment by ckrey** [comment]
Won't fix b/c 8.0.32
