### ISSUE TITLE
Documentation URL in settings

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#260]
... currently points to wiki (which we deprecated). Please have it point to [Booklet](http://owntracks.org/booklet/)

**Comment by ckrey** [comment]
![img_3912](https://cloud.githubusercontent.com/assets/4027289/8767431/00bae1c8-2e5d-11e5-9c69-2d38221679d9.PNG)

**Comment by jpmens** [comment]
That's the help behind (i), right?

I meant the link at the bottom of Settings tab:
![image](https://cloud.githubusercontent.com/assets/60706/8767462/11238190-2e5e-11e5-950f-ffe6f56cfe3f.jpg)
