### ISSUE TITLE
Show coordinates and geohash in Info screen

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#261]

**Comment by ckrey** [comment]
![img_3914](https://cloud.githubusercontent.com/assets/4027289/8767358/1babb8ac-2e5a-11e5-935b-3a4cd3775021.PNG)

**Comment by jpmens** [comment]
Nice.
Can you add `geohash:` before the actual hash so people understand?

**Comment by ckrey** [comment]
![img_3915](https://cloud.githubusercontent.com/assets/4027289/8767428/f438dbf8-2e5c-11e5-99f7-4679838a81bf.PNG)

**Comment by jpmens** [comment]
Very good. This is nitpicking, I'm certain, but I _think_ it should be Coordinates (plural), though I'm not 100% sure.

My very humble apologies! :smile:

**Comment by ckrey** [comment]
but you are right
