### ISSUE TITLE
8.2.6 TID wrong on map

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#265]
Related to #264: TID is now correctly published, but auto-TID on map is wrong (contains last two characters of DeviceID), also after swipe-out and reconnect.

**Comment by jpmens** [comment]
Changing UserID (which changes the topic published to) does something strange: I changed from username `fff` to `ppp` and then I see in Friends:

* `owntracks/fff/mybox` with tid=`pI` (which I set)
* `owntracks/ppp/mybox` (new username) with tid=`OX`

**Comment by ckrey** [comment]
The problem was in 8.2.5. The TID transmitted by a friend was not stored. This means "old" publishes received use the auto-or-default-TID.
Can you publish once more with 8.2.6? Should solve the problem

**Comment by jpmens** [comment]
I have

1. swiped all friends away (deleted)
2. published manually
3. swiped app out
4. published again

TID is correctly published, but the TID on the map remains "OX" (i.e. last two chars of device name)

I then changed device name. A publish immediately updates TID on map with *those* last two characters!

**Comment by ckrey** [comment]
ok, understood and fixed.
