### ISSUE TITLE
8.2.6 TLS client certs: reconnect fails

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#266]
As discussed: when device goes to sleep or when app is swiped out and restarted, connection to broker using TLS client cert fails. The only solution seems to be:

1. enable TLS policy
2. check connection (which fails)
3. disable TLS policy

**Comment by ckrey** [comment]
I can't reproduce this

**Comment by jpmens** [comment]
I've found the cause: contrary to what you probably did, I did *not* install the CA certificate in iOS, relying on the fact that the PKCS#12 container I provided to the app contained it.

A search for the `OSSStatus error 9807` took me to [this page](http://stackoverflow.com/questions/8394293/how-to-accept-self-signed-certificate-with-asihttprequest) which enlightened me. After installing the CA certificate separately, the app behaves as we expect it to.

**Comment by jpmens** [comment]
So, the question basically is: can we have the app trust the CA certificate which is in the PKCS#11 (`.otrp`) container? For the record, this is how I built it:

```
openssl pkcs12 \
   -export -in "${name}.crt" \
   -inkey "${name}.key" \
   -certfile ca.crt \
   -name "fff at tiggr" \
   -out fff.otrp
```

Note the `-certfile` parameter.

**Comment by jpmens** [comment]
This is ok as it is. Users shall import the broker's CA certificate into global profile and they can then use PKCS#12 containers for authentication with client certificates.

Alternatively, if they wish to skip the first bit, they should configure the app to allow an invalid (i.e. untrusted) server certificate.
