### ISSUE TITLE
TLS settings caption: Allow untrusted

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#269]
TLS settings currently says `Allow Invalid Certificates`; that should be `Untrusted` I think.(in case of space constraints, `s/Certificates/Certs/` )

**Comment by ckrey** [comment]
Here's what the documentation says:
```
/**
Whether or not to trust servers with an invalid or expired SSL certificates. Defaults to `NO`.
Note: If your server-certificates are self signed, your should set this property to 'YES'.
*/
@property (nonatomic, assign) BOOL allowInvalidCertificates;
```
I will give it a closer look

**Comment by ckrey** [comment]
continued...
```
// ssl security policy
/**
* The security policy used to evaluate server trust for secure connections.
*
* if your app using security model which require pinning SSL certificates to helps prevent man-in-the-middle attacks
* and other vulnerabilities. you need to set securityPolicy to properly value(see MQTTSSLSecurityPolicy.h for more detail).
*
* NOTE: about self-signed server certificates:
* if your server using Self-signed certificates to establish SSL/TLS connection, you need to set property:
* MQTTSSLSecurityPolicy.allowInvalidCertificates=YES.
*/
```

**Comment by ckrey** [comment]
The function used to check is SecTrustEvaluate (see below), so the term should be `untrusted'!

https://developer.apple.com/library/prerelease/ios/documentation/Security/Reference/certifkeytrustservices/index.html#//apple_ref/c/func/SecTrustEvaluate

**Comment by jpmens** [comment]
I understand. I have a problem with the word `Invalid` because that sounds to me like broken or corrupt, i.e. KAPUTT. I interpret the documentation as saying "expired" or "self-signed". Anyhow, unimportant.
