### ISSUE TITLE
Use custom security policy

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#273]
If "use custom security policy" is enable, should you see the options below that? Or is it for something else?

![image](https://cloud.githubusercontent.com/assets/1978503/8822608/067df8e4-30aa-11e5-93e2-01cfe4b9bde9.jpg)

**Comment by ckrey** [comment]
All the 5 subsequent parameters only apply if "Use" is on. 
Probably the best way to make this clear would be to "gray"/disable the 5 fields if "Use" is off.
And... we have to add some explanation to the docs

**Comment by jpmens** [comment]
I've purposely not yet addressed the [TLS client cert documentation](http://owntracks.org/booklet/features/tlscert/) because we're still talking about how to best do this.
