### ISSUE TITLE
The 'i' button.

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#276]
Just a discussion..... With the 'i' button, just wondering if you need it?

Reason I bring it up is because if you look at all the apple settings they only use the 'i' if you want to delete something. (Example -- if you look at FaceTime settings clicking the 'i' deletes gives you the option to delete one of the email addresses.)

Referring to the 'i'  button here;
![image](https://cloud.githubusercontent.com/assets/1978503/8823677/2ba85990-30b2-11e5-838d-a30045b3aa7e.jpg)

Apple settings example for more information/settings, it just shows what is currently enabled, but shows that there are more options just by clicking the arrow;
![image](https://cloud.githubusercontent.com/assets/1978503/8823678/2c049e1c-30b2-11e5-81ee-5305bde14777.jpg)

**Comment by jpmens** [comment]
You make a very valid point; I stumbled there myself actually, thinking the (i) would give me more info. ;-)

That could be done and would probably look rather good:

```
Filename     xxxxyyyzzz.otrp   >
Passphrase             *********

Pinned certificate   broker.otre >
```

**Comment by matbor** [comment]
Another example of what you are thinking I believe;

![image](https://cloud.githubusercontent.com/assets/1978503/8824034/725a1a10-30b5-11e5-89c3-40f901b34f0e.jpg)

**Comment by ckrey** [comment]
No you are right and I already changed it

**Comment by jpmens** [comment]
@matbor Good example, yes!

**Comment by matbor** [comment]
@ckrey goodwork

**Comment by jpmens** [comment]
This looks very good now. There are still two (i) left, but I think they're right.

**Comment by ckrey** [comment]
The difference:
> points to a sub table view. You get there by selecting the table row

(i) points to a detail screen. You need to tap on the (i) button
