### ISSUE TITLE
Nit: phrasing

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#279]
Two small nits:

1. Switching between "modes" (plural)
2. OwnTracks data will be deleted (not all data on device ;-)

![image](https://cloud.githubusercontent.com/assets/60706/8828566/28143cb4-3093-11e5-87e3-63ac6b4204f3.jpg)

**Comment by ckrey** [comment]
![bildschirmfoto 2015-07-22 um 17 11 25](https://cloud.githubusercontent.com/assets/4027289/8828925/cf786be6-3094-11e5-8bcf-53cdb04ea9a8.png)

**Comment by jpmens** [comment]
ACK, thanks.
