### ISSUE TITLE
Adding waypoints from Regions tab

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#280]
The current method for adding waypoints is to tap and hold on the map until a pin drops, and then either edit (via the pin) or via the Regions tab. I would like to propose doing this in a (maybe) more intuitive way, as we do it in Android.

![image](https://cloud.githubusercontent.com/assets/60706/8835121/d5e9dbda-30b8-11e5-85b1-79a0f009b9f5.jpg)

The pertinent screen in Android is similar to this in iOS. At the point I've indicated with an arrow, there is a kind of + symbol which allows me to enter details: Description, lat, lon (with a button I can click for "here" which adds current to lat & lon), radius, shared, etc.

Maybe we can get some feedback on this?

**Comment by ckrey** [comment]
We had this in earlier versions. At that time it was confusing b/c we did not have split locations and waypoints at that time. No problem to reintroduce. hit (+) and get a new region initializes with "here" data

**Comment by ckrey** [comment]
![ios simulator screen shot 22 07 2015 23 46 45](https://cloud.githubusercontent.com/assets/4027289/8838348/4c2cb124-30cc-11e5-8a47-67ea0b74f1de.png)

**Comment by jpmens** [comment]
I was thinking more along the lines of `+` opening a new page to enter details, etc, but this is fine. Thank you.

**Comment by ckrey** [comment]
done

**Comment by jpmens** [comment]
Thank you!
