### ISSUE TITLE
crash when receiving messages - Setting+Create.m line 22

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#282]
#### in +[Setting(Create) existsSettingWithKey:inManagedObjectContext:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55b217eb2f03874947a61300](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55b217eb2f03874947a61300)

**Comment by ckrey** [comment]
fixed, serialized access to settings
