### ISSUE TITLE
Messages and Notifications

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#283]

**Comment by ckrey** [comment]
* Enter/Leave Messages of Friends are shown in Messaging table
* Own Enter/Leave Messages are shown in the Messaging table
* Messaging messages are shown as notifications

![img_3956](https://cloud.githubusercontent.com/assets/4027289/8875589/9f9f92e6-321a-11e5-9b31-771e679a6058.PNG)

![img_3955](https://cloud.githubusercontent.com/assets/4027289/8875611/be03fbd2-321a-11e5-8e84-4f1394840012.PNG)

**Comment by jpmens** [comment]
This is very nice.

**Comment by matbor** [comment]
looks good.
