### ISSUE TITLE
Message+Create.m line 82

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#286]
#### in +[Message(Create) expireMessages:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55b37d932f03874947a9553b](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55b37d932f03874947a9553b)

**Comment by ckrey** [comment]
happened 3 times in pre-release 8.2.10
