### ISSUE TITLE
QuartzCore

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#287]
#### in CA::Context::destroy()

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55b590ac2f03874947ad5cda](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55b590ac2f03874947ad5cda)

**Comment by ckrey** [comment]
wontfix 8.0.32
