### ISSUE TITLE
Nit: text alignment in Messaging

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#290]
The text of a Message is not left-aligned with the Title and `tst` which makes it look a bit strange.

![img_3068](https://cloud.githubusercontent.com/assets/60706/8958226/e109a2ac-3603-11e5-86ad-8046ae34bfaa.jpg)

**Comment by ckrey** [comment]
![ios simulator screen shot 29 07 2015 15 55 57](https://cloud.githubusercontent.com/assets/4027289/8959312/5c9a9e84-360a-11e5-8427-329e08f3a0f5.png)

**Comment by jpmens** [comment]
Nice, thanks.

Additional question: do those table cells actually HTML (e.g. the links in your screenshot) to be rendered somehow? That would greatly enhance the view.

**Comment by ckrey** [comment]
![ios simulator screen shot 01 08 2015 10 16 44](https://cloud.githubusercontent.com/assets/4027289/9021204/a34b0390-3836-11e5-9777-7cb7e9acdc9a.png)

**Comment by jpmens** [comment]
That is gorgeous, @ckrey !

Now comes the bit where you kill me: the `@date` has slipped back to the left compared with your second-to-last screenshot. ;-)

![jmbp-1726](https://cloud.githubusercontent.com/assets/60706/9021232/ddea077a-3837-11e5-9feb-33c26e3d4911.jpg)

**Comment by ckrey** [comment]
![ios simulator screen shot 01 08 2015 10 44 09](https://cloud.githubusercontent.com/assets/4027289/9021268/4d6c8062-383a-11e5-9f7e-dbb94726d661.png)

**Comment by jpmens** [comment]
That cannot be improved upon.
