### ISSUE TITLE
Setting+Create.m line 22

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#292]
#### in +[Setting(Create) existsSettingWithKey:inManagedObjectContext:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55ba69982f03874947b8eafe](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55ba69982f03874947b8eafe)

**Comment by ckrey** [comment]
Settings is now thread safe
