### ISSUE TITLE
Message+Create.m line 82

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#294]
#### in +[Message(Create) expireMessages:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55c54385e0d514e5d6d46739](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55c54385e0d514e5d6d46739)

**Comment by ckrey** [comment]
happened only a few times in old 8.2.10
