### ISSUE TITLE
Fontawsome icons

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#297]
I've tried using `fa-child`, `fa-bomb`, `fa-building` in a Message, but I seem to be getting some default glyph.

`fa-anchor` and `fa-bell` work. Do we not support all the FA names in the [cheat sheet](http://fortawesome.github.io/Font-Awesome/cheatsheet/) ?

![jmbp-1762](https://cloud.githubusercontent.com/assets/60706/9222588/3d6c26ec-40f3-11e5-94eb-6c6456187e89.png)

Payload: ```
{"_type": "msg", "sender": "owntracks/public/fortune", "title": "Home monitor", "ttl": 600, "tst": 1439377565, "icon": "fa-child", "desc": "Backup disk almost full (97%)"}
```

**Comment by ckrey** [comment]
I completely re-did the implementation but still:

Seems Unicodes > \uf195 are not displayed

![ios simulator screen shot 12 08 2015 23 03 37](https://cloud.githubusercontent.com/assets/4027289/9236676/70bd8718-4146-11e5-90a5-15f18cfdc648.png)
![ios simulator screen shot 12 08 2015 23 03 46](https://cloud.githubusercontent.com/assets/4027289/9236677/70beffee-4146-11e5-9d94-6a3f6739cd68.png)

**Comment by ckrey** [comment]
WTF: have to use `fontawesome-webfont.ttf`rather than `FontAwesome.otf`.
Fixed

**Comment by ckrey** [comment]
![ios simulator screen shot 13 08 2015 12 21 14](https://cloud.githubusercontent.com/assets/4027289/9247745/09c159a2-41b6-11e5-9336-54e5845b0e5e.png)

**Comment by jpmens** [comment]
Thanks
