### ISSUE TITLE
Large number of events on Friends' badge == large number of reverse geo lookups

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#302]
Not sure if this can be changed: installed 8.2.11. I then noticed she had `> 1200` on Friends badge. Each time that was decremented, I noticed reverse geo-lookup being done in Friend’s list…

**Comment by ckrey** [comment]
Well, if the friends list is displayed and the locations are updated, reverse geo-lookup is triggered.
What I could do is to delay the lookup, which means when incoming updates are processed in batch, nothing will happen until the last update is done.
On the other hand, it would mean that rev-geo would be slower from a user perspective (e.g. 1sec)

**Comment by jpmens** [comment]
I was going to say 'leave it', but I see a Fixed label on this now.
