### ISSUE TITLE
Local Pushes

### ISSUE THREAD

**Issue by senfi** [owntracks/ios#304]
I installed the app a while ago. After the latest update, i started it the first time. Due to a lack of time, i did not set up something. So i have a somehow-fresh installed app with nothing configured. But i am receiving this push messages multiple times a day. Searching this repo for the messages does not give a single result. So, where are these messages coming from?
![owntracks](https://cloud.githubusercontent.com/assets/806859/9325332/cd46236a-4591-11e5-8a01-a3f4690b6c3f.png)

**Comment by jpmens** [comment]
@senfi Apologies for your being spammed like that, although we are pleased it's working for you. :-)

Background: our iOS and Android apps now have support for [location-based messaging](http://owntracks.org/booklet/features/msg/), and for test purposes, we've been pushing messages to the geohash corresponding to the 3 location we (the OwnTracks Team) are located at.

It would appear you are also in one of these locations ... ;-) ;-)

We'll try to shut this down in the course of this evening.

**Comment by jpmens** [comment]
You saw these when in Public mode, didn't you, @senfi ?

**Comment by senfi** [comment]
Yeah, i think so. For the record: i am in Aachen, Germany.

**Comment by chris021** [comment]
I am also getting these in New Zealand.

**Comment by jpmens** [comment]
That's good to hear, thanks -- it means our system works. ;-)
