### ISSUE TITLE
Re-introduce Messaging switch in settings?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#305]
We should consider re-introducing configurable Messaging (on/off) in Settings after reading #304 :-)

I don't think we considered that some people wouldn't want weather warnings, etc. when living in or passing through areas which have Messages pushed to relevant geohashes. While it's configurable via JSON import, that may be a bit too much to expect from users (export, edit JSON, import).

**Comment by ckrey** [comment]
I vote against this!

We should turn off unsolicited messages in Public mode. We may send some messages to `msg/system` to indicate backhand outages, etc.

In Hosted mode, when we offer some message channels, we need an opt in/out UI similar to the tracker/tracking one.

**Comment by jpmens** [comment]
I was under the impression the user *was* in Hosted mode; hence my suggestion. For Public it's fine as it is.
