### ISSUE TITLE
AGXCompilerConnection

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#306]
#### in CompilerFSCache::GenerateHash(void const*, unsigned long, unsigned char*)

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55d363c6e0d514e5d6150985](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55d363c6e0d514e5d6150985)

**Comment by ckrey** [comment]
Mapkit, won't fix
