### ISSUE TITLE
Rephrase message?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#308]
Nitpicking as a Service. :)

My client is disconnected, as can be seen by the yellow indicator line. I tap on Publish and get this message.

![image](https://cloud.githubusercontent.com/assets/60706/9368398/5b941bc2-46c3-11e5-8c74-27bac14c3d64.jpg)

This means the publish has basically been queued, because the client is disconnected. Should we change that so as to not confuse people who may be checking their broker for its arrival? (I don't think there'll be many who do, but we never know. :-)

**Comment by ckrey** [comment]
![img_4259](https://cloud.githubusercontent.com/assets/4027289/9378333/e53814a2-4720-11e5-98fc-6b0511d08c8b.PNG)

**Comment by jpmens** [comment]
Good, thanks.
