### ISSUE TITLE
Introduce locked settings for managed environments

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#309]
Imagine you are operating an OwnTracks backend for e.g. your family and you want to avoid your family members to accidentally switch modes or modify settings locally on the device:

new settings parameter
`"locked":true/false`, default false

controls whether the settings are editable in the device's UI.

`locked` can only be set via .otrc file.

**Comment by ckrey** [comment]
![img_4260](https://cloud.githubusercontent.com/assets/4027289/9379011/7df4458a-4726-11e5-9bf4-05578b53f787.PNG)
![img_4261](https://cloud.githubusercontent.com/assets/4027289/9379012/7df52f68-4726-11e5-8a02-603213510018.PNG)

**Comment by jpmens** [comment]
Very good, thanks. Clarification added just now to JSON in booklet.
