### ISSUE TITLE
Cannot connect to Server since update to 8.2.11

### ISSUE THREAD

**Issue by Lenzebo** [owntracks/ios#310]
Hi, since the last Upgrade of the ios App i cannot connect to my Server (mosquitto) anymore with the following error:

error The operation couldn’t be completed. (OSStatus error -9807.) {
}

Do you have any clue what might cause this?

**Comment by jpmens** [comment]
Am I right in thinking you're using TLS with a self-signed certificate? We've locked down a bit on that. Under settings, TLS, activate "Use profile" and activate "allow invalid certificates". Go back and hit "Check" once or twice; that should attempt to reconnect to your broker.

**Comment by ckrey** [comment]
We use an updated version of the MQTT-Client-Framework in the app which fixed an TLS checking problem ckrey/MQTT-Client-Framework#31.

In addition to @jpmens comment, you may connect to a host with a name which does not match the name in the certificate. In that case, change your certficate or deactivate "Validate domain name".

![img_4271](https://cloud.githubusercontent.com/assets/4027289/9403728/db04be6c-47e9-11e5-93d9-a21c61a1e5a6.PNG)

**Comment by jpmens** [comment]
@Lenzebo be advised that you will probably not want to set Validate Certificate Chain as shown in above screenshot if you don't have a valid chain. FYI.

**Comment by ckrey** [comment]
@Lenzebo did you resolve the problem?

**Comment by Lenzebo** [comment]
yes the issue was resolved after updating my certificate settings in the
app

2016-02-29 10:34 GMT+01:00 Christoph Krey <notifications@github.com>:
