### ISSUE TITLE
crash when opening Messages - MessageTVC.m line 94

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#311]
#### in -[MessageTVC tableView:cellForRowAtIndexPath:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55d765b5e0d514e5d628d9cb](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55d765b5e0d514e5d628d9cb)

**Comment by ckrey** [comment]
textContainerInsets settings fixed
