### ISSUE TITLE
Little cosmetic issue in Friends tab

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#314]
some cells overflow and scroll. makes it hard to scroll the list because the cell catches the drag

**Comment by jpmens** [comment]
The workaround for scrolling, at least on a narrow device such as the 5s, is to drag just left of the (I) buttons. :-)

**Comment by ckrey** [comment]
True, but if I make the cells adjust to the content we get other effects:
![resolving](https://cloud.githubusercontent.com/assets/4027289/9461067/8d05f968-4b0b-11e5-852f-b06e80654458.gif)

**Comment by jpmens** [comment]
What if

a) we do a fixed cell height and "hope for the best" (TM) ?
b) e.g use `TID` instead of `topic` for uses without CARD (1st example above) to reduce height?

**Comment by ckrey** [comment]
fixed, address fields are now fixed
