### ISSUE TITLE
CoreData.m line 93

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#317]
#### in +[CoreData saveContext:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55e5366af5d3a7f76bb354d7](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55e5366af5d3a7f76bb354d7)

**Comment by ckrey** [comment]
happened 8 times in 8.2.11. A number of Coredata concurrency problems were solved with newer versions
