### ISSUE TITLE
Waypoint+Create.m line 28

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#323]
#### in __37-[Waypoint(Create) getReverseGeoCode]_block_invoke

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55f265bff5d3a7f76bf05f7d](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55f265bff5d3a7f76bf05f7d)

**Comment by ckrey** [comment]
Happened once on old 8.2.11 version, last on Sep 11.
