### ISSUE TITLE
GLEngine

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#325]
#### in gliCreateContextWithShared

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55fd83bbf5d3a7f76b276094](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/55fd83bbf5d3a7f76b276094)

**Comment by ckrey** [comment]
won't fix GLEngin
