### ISSUE TITLE
Beacon ranging: Define Major/Minor as decimal or hex (explicitely)

### ISSUE THREAD

**Issue by tiptronic** [owntracks/ios#326]
Here's some problems in the iOS-UI, when creating beacon regions:

Entering values for Major/Minor is confusing (Booklet states we need hex - which ist not really the case):

Here's an example modifying a Minor value (Major is the same)

If I enter a value of 12368, the value is kept in the UI as is when re-opening a beacon's settings pane.

Now let's look at the value 37321 (no matter if I intended hex or dec, OwnTracks interprets the value itself), so:
- If I enter a value of 37321, the value is converted to 4294939081 in the UI (after re-opening the pane)
- which is: 0xFFFF91C9
- which is: 0x91C9 (=37321) padded to 16 bit

From a user's pov, this doesn't look really friendly, because to enter an arbitrary decimal value the user needs to:
- calculate the hex-value (from his/her current decimal minor)
- pad it to 16bit
- get its decimal representation (and enter that, because entering 0x91C9 is cutted to 91)
- This is only true for values > 32767.

Values < 32768 are unknown (hex) as what they are interpreted, but they are not padded.

So my vote would be to define Major/Minor as DECIMAL values, or in case you prefer hex, let the user prefix the value using '0x' - so everyone is clear what the value means (which - IMO - currently is simply not the case).

**Comment by ckrey** [comment]
Thanks for spotting this, booklet will be updated immediately, fix in the app with the next iteration
