### ISSUE TITLE
Add support for passive geofence tracking in addition to the current modes.

### ISSUE THREAD

**Issue by Shirk** [owntracks/ios#327]
iOS has native support for geofence tracking and will start the application in the background to notify it of enter / leave events.  

Since many users use Owntracks in combination with home automation systems like openHAB it would be beneficial to have support for the native geofence tracking in addition to the current "significant location change" and other modes.

This mode wouldn't be able to record precise tracks since it would only operate on fences and iOS would do all the work in the system frameworks but on the other hand it would provide a great enhancement in battery consumption compared to the current implementation (and because of that I suggest adding it in addition to the current tracking modes).

Owntracks already supports sized, circular regions so it shouldn't be too difficult to register these with the built-in geofence support.

**Comment by ckrey** [comment]
OwnTracks iOS does use the native geofence tracking already.
If you specify a circular or iBeacon region, it uses the native tracking.

Significant Changes mode and Move mode are available in addition, based on changes in position and time. Significant Changes mode is the native battery saving mode provided by iOS.

Move mode is the active mode, similar to turn-by-turn navigation apps and is quite battery consuming.

In Manual mode, only native geofence tracking is enabled. In Quiet mode, all reporting is switched off.

**Comment by Shirk** [comment]
I'm sorry to say that but the location icon tells a different story. 
If you only register for geofencing the icon in the status bar is displayed as an outline opposed to a filled item for other modes..
Which mode do I had to select (play,pause,stop,ff icon) to get geofence only? 
Currently I get the filled only location icon for Owntracks and it spends significant time in the background.

**Comment by ckrey** [comment]
I am not sure what you are referring to:

When you open the app, the map display has the current location indicator switched on, which means, that the app does receives what you call "active" location updates.

When you send the app to background and you are not in Move mode (FF-symbol) or significant Changes mode (Play-symbol), the app uses geofences only.

When testing here with an iPhone5C on iOS9, the indicator reverts to outline when you background the app while in manual or quiet mode.

What do you mean by "spends significant time in the background" ?

**Comment by Shirk** [comment]
Thanks clarifying that Chris - I think the solves the issue! 

So far I was only testing in significant changes mode  and not in manual or quiet mode. 

I think my problem is that neither the names (manual/quiet) nor the icons (pause/stop) suggest that Owntracks will send any events without manual action. 

Are enter/leave events being send to the mqtt broker even in quiet mode?

**Comment by ckrey** [comment]
Thank you for the feedback.

I will make an update to 
http://owntracks.org/booklet/features/location/#ios
and will try to be even more specific describing the 4 modes
