### ISSUE TITLE
Barometric pressure after upgrade from iOS8 to iOS9

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#328]
As reported, OwnTracks on iOS no longer reports barometric pressure after upgrading from iOS8 to iOS9. As you correctly told me personally, the solution is to:

1. open OwnTracks and keep it in the foreground for a minute or two
2. hit `Publish now`

From that moment onwards, `"p"` is correctly transmitted (also when app in background).

**Comment by ckrey** [comment]
In new Testflight version 8.2.16, activation of Altimeter data is now done only once and never deactivated.
Can't test with simulator here, need support from iPhone 6 or iPad Air 2 users

**Comment by ckrey** [comment]
Documentation is somewhat vague:

>Use a CMAltimeter object to initiate the delivery of altitude-related data to your app. Altitude events reflect the change in the current altitude, not the absolute altitude. So a hiking app might use this object to track the user’s elevation gain over the course of a hike. Because altitude events may not be available on all devices, always call the isRelativeAltitudeAvailable method before using this service.
>
>After checking for the availability of altitude data, you start the delivery of events by calling the startRelativeAltitudeUpdatesToQueue:withHandler: method. Core Motion generates events at regular intervals (regardless of whether the data has changed) and delivers them to the block you specified at startup. When you no longer need the event data, call the stopRelativeAltitudeUpdates method.
>
> Core Motion delivers altimeter events only while your app is running, either in the foreground or background. If your app is suspended, event delivery stops temporarily. Event delivery resumes when your app returns to the foreground.

**Comment by jpmens** [comment]
Installed and launched on iPad2. The first and subsequent publishes all had "p"ressure, which looks fine.

**Comment by jpmens** [comment]
Status report: this seems to be working well on an iPad Air 2 with TestFlight versions installed: I am getting `p`ressure publishes. On an iPhone6 with retail version of OwnTracks, it is touch and go wether pressure is reported. I will keep an eye on this as soon as 8.3.0 is out.
