### ISSUE TITLE
Waypoint pubs have a `:` appended to the `desc` value

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/ios#329]
```/owntracks/renee/phone/waypoint {"tst":1443314772,"lat":xxx.xxx,"_type":"waypoint","lon":xxx.xxx,"rad":75,"desc":"home:"}```

**Comment by jpmens** [comment]
Confirmed in newest TestFlight version. Some artifact of beacon change?

**Comment by ckrey** [comment]
I Coat' see anything wrong:

>owntracks/cky/5c/event {"desc":"B79b","t":"b","tst":1443347122,"acc":30,"lon":xx,"_type":"transition","lat":yy,"event":"leave","tid":"5c"}
>owntracks/cky/5c/waypoint {"tst":1443347122,"lat":yy,"_type":"waypoint","lon":xx,"rad":-1,"desc":"B79b:CA271EAE-5FA8-4E80-8F08-2A302A95A959"}
>owntracks/cky/5c {"cog":-1,"lon":xx,"acc":30,"vel":0,"_type":"location","batt":70,"vac":24,"lat":yy,"t":"b","tst":1443347122,"alt":43,"tid":"5c"}
>owntracks/cky/5c/waypoint {"tst":1443347223,"lat":xx,"_type":"waypoint","lon":yy,"rad":-1,"desc":"B79b:CA271EAE-5FA8-4E80-8F08-2A302A95A959"}

**Comment by ckrey** [comment]
how is your waypoint specified? (screenshot)

**Comment by sumnerboy12** [comment]
Tricky to get a screenshot as it is on the wifes phone - it was created via a config update however. Would that make a difference?

**Comment by ckrey** [comment]
wait, I can recreate the problem now here

**Comment by jpmens** [comment]
![image](https://cloud.githubusercontent.com/assets/60706/10122163/09071282-650f-11e5-8b7a-65fdafc1123b.jpeg)

produces

```
"desc":"WP02:",
```

**Comment by jpmens** [comment]
Confirm working in TestFlight; thank you!

**Comment by sumnerboy12** [comment]
When will this be available for public? Don't have access to the TestFlight version on the wife's phone.

**Comment by ckrey** [comment]
@sumnerboy12 I just pushed the version to iTunes Connect for approval. This will take a few days

**Comment by sumnerboy12** [comment]
ok thanks - have written a hack into mqttwarn to re-pub the transition event with the `:` removed in the meantime
