### ISSUE TITLE
crash - OwnTracksAppDelegate.m line 233

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#330]
#### in -[OwnTracksAppDelegate application:openURL:sourceApplication:annotation:]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/56084ffef5d3a7f76b5fdc5f](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/56084ffef5d3a7f76b5fdc5f)

**Comment by ckrey** [comment]
iOS9 incompatibility
