### ISSUE TITLE
Missing waypoint reports. 

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#331]
Just re-installed the beta (so moved from AppStore version 8.2.11 -> TestFlight version 8.2.17) and have noticed that the waypoints have stopped publishing. I am running in private mode, has anything changed that could be causing this?

Will monitor and see if it does it again. I noticed it with the previous version of TestFlight but didn't have time to report it.

**Comment by ckrey** [comment]
This might be related to changes of handling in iOS9:
> locationmanger.pausesLocationUpdatesAutomatically = NO;

and to the introduction of a new parameter in iOS9:
> locationManger.allowsBackgroundLocationUpdates = TRUE;

which both default to values impacting background location updates

**Comment by matbor** [comment]
Ok. Yeah still happening.
