### ISSUE TITLE
Missing wtst element in JSON of waypoints

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#332]
The booklet says about `_type: waypoint`:

>`wtst` is the timestamp of waypoint creation even if it was subsequently modified by the user

I created a waypoint yesterday:

```json
{"_type":"waypoint","tst":1443351043,"lat":42.0345,"lon":7.47658,"rad":500,"desc":"WP03"}
```

and updated its radius and description just now:

```json
{"_type":"waypoint","tst":1443429791,"lat":42.0345,"lon":7.47658,"rad":600,"desc":"WP03mod"}
```

The `tst` in the updated waypoint has definitely changed, and the JSON doesn't contain a `wtst` element, so there is no way (server-side) to consider these waypoints as being "the same".

I think the bug is that `_type: waypoint` contains a `tst` (which it shouldn't) and is missing a `wtst` as the "key" of the waypoint.

**Comment by jpmens** [comment]
Considering Android handles `tst` correctly (i.e. doesn't change it on waypoint modification), I would propose that 

1. iOS does likewise (i.e. use `tst` as the unchanging _key_ of the waypoint)
2. iOS copies `tst` into `wtst` of transition events
3. I update the booklet to match.

**Comment by ckrey** [comment]
Ack, I think I "optimized" the storage of Waypoints a while ago. Before that Waypoints were stored in the same table as Trackpoints. 

Waypoints (Circular Regions or iBeacon Regions) are now internally identified by their name ("desc")!

I will record a creation timestamp and use this as android.

**Comment by jpmens** [comment]
Documentation updated to reflect how Android does it.

**Comment by ckrey** [comment]
`tst`of waypoints is now unchanging attribute.
It is set once when the waypoint is created or (for already existing waypoints without `tst*) set to `now`on the fly when the waypoint is updated or published next.
Will be in release 8.2.18

**Comment by jpmens** [comment]
> `tst` is the timestamp of waypoint creation even if it was subsequently modified by the user. (See Waypoints.) It is copied into the `wtst` of the transition event (type: transition) when an event pertaining to this waypoint fires.
