### ISSUE TITLE
Region+Create.m line 13

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#333]
#### in -[Region(Create) tst]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/56092469f5d3a7f76b6366d9](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/56092469f5d3a7f76b6366d9)

**Comment by ckrey** [comment]
Testing artefact won't fix
