### ISSUE TITLE
no significant changes in background mode

### ISSUE THREAD

**Issue by fetlam** [owntracks/ios#337]
Since I updated to IOS 9 Owntracks is not tracking any significant changes anymore if it runs in the background. I am wondering if I am the only one with this problem since IOS 9 is out now for a while and nobody else is reporting this issue.

**Comment by jpmens** [comment]
This is, indeed, the first report of a kind: we know of several iOS9 users without issues. It's unusual for this to happen, but something (not necessarily OwnTracks) may have got stuck somewhere: have you tried shutting down and restarting the iPhone?

**Comment by fetlam** [comment]
Should have been the first thing to do. The restart really helped.. I just restarted the app quite some times, but it seems that something else stucked. I think I did not restart the phone after the iOS9 update. 

Now everything seems to work fine as before. Thank you for this great app and your fast support!
