### ISSUE TITLE
Missing lat,lon whilst in Move Mode

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#338]
We're seeing some payloads with missing `lat` and `lon` when in Move mode. It is to be expected that iOS hasn't yet delivered the necessary data.

I think we should suppress location publishes if we don't know _where we are_.

**Comment by jpmens** [comment]
```
lat or lon for owntracks/jpm/5s are NaN: 
```

```json
{"tst":0,"vel":0,"_type":"location","alt":0,"vac":0,"cog":0,"batt":95,"tid":"jp"}
```

**Comment by ckrey** [comment]
Probably b/c no current location was present at that time.
Messages will be suppressed if no current location is available
