### ISSUE TITLE
IOS app on Iphone 3GS / iOS6 crashes upon launch

### ISSUE THREAD

**Issue by toddeye** [owntracks/ios#342]
It is an iPhone 3GS with IOS 6.1.6 (I assume latest).   When I downloaded it from the app store it prompted me to download the latest version that is compatible with IOS < 7.  The version of OwnTracks that I see on the phone is 8.0.32 (according to General | Usage.  Is there a way to make it work on this old of phone and IOS?

Thanks,
Todd

**Comment by ckrey** [comment]
@toddeye there were a few things which became incompatible with iOS 6 before I noticed it.

Though, I will have a look if I can prepare a stripped down version.

Anybody else around still using a 3GS?

**Comment by ckrey** [comment]
I just changed the last compatible version for iOS < 7 to OwnTracks 7.5.1.

Please try to install and run it on your 3GS

**Comment by toddeye** [comment]
Thanks!  I will try again.  Appreciate the quick response.
