### ISSUE TITLE
libxpc.dylib

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#343]
#### in _xpc_api_misuse

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5617e82ef5d3a7f76bad1b1c](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5617e82ef5d3a7f76bad1b1c)

**Comment by ckrey** [comment]
happened only once on old 8.2.11 release.
