### ISSUE TITLE
Re-publish all Waypoints via MQTT

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#346]
same as owntracks/android#287

- Button in settings to publish waypoints to MQTT <basetopic>/waypoints
applies to Private mode only

- button in settings to publish configuration to MQTT <basetopic>/dump
applies to Private mode only

- command (`waypoints`) to publish all waypoints to MQTT <basetopic>/waypoints (similar to `dump` command)

**Comment by jpmens** [comment]
I note 8.3.2 has the Publish waypoints enabled for Hosted mode as well.

**Comment by jpmens** [comment]
This is fine as it is.
