### ISSUE TITLE
vel == -3 in 8.3.[01]

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#347]
Since 8.3.[01] `vel` is being published as -3 instead of -1. This is not a big issue but we should revert to previous behavior.

Ideally, we should not add `vel` element to the JSON if it isn't known (or set it to `null`?)

**Comment by ckrey** [comment]
fixed
+
vel, acc, vac, and cog are only published if valid (>= 0)

**Comment by jpmens** [comment]
Booklet updated.
