### ISSUE TITLE
Waypoint+Create.m line 35

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#348]
#### in __37-[Waypoint(Create) getReverseGeoCode]_block_invoke

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/562c3c2af5d3a7f76b0e70cb](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/562c3c2af5d3a7f76b0e70cb)

**Comment by ckrey** [comment]
happened only twice on old 8.2.11 version
