### ISSUE TITLE
StoreKit

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#349]
#### in -[SKRequest cancel]

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5630d08ef5d3a7f76b240509](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5630d08ef5d3a7f76b240509)

**Comment by ckrey** [comment]
testing artefact
