### ISSUE TITLE
Unreliable enter/exit event after latest iOS release

### ISSUE THREAD

**Issue by Shirk** [owntracks/ios#351]
Since updating enter and exit events have gotten mostly unreliable for me. 
I'm using Owntracks in manual mode with geofences for locations I'm interested in tracking. 

Before updating to the latest app store release these events would be triggered as expected about 99% of the time. 
With the current release I'm getting flaky events at best. 
Most times I'll see mqtt enter events for one fence without exit for the previous or even no enter/exit at all. 

- iPhone6 running iOS 9.1
- self hosted mode with mosquitto as broker
- only part that changed between reliable and flaky is the iOS app

**Comment by ckrey** [comment]
We already found the problem, it is related to a premature fix to #76 .
Will provide a fix soon.

**Comment by Shirk** [comment]
Glad to hear that - I rely a lot on Owntracks for my openHAB at home.
Any testing etc. I can do to help out?

**Comment by ckrey** [comment]
Fixed in 8.3.3 (to be available in the app store soon) and upcoming 8.4.x releases

**Comment by Shirk** [comment]
Nice, do you do TestFlight betas?

I could of course clone and build the sources for private tests but that way I could provide feedback on the real thing.

**Comment by ckrey** [comment]
Yes we do. I need your email-address to include you in public beta testing via Testflight (direct message to krey.christoph@gmail.com
