### ISSUE TITLE
Device Subscriptions for 'msg' and 'cmd'

### ISSUE THREAD

**Issue by jwende** [owntracks/ios#352]
Hi,
I'm just looking at the subscriptions generated by Version 8.3.2:
owntracks/jwende/ipadjw/cmd 
owntracks/user/ipadjw/msg
Looks to me a bit inconsistent ....

Anyway - any message sent to these topics don't trigger an action on my ipad ( I can see that messages are delivered by my broker)

Cheers
Joerg

**Comment by ckrey** [comment]
mmh,

I see here
```
owntracks/+/+ (QoS 1)
owntracks/+/+/event (QoS 1)
owntracks/+/+/info (QoS 1)
owntracks/<user>/<device>/cmd (QoS 1)

owntracks/<user>/<device>/msg (QoS 2)
msg/system (QoS 2)
msg/+/u1h (QoS 2)
msg/+/u1hg (QoS 2)
msg/+/u1hg0 (QoS 2)
msg/+/u1hg0p (QoS 2)

```

The first 4 subscriptions are not messages related.
The last 6 subscriptions are 
- user/device specific messages
- broadcase messages
- location based messages on 4 different levels of geohash

Can you share your configuration please?

**Comment by jwende** [comment]
This is my exported configuration:
{
  "host" : "192.168.178.34",
  "locatorDisplacement" : 200,
  "subTopic" : "",
  "usepolicy" : false,
  "validatecertificatechain" : false,
  "cleanSession" : false,
  "locked" : false,
  "mode" : 0,
  "tls" : false,
  "positions" : 50,
  "willRetain" : false,
  "deviceId" : "ipadjw",
  "extendedData" : true,
  "messaging" : true,
  "monitoring" : 2,
  "_type" : "configuration",
  "locatorInterval" : 180,
  "updateAddressBook" : true,
  "waypoints" : [
  ],
  "username" : "jwende",
  "tid" : "",
  "policymode" : 0,
  "willTopic" : "",
  "clientpkcs" : "",
  "ranging" : false,
  "keepalive" : 60,
  "willQos" : 1,
  "pubTopicBase" : "",
  "auth" : false,
  "passphrase" : "",
  "port" : 1883,
  "allowinvalidcerts" : false,
  "clientId" : "",
  "validatedomainname" : false,
  "pubQos" : 1,
  "allowRemoteLocation" : true,
  "password" : "pass",
  "subQos" : 1,
  "servercer" : "",
  "cmd" : false,
  "pubRetain" : true
}

Device: Ipad, iOS 9.1

Thanks
Joerg

btw: where can I find the advanced settings ?

**Comment by jpmens** [comment]
> btw: where can I find the advanced settings ?

We removed the advanced settings from the UI to simplify things for new users (there was just far too much there). If you want to set a particular setting use remoteConfig (a.k.a edit your config and send it back to your device)

**Comment by buhl** [comment]
I have the same issues. There is an old closed issue on the android app here https://github.com/owntracks/android/issues/281. The fix however did not work for me.

I can do
```bash
mosquitto_pub -t 'owntracks/<user>/<device>/msg' -q 2 -l
{"_type":"msg","prio":0,"title":"Library","desc":"Don't forget to return War and Peace","icon":"fa-book","tst":1435017442}
```
and receive them with
```bash
mosquitto_sub -t 'owntracks/<user>/<device>/msg'
```

But I never see the messages in the app.

I have tried the following topics:
 * owntracks/<user>/<device>/msg
 * owntracks/msg
 * /msg

My configuration:
```json
{
  "_type":"dump",
  "configuration":{
    "host":"<ip>",
    "locatorDisplacement":200,
    "subTopic":"",
    "usepolicy":false,
    "validatecertificatechain":false,
    "cleanSession":false,
    "locked":false,
    "mode":0,
    "tls":false,
    "positions":50,
    "willRetain":false,
    "deviceId":"<device>",
    "extendedData":true,
    "messaging":true,
    "monitoring":1,
    "_type":"configuration",
    "locatorInterval":180,
    "updateAddressBook":true,
    "waypoints":[],
    "username":"<user>",
    "tid":"",
    "policymode":0,
    "willTopic":"",
    "clientpkcs":"",
    "ranging":false,
    "keepalive":60,
    "willQos":1,
    "pubTopicBase":"",
    "auth":true,
    "passphrase":"",
    "port":"<port>",
    "allowinvalidcerts":false,
    "clientId":"",
    "validatedomainname":false,
    "pubQos":1,
    "allowRemoteLocation":true,
    "password":"<passwd>",
    "subQos":1,
    "servercer":"",
    "cmd":false,
    "pubRetain":true
  }
}
```
Any help/pointers on how to solve this is much appreciated

**Comment by ckrey** [comment]
When removing all messages by hitting the trash button in message window, user specific and systemwide message subscriptions are not renewed.

Workaround for current version: Swipe app out and restart
