### ISSUE TITLE
Delayed publish of enter/leave events

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#357]
One thing I noticed is that despite of receiving an "entered XX" notification on my phone it'll still take some time for the matching event to be submitted to the broker if the app is only running in the background (i.e. not actively opened once the notification was received).

via shirk

**Comment by ckrey** [comment]
I noticed that problem in background when on mobile data (non Wifi). 
The app has only limited time to establish the connection (including TLS handshake) and publish the queued messages when in background.
I will have a look if this can be a) optimized or b) the time given can be extended

**Comment by jpmens** [comment]
I've been seeing this as well (both retail & 8.4.9)

**Comment by ckrey** [comment]
The problem is found: The first messages from the app after waking up are sent before the connection is establised. Thats why they are put on hold for retry after 20sec. If in background this means transmission at the next connect only.
