### ISSUE TITLE
8.4.9 To...

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#358]
Is this supposed to be `Topic` ? ;-)

![image](https://cloud.githubusercontent.com/assets/60706/11103535/366b0350-88c3-11e5-81c7-3cae006c22c8.png)

**Comment by ckrey** [comment]
Yes, font sizes changed with iOS 9, need to review sizes / autolayout

**Comment by ckrey** [comment]
Changed size due to iOS9 font changes
