### ISSUE TITLE
Not publishing transition events

### ISSUE THREAD

**Issue by cpcowart** [owntracks/ios#359]
Hello,

I don't know exactly when this issue began, but I suspect it was around the 8.3.2 release. I only use Owntracks to geofence waypoints and publish enter/leave events. As such, I have always used it in the "Manual" mode. Near as I can tell, that's now the "Pause" mode.

I see the colored circles on the Regions sheet change colors when I enter/exit regions, but I do not see any queued messages on the Messaging sheet, nor do I see anything published on the queue.

I'm also no longer seeing the banner notifications on my phone that accompany entering and leaving a geofence area.

If I go into "Move" mode, I see location messages, but no transition messages.

My configuration is here:

{
  "host" : "www.example.net",
  "locatorDisplacement" : 200,
  "subTopic" : "",
  "usepolicy" : false,
  "validatecertificatechain" : false,
  "cleanSession" : false,
  "locked" : false,
  "mode" : 0,
  "tls" : true,
  "positions" : 50,
  "willRetain" : false,
  "deviceId" : "chris",
  "extendedData" : true,
  "messaging" : true,
  "monitoring" : 0,
  "_type" : "configuration",
  "locatorInterval" : 180,
  "updateAddressBook" : true,
  "waypoints" : [
    {
      "_type" : "waypoint",
      "tst" : 1446255749,
      "lat" : X,
      "lon" : Y,
      "rad" : 90,
      "desc" : "baz"
    },
    {
      "_type" : "waypoint",
      "tst" : 1446847126,
      "lat" : X,
      "lon" : Y,
      "rad" : 25,
      "desc" : "bar"
    },
    {
      "_type" : "waypoint",
      "tst" : 1446789389,
      "lat" : X,
      "lon" : Y,
      "rad" : 20,
      "desc" : "foo"
    }
  ],
  "username" : "owntracks",
  "tid" : "",
  "policymode" : 0,
  "willTopic" : "",
  "clientpkcs" : "",
  "ranging" : false,
  "keepalive" : 60,
  "willQos" : 1,
  "pubTopicBase" : "owntracks\/chris",
  "auth" : true,
  "passphrase" : "",
  "port" : 8883,
  "allowinvalidcerts" : false,
  "clientId" : "chris",
  "validatedomainname" : false,
  "pubQos" : 1,
  "allowRemoteLocation" : true,
  "password" : "*****",
  "subQos" : 1,
  "servercer" : "",
  "cmd" : false,
  "pubRetain" : true
}

**Comment by jpmens** [comment]
Possibly related to https://github.com/owntracks/ios/issues/357

**Comment by ckrey** [comment]
see #351 

Anfang der weitergeleiteten Nachricht:

Von: iTunes Store <no_reply@email.apple.com>
Datum: 13. November 2015 um 03:07:51 MEZ
An: krey.christoph@gmail.com
Betreff: Your app status is In Review

The status for the following app has changed to In Review.

App Name: OwnTracks
App Version Number: 8.3.3
App SKU: MQTTitude-1.8
App Apple ID:692424691

**Comment by cpcowart** [comment]
Hello,

This problem has been greatly reduced in the new version, but I am still having at least 10% of my messages go unpublished.

The previous behavior was that OpenTracks created an alert indicated an unsent message. If I subsequently launched it in the foreground, the queued messages would be sent.

The current behavior seems to be that OpenTracks does not queue messages that failed to send; they just disappear. This is proving to be very unreliable for controlling the lights at my house. :(
