### ISSUE TITLE
Location flapping constantly

### ISSUE THREAD

**Issue by hyperbolic2346** [owntracks/ios#360]
I have a home location that is a couple hundred meters and at times I see the enter and exit events occur very rapidly. This happens when my phone is asleep or awake. I have hundreds of notifications at times. When I click the i inside the app I will see the location error anywhere from +- 100m to even +- 5500m. When the application is open the error quickly jumps down to 100ish meters and will stay there, but once in the background things can go crazy and going back to the app will temporarily show massive error.

Any idea what could be causing this for me and, better yet, how I can fix it?

**Comment by ckrey** [comment]
I think it might be related to the quality of GPS/CELL/Wifi signals in your home. I assume the iPhone powers GPS down when asleep.
What you can do is to prefix your region name wit `-`. This holds down the leave event for a few seconds. If an enter event is triggered eithin that time, both events are suppressed

**Comment by hyperbolic2346** [comment]
Thanks for the help here, I am going to try that. Will this impact the published name of the location?

**Comment by hyperbolic2346** [comment]
I have changed the name of my location to -home and when I was changing my mail password on my phone the location flapped 10 times. Is there something else I can do here or some other way to figure out what might be going wrong?

**Comment by ckrey** [comment]
I have no idea, but maybe we go through some points I can think of:

What Mode do you use (Move ⏩, Significant Changes ▶️, Manual ⏸, or Quiet ⏹)?
When you put OwnTracks in Foreground or Background, which Location symbol is shown in the Statusbar (⬈ or⬀ or none)?
Do you have Wifi on or off?
Which radius does your position show on the map display of OwnTracks (blue-ish circle aroud the blue position circle)?
If you go to another map app (Apple or Google), which radius is displayed there.
Does the position or radius change although you are not moving?
Do you use other location-aware apps?
Do you have a large number of regions defined?

**Comment by hyperbolic2346** [comment]
I am using significant changes.
In the foreground and background I see a solid arrow for location services. I will verify it is there when it is flapping.
Wifi is on, but most things that guess my location from IP have me in the adjacent state about 100 miles away, which is where the internet provider's data center is for me. Unsure if this could be related.
The radius is currently small, but I can't tell how big it is. If I select the i icon I see +-65m currently.
Google maps appears to show the same radius.
When it is flapping the position shown in owntracks will jump around a massive amount. It shows me at my home and then a state and a half away for a blip and then back at my house. It is like the error jumps from absurdly large to normal and back very quickly.
I use google maps and apple maps and haven't had an issue with either, but I admit that I use owntracks much more and it also tells me when this location jumping is happening. I will open google maps next time it is flapping and see if google maps shows the same issue.
I have a single region that is defined as 150 meters.

**Comment by hyperbolic2346** [comment]
Ok, during flapping Google Maps shows me all over the place as well. I think I can claim this is some OS or hardware issue and nothing with OwnTracks. Any idea where I should go from here?
