### ISSUE TITLE
iBeacon monitoring only

### ISSUE THREAD

**Issue by svrooij** [owntracks/ios#367]
I think it would be nice to be able to only monitor iBeacons. That way it should only show the ⬀ (not filled arrow)
That would save battery I think.

Am I mistaking that this is not yet possible?

**Comment by ckrey** [comment]
It is already possible:
If you put OwnTracks into Manual Mode (pause symbol) it only publishes on region enter/leave or manually.




When you bring OwnTracks up on screen, the symbol changes to solid because the map is displayed with the current location indicator.

**Comment by svrooij** [comment]
Thanks for the help!
