### ISSUE TITLE
beacon ranging has to stop when in background

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#370]
otherwise, MQTT connection will be terminated un-gracefully

**Comment by cmsimike** [comment]
Hi,

I just enabled ranging today and noticed that I stop getting MQTT updates when the app is in the background. Quick googling lead me here.

Is there no work around to continue ranging while the app is in the background?

**Comment by jpmens** [comment]
There is not. The app is put to sleep when it's backgrounded and that would kill off the MQTT connection. That's a "feature" of iOS we cannot overcome.

**Comment by cmsimike** [comment]
I guess my question is what is the difference between this MQTT funcitonality where as enter/leaving ibeacons, and gps location updates can be pushed to my MQTT server in the background?

**Comment by jpmens** [comment]
When your app is in the background it is woken up periodically (by the OS), connects to your MQTT broker, publishes a location, and disconnects; the app has but a few seconds in which it can do it (before it's "killed off" again). Similarly on enter/leave, these regions are monitored by iOS and wake up the app to do its thing before putting it to sleep again.

**Comment by cmsimike** [comment]
@jpmens I really appricate the responses here! 

Background ranging is a pretty big deal for me in the context of my home automations as I feel this is the best method we have currently to do user-specific room-level awareness, so please excuse me if I end up asking too many questions. 

Given that, I've been diving into different resources about ranging on iOS, and I did find something promising:

https://forums.estimote.com/t/ranging-beacons-in-background-is-that-possible/151/5

I'm hoping with someone with more iOS dev knowledge than me can check this out and see if there is anything hugely objectionable here, and if not, whether this is something that would be accepted back into the Owntracks codebase?
