### ISSUE TITLE
MQTT session present always returns false

### ISSUE THREAD

**Issue by usersilpa** [owntracks/ios#373]
I am using the sessionPresent property for knowing whether there exists an active MQTT connection or not. Checked just after connection and subscription even though the sessionPresent property of MQTTSession is always getting false.

checking the same in connection call back
- (void)connected:(MQTTSession *)session
 
and also checking the session present in 
- (void)connected:(MQTTSession *)session sessionPresent:(BOOL)sessionPresent 

In both the above cases it returns false which is unexpected. Why this is happening? 
Is this the right way to check the connection existance? If not please suggest the appropriate method.

**Comment by ckrey** [comment]
If you are referring to the MQTTClient framework, please post your issues here:
https://github.com/ckrey/MQTT-Client-Framework/issues

ANSWER:
When connected is called, the session is connected.
This may obviously change any time.

To check, test session.status == MQTTSessionStatusConnected
or wait for the disconnected callback.

The session present flag has a special meaning and indicates if the broker
still has session information about the last session with the same client id. Further reading:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.pdf

**Comment by usersilpa** [comment]
Thanks @ckrey .
It worked.
