### ISSUE TITLE
Credits need cutting

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#374]
Credits page in 8.5.4 erroneously mentions Fabrics/Crashlytics

![image](https://cloud.githubusercontent.com/assets/60706/12763522/264852a2-c9f5-11e5-8ab7-2d57568e6598.jpeg)

**Comment by ckrey** [comment]
![bildschirmfoto 2016-02-03 um 08 06 36](https://cloud.githubusercontent.com/assets/4027289/12775318/4f6e7cc6-ca4d-11e5-9167-acc7daa4b804.png)
