### ISSUE TITLE
Latitude and Longitude get rounded when regions are modified

### ISSUE THREAD

**Issue by cpcowart** [owntracks/ios#376]
Owntracks 8.3.3 on iOS 9.2.1

Touch the center of the map to create a region.

Publish settings.

The waypoint is created with 14 decimal figures of latitude precision and 13 decimal figures of longitude precision. The waypoint will display at precisely this location on the map. When you view the published settings, you can see that this precise value is the current internal representation.

Open the Regions view. Here, the location is displayed with only 4 decimal figures of latitude and 3 figures of longitude. Change an attribute (e.g., name or radius).

Go back to the map. The pin for the region has moved.

Publish settings.

The rounded, significantly less precise latitude and longitude that were displayed by the Regions UI have been saved to the internal representation that gets published.

Workaround: If you add precision back manually using the Regions UI, what you type will save. After reopening the Regions sheet and altering any other attribute of the region, you will lose your precision again.

I don't know exactly when this issue was introduced, but it is 100% reproducible for me.

**Comment by ckrey** [comment]
lat and lon are displayed with %g (6 significant digits by default) everywhere in the app.
Formatting using %g is done when displaying in RegionsUI too.
If values change, the displayed value is converted back to double, causing the loss in precision.

**Comment by ckrey** [comment]
Fixed:
lat, lon now display and 14 decimal digits
radius displays no (zero) decimal digits
