### ISSUE TITLE
Certificate error connecting to broker - 'peer did not return a certificate'

### ISSUE THREAD

**Issue by mabnz** [owntracks/ios#379]
After upgrade to 8.5.5, TLS authentication fails. Mosquito reports 'peer did not return a certificate'. 

Feb 11 19:09:51 mgmtnuc mosquitto[716]: OpenSSL Error: error:140890C7:SSL routines:SSL3_GET_CLIENT_CERTIFICATE:peer did not return a certificate

No config has changed on the client, certificate is still valid. Only after upgrading this morning to 8.5.5. Client returns 'The operation couldn't be completed. (OSSStatus error -9829.).

**Comment by ckrey** [comment]
I can't simply reproduce here.
Would you share a screenprint of your SLL settings with me, please:
![simulator screen shot 11 02 2016 09 09 11](https://cloud.githubusercontent.com/assets/4027289/12971815/62388db2-d09f-11e5-8c84-8fb76bdf92c8.png)

**Comment by mabnz** [comment]
See attached

**Comment by ckrey** [comment]
attachments are not uploaded when answering to a github issue via mail - unfortunately

**Comment by mabnz** [comment]
![image](https://cloud.githubusercontent.com/assets/150990/12971938/736b8b96-d105-11e5-8adc-b8d0a3ac2eac.png)

**Comment by ckrey** [comment]
Thanks, reproduced

**Comment by ckrey** [comment]
@mabnz if you send me your email directly to krey.christoph@gmail.com, I will have a beta version for you to test by tomorrow

**Comment by mabnz** [comment]
Thanks ckrey, have you managed to build a version for me to test?

**Comment by ckrey** [comment]
yes, there was an itunes connect hickup yesterday. will release to beta when home

**Comment by mabnz** [comment]
Thanks :)

**Comment by n8henrie** [comment]
I am having this issue again -- did something change?

**Comment by n8henrie** [comment]
Darn, continued messing with those settings and now in what seems to be an unrecoverable crash-on-launch loop, resistant to closing out the app (swipe up) and a device reboot.

**Comment by n8henrie** [comment]
I went back and just disabled `require_certificate` in mosquitto for now. I'd prefer to leave that enabled, but I'm having a hard time figuring everything out.
