### ISSUE TITLE
Crash on (I)

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#381]
8.6.5 opened. Red bar shows connection trouble. I tap on (I) to see the error message. App crashes. After restarting it, connection is fine.

**Comment by jpmens** [comment]
version 8.6.5

**Comment by ckrey** [comment]
Unfortunately, I don't see a crash dump in iTunes. It may turn up when you connect your device to your mac next time

**Comment by jpmens** [comment]
"Copying diagnosting information" is complete.

**Comment by ckrey** [comment]
No crash report received here

**Comment by jpmens** [comment]
Made available to you offline

**Comment by ckrey** [comment]
probably fixed
