### ISSUE TITLE
Addresses returned from reverse geocoding should be more compact

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#385]

**Comment by ckrey** [comment]
![simulator screen shot 28 02 2016 19 06 02](https://cloud.githubusercontent.com/assets/4027289/13380917/55e8f6f2-de4e-11e5-9336-5a590b413bb7.png)

**Comment by jpmens** [comment]
The time is **bold** which looks a bit overpowering; can you "thin it out"?
