### ISSUE TITLE
Loss of data when changing mode or reopening app after crash

### ISSUE THREAD

**Issue by elyobelyob** [owntracks/ios#387]
Hi,

I've a couple of scenarios where I lose data. They both happen when collating data offline on an iPhone.

Firstly, if I change the mode I am in e.g. from move mode to significant change mode, the previous data is erased.
If the app crashes, and I reopen, the previous data (although shown on the app number counter) is then reset to zero.

I understand the privacy data removal when changing the host, but in these situations, I would like the data to remain. Especially with the increased storage fix coming soon.

Thanks
Nick

**Comment by ckrey** [comment]
Please clarify:

When we use the term "app mode", we mean either "Private", "Hosted", or "Public" mode. And yes, if you change the mode, all your data is reset to prevent sending your private data to a broker you may not want it to be sent to.

The other thing is "monitoring mode", which is "Move", "Significant Changes", "Quiet" or "Silent" mode. Changing between these modes is not supposed to clear any queued data. I am not able to reproduce the data loss by changing "monitoring mode" here, neither in off-line nor in on-line. Would you explain the exact steps you do to create the problem?

If the app crashes and is reopened things may go wrong. Can you try to describe how you make the app "crash".

**Comment by elyobelyob** [comment]
I recreate this when on a plane easily. I have 200+ stored points and change the mode ie from move into significant mode and then back into move and I have lost all my earlier points. I'm about to jump on another plane, anything I can do to help log this? I am not chasing the app mode from private, just the monitoring mode. My phone is in flight mode when doing this. I am running an iPhone 6 Plus on the latest 9.2.1 firmware.
In terms of crashing, this happens when on a plane mainly. I don't have the app open at the time, just running in background. I have also had it crash when on a motorbike, it was logging then I discovered it had failed when at destination. I can't give any clues but if there is a log, I will happily provide it next time it happens.

**Comment by elyobelyob** [comment]
At the time it reset I had over 250 points. It's not happened the once, it's happened each time. I've not edited the app mode from private as I have no need.

**Comment by elyobelyob** [comment]
I worked out what it was on my flight a few minutes ago. It's restarting the app that loses all the points. Nothing to do with the mode, that was a red herring as I was messing about with it on last flight. So, if I close the app (double home and swipe app up) it retains the message numbers, but as soon as app opens, it clears this cache of data.

**Comment by jpmens** [comment]
You should not swipe out the app; there's absolutely no reason to do that. (If you're doing it to "conserve RAM" or battery, that's an old wives tale. :)

**Comment by elyobelyob** [comment]
I was testing the "crash", it definitely had the same behaviour when I reopened the app when I noticed the notification number had stopped climbing. In either situation the cache data was cleared and reset to zero.

**Comment by ckrey** [comment]
@elyobelyob thank you so much for making the problem easy to reproduce. It is a bug in the persistence layer. Will be available with 9.0.8

**Comment by ckrey** [comment]
Sorry, the fix works but causes deadlocks

**Comment by elyobelyob** [comment]
I couldn't see on my phone what the fix was but migration to MQTT version.
But I have limited resource travelling. I'd be interested as I may get time
to learn and delve in myself. At least it's highlighted, I've moved into
switching modes more and that's rock solid.
Also, not really an iOS developer, but get the languages.

**Comment by elyobelyob** [comment]
I also have another issue, but it's very, very specific. Can I offline you
about it?

**Comment by ckrey** [comment]
Sure, mailto:krey.christoph@gmail.com
