### ISSUE TITLE
Significant mode not happening at 800kph

### ISSUE THREAD

**Issue by elyobelyob** [owntracks/ios#388]
As mentioned, I was unsure how significant mode worked as I expected it to work well in flight mode on my iPhone. I tested again today and it would not mark at all - left for15-20 mins before adding a manual marker. Submitting images direct to Christoph as unable to upload on my phone.

**Comment by ckrey** [comment]
As far as I know from the iOS documentation, Significant Changes Mode (SCM) relies on Wifi and Cell tower positioning, which are both off in Airplane mode. In SCM, GPS is not used to save battery.

I will add some test cases for the future in SubSonic and SuperSonic mode ;-)

**Comment by ckrey** [comment]
Speedometer uses an logarithmic scale, but overruns if > 400km/h
![bildschirmfoto 2016-03-04 um 17 49 15](https://cloud.githubusercontent.com/assets/4027289/13533626/92453d9a-e231-11e5-97ad-393411cb0ed1.png)
![bildschirmfoto 2016-03-04 um 17 49 24](https://cloud.githubusercontent.com/assets/4027289/13533627/926f9266-e231-11e5-89d3-df685b7f6a12.png)

**Comment by elyobelyob** [comment]
OK, shame as it'd be ideal for that. A quick email to Apple then.... Feel
free to close. May be worth adding to docs though.

**Comment by ckrey** [comment]
The speedometer display is under our control. Will change

**Comment by elyobelyob** [comment]
So those speeds were all well off then? Seemed reasonable to me. Kph, not mph.

**Comment by jpmens** [comment]
@elyobelyob I can't resist asking: does Move mode work at your speeds?

Oh, and next time you touch down in our vicinity, I want to buy you a beer! Honestly.

**Comment by elyobelyob** [comment]
To me today, a change in direction, speed or constant altitude speed were the important parts of following a flight. Perhaps there is a possibility of a specific mode to track these only.

**Comment by elyobelyob** [comment]
@jpmens I have no problems with move mode except the limit of points, which I'm still hanging on for. But following a 12 hr flight and then uploading later seems overkill. Another point I've been wondering is whether it's possible to limit the flow to MQTT once back in the world of the Internet. It seems to throw an awful lot of requests at once, which my server handles, but I'd prefer to limit to say 10/second.

**Comment by elyobelyob** [comment]
Not MQTT being the issue, but any subscriber having to deal with that. In other words my php script to MySQL.

**Comment by jpmens** [comment]
We already throttle that a bit IIRC. You can adjust your Mosquitto installation to accept fewer inflght messages which ought to help on your end.

**Comment by jpmens** [comment]
To avoid misunderstanding: we're aware of the 100 points limit you're hungering after. Christoph had applied a patch, but we had to pull that back because it froze the app completely in our testing. To be clear, you'll need a bit of patience for that, but rest assured, we are on it!

**Comment by elyobelyob** [comment]
The 1025 limit is the one I'd love right now, I'll beta test if possible, I did apply. The issue with persistence got rolled back. I had no crashes today in the software and didn't do the swipe up test either :) where do we have the beer?

**Comment by elyobelyob** [comment]
I upload the data as soon as I land, managed 1025 limit just as we hit the gate. :)

**Comment by elyobelyob** [comment]
I've also a Spot GPS with me that has become entirely redundant due to owntracks :)

**Comment by jpmens** [comment]
That's the spirit!! Glad to hear that.

The beer we'll have in Hannover. That's 1/2 way for Christoph and me and you get to then meet Alexander, who does our Android app. The whole OwnTracks organization at once, if you will. :smiley:

**Comment by elyobelyob** [comment]
Definitely on. A weekend on my motorbike in late April / early May would be
fun. Nice to tie it in with an event in Hanover.
