### ISSUE TITLE
Font issue on Friends geo-locator

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#391]
I'm not sure whether this is a bug or an artifact of a 4-line address:

![image](https://cloud.githubusercontent.com/assets/60706/13844776/bb8c266c-ec33-11e5-80b6-2e0754a8e8f3.jpeg)

**Comment by ckrey** [comment]
it is an artefact of a 5 line address.

The label is configured to autoshrink the font size to accomodate up to 4 lines. I changed it now to up to 5 lines. This will eliminate the `...`overflow indicator.

**Comment by ckrey** [comment]
This is the new look with _very british_ 5-line address

![bildschirmfoto 2016-03-17 um 13 39 46](https://cloud.githubusercontent.com/assets/4027289/13846220/dd3d6764-ec45-11e5-873e-c883ab7bdad0.png)
