### ISSUE TITLE
TLS options for iOS app

### ISSUE THREAD

**Issue by arnaudmm** [owntracks/ios#397]
Hello,

How to set ca.crt in iOS app? I got everything working fine with Android app but I can't locate where to set the ca.crt in options with iOS

Thanks

**Comment by jpmens** [comment]
Import your CA root certificate by sending yourself an e-mail and install it in the typicall iOS profile. 

If you mean other options, they're in Settings, TLS, then click on the `(I)`.

**Comment by arnaudmm** [comment]
Ok, got it, it is working now, thank you
