### ISSUE TITLE
Location stops updating in iOS 9.3 in background

### ISSUE THREAD

**Issue by kudaras** [owntracks/ios#399]
I am not sure if this is a bug or some sort of configuration issue but OwnTracks stops updating the location after some (random) time when in background (the app closed). The problem seems to be similar to #307 but my app is in Move mode. All the relevant permissions are enabled in iOS (and it does publish the location in background for a while until it stops for some reason).

I am using iPhone 5S with iOS 9.3 and Owntracks 9.1.0 from App Store. Is there any other info that I could provide?

**Comment by jabesq** [comment]
Same bug seen with ios10, but it seems to works in "significant move" mode

**Comment by ckrey** [comment]
Fixed authorisationrequest for iOS 9.3 iOS 10
