### ISSUE TITLE
iOS Region Monitoring Limit of 20

### ISSUE THREAD

**Issue by tySwift93** [owntracks/ios#400]
I am assuming that OwnTracks uses Core Location's Region Monitoring.  If that is the case, then there should probably be a limit on how many OwnTracks regions a user can enter, or the user should at least be informed that having more than 20 'monitored regions' will cause the phone to start ignoring all new regions added in the future.

This is all detailed here: 

[https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/LocationAwarenessPG/RegionMonitoring/RegionMonitoring.html#//apple_ref/doc/uid/TP40009497-CH9-SW1](url) 

in the section titled **Monitoring Geographical Regions** in subsection _Defining a Geographical Region to Be Monitored_

On a separate note, there is an SDK for iOS (I believe also for Android, but not sure) called LocationKit ([https://github.com/LocationKit/LocationKit-iOS](url)) that allows developers to have an 'unlimited' number of monitored regions, as the code will dynamically add and remove regions depending on your location!  Additionally, the SDK is shockingly good at maintaining a super accurate location without adding much more (if any) battery drain than OwnTracks's Significant mode.  These features might be useful for OwnTracks.  It works perfectly in my own tests.

**Comment by ckrey** [comment]
Thanks for your remark. I think the warning message would be helpful when the regions are entered via the UI, but will not help when setting up the regions via MQTT or configuration file.

Dynamically adding and removing regions might be a good workaround for the limitation if a large number of regions are necessary.

LocationKit is not an option for OwnTracks as LocationKit is gathering data of its users.
