### ISSUE TITLE
Crash on null url for Featured

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#402]
`{"action": "action", "url": null, "_type": "cmd", "tst": 1461323509}`

**Comment by jpmens** [comment]
This also crashes the app: 

```
{"action": "action", "content": null, "_type": "cmd", "tst": 1461323691}
```

And yes, I am aware that these elements ought not to be null, but I think this shouldn't be happening anyway.

**Comment by ckrey** [comment]
Problem found and solved:

{"key":1}  -> NSNumber
{"key":"1"}  -> NSString
{} -> nil
__{"key":null}  -> NSNull__

**Comment by jpmens** [comment]
Confirmed working; thanks.
