### ISSUE TITLE
OwnTracks considers multiple ibeacons the same if they share UID + Major

### ISSUE THREAD

**Issue by cmsimike** [owntracks/ios#404]
Hi,

I have 3 ibeacons in my apartment. They share a UID and they share the same major (0) however differ only in minor: (1-3).

In iBeacon, i then have 4 regions setup. one for home (which scans for the UUID and major/minor of 0), living room (uuid, major:0, minor:1), bed room (uuid, major:0, minor:2) and second bedroom room (uuid, major:0, minor:3).

OwnTracks seemed to have think they were all the same iBeacon in this configuration.  I confirmed this behavior as I had disabled 2 of the 3 ibeacons, but all the regions continued to be red.

I ended up trying to trouble shoot this as, to my knowledge, this should work as I expect, meaning given the above, owntracks should see each individual ibeacon.

I ended up keeping the UUID the same across the board, but changed the major to match the minor, meaning now i have UUID major:1, minor:1, major:2, minor:2, major:3,minor:3. This allowed owntracks to see each ibeacon and properly showed ibeacons as not being connected when they were off.

**Comment by jpmens** [comment]
Did you configure uuid/major/minor using the region `desc`ription (with the colon in it [as described here](http://owntracks.org/booklet/features/beacons/) in the example) or using the fields at the bottom of the screen? If the latter, would you please test the former? That should work.

**Comment by ckrey** [comment]
You should not use 0 (zero) for major or minor, because the meaning of zero is "any".

This means the app works as designed because it matches all beacons. If you use major = 1 and minor = 1, 2, and 3. Everything will work as expected

**Comment by cmsimike** [comment]
@ckrey that is the other thing i assumed (which is why this is more of a question (which i just realized i left the question label off)).

I am happy with that knowledge, nothing needs to be done AFAIC. Thank you for the reply.


@jpmens it was the latter. I will try it out if i get an opportunity but i am happy with the setup i have now.
thanks all!
