### ISSUE TITLE
Event Status Not Sent in iOS app v.9.1.6

### ISSUE THREAD

**Issue by dathbe** [owntracks/ios#405]
I'm brand new to OwnTracks (thank you!).  I've gotten just about everything working except the event status updated on my iPhone.  When I use the Android tablet app and enter/leave a defined region, it will post a message to `owntracks/<user>/<device>/event` with `"_type":"transition"`.  But it does not do this for my iPhone.  I get neither a `"_type":"transition"` message nor a `"_type":"location"` message with an `event` tag (the documentation is unclear as to which I should be getting, perhaps it was changed at some point).  I AM receiving regular `"_type":"location"` messages, and **sometimes** my wife's phone will get a notification that I've entered or left a region, but I have yet to see a message while monitoring the MQTT topics `owntracks/<user>/<device>` and `owntracks/<user>/<device>/+`.
Details:
OwnTracks 9.1.6 running on iPhone 5s
Mosquitto broker running on Raspbian Jessie
Monitored through Eclipse Paho on Win10 (and mosquitto_sub command on Pi)

**Comment by jpmens** [comment]
You should be seeing `owntracks/user/device/event` with an appropriate `_type: transition` payload, in particular because your wife's device is getting that notification you say; this is possible only because of our messages to your broker. :-)

The ACLs on your Mosquitto broker appear to be correct (b/c of the reasons specified above), so I'm assuming your `mosquitto_sub` isn't allowed to subscribe to that topic. Would that be a possibility?

**Comment by dathbe** [comment]
I haven't set any ACL permissions yet.  It's just my wife and I, so I set it to where we can both see everything (I may change that once my install is more stable).  

I'm definitely receiving messages at `owntracks/user/device` for all devices (wife's iPhone, my iPhone, my Android table), I'm also receiving `owntracks/user/device/waypoints` and `owntracks/user/device/dump` from the various devices.  And I can see `owntracks/user/device/event` from the Android, but have yet to see anything from my iPhone even though I've set up a small region inside my house so I can move the phone in and out of it easily.  The region IS turning blue and red depending on where I am, but there just aren't any messages posted to the broker (or at least it's not every time I enter or leave).

**Comment by jpmens** [comment]
How small is the 'small' region? You may well see that anything below 50m radius can pose a problem.

**Comment by dathbe** [comment]
That could be it -- it's only 8m!!  I'll test it out with a bigger region and let you know.

**Comment by dathbe** [comment]
The larger region seems to have worked.  Thanks!

**Comment by ckrey** [comment]
assume answered
