### ISSUE TITLE
App has stopped generating enter/leave events

### ISSUE THREAD

**Issue by cpcowart** [owntracks/ios#406]
Hello,

I'm troubleshooting an issue where enter/leave events appear not to be triggered on the app. I'm running OwnTracks 9.1.6/en_US and iOS 9.3.2 on an iPhone 6.

I have 3 geofenced areas. About 72 hours ago, my last "enter" event showed up on my queue. In the intervening time, I have entered and left every geofenced region several times, but not a single message was published to the queue during this time. I am also not receiving any iOS notifications regarding the enter/leave events (generally, I get a notification on every enter and leave). I am not seeing a red notification / unread indicator on OwnTracks indicating a queued message that failed to send in the background.

This evening, in order to troubleshoot, I tried launching, killing, relaunching the app, restarting my mqtt instance, and restarting my iPhone. I tried walking out of the geofenced area and coming back. The behavior is unchanged.

If I open up the app, my regions change from blue to red and back to blue again, corresponding with my enter/leave activity. But still no iOS notification, no message on the bus, nothing.

The settings screen shows that I am connected (as does netstat/tcpdump on the server). If I enter and leave the settings screen, I do get a message published to the bus: `owntracks/chris {"t":"u","tst":1465277241,"acc":65,"_type":"location","alt":1,"lon":-122.X,"vac":10,"p":101.0306625366211,"lat":37.Y,"batt":65,"tid":"IS"}.

I have previously had issues with intermittent publish failures (#375), but this consistent and completely reproducible behavior is much different.

I'd really appreciate any help you can spare on this. The rules controlling my lights don't work very well if the system doesn't know whether I'm home.

Thanks!

**Comment by cpcowart** [comment]
For what it's worth, uninstalling and reinstalling the app did not change the behavior either.

But my partner came home today, and his app (same version of Own Tracks and iOS) published an enter event even though he hasn't launched the app manually in ages.

**Comment by jpmens** [comment]
Are your regions set to a low radius? I think anything below 50m can be "difficult".

**Comment by cpcowart** [comment]
I have my regions set between 50 and 80 meters.

One of the troubleshooting steps I took (restarting the broker, reinstalling the app, rebooting my phone) appears to have fixed the problem. I wasn't walking far enough outside the geofence to get it to trigger the other evening. 

This is probably not going to be reproducible at this point, so I'm just going to close it.

Thanks for your help!
