### ISSUE TITLE
All configured regions disappear

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#409]
9.1.6 on iPhone 5S with iOS 9.3.3

I suddenly realized `enter` / `leave` events are no longer being transmitted. Upon opening the app I see that all configured regions have disappeared. The only explanation I have for this is that it happened during iOS update to 9.3.3, but I cannot say with certainty whether that is the case because I don't know exactly when I did it.

I mention this for the record; it's probably not an OwnTracks iOS bug.

**Comment by jpmens** [comment]
Correction: it's probably not due to the upgrade. Last event on `2016-07-17 00:31:21` and I did the upgrade on [2016-07-21](https://twitter.com/jpmens/status/756080885393420288) 😄

**Comment by tomjmul** [comment]
I've noticed they all disappear when I changed from MQTT to HTTP

**Comment by jpmens** [comment]
@tomjmul This is not a bug; it works as designed. When switching modes, configuration is "wiped" for the target mode.
