### ISSUE TITLE
Ignore _old_ location pubs

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/ios#410]
Ignore any retained location pubs that are older than *n* days (configurable?). Means spurious retained pubs that are left lying around by old devices/users don't pollute the app (without having to clear those topics).

**Comment by jpmens** [comment]
Please not yet another config entry. Nail it to 10 or 30 days and be done with it.
If at all.

**Comment by sumnerboy12** [comment]
The more the merrier! I miss being able to configure the base topic!! ;)
But yes, sensible default of 30 days works.

**Comment by jpmens** [comment]
[more comments](https://github.com/owntracks/android/issues/401)

**Comment by ckrey** [comment]
it is configuration parameter `ignoreStaleLocations`. This is an int and means days. The default is 0 (zero) and is interpreted as show all locations.
