### ISSUE TITLE
Enable Remote Commands

### ISSUE THREAD

**Issue by travisghansen** [owntracks/ios#411]
I see in the android app how to enable remote commands but I cannot find the corresponding option in the iOS app.  Any tips?

I'm attempting the idea spelled out here: http://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/

**Comment by travisghansen** [comment]
I also just noticed a 'Messaging' tab on screenshots.  What is that and how is that enabled as well?

Thanks!

**Comment by ckrey** [comment]
Hi Markus,

"I remember having a messaging window where all the announcements showed up and where I could send custom messages to.
Is that gone or did I just not find it in the new UI?"

Oh yes, we experimented with Location Based Messaging and tried to find partners for content. But this did - unfortunately - not work out well.

So we decided to remove Messaging but introduce a "Featured Content“ functionality, which is limited to one topic and one message at a time.

It pops up on the tab bar when a new message arrives and renders plain text, html, or calls an external app (e.g. browser).

We did not update the booklet comprehensively, but the links below should help.

http://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/
https://github.com/owntracks/ios/issues/380
http://owntracks.org/booklet/tech/json

**Comment by ckrey** [comment]
http://owntracks.org/booklet/features/featured/#featured

**Comment by travisghansen** [comment]
@ckrey yeah, so messaging aside I can't seem to figure out how to enabled remote commands for iOS.  Any help you can provide would be great!

For example, I've tried sending ```{"_type":"cmd","action":"reportLocation"}``` to an iOS device and it does nothing, the same data sent to an android client triggers a location report.

I'm guessing if I get cmd's in general working I'll be able to make the featured tab work correctly as well.

**Comment by jpmens** [comment]
Remote commands need to be enabled with remoteConfig: export your configuration, add `cmd: true`, and re-import (e.g. by sending the `.otrc` file to iOS and open in OwnTracks).

Once you've done that, you can send remote commands. Note though, that the iOS app is put to sleep by the OS which means that when it's in the background you will have to wait until it wakes up for the command to take effect / be processed; this can take a while. Hence we suggest you post commands to iOS with QoS=2

**Comment by travisghansen** [comment]
@jpmens ok great!  I'll try it out and report back.

**Comment by travisghansen** [comment]
I've confirmed both the import and the featured items working.

A couple notes:

1. Setting that via the interface like the android app is ideal.
2. I tried sending a bare minimal config
```
{
  "_type": "configuration",
  "cmd": true
}
```
Which seemed to work fine *except* it deleted the configured password for the mqtt server.  I doubt that's desired behavior but perhaps.

Thanks!

**Comment by ckrey** [comment]
@binarybucks how is the config load via MQTT triggered?

Like `setWaypoints`?
```
{"_type":"cmd","action":"setWaypoints","waypoints":[...]}

```

**Comment by jpmens** [comment]
> It's just a plain configuration message like the normal import published to `owntracks/user/device/cmd`

**Comment by ckrey** [comment]
Do you all mean the app should process incoming `{"_type":"configuration",...}` messages without respecting the `cmd` flag set?

I would prefer to do it like

`{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration",...}}`
and check `cmd`before doing it.
