### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by DaElf** [owntracks/ios#415]
I'm having trouble getting started with the build.
Apparently I don't have a needed library?

ld: warning: directory not found for option '-L/Volumes/data/upstream/owntracks-ios/OwnTracks/Build/Products/Debug-iphonesimulator/ABStaticTableViewController'
ld: warning: directory not found for option '-L/Volumes/data/upstream/owntracks-ios/OwnTracks/Build/Products/Debug-iphonesimulator/CocoaLumberjack'
ld: warning: directory not found for option '-L/Volumes/data/upstream/owntracks-ios/OwnTracks/Build/Products/Debug-iphonesimulator/MQTTClient'
ld: warning: directory not found for option '-L/Volumes/data/upstream/owntracks-ios/OwnTracks/Build/Products/Debug-iphonesimulator/QRCodeReaderViewController'
ld: warning: directory not found for option '-L/Volumes/data/upstream/owntracks-ios/OwnTracks/Build/Products/Debug-iphonesimulator/libsodium'
ld: library not found for -lABStaticTableViewController
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Some build / setup instructions would be nice.

**Comment by DaElf** [comment]
Getting closer but still running into errors.

Check dependencies

OwnTracksToday requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
Code signing is required for product type 'App Extension' in SDK 'iOS 10.0'

**Comment by ckrey** [comment]
I cannot do an iOS/XCode programming class here.

But to run an iOS app on a real device, you need to register as an iOS developer. Then you may register your own apps and create provisioning profiles for it.
