### ISSUE TITLE
iOS 10 issues?

### ISSUE THREAD

**Issue by elyobelyob** [owntracks/ios#416]
Hi,

I'm away again and have updated my OS to iOS 10. I now don't get any real background refresh at all. I used to have to restart owntracks twice a day or so, but now get no real tracking once closed.

I'm posting to a private, authenticated MQTT server.  Own tracks is allowed to Always access Location. Background App Refresh is On. Mobile Data is On.
In the general area, Owntracks is clicked to background app refresh and is set to on generally.
Running 9.1.6/en_GB on an iPhone 6plus on iOS10 (10.0.1 (about to move to 10.0.2)).

At the moment, I only send updates when I manually open owntracks.

http://track.elyob.com/index.php/owntracks/owntracks-48hr/ (p:njb123)

Only the points where I have stopped and opened the app are being posted. I get the splash page every time I open the app (after a small time).

I also get no data being sent to the OWNTRACKSTODAY right-swipe widget (not sure if this is implemented anyway).

I'm considering buying a cheap Android phone just for Owntracks as I have quite a lot of dependancies off its data.

Just wondering if anyone else has had any issues.

**Comment by ckrey** [comment]
Hi @elyobelyob,

there are two known issues in OwnTracks 9.1.6 under iOS 10 which you are experiencing:

#417 and #413

Unfortunately you will have to wait for the next version to fix #413, but you can manually set the location permissions for OwnTracks to `always` in the `Settings/Privacy/Location` screen.
