### ISSUE TITLE
Today widget size too small to show 3 lines in iOS10

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#418]
![img_0894](https://cloud.githubusercontent.com/assets/4027289/18807849/96358c0e-8252-11e6-9a42-c6005e5723a4.PNG)

**Comment by ckrey** [comment]
Fixed!

**Comment by jpmens** [comment]
9.2.4 installed from TestFlight.

Widget shows 3 friends although I have 4 in app. (2 on first 'page', 1 on second)

**Comment by jpmens** [comment]
Sorry, forgot to say: HTTP mode, iPad, iOS 10

**Comment by ckrey** [comment]
Friends displayed in the Today widget or on the Apple Watch are the Friends linked to your address book.

Would you verify please all your 4 friends and not just the 3 shown are linked to your address book

**Comment by jpmens** [comment]
None of the friends on this device have matching topics in address book. One of the names (e.g. Yours) matches, but not the MQTT topic names. For two of the devices I'm seeing, neither the name (`JP Mens (HTTP/iPad)`) matches nor its topic name.

**Comment by ckrey** [comment]
Well we never document this feature properly (in the booklet). Most of the information is in here: #113

* All friends which have a `name` are shown on the Today Widget or on the Apple Watch.
* A name is assigned either by linking a friend to an address book entry (remember we have two different ways to do that: One modifies the address book, the other one just keeps a pointer to the address book record in OwnTracks).
* or by sending a `card`.

**Comment by jpmens** [comment]
You are right, of course: one of the friends had no card. I have added that and now 4/4 are shown.
