### ISSUE TITLE
iOS 10 iBeacon ranging doesn't work?

### ISSUE THREAD

**Issue by cmsimike** [owntracks/ios#420]
Hi,

I had previously setup my OwnTracks to broadcast ranging mqtt updates. This worked great under iOS 9. Today I decided to fire up the ranging functionality to continue some work, and I notice that Owntracks no longer pushes these ranging updates.

I have downloaded and confirmed that my Owntracks config still has it enabled:
> "ranging" : true,

Is there something else I should be looking at?

**Comment by cmsimike** [comment]
It seems extremely inconsistent, at best. A sudden flash of about 53-ish messages and no other ranging until app restart.

**Comment by cmsimike** [comment]
When the messages do come in, the distances reported by the different beacons are exactly the same, always:

{"major":2,"tst":1474842339,"minor":2,"_type":"beacon","prox":3,"uuid":"110C40B8-A46C-49C0-9E6E-EC016C439949","acc":12.91549665014884,"rssi":-76,"tid":"KE"}

{"major":1,"tst":1474842339,"minor":1,"_type":"beacon","prox":3,"uuid":"110C40B8-A46C-49C0-9E6E-EC016C439949","acc":12.91549665014884,"rssi":-76,"tid":"KE"}

**Comment by ckrey** [comment]
I just tried to recreate your issue here, but I see the expected behaviour.

When the beacons are in range an the app is in foreground, beacon messages are sent.
Messages for different beacons have different RSSI values and those values, the proximity value and  the accuracy value change.

Would you share your configuration with regards to beacons with to check for anything special?

**Comment by cmsimike** [comment]
Thank you for checking up on this! I will re-double check my config and see if it is something on my end.

Here is the config I am using:
```
{
  "host" : "X",
  "locatorDisplacement" : 200,
  "subTopic" : "",
  "usepolicy" : true,
  "validatecertificatechain" : false,
  "cleanSession" : false,
  "locked" : false,
  "url" : "https:\/\/user:password@host:port\/path",
  "tls" : true,
  "positions" : 50,
  "mode" : 0,
  "willRetain" : false,
  "deviceId" : "mike",
  "extendedData" : true,
  "monitoring" : 1,
  "_type" : "configuration",
  "locatorInterval" : 180,
  "updateAddressBook" : true,
  "waypoints" : [
    {
      "_type" : "waypoint",
      "tst" : X,
      "lat" : X,
      "lon" : X,
      "rad" : 0,
      "desc" : "-home:X"
    },
    {
      "_type" : "waypoint",
      "tst" : x,
      "lat" : x,
      "lon" : x,
      "rad" : 0,
      "desc" : "-work:X"
    },
    {
      "_type" : "waypoint",
      "tst" : x,
      "lat" : x,
      "lon" : x,
      "rad" : 0,
      "desc" : "LivingRoom:x"
    },
    {
      "_type" : "waypoint",
      "tst" : X,
      "lat" : X,
      "lon" : X,
      "rad" : 0,
      "desc" : "Catroom:X"
    },
    {
      "_type" : "waypoint",
      "tst" : X,
      "lat" : X,
      "lon" : X,
      "rad" : -1,
      "desc" : "car1:X"
    },
    {
      "_type" : "waypoint",
      "tst" : X,
      "lat" : X,
      "lon" : X,
      "rad" : 0,
      "desc" : "purse:X"
    },
    {
      "_type" : "waypoint",
      "tst" : x,
      "lat" : x,
      "lon" : x,
      "rad" : 0,
      "desc" : "BedRoom:x"
    },
    {
      "_type" : "waypoint",
      "tst" : X,
      "lat" : X,
      "lon" : X,
      "rad" : -1,
      "desc" : "car2:X"
    }
  ],
  "username" : "X",
  "tid" : "",
  "policymode" : 0,
  "willTopic" : "",
  "clientpkcs" : "",
  "ranging" : true,
  "keepalive" : 60,
  "willQos" : 1,
  "pubTopicBase" : "",
  "auth" : true,
  "passphrase" : "",
  "port" : 8883,
  "allowinvalidcerts" : false,
  "clientId" : "",
  "validatedomainname" : false,
  "pubQos" : 1,
  "allowRemoteLocation" : true,
  "password" : "X",
  "subQos" : 1,
  "servercer" : "",
  "cmd" : false,
  "pubRetain" : true
}
````

**Comment by ckrey** [comment]
I would like to see if your iBeacon's UUIDs are all the same and what are the major and minor settings in e.g. "LivingRoom:x"

**Comment by cmsimike** [comment]
I have tried again and I am still seeing a similar issue. All other MQTT messages go through without a problem (push location, for instance), but I am not seeing nearly the amount of MQTT "_type":"beacon" updates as I was a while ago.

As I was debugging further, I did notice my bluetooth behave somewhat oddly, so I plan on enabling ranging on my gf's phone (which is newer and has ios 10 as well) as a test case. See if that gets me anything different. If it is just the bluetooth on my phone dying, I will be sad.

**Comment by cmsimike** [comment]
Oh sorry! I noticed we updated around the same time.


There are three ibeacons which all have the same UUID (which i use to determine if I am at home, and that region has a major/minor of 0). Then each of the rooms has a different major/minor:

bedroom is 3,3
livingroom is 1,1
cat room is 2,2


I am at work right now, which has a completely different UUID and major/minor numbers, and the problem persists.

**Comment by cmsimike** [comment]
Hi,

I have not had a chance to try this on another iPhone (that is hopefully soon!) but I've confirmed things on my end seem ok, so this is definitely new behavior (other than the introduction of iOS 10).

I'm curious, in your test case, does your ranging always push data out to MQTT? It seems to only send very infrequent updates now, and not pushing updates multiple times per second (which is what my desired behavior is).

**Comment by cmsimike** [comment]
Hmm - oddly, my phone does seem to be sending out background ibeacon updates. They are not frequent at all, but the app is definitely in the background (and my phone is locked) and I am noticing MQTT updates for /user/beacon.

This (seemingly?) goes against what this changed https://github.com/owntracks/ios/issues/370

**Comment by cmsimike** [comment]
I have tried this on different hardware and it seems to work as expected. Sorry for the inconvenience!
