### ISSUE TITLE
Owntracks only sends _location but not _transition message when entering and leaving regions

### ISSUE THREAD

**Issue by dingedan** [owntracks/ios#422]
Hi, I'm new to Owntracks. Using the latest iOS10 and Owntracks versions on iPhone 6S. MQTT client is subscribed to owntracks/# so I should see all messages. Tracking in manual mode. Same behavior for my GF with the same setup except for iOS9.

Problem: When we enter or leave regions, Owntracks correctly publishes the location to owntracks/user/device but not the transition event like documented [here](http://owntracks.org/booklet/features/waypoints/)

edit: going through the [JSON documentation](http://owntracks.org/booklet/tech/json/) it appears that the location event should also contains waypoint information, which it doesn't. Should I expect a separate message or should everything be contained in my location message?

**Comment by ckrey** [comment]
Did you enable "Shared" when setting up your Region(s)? If not, the the additional events are not sent for privacy reasons.

**Comment by dingedan** [comment]
That was the issue, thanks! I thought sharing was enabled during my tests but apparently it wasn't. I just tested again and I'm getting the transition event correctly. The location event still does not contain the waypoint information unlike the documentation but I don't think that's an issue.
