### ISSUE TITLE
App crashes when asking for Steps

### ISSUE THREAD

**Issue by DaElf** [owntracks/ios#424]
% mosquitto_pub -d   -h localhost -p 11883 -q 2 -t 'owntracks/russell/russell/cmd' -m '{"_type" : "cmd", "action": "reportSteps"}'

This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMotionUsageDescription key with a string value explaining to the user how the app uses this data.

Note this is an IOS10 device

**Comment by ckrey** [comment]
Thanks for spotting this. Fixed

**Comment by jpmens** [comment]
Is this on iOS 10? Not an issue on iOS 9

**Comment by ckrey** [comment]
> Important: To protect user privacy, an iOS app linked on or after iOS 10.0, and which accesses the device’s accelerometer, must statically declare the intent to do so. Include the NSMotionUsageDescription key in your app’s Info.plist file and
