### ISSUE TITLE
Turn off iBeacon monitoring (on a schedule)

### ISSUE THREAD

**Issue by svrooij** [owntracks/ios#426]
We are trying to make a prototype where a screen would display the location of me and some other people around the office based on iBeacons.
This still works even in manual mode (nice work!!) but I notice that it still uses extra battery, then when I'm not in the office.

If I want OwnTracks to not monitor anything I have to remove all beacons (and add them again later). Would it be possible to have a switch that would disable monitoring temporarily?

And if there is a switch would it be possible to switch monitoring off on an schedule? Like Friday 8pm?
And off course switch it back on at Monday 8am? The switching on could maybe be triggered by a local notification, if you're not allowed to turn it on in the background.

**Comment by ckrey** [comment]
@svrooij not sure if your request is still valid, but you can implement mode switches via Siri shortcuts since Version 13.3.3 (released in 2020).
![IMG_3C3684E460A1-1](https://user-images.githubusercontent.com/4027289/146751521-431b7e01-e294-4f90-b0da-7a653ff9d503.jpeg)

**Comment by svrooij** [comment]
@ckrey thanks Christoffer! My request is 5 years old and personally I've moved on to some other company.

Is iBeacon monitoring still possible? To my understanding Apple and Android stopped supporting it long time ago.

**Comment by ckrey** [comment]
Yes, iBeacon monitoring ist still possible in OwnTracks iOS. We are using iBeacons by [blukii](https://blukiishop.com) and Raspberry Pi running `BlueZ` for testing.
