### ISSUE TITLE
Foundation

### ISSUE THREAD

**Issue by owntracks-fabric** [owntracks/ios#429]
#### in -[NSURL(NSURLPathUtilities) URLByAppendingPathExtension:]
- Number of crashes: 1
- Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5808514c0aeb16625bb3af7e](https://fabric.io/owntracks/ios/apps/org.mqttitude.mqttitude/issues/5808514c0aeb16625bb3af7e)

**Comment by ckrey** [comment]
We don't use fabric / crashlytics anymore
