### ISSUE TITLE
Significant location change mode - Need user input for distance & time settting

### ISSUE THREAD

**Issue by supakdee** [owntracks/ios#431]
Hi,
Owntracks is the great app.
I would think that it would be even better if you could allow user to set the distance & time to publish new location - this would really help to optimize the use of owntracks.
Thanks.

**Comment by jpmens** [comment]
This is possible to a certain extent by loading your own configuration settings through `otrc`; it is described in our Booklet.

**Comment by ckrey** [comment]
The time and distance settings in `otrc` are valid in Move Mode only.

The Significant Changes Mode does not accept parameters and is define by iOS/Apple. It triggers after moving more than 500 meters __and__ after 5 minutes

**Comment by supakdee** [comment]
Move mode needs app to be active (foreground) - cannot be used in a daily life.

Significant location change mode is nice as it runs in background.

It would be great if there is an additional mode which run in background & able to customize distance + timing interval.

**Comment by ckrey** [comment]
I think this is a very valid request. We experimented quite a bit and found that more than Significant Change Mode in the background is not possible without a lot of battery usage and decided not to use it.

**Comment by kaspergrubbe** [comment]
I could use this, I need the application to push to me:

- When I move (already covered by `Significant Change Mode`, awesome!)
- At least once every 24 hours.

I am no iOS expert, but couldn't it be done with `setMinimumBackgroundFetchInterval` set to `6/12/24 hours`, and a `performFetchWithCompletionHandler`?

**Comment by ckrey** [comment]
background fetch is already active. There were issues for iPhone 6/7. Now a new version 9.5.9 is in the app store

**Comment by kaspergrubbe** [comment]
@ckrey Is background fetch the same as background push? And how often does it push?

**Comment by ckrey** [comment]
background fetch is what calls `performFetchWithCompletionHandler` as you proposed. It is called typically every 15 minutes, but it is up to iOS to lower the frequency when battery is low, etc.

**Comment by ckrey** [comment]
I think the discussion here has come to an end
