### ISSUE TITLE
Reconsider iBeacon implementation

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#432]
https://github.com/Instrument/Vicinity

via @iot_berlin

**Comment by cmsimike** [comment]
So, was there any work done on Owntracks to support this? I feel like all of a sudden, Owntracks is ranging iBeacons in the background?

**Comment by ckrey** [comment]
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20am%20happy%20with%20the%20iBeacon%20functionality%20in%20OwnTracks)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20am%20happy%20with%20the%20iBeacon%20functionality%20in%20OwnTracks/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20would%20like%20iBeacons%20in%20OwnTracks%20to%20be%20enhanced%20an%20I%20opened%20an%20issue)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20would%20like%20iBeacons%20in%20OwnTracks%20to%20be%20enhanced%20an%20I%20opened%20an%20issue/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20don't%20use%20iBeacons%20in%20OwnTracks)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20don't%20use%20iBeacons%20in%20OwnTracks/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20don't%20know%20what%20iBeacons%20are%20or%20how%20to%20use%20them%20in%20OwnTracks)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD3C5Z7C4M5WB8AQX0GNCCV/I%20don't%20know%20what%20iBeacons%20are%20or%20how%20to%20use%20them%20in%20OwnTracks/vote)

**Comment by ckrey** [comment]
Judging from the lack of issues and support requests, iBeacons seem to work generally as expected or are not used widely.
