### ISSUE TITLE
App does not report steps (when in background)

### ISSUE THREAD

**Issue by 5ea** [owntracks/ios#433]
Hello. Thank you for this great app!

I'm experiencing an issue that steps are only reported when the ios app is brought into foreground.
When in the background it does report location alright, but fails to report steps.

Would you have any advice on how to debug it? It clearly works for other people.

```
owntracks/xxxxxx/xx/step, msg:
{ "_type": "steps", "tst": [epoch], "to": [epoch], "steps": [valid steps], "distance": [valid distance], "from": [epoch] }
```

**Comment by jpmens** [comment]
Please check the Booklet for an example: you have to publish the request with QoS=2 so that the app will get it when it next wakes up (which can be a while)

**Comment by 5ea** [comment]
I do this by the book (QoS=2). And the app reports back, but only when brought into foreground.

**Comment by jpmens** [comment]
How long have you waited? This can take an hour even

**Comment by 5ea** [comment]
Days. I must really wrap my mind around it... it seems really odd.

**Comment by jpmens** [comment]
Sorry: you need to enable remote commands using an otrc config for ghis to work

**Comment by 5ea** [comment]
But if otrc config is uninitiated I would receive no steps reporting at all, right? And I do get reports --

**Comment by jpmens** [comment]
Show me the exact command you use to publish the request please

**Comment by 5ea** [comment]
I use Node-Red, so it is:

// now
var seconds = new Date();
seconds.setHours(0,0,0,0);
seconds = seconds.getTime() / 1000;

```
msg.payload = {
        '_type' : 'cmd',
        'action' : 'reportSteps',
        'from'  : seconds - 86399,
        'to'    : seconds
};
return msg;
```
(QoS set to "2" in settings)

and when I wake up the app I receive:

`{ "_type": "steps", "tst": 1480023938, "to": 1479942000, "steps": 9387, "distance": 5443.98378209956, "from": 1479855601 }`

What do I miss?

Thank you very much for taking time to help.

**Comment by jpmens** [comment]
Please try with mosquitto_pub as shown in Booklet with qos=2

**Comment by bdleedy** [comment]
I have the same problem. OwnTracks will hold messages (shown with a number in a red circle on the icon) and will not send them for very long periods of time (I've never been patient enough to wait for for than 6 hours). As soon as the app is brought forward though, it vomits all over my MQTT server. (I use OpenHAB2)

**Comment by jpmens** [comment]
Your comment is not helpful and you have not made any attempt to show that it's anything to do with the topic of this issue.

**Comment by 5ea** [comment]
Excuse me for not replying for a long time.

For unclear reasons Ontracks app started reporting steps regularly. And, since a couple of days I have full, daily reports (without forcing Ontracks to foreground). Unfortunately it is little help for others having similar issues.

**Comment by bdleedy** [comment]
If you mean that my comment does not add to the 'steps' data not being sent, true. However it seems as though we have the same issue, when the app is in the background, it doesn't send MQTT data. I do get the notifications from the app that I am leaving/entering but they (many times, for extended periods) sit in the app waiting to send them to my mosquitto server. So I'm not sure how that isn't helpful (if nothing else it's a +1) and how it doesn't directly show similarity to the OPs problem.

If I'm wrong, please tell me how.

**Comment by jpmens** [comment]
As the mystery of the "missing steps" has apparently been solved, I'm closing this.

@bdleedy please open a new issue if you need regarding your app not reporting to your broker.
