### ISSUE TITLE
Apple watch: mode change

### ISSUE THREAD

**Issue by MrBramme** [owntracks/ios#434]
I'd like to request a new feature for the apple watch client. to preserve my battery and because not everything needs to be monitored in my case, my tracking mode is mostly manual. I would find it extremely handy if I could change that mode using my Apple Watch. That way there's no need to get my phone out of my bag/pocket/... when I want to log my movements but I can simple toggle the tracking mode from my wrist.

**Comment by tomyvi** [comment]
This and manually push location by a single tap on the watch for the same reason would be useful !

**Comment by ckrey** [comment]
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD2VD42P8XW82DGYC688NZQ/I%20would%20use%20this%20on%20my%20Apple%20Watch)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD2VD42P8XW82DGYC688NZQ/I%20would%20use%20this%20on%20my%20Apple%20Watch/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD2VD42P8XW82DGYC688NZQ/I%20am%20not%20interested)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD2VD42P8XW82DGYC688NZQ/I%20am%20not%20interested/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD2VD42P8XW82DGYC688NZQ/I%20don't%20have%20an%20Apple%20Watch)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BTD2VD42P8XW82DGYC688NZQ/I%20don't%20have%20an%20Apple%20Watch/vote)

**Comment by ckrey** [comment]
Done for Apple Watch and Today Widget

**Comment by ckrey** [comment]
Heading for the App Store version >= 9.7.8
