### ISSUE TITLE
Feature request: Change to move mode automatically when phone is charged.

### ISSUE THREAD

**Issue by kirichkov** [owntracks/ios#436]
I think it'd be handy if the application automatically switches to move mode, when it's connected to a power supply. When the device is no longer being charged and running on battery power, or drops under let's say 50% of battery charged, switch back to the previous mode or even to significant location changes mode. This will need an extra toggle in Settings.

I'm mentioning the battery charge, because I've found out that when I charge my phone with just 500mA, and use GPS navigation, the battery still continues to drop.

**Comment by ckrey** [comment]
Good idea @kirichkov !

With regards to charging I noticed a similar behavior when I listen to podcasts while driving. The battery drops even when connected to a 500 mA charger.

What I wouldn't like to do is to `up` the mode without explicit intervention by the user. The reasons for this are
- privacy (the user may want to update his location only a few times)
- data plan (though our payloads are small, transmitting your location often has some effect on your data plan and/or costs).

What I would like to discuss here ( @jpmens @binarybucks ):

`down` monitoring mode when battery runs low e.g. 
- from move mode to significant changes mode if less than 20%
`up` monitoring mode when battery is recharged e.g.
- return to move mode if more than 50%

**Comment by kirichkov** [comment]
I completely agree about this functionality requiring explicit intervention by the user! What I had in mind is to have a toggle in settings, OFF by default, that requires a user to flip it manually, for this functionality to be activated.

My use case is that whenever I'm driving, I usually connect my phone to a 2 Amp charger, which is sufficient to use GPS Navigation and charge the battery at the same time, so it'd be handy if OwnTracks was logging more often to have a better log of my trips.

Thanks for the great app and considering my suggestion! 😃

**Comment by jpmens** [comment]
I like the idea of an explicit enable by the user. What I'm a bit afraid of is if battery is charged, how quickly it'll discharge when in move mode (tested: one hour suffices to drain iPhone 5S battery), so the auto-fallback to the lower mode sounds good.

**Comment by kirichkov** [comment]
Just to clarify, what I mean, is to turn on this mode while the phone is connected to a power supply and in the charging/fully charged state. The idea is to use when traveling by vehicle to have more often and more precise waypoints logged.

I'm no iOS developer, but I found several questions on StackOverflow that state determining when a device is charging / fully charged is indeed possible. They are quite old, so might not be relevant anymore:

[Question 1](http://stackoverflow.com/questions/11345645/ios-how-to-detect-if-power-cable-is-plugged)
[Question 2](http://stackoverflow.com/questions/839279/detect-if-device-is-charging)

I think these are the relevant APIs:
[UIDeviceBatteryState](https://developer.apple.com/reference/uikit/uidevice/1620051-batterystate)
[UIDeviceBatteryState values enum](https://developer.apple.com/reference/uikit/uidevicebatterystate)

**Comment by ckrey** [comment]
Sorry, as explained in #683 there is no (or I don't now any) way to implement this.

**Comment by kirichkov** [comment]
Still grateful, for looking into this, and for making such a great app!

**Comment by ckrey** [comment]
It looks like I found a way to change monitoring mode in background. Will have a look how to implement the feature

**Comment by ckrey** [comment]
There will be a new Settings parameter "downgrade" indicating the percentage of battery level.

If the phone is in Move Mode and the battery level drops below "downgrade" percent, the app will automatically switch from Move Mode to Significant Mode.

If the phone did that automatic switch and detects the charges is connected, it will automatically switch back to Move Mode.
This will happen when then next location update in Significant mode is processed.

**Comment by ckrey** [comment]
@kirichkov if you drop me your email, I'll invite you as a Beta-Tester

**Comment by kirichkov** [comment]
> @kirichkov if you drop me your email, I'll invite you as a Beta-Tester

kirichkov at gmail com should do the trick.

**Comment by kirichkov** [comment]
Here's my test results:

1. I plugged in the phone with battery showing 67% full (I think this doesn't always coincide with what the internal API is returning).
2. UI didn't change to "Move"
2. I set the "downgrade" setting to `60`
3. UI still remained in "Significant" mode.
3. Drove for 30 minutes. 

Unfortunately neither the UI, neither the logged data showed improved "resolution" - i.e. more frequent logging, while driving. I  then switched it to move mode to make sure what I should expect, and indeed the logging was happening every few seconds, as opposed to once every 5-10 minutes, as it does in significant changes mode.

I checked a38d347 and the logic should be that once I plug it it should switch to move mode and report more often its location. Is my test wrong?

**Comment by kirichkov** [comment]
@ckrey I see! I actually haven't tested this scenario, but I will and report back. My original request was to switch to move mode automatically while charging, hence my confusion.

**Comment by ckrey** [comment]
Release in version 16.1.3

**Comment by jbrepogmailcom** [comment]
Sorry but this feature does not work now with iOS 17. I had battery 95%. I set up Downgrade to 94 and switched to Move mode. Then I waited until battery dropped to 93%. According to what you wrote, the mode should switch to Significant move, but it did not happen.

I had phone stationery, does it need to move and report location in order to change mode?

**Comment by ckrey** [comment]
yes, either you move (`locatordistance`) or wait (`locatorinterval`) in move mode
