### ISSUE TITLE
Cannot delete frields

### ISSUE THREAD

**Issue by turboc1208** [owntracks/ios#438]
When I started out I setup a topic /owntracks/user/iphone.  It is now a friend and I can't get rid of it.  There needs to be the ability to just swipe the friend and delete in the same way you delete a waypoint.  That should also remove the user from the map as well.

**Comment by jpmens** [comment]
The reason is, this topic is probably retained on your MQTT broker. Publish a null retained value to that topic, and *then* swipe out the friend; it should be gone for good.
