### ISSUE TITLE
owntracks/iOS cannot connect to mosquitto with ssl certificate based authentication

### ISSUE THREAD

**Issue by otdftr** [owntracks/ios#439]
For no obvious reason, Owntracks on iOS ceased to connect to mosquitto with TLS and authentication using certs:
Stream Error Code Key -9807 / Stream Error Domain Key 3
The same combination of client cert / server cert / ca-chain works well with an Android client.

This failure can be fixed temporarily by 
1. setting up SSL incorrectly (e.g. SSl Settings > TLS > Custom Securiy Policy > Pnned Cert > pick any cert) -> connect continues to fail, 
2.  then correcting the TLS settings --> Owntracks connects an transmits all queued events. 
3. Subseqent conections will be successful as long as Owntracks runs in the foreground. 
4. As soon as it is sent to the background, connections will fail again.

**Comment by ckrey** [comment]
are talking about pinned certs for server authentication or client certs?
What does the setup look like?

**Comment by otdftr** [comment]
no, not pinned - self signed root CA + intermediate CA + server / client cert signed by intermediate.  so, basically, a (pivate) PKI with self-signed root.
objective is client auth by cert.

config is like this:
```
{ "host" : "mqtt.AAA.de",
  "locatorDisplacement" : 200,
  "subTopic" : "",
  "usepolicy" : false,
  "validatecertificatechain" : false,
  "ignoreStaleLocations" : 0,
  "cleanSession" : false,
  "locked" : false,
  "url" : "",
  "mode" : 0,
  "positions" : 50,
  "tls" : true,
  "willRetain" : false,
  "ignoreInaccurateLocations" : 0,
  "deviceId" : "BBBBBBB",
  "extendedData" : true,
  "monitoring" : 1,
  "_type" : "configuration",
  "updateAddressBook" : true,
  "locatorInterval" : 180,
  "waypoints" : [
    {
      ...
    },
    ....
  ],
  "ws" : false,
  "username" : "CCC",
  "tid" : "DD",
  "policymode" : 2,
  "willTopic" : "",
  "clientpkcs" : "H_EEEEEEEE_1.otrp",
  "ranging" : false,
  "keepalive" : 60,
  "willQos" : 1,
  "pubTopicBase" : "",
  "auth" : true,
  "passphrase" : "nopass",
  "port" : 8883,
  "allowinvalidcerts" : false,
  "clientId" : "",
  "validatedomainname" : false,
  "sub" : false,
  "pubQos" : 1,
  "allowRemoteLocation" : true,
  "password" : "",
  "subQos" : 1,
  "servercer" : " CA_-_FFFFF_trusted_CA-2015.otrp",
  "cmd" : false,
  "pubRetain" : true
}
```

**Comment by ckrey** [comment]
The problem is the leading space in the "servercer".
The leading space is treated as a delimiter between cer files. As the first file is kind-of invalid

**Comment by otdftr** [comment]
Well, I dumped he config in both situations (working and connection failing) and vim-diffed them - they are absolutely identical.

The "servercer" value reflects settings of the "pinned server cert" in "custom security policy", it was not  set in the original config I provided but may have been set when trying around.

What I now found out playing around and checking configs is:
- with the "custom security policy" slider set to off, options like pinned server cert, validate chain etc. cannot be changed in the gui, they are disabled
- at least the "pinned sever cert" still occurs in the config and seems to remain enabled (?) - maybe the leading space was meant to enable/disable (?), but I cross-checked: whenever a single pinned cert is selected, it will show with a leading space in the dumped config - regardless off whether "custom security policy" is enabled or not ... but I didn't dig into the code or settings there ...  
- BUT: if I enable "custom sec....", remove / switch off all settings, and thean disable it again, situation seems to improve, ans connectios will still work when app was in the background or device sleep for a short while

But in general, after having the app in the background or the device sleeping for some time, the connection problem returns / persists. And to make connections work again, one has to perform the steps given in my first post: randomly change TLS settings, go back to settings / status page, again go to TLS settings and correct them, go back to settings / status or map -> connections will work for a while.

Just to be sure and after all the trying around, I exported a failing config, applied the "fix", expoted the (working) config and checked again: they are identical to the very letter. This is the last config I used, which works or fails - depending... (again some confidental things replaced by capitals - NB the now empty servercer)

````
$ diff -s work7.otrc fail7.otrc 
Dateien work7.otrc und fail7.otrc sind identisch.

$ cat work7.otrc
{
  "host" : "mqtt.AAAA.de",
  "locatorDisplacement" : 200,
  "subTopic" : "",
  "usepolicy" : false,
  "validatecertificatechain" : false,
  "ignoreStaleLocations" : 0,
  "cleanSession" : false,
  "locked" : false,
  "url" : "",
  "mode" : 0,
  "positions" : 50,
  "tls" : true,
  "willRetain" : false,
  "ignoreInaccurateLocations" : 0,
  "deviceId" : "oAAAAAAo",
  "extendedData" : true,
  "monitoring" : 1,
  "_type" : "configuration",
  "updateAddressBook" : true,
  "locatorInterval" : 180,
  "waypoints" : [
    .... WAYPOINTS ....
  ],
  "ws" : false,
  "username" : "BBB",
  "tid" : "CC",
  "policymode" : 2,
  "willTopic" : "",
  "clientpkcs" : "H_oDDDDDDDe_1.otrp",
  "ranging" : false,
  "keepalive" : 60,
  "willQos" : 1,
  "pubTopicBase" : "",
  "auth" : true,
  "passphrase" : "nopass",
  "port" : 8883,
  "allowinvalidcerts" : false,
  "clientId" : "",
  "validatedomainname" : false,
  "sub" : false,
  "pubQos" : 1,
  "allowRemoteLocation" : true,
  "password" : "",
  "subQos" : 1,
  "servercer" : "",
  "cmd" : false,
  "pubRetain" : true
}
````

**Comment by ckrey** [comment]
I wonder if you installed your CA certificate (for your self signed server certificate) in iOS keychain.
You don't need to, but if you don't, you need to set `allowinvalidcerts` to `true`.
If you do, you don't need custom security policy at all.

**Comment by otdftr** [comment]
Yes, I Installed the self signed root CA cert in the iOS keychain, because I need it for e-mail encrypting / signing too.
And: 
- my standard setup is "custom security policy" = off (I only switch it I on and off again to "fix" the failing connection issue)
- although it should have no effect without  custom security policy enabled, I keep all custom options disabled
(see the attached [TLS config](https://cloud.githubusercontent.com/assets/1713611/23232040/2aed4b02-f94a-11e6-9633-c5648c6dc92e.png) screnshot)

As this setup works until the app goes to the background or the device goes to sleep mode, I would rather suspect some sharing or reinitialisation error with the TLS libraries.
Maybe it is linked to some iOS update, because this config worked fine for weeks and started failing sometime around end of January. Right now, I cannot figure out _when_ _exactly_ I updated to iOS 10.2. I haven't updated to iOS 10.2.1 yet and I am going to do that this weekend, so if the issue is linked to the iOS version, this might fix it.

**Comment by otdftr** [comment]
I wasn't an iOS 10.2 / 10.2.1 issue. But: I re-checked all certificates and serials thoroughly and found out that the server and client certs have been signed by a CA cert with an older serial number which was not present in the iOS trusted certs. They used the same CNs, so it wasn't obvious in the first place.

Now, after fixing this, the iOS devices connect correctly. Sorry for providing misleading information. No problem there. 

But this leads to another question: why did the connection succeed with the same config, but _without the right certs in place_ 
- until  around January (okay, bygones...)
- and even now for a few minutes after fiddling around with the TLS settings? Remember the "workaround" suggested in [my previous posting](https://github.com/owntracks/ios/issues/439#issuecomment-281803118) ... it should not work.

**Comment by eclecticitguy** [comment]
I am having this exact problem right now.  @otdftr , would you be able to provide the steps you used to fix the issue?  My owntracks connects just fine when the app is in the foreground but once it goes to the background, it stops connecting and I have to fiddle with the TLS settings again to get it to connect again.

Thanks.

**Comment by otdftr** [comment]
Hi @eclecticitguy, as I wrote: Re-check all the certicates, and, in case of a PKI with a self signed root, make sure that the root CA cert and the trusted intermediates (if any) are installed on the device. I thoroughly double- and triple-checked the certificates - well, at least I thought I did - and still missed on minor faults, which effectively made the connections fail. 

In the past weeks, I encountered two SSL related "issues" (one on iOS and one on Android 7) - which eventually weren't issues, but missing or faulty certificates. Unfortunately, neither the status messages on the client nor the logs on the broker / openssl libs are of any help, but rather misleading in most cases.

Your description of "**connects just fine when the app is in the foreground but once it goes to the background, it stops connecting and I have to fiddle with the TLS settings again**" rings a bell with me: It was exactly the same behaviour I encountered with an older version of owntracks, related to a missing intermediate CA cert and "masked" by some short-circuiting of checks in ?owntracks? or ?iOS's SSL? - which made the config not fail entirely, but it seemed to work initially and then - after some time or going to background - cease working again. 

Now, for the past few months and always with the most recent iOS version (9.5.3 was released a few days ago), everything works fine - no issues at all.

### My config is

- all root and intermediate CA certs are installed on the device
- mqtt broker is mosquitto
- no auth by username (authentication OFF, empty password), but mosquitto configured to
````
    require_certificate true
    use_identity_as_username true
````
- connection mode private / TLS
- on the device, client cert PKCS12 with full chain, no "custom security policy"
- I normally use "significant change" or "move" mode with owntracks

### My learnings are

- check the certificates, check the certificates, check the certificates
- check them again
- check the certificates to include Subject Key Identifier / Authority Key Identifier - I always did well without them in the past, but I suspect missing key identifiers were somehow linked to the problems I had with owntracks on Android7 (see https://github.com/owntracks/android/issues/481#issuecomment-306296061 - the alleged Android issue I mentioned before) *
- when tryin different settings, at least go back to the status screen, or better even to the map view - some settings seem to be applied only when you leave the settings screen, although they appear to take effect earlier or even immediately *
- to track down certificate verification issues, temporarily enable custom security policy in status>settings>tls and "allow untrusted certificates", disable verification and so on
- to further track down certificate issues and exclude broker configuration issues, use `openssl s_client` and the client's certs to simulate and check the communication with the broker
- My impression is that SSL implementations and their usage in apps tended to be quite lenient in the past - which made a lot of not 100% clean scenarios 'just work' - and with this being improved, proven settings "suddenly" fail. See my messages from end of February earlier in this thread. That a particular combination of certificates works well in _one_ environment or vesion is not neccesarily proof that they are correct ... maybe it is just a more or less f'upped environment. *

\* Please don't quote me on these points ... I can't prove them, they are just feelings... 

@eclecticitguy - sorry I have no solution for your issues, but maybe some of my learnings can help.

### BTW: 

- I use XCA to mange all certificates (my entire self signed PKI). XCA is quite strict about the certificates and helps maintaining integrity and consistency throughout your certificate collection. In 999 out of 1000 cases it will help providing a fail safe set of certificates. (Only once did I manage to create a certificate with a duplicate extension in XCA. This cert worked flawlessly on all devices so far and _only_ failed on Andoid 7).
- The "duplicate extension issue" was _only_ reported by the portecle java app I use for BKS management - all other applications reported protocol errors, missing trust anchors or whatever: Erroneous error messages putting you on the wron track.

**Comment by ckrey** [comment]
thanks @otdftr
