### ISSUE TITLE
Friends show "Resolving..."

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#440]
I occasionally see two or three friends as `Resolving...` in the Friends list:

![img_4691](https://cloud.githubusercontent.com/assets/60706/23449798/49b9d16e-fe58-11e6-95f3-a1283aaf79d9.png)

I can typically "force" resolution for one friend by hitting "Publish now", but this trick doesn't work for more than one friend (if it's a trick at all -- it might well be pure coincidence).

Sometimes exiting the app, waiting a bit, and re-entering solves the issue. Sometimes.

This is not a new phenomenon: it's existed for quite a number of releases. :-)

**Comment by ckrey** [comment]
"resolving..." should be visible for a few seconds while the address is reverse-geocoded.

Do I understand you correct if you say "resolving..." is displayed permanently?

**Comment by jpmens** [comment]
Indeed, and I should have said so. If I remain on the Friends tab, `resolving..` is displayed permanently.

**Comment by jpmens** [comment]
I said above that sometimes "resolving..." goes away if I manually publish; it seems as though a switch to map view and then back to friends view suffices.

**Comment by jpmens** [comment]
Switching to Regions view also suffices: the `resolving..` goes away and is replaced by the address. Somthing is *stuck*. :-)

**Comment by ckrey** [comment]
Example caught in Simulator:

```
2017-06-01 08:06:34.851400+0200 OwnTracks[52651:759922] [Client] Geocode error: Error Domain=GEOErrorDomain Code=-3 "(null)"
```

**Comment by ckrey** [comment]
https://stackoverflow.com/questions/40735302/clgeocoder-error-geoerrordomain-code-3

**Comment by jpmens** [comment]
This hasn't ocurred here again since 9.5.3.

**Comment by jpmens** [comment]
Can no longer reproduce. Closing with thanks.

**Comment by jpmens** [comment]
I'm afraid it still is there: my own entry plus those of 2 friends show "resolving..." and have done now for two (2) minutes.

**Comment by ckrey** [comment]
BTW: The docs say "you should not send more than one geocoding request per minute".

For clarification, the following message will be displayed instead of repeating to resolve the address:
![ohne titel](https://user-images.githubusercontent.com/4027289/27250782-d3c42fba-5337-11e7-88b2-b3319b9a4ca4.png)
