### ISSUE TITLE
iOS QR Configuration

### ISSUE THREAD

**Issue by andrewferrier** [owntracks/ios#443]
Currently it is a bit fiddly to download `.otrc` configuration files to an OwnTracks instance on an iOS device as described at http://owntracks.org/booklet/features/remoteconfig/. So far the only way I've found of doing it is to use GoodReader, a third-party app - mail and/or Dropbox expose the `.otrc` file to other public services and hence aren't really suitable for something containing a password.

I noticed the camera icon in the Settings page and was hoping that the QR code scanner it brings up allowed me to point the device at a QR code pointing to an `.otrc` file on an https endpoint (which I already have), but no dice.

So this is a 2-part request:

1. Clarify the docs at http://owntracks.org/booklet/tech/qr/, which are ambiguous as to what exactly the QR code does - it says it can be used to "setup the iOS app", but this isn't quite true - it's only suitable for setting up iBeacons AFAICT. I can submit a pull request if you agree.

2. Add support for downloading `.otrc` files from an HTTP(S) endpoint through the QR code reader.

Thanks for your great work on OwnTracks, by the way!

**Comment by ckrey** [comment]
Downloading and processing of .otrc, .otrw, and .otre files over HTTP or HTTPS implemented
