### ISSUE TITLE
App sends empty POST data in http mode

### ISSUE THREAD

**Issue by nekdolan** [owntracks/ios#446]
On iPhone 7 IOS 10.3.1

This is what happened.
I had a working configuration of the app sending data to my server.
Then I changed the server route url and the app couldn't send data to my server.
Then I changed the url in the app, but then the app was sending empty POST data.
My server kept sending back 404 to the server because of the missing data and the app kept sending the empty data because of this.
Then I changed the server to always respond with 200 and after that I started to get requests with POST data from the app.
Before I did that I checked if my server could receive any POST data with postman and I also checked if the app sent any data at all. It was sending nothing when it was failing.

**Comment by jpmens** [comment]
sends empty

**Comment by jpmens** [comment]
Please tell us how you've configured the app and also describe how you're obtaining the POST server-side. Are you using our Recorder?

**Comment by jpmens** [comment]
So you made a bunch of mistakes and expect exactly what to happen?

If you can provide a reproducible chain to the bug, we'll look at it.

**Comment by jpmens** [comment]
So, not telling us what the issue really was, how to reproduce it, and/or how you solved it? Well, then.
