### ISSUE TITLE
Cannot parse payload

### ISSUE THREAD

**Issue by df1gr** [owntracks/ios#447]
Hi,
get the error message from own tracks from the try block within client.on('subscribe', function (packet) 
in main.js. Using latest released own tracks adapter 0.2.0.
I assume that the reason for the fault is the following JSON data line: 

```
{"cog":136,"batt":75,"lon":9.227956132971894,"acc":10,"vel":0,"vac":4,"lat":47.72337962412063,"t":"u","conn":"m","tst":1494851972,"alt":394,"_type":"location","tid
```

The last key tid is not correctly terminated as any other records coming from iPhone App. I'm using OwnTracks version 9.3.0/de_DE on my iPhone. 

Any help or fix would be appreciated.
Thank you in advance.

df1gr

**Comment by jpmens** [comment]
I have formatted your data between two blocks of 3 backticks.

Where is that data coming from? Is this data you are parsing which has been transmitted by our iOS app? If so, *your* receiving buffer is too small and is being truncated; hence the JSON parsing error.

**Comment by jpmens** [comment]
Also, what is ` own tracks adapter 0.2.0` ?

**Comment by df1gr** [comment]
Hi, it's the adapter in iobroker.

Von meinem iPhone gesendet

**Comment by jpmens** [comment]
So, this is the OwnTracks project. 
Would you now like me to guess what `iobroker` is?!?!

**Comment by df1gr** [comment]
Iobroker is a framework for home Automation. With that, adapters realize access to different devices controlling it. In that respect OwnTracks is a kind of "device" used to make home owners location.

Von meinem iPhone gesendet

**Comment by jpmens** [comment]
This is most likely an iobroker issue then; we are not aware of any iOS app versions which truncate outgoing data (nothing at all would work if that happened). If I were you I'd ask the other project.
