### ISSUE TITLE
copy attribute in payload controlled by UI

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#449]

**Comment by jpmens** [comment]
+1

**Comment by ckrey** [comment]
Watch here on public:
public/user/FFA4E773-522D-4224-A143-6BB336B5BD32 {"t":"u","tst":1495968123,"acc":5,"_type":"location","alt":0,"lon":-122.0312186,"vel":0,"lat":37.33233141,"_cp":true,"conn":"w","tid":"32"}

**Comment by jpmens** [comment]
Perfect!

**Comment by ckrey** [comment]
![simulator screen shot 28 05 2017 12 52 52](https://cloud.githubusercontent.com/assets/4027289/26528153/a0fc8caa-43a4-11e7-85e5-e5403c9dc667.png)
![Uploading Simulator Screen Shot 28.05.2017, 12.52.54.png…]()
