### ISSUE TITLE
Restrict clientId to minimum MQTT 3.1.1 requirements

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#450]
<img width="840" alt="bildschirmfoto 2017-05-30 um 19 32 09" src="https://cloud.githubusercontent.com/assets/4027289/26596370/c96e326c-456e-11e7-9125-37c0e8357285.png">

Currently using default client-id = `userID/deviceID`.
Will become `userIDdeviceID`.

**Comment by jpmens** [comment]
cc: @binarybucks Is this also a matter in Android? (Mosquitto 1.4.12 has tightened rules regarding clientIDs in ACLs)

**Comment by binarybucks** [comment]
Yes, could you create an issue for me so I can take care of it once I return?

**Comment by ckrey** [comment]
Updated [booklet](http://owntracks.org/booklet/tech/json/)
---
<img width="415" alt="bildschirmfoto 2017-06-01 um 11 15 41" src="https://cloud.githubusercontent.com/assets/4027289/26673114/0bdf29e6-46bc-11e7-88d6-809225311f44.png">
---
