### ISSUE TITLE
Topic weirdness

### ISSUE THREAD

**Issue by sheppy99** [owntracks/ios#453]
I've just recreated my waypoints on Owntracks 9.5.2 running on IOS 10.3.2, after resetting the settings on the phone to cure a different problem, and the topic used by owntracks seems to have lost a "/" between "Username" and "DeviceID"
Subscribing to the base topic "owntracks" I find the messages are published to the topic "owntracks/MyLoginUserDeviceID/waypoint" whereas they used to be published to "owntracks/MyLoginUser/DeviceID/waypoint"
My partners phone still publishes to "owntracks/MyLoginUser/DeviceID/waypoint"
Is this a permanent change, or likely a bug?

**Comment by ckrey** [comment]
This was a bug in 9.5.2
A new version 9.5.3 fixing this bug is available.

**Comment by sheppy99** [comment]
Thanks, is this likely to add the "/" back into my waypoint topics?

**Comment by jpmens** [comment]
Yes, that should fix it; please test.

**Comment by sheppy99** [comment]
Will do, but it won't be for around 12 hours or so - it's late here :-)

Sent from my iPhone

On 4/06/2017, at 10:04 PM, JP Mens <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that should fix it; please test.

**Comment by jpmens** [comment]
You've got your priorities wrong: first you test our software, THEN you go to sleep! ;-)

#justkidding

Sleep well. :-)

**Comment by sheppy99** [comment]
It works, and happily I didn't have to recreate my Regions as they just changed to the original waypoint format of "owntracks/MyLoginUser/DeviceID/"
Thanks for the prompt response, I can head into Winter with working heating!
