### ISSUE TITLE
Can't connect unless "Custom Security Policy" enabled

### ISSUE THREAD

**Issue by Ggator** [owntracks/ios#455]
I'm using OwnTracks iOS 9.5.3 with mosquitto v1.4.12.  I apologize regarding the formatting of this message, I'm new to github.

My issue is similar to the issue reported in owntracks/booklet "TLS Client Certificate Documentation" 17, in that I can't connect unless "Custom Security Policy" is enabled.  The difference with my situation is that I'm NOT authenticating using Client certs at all (just using ca.crt).

Without  "Custom Security Policy" enabled, OwnTracks shows:

```
error The operation couldn't be completed.
(OSStatus error -9807.){
 "_kCFStreamErrorCodeKey" = "-9807";
 "_kCFStreamErrorDomainKey" = 3;
}
```

The mosquitto log shows:

```
1497023847: New connection from XX.XX.XX.XX on port 8883.
1497023847: OpenSSL Error: error:140940E5:SSL routines:ssl3_read_bytes:ssl handshake failure
1497023847: Socket error on client <unknown>, disconnecting.
```

My mosquitto.conf contains the following:

```
listener 8883
cafile /etc/mosquitto/certs/ca.crt
certfile /etc/mosquitto/certs/server.crt
keyfile /etc/mosquitto/certs/server.key
#tls_version tlsv1.2
#require_certificate true
#use_identity_as_username true
```

Of course, everything connects fine as soon as I enable "Custom Security Policy."

My understanding via the documentation is that enabling "Custom Security Policy" simply gives you more control over the TLS authentication process.  When it is disabled, it uses the iOS certificate store to check the ca.crt.  This apparently is not my experience.

**Comment by ckrey** [comment]
Client certs are not related to Custom Security Policy. TLS Client Certs can be used with or without Custom Security Policy.

Your understanding is correct. When you don't use Custom Security Policy, the app uses the default iOS certificate store.

I assume your server.crt is self signed by the ca identified by the ca.crt. How should iOS know about your private ca? You can do it by sending the ca.crt (e.g. per mail) to your phone and installing it in your certificate store.

**Comment by fdkz** [comment]
I'm having the same problem as Ggator. I installed the ca.crt through safari and got Owntracks to report coordinates to my mqtt broker. But every time I close Owntracks (swipe up from task manager) and reopen, I get the same error as Ggator.

If I go to settings-> "i" near the TLS -> enable "Use Custom Security Policy", maybe select something in "Pinned Server Certificate", go out of the settings window, then go back and disable "Use Custom Security Policy", Owntracks suddenly connects successfully to my mqtt broker.

**Comment by ckrey** [comment]
For now, self signed certificates require Custom Security Policy!

There seems to be a problem we have not tracked down yet. Using Custom Security Policy once does mark a self signed certificate as valid until the app is restarted. This isn't reset even when Custom Security Policy is switched off afterwards.
