### ISSUE TITLE
can't set `cp` config parameter via remote command

### ISSUE THREAD

**Issue by sumnerboy12** [owntracks/ios#457]

**Comment by ckrey** [comment]
cp can be set remotely e.g. `"c" : false`

But the change is not visible on the map view immediately. You only see the updated value after an app restart

**Comment by jpmens** [comment]
@ckrey did you mean `"cp" : false`?

**Comment by ckrey** [comment]
yes `"cp": false` or `"cp": true`

**Comment by ckrey** [comment]
In addition to not being displayed, it wasn't activated immediately.

I think we initially did not have in mind to change configuration settings immediately, but to provide an initial setup for a "dumb" user. I will check for other occurances of the same problem
