### ISSUE TITLE
Beta - app crash when deleting friends

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#460]

**Comment by jpmens** [comment]
For the record: this happens with 9.5.3 retail also.

**Comment by ckrey** [comment]
Oh, the problem I fixed was related to inserting the topic for HTTP-traccar

**Comment by ckrey** [comment]
in 9.5.3 does it happen in MQTT or HTTP mide?

**Comment by jpmens** [comment]
in MQTT mode. I had to clear persistence DB on server for the app to be able to open again; without that: endless crashes upon launch.

**Comment by ckrey** [comment]
when you recreate the problem, could you run mosquitto_sub with the same clientId as the iPhone and cleansession = no please

**Comment by jpmens** [comment]
I ran `mosquitto_sub -i clientID -c`, and was then able to launch the app. The deleted friend was still visible. I re-swiped the friend away, the app crashed, but I could reopen it without problem.

In short the `mosquitto_sub` cleared things up.

**Comment by ckrey** [comment]
9.5.9 is in the app store
