### ISSUE TITLE
Missing t:p on iPhone 6 and higher?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#462]
We've noticed that iPhone 5s periodically publishes location messages with `t:p` as documented in the Booklet, however these are sporadic to almost non-existent on iPhone 6 (and possibly newer).

Do we know why this happens?

**Comment by ckrey** [comment]
https://forums.developer.apple.com/thread/69422

Same thing described in the above discussion. iOS 10.3 seems to solve the problem for the 6s

**Comment by ckrey** [comment]
I may add check for the background fetch and issue a warning to the user

```
UIBackgroundRefreshStatus status = [[UIApplication sharedApplication] backgroundRefreshStatus];
switch (status) {
    case UIBackgroundRefreshStatusAvailable:
    // We can do background fetch! Let's do this!
    break;
    case UIBackgroundRefreshStatusDenied:
    // The user has background fetch turned off. Too bad.
    break;
    case UIBackgroundRefreshStatusRestricted:
    // Parental Controls, Enterprise Restrictions, Old Phones, Oh my!
    break;
}
```

**Comment by jpmens** [comment]
IPhone 6 here with `10.2.1`. Now upgrading to `10.3.2`.

**Comment by sumnerboy12** [comment]
iPhone 7 with `10.3.2` seems to have the same issue

**Comment by ckrey** [comment]
I found the problem! It is **not** the iOS version or the iPhone model, it is the programmer.

Newer models seem to check the background handling more strict than older ones.

**Comment by jpmens** [comment]
:-)

I confirm upgrade on the iPhone 6 did not magically start reporting `t:p`.

**Comment by ckrey** [comment]
9.5.9 is in the app store

**Comment by jpmens** [comment]
I confirm loads of `t:p` on iPhone 6 with 9.5.9: overnight 55 of them.
