### ISSUE TITLE
Beacons not working

### ISSUE THREAD

**Issue by NightRang3r** [owntracks/ios#463]
Hi,

I am trying to setup ownTracks to work with beacons, I have followed the following guide:

https://home-assistant.io/blog/2016/04/30/ibeacons-part-1-making-presence-detection-work-better/ 

I also followed the instructions on the ownTracks booklet.

I am using the latest version of the app on an iPhone with the latest iOS, I have a beacon scanning app which can see the beacons, but in the ownTracks app I don't see the Regions turning red when I am near the beacons and I am not receiving any updates to my mqtt.

I have tried using several beacons and tested with two iPhones, not sure if I am doing something wrong.

Is there a way to debug this, maybe someone can point me in the right direction...

Any help will be appreciated.

**Comment by ckrey** [comment]
which brand of iBeacons do you use?

would you share your waypoint definitions (export waypoints) with us?

**Comment by NightRang3r** [comment]
Thanks for the reply @ckrey 

I am using these beacons:

https://www.aliexpress.com/item/2017-Hot-Sale-For-Estimote-Beacons-type-Bluetooth-Ibeacon-waterproof-NRF51822-IBeacon-with-Silicon-Case/32800015850.html?spm=2114.13010608.0.0.9EhCMk

https://www.aliexpress.com/item/High-Performce-2-3-year-Battery-lifespan-IP67-Bluetooth-iBeacon-Waterproof-iBeacon-with-Temperature-sensor/32798135443.html?spm=2114.13010608.0.0.9EhCMk

And here are my waypoints:

{
  "_type" : "waypoints",
  "waypoints" : [
    {
      "_type" : "waypoint",
      "tst" : 1498209432,
      "lat" : redacted,
      "lon" : redacted,
      "rad" : -1,
      "desc" : "-building:8026A206-F26B-4C16-9287-9980F498A2BB"
    },
    {
      "_type" : "waypoint",
      "tst" : 1498155348,
      "lat" : redacted,
      "lon" : redacted,
      "rad" : 0,
      "desc" : "-Home:AAFA138D-6670-4CF5-857E-CA6A4D381627"
    }
  ]
}


I tried multiple configurations, with sharing, without sharing, with circular region settings and without.

**Comment by ckrey** [comment]
The setup is correct

You need to activate sharing to receive enter/leave events, otherwise detecting a beacon just triggers a location update

It may take a while (up to 1 minute) until the beacon is detected. 

If it doesn't work, try the following:
- stop all other iBeacon related apps
- swipe out and restart OwnTracks
- restart the iPhone

Would you check the beacons with the free app "Locate Beacon" by Radius Networks, please? I found that if this app sees them, OwnTracks sees them too.
In addition you may use this app to simulate a beacon (on a second phone).

**Comment by NightRang3r** [comment]
I have the share option enabled, unfortunately, the  "Locate Beacon" doesn't see any of my beacons (the other apps do), I tried advertising like you suggested using a second phone and the region turned red.

Thanks for helping!

**Comment by ckrey** [comment]
OwnTracks uses the iOS function which only detects iBeacons.

Some beacons support different standards. You may configure your beacons as `iBeacon`, `Eddystone`, or `Alt Beacon`. Please check
