### ISSUE TITLE
No connection with latest iOS Version 9.5.7 - Error -9807

### ISSUE THREAD

**Issue by binford6000** [owntracks/ios#464]
Since i installed latest version 9.5.7 i got no connection to my mqtt server. Status says:

connecting Der Vorgang konnte nicht abgeschlossen werden. (OSStatus-Fehler -9807.) {
    "_kCFStreamErrorCodeKey" = "-9807";
    "_kCFStreamErrorDomainKey" = 3;
}
With prior version there were no problems at all...

**Comment by ckrey** [comment]
@binford6000 there was no change regarding TLS in the latest versions and error -9807 means
`CFNetwork SSLHandshake failed`

Are you using client certificates? Did you delete and re-install the app rather than update it?

Or, were you able to solve the problem in the mean time?

**Comment by jjmmss00** [comment]
I'm having the same problem with iPad Pro. Can only connect with custom/none. I have created my own CA certificate with OpenSSL and installed per instructions. The CA cert works when tested with the mqttFX utility on windows, and selecting the CA file option.

Is there anywhere where the custom options are explained?

Very nice program by the way. Thanks

**Comment by ckrey** [comment]
For now, self signed certificates require Custom Security Policy!

**Comment by binford6000** [comment]
@ckrey: I did no delete and reinstall. Indeed i solved my issue with a new self signed certificate plus client certificate, custom sec policy with mode none and allowed untrusted certificates. With 9.6.1 everything is still ok!

**Comment by ckrey** [comment]
Thanks for the feeback

**Comment by jjmmss00** [comment]
I gather that this an iOS problem where they are blocking the use of user CAs created with OpenSSL. Like they don't like the little DIY guy, and want to make them spend a lot of money and buy a CA from the VeriSigns of the world. Should we be complaining to the Apple/iOS people?

It's not so good to disable identity checking of the server.

**Comment by jpmens** [comment]
@jjmmss00 totally untrue; works fine with certificates and CA created with openssl.

**Comment by jjmmss00** [comment]
I am a little confused. It seems you were saying that the app only works in custom mode. Doesn't that mean that part of the SSL is turned off?

**Comment by jjmmss00** [comment]
I think I have a breakthrough on this.

App now works for me without custom security policy enabled!

On iPad go to settings/about (very top)/certificate trust settings (very bottom). Then enable full trust fo the CA that you have installed.
