### ISSUE TITLE
Why not ignore outstanding updates after some time?

### ISSUE THREAD

**Issue by arsaboo** [owntracks/ios#466]
I am guessing many (if not most) are affected by Owntracks accumulating updates and then sending them all when the app connects (also see https://github.com/owntracks/ios/issues/441). 

While delayed location updates are bad, WRONG location updates are terrible. I am using Owntracks for home automation and pushing those old location updates is a terrible idea, where it can indicate a user is Home (which can disarm the security), when the user is currently Away. 

Why not have a time-out for all the location updates? Thus, Owntracks should not push out updates if they are older a user configurable value. I am not interested in updates, for example, that are more than 10 minutes old.

**Comment by brg468** [comment]
100% agree. Wrong locations are becoming a big problem for me as well with setting home/away based off location in my home automation.

**Comment by otdftr** [comment]
Completely disagree. 
I use owntracks for tracking, I think it is a great feature owntracks caches location updates (even when no networks are available) and deliveres them in a row once it reaches the server again. For me, this feature is essential.

Location updates carry timestamps, so it should be easy to sort out all updates considered outdated. On iOS, payload even includes accuracy (vac), which can be used to estimate reliability of locations.
And as the last updates comes last, just take a "last one wins" approach and check it's timestamp to be >= (new Date()/1000 - 600)  or whatever the desired time window is.

Actually, I would even go the other direction and suggest regular heartbeats while the device is NOT moving: see https://github.com/owntracks/ios/issues/467 for this

**Comment by ckrey** [comment]
- Location updates carry timestamps and 
- accuracy and
- inaccurate positions can be filtered out already 
> `ignoreInaccurateLocations` Location accuracy below which reports are supressed (iOS,Android/integer/days)

**Comment by arsaboo** [comment]
I don't see the value of inaccurate positions and that is the whole point. Why report inaccurate information?Also, I am not sure how do I use `ignoreInaccurateLocations` in Owntracks? Here's the Owntracks device tracker code (https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/device_tracker/owntracks.py). Any advice?

**Comment by arsaboo** [comment]
@otdftr If the device can send a heartbeat, it might as well send the entire information. The problem essentially is that Owntracks on iOS devices do not communicate in real-time.

**Comment by jpmens** [comment]
@arsaboo this is the second time I say: "this is not a Home Assistant support forum". Go there to ask how/why/when to do something with Home Assistant please.

You've been told how to suppress inaccurate locations. What Home Assistant does or doesn't do with them is not an OwnTracks issue.

**Comment by ckrey** [comment]
@arsaboo This is not a Home Assistant support forum (re owntracks.py).

@arsaboo The OwnTracks documentation describes how to ignore inaccurate locations http://owntracks.org/booklet/search.html?q=ignoreinaccuratelocation

@arsaboo Whether inaccurate locations are to be ignored and which level of inaccuracy is tolerable is a very subjective decision and depends on the use case.

@arsaboo The device does send the full information with the heartbeat.

@arsaboo If you don't like the concept of OwnTracks, use another open source, free of charge, advertisement free, non-cloud, actively supported system

**Comment by ckrey** [comment]
@skot0123 Yes you are right, it is looking for 

> `acc` Accuracy of the reported location in meters without unit (iOS/integer/meters/optional)

which is available when a location is reported.

If the accuracy is greater the the threshold, the location is ignored.

And yes, the accuracy is in meters.
