### ISSUE TITLE
Improvement: suggesting a "significant change with heartbeat" mode

### ISSUE THREAD

**Issue by otdftr** [owntracks/ios#467]
Reason: As long as I do not receive updates from the device, I cannot know whether the device just doesn't move, or has no connection, or the battery is plain dead. 
I, for example, use owntracks to not only monitor position, but also the  battery gauge on iOS (and Android).

So a hertbeat every, say, 900s = 15' saying "I'm still alive, just not moving, and BTW my battery is at 21%, (and my location since is...)" would be fine. For clarity, this could be indicated in payload by a special type (heartbeat), and/or a vel=0 and/or a flag resting = true or whatever.

**Comment by ckrey** [comment]
There is a heartbeat trigger, which uses the `Background App Refresh` of iOS. The payload is marked as `"t":"p"` (`p`as in ping).
Typically the `Background App Refresh` happens every 15 minutes as long as battery is not low.

We had a problem with iPhone6S / iPhone7S in iOS 10.2 regarding `Background App Refresh`, but this is solved with the current App Store version

**Comment by otdftr** [comment]
Thanks @ckrey for pointing me to the Background App Refresh of iOS - I didn't dig into the data, just wondered about the looong gaps in my battery gauge traces on the iPad (which was on iOS 10.2) compared to the iPhone (iOS 10.3.2)

Still, the heartbeats seem not to come in really reliably while the device is locked - but this might be caused by WIFI handling in iOS. As soon as I unlock the device, the pings are sent.
I'll keep checking this.
(iOS 10.3.2 / Owntracks 9.5.9de)

**Comment by otdftr** [comment]
Tested background pings - they seem to stop some time after the device ceased moving. See this: 
![28hrs](https://user-images.githubusercontent.com/1713611/28136601-910e992c-674a-11e7-82cb-6b4387b05922.png)
- the grid is 30'
- green is an Android devicd (off-topic here) 
- red and violet are iOS devices with owntracks on significant change mode
- all devices had WIFI or 4G connectivity all the time
- actual movements were 
    - Tue 1735-1840
    - Tue 2340 - Wed 0025
    - Wed 0915-0930 
    - Wed 1840-1900 + 1930-1951
- (horizontal graph sections result from carrying on the last known value for some time, so they basically indicate only one valid data point at the beginning) 

The graphs are consistent with the last known values reported by mosquitto-sub circa @1499888100 = Wed 2135:
````
$ mosquitto_sub -v -t "owntracks/#"    # Wed 21:35
owntracks/osc/ipad {"batt":37, ... "t":"c","tst":1499881830,"_type":"location" ...}
  # @1499881830 = Mi 12. Jul 19:50:30 CEST 2017
owntracks/osc/iphone {"batt":77, ... "t":"p","tst":1499887071,"_type":"location" ...}
  # @1499887071 = Mi 12. Jul 21:17:51 CEST 2017
## re-checked 2145: last ping from iphone still was @1499887071 = 21:17:51
````

### parameters and conditions

- Most of the time, the devices are/were locked,  sometimes being charged.
- both devices are iOS 10.3.2 / Owntracks 9.5.9de
- at 21:47, I unlocked both iOS devices: no change - last values still from @1499881830 / @1499887071
- bringing owntracks to the foreground didn't trigger updates, either.
- the reported connection state on both devices is "connected"
- iOS background updates are "on" for owntracks.
- finally, at ~21:57, I triggered manual updates to check network connectivity "end to end" with success:
````
   owntracks/osc/ipad {"batt":34, ... "t":"u","conn":"w","tst":1499889408 ...}
   owntracks/osc/iphone {"batt":73, ... "t":"u","tst":1499889415 ...}
````

So, to me it seems owntracks gives up sending pings at some time. Which still leaves me clue-less why...

Especially since, for example, I didn't unlock the devices Tue evening, and without being unlocked or even touched, they still flawlessly reported all movements for the hours after 17:35 and 23:40 - so owntracks obviously handles background operation really well, it just forgets to ping or doesn't receive the resp. wake-up-calls from iOS.

**Comment by ckrey** [comment]
@otdftr Thank you very much for the analysis. Still we do not understand yet what are the circumstances of your problems. Which model of iPhone/iPad do you use?

We saw the following publish times on an iPhone5S in day to day use in July:

![bildschirmfoto 2017-07-13 um 08 23 50](https://user-images.githubusercontent.com/4027289/28153358-4a159ce0-67a5-11e7-9bf2-7352dda3e18a.png)

**Comment by otdftr** [comment]
Well, your graph looks really good!

My devices are
- model MG4F2ZD/A (A1586) iPhone 6
- model MD792FD/A (A1475) iPad Air

Please let me know if I could run further tests or provide additional information.

**Comment by otdftr** [comment]
so, right after doing the in-depth analysis last wednesday evening, iPhone started doing regular pings ... ipad followed 1 day later. 
setup is/was unchanged, but everything has been fine since then.
in the meantime, devices have been upgraded to the most recent app store version, still working :-)

it's strange - neverthelsess, I suggest closing the issue. 

![batt_d-7-0](https://user-images.githubusercontent.com/1713611/28338311-d602060a-6c08-11e7-97ec-a0c631acbcab.png)
