### ISSUE TITLE
Saying home after I leave

### ISSUE THREAD

**Issue by bolsen27** [owntracks/ios#469]
So I'm having some issues with my owntracks for iOS. I use significant change mode and have a node red instance set up to receive the data from owntracks. I didn't not right the integration myself but it has worked flawlessly for over a year.

But over the 2-3 weeks (no changes on the node red side) it has started to act weird. When my wife or I leave the house owntracks properly sends the info over showing we left and the node red sets the house to away. But then within 5 minutes or so owntracks has begun randomly sending another message saying we are home. Which sets the house to home. Then it corrects itself with the next update and sets the house to away again.. it's driving me nuts because it's saying I'm home when I'm 4 miles away!

Also last night I noticed that while I was asleep owntracks had me leave and come home 4 separate times even though my phone was right next to my bed the whole night.

**Comment by jpmens** [comment]
Which device are you using and what iOS version is on them? Also, please say how large the waypoint radius is; if it's less than 100m, try increasing it to, say, 200m.

**Comment by bolsen27** [comment]
Hi!

We both have iPhone 7+'a running iOS 10.3.2

We are using a radius of only 50m I'll up the radius to 200m like you mentioned.

Brian Olsen
940-782-2401

**Comment by bolsen27** [comment]
Increased to 200m. Let the house got the leaving home notification. Then when I was 1500-2000m (as the crow flies) away from home it sent a home message.

It's weird because if I have the phone unlocked I can see the little red number showing a message is being sent before it goes away. But it doesn't pop up "entering home". But as soon as that message is sent my home goes through the arriving home stuff. Then the very next message sent locks it back up again.

It's so bizzare.

**Comment by brg468** [comment]
I recently started seeing this as well (last app update or two). I was just watching my MQTT broker as my wife left and was reported away, home, then away again.  The message that triggered the false home is the one with the "v" flag, which according to the docs says `v updated by Settings/Privacy/Locations Services/System Services/Frequent Locations monitoring (iOS)`.  Neither of us have this feature enabled. Note the timestamp is much earlier than the two events surrounding it. Iphone 6, IOS 10.0.2



owntracks/xxxxxxxxxx | {"tst":1500064920,"acc":72,"_type":"location","alt":226,"lon":-85.64482461722214,"vac":10,"lat":42.8180618093509,"batt":68,"conn":"m","tid":"RR"}
-- | --
owntracks/xxxxxxxxxxx| {"t":"c","tst":1500065144,"acc":65,"_type":"location","alt":236,"lon":-85.62481022780781,"vac":13,"lat":42.83821175518709,"batt":66,"conn":"m","tid":"RR"}
owntracksxxxxxxxxxx| {"t":"v","tst":1500064876,"acc":26,"_type":"location","alt":-1,"lon":-85.63648433585757,"lat":42.8182914880805,"batt":66,"conn":"m","tid":"RR"}
owntracks/xxxxxxxxxl | {"tst":1500065269,"acc":65,"_type":"location","alt":230,"lon":-85.62528815539522,"vac":22,"lat":42.84928990911278,"batt":65,"conn":"m","tid":"RR"}
owntracks/xxxxxxxxxx | {"cog":90,"batt":63,"lon":-85.62474385697622,"acc":5,"vel":40,"vac":3,"lat":42.88361861981343,"conn":"m","tst":1500065569,"alt":222,"_type":"location","tid":"RR"}
owntracks/xxxxxxxxxx | {"tst":"1500065048","_type":"lwt"}
owntracks/xxxxxxxxxxx | {"tst":1500066261,"acc":1944,"_type":"location","alt":0,"lon":-85.63721159999997,"lat":42.82710047999998,"batt":50,"conn":"w","tid":"BR"}

**Comment by bolsen27** [comment]
Thanks for posting all of that! Hopefully it helps get whatever is going on sorted out. As I would have no clue how to even find that information if asked for it.

**Comment by ckrey** [comment]
@brg468 thank you very much for your log. I suspected the visit monitoring `"v"` which was introduced with 9.5.9 to cause the problems but couldnt recreate the situation in my environment.

For systems which store the track based on timestamp, visit monitoring adds a bit of granularity, but for systems which take the incoming position as a current position, it is distracting.

I did change the corresponding messages: The visits (enter/leave of frequent locations as seen by iOS) are now not reported literally, but are just used as a trigger for a location update of the current position and timestamp.

Please check with the version `9.6.1` which just arrived in the App Store.

**Comment by bolsen27** [comment]
Just installed the updated app. Fingers crossed that it fixes the issue, I'll know later when I head out to the store.

Thanks for helping with this!

**Comment by bolsen27** [comment]
I was finally able to test the new build today! It seems to have fixed my issue. Thank you so much!
