### ISSUE TITLE
Error in 9.6.1

### ISSUE THREAD

**Issue by arsaboo** [owntracks/ios#470]
I am seeing the following error after updating the app today to 9.6.1:
```
error The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 2.) {
    "_kCFStreamErrorCodeKey" = 8;
    "_kCFStreamErrorDomainKey" = 12;
    kCFGetAddrInfoFailureKey = 8;
}
```
Everything was working fine and other components relying on Mosquitto are working fine.  I force closed the app and restarted, but that did not help. Anyone else seeing this?

**Comment by ckrey** [comment]
OwnTracks could resolve the hostname you provided, please re-check your configuration

```
#define	EAI_NONAME	 8	/* hostname nor servname provided, or not known */
```

**Comment by arsaboo** [comment]
Nothing changed, but it started working in the morning. I am guessing there was some problem with Asus ddns servers. Thanks!
