### ISSUE TITLE
Not receiving location

### ISSUE THREAD

**Issue by DeefK** [owntracks/ios#471]
Im using owntracks on ios and im having problems to receive the geo location. Ive added a home location and on the map it shows in red that im in the location. When i manually publishing the location the location is not there. Therefore i cannot take any actions. Notice i replaced the latitude and longitude

```
20170716-21:49:29 {"batt":62,"lon":  balbalbal  ,"acc":65,"vac":10,"topic":"owntracks/Henk/41151CB8-4C3B-4A0A-BEA2-2E49E2B5FEA9","lat":  balbalbal  ,"t":"u","conn":"w","tst":1500234568,"alt":6,"_type":"location","tid":"DK"}
20170716-21:49:29 received '{"batt":62,"lon":  balbalbal  ,"acc":65,"vac":10,"topic":"owntracks/Henk/41151CB8-4C3B-4A0A-BEA2-2E49E2B5FEA9","lat":  balbalbal  ,"t":"u","conn":"w","tst":1500234568,"alt":6,"_type":"location","tid":"DK"}' on 'owntracks/Henk/httpendpoint'
20170716-21:49:29 We have received a location message
20170716-21:49:29 Set battery percentage for Henk to 62%
20170716-21:49:29 User Henk authenticated
20170716-21:49:33 getLogLines called
20170716-21:58:08 handleOwntracksEvents called
20170716-21:58:08 {"batt":61,"lon":lbalbal,"acc":10,"vel":0,"vac":4,"lat":lbalbalba,"topic":"owntracks/Henk/41151CB8-4C3B-4A0A-BEA2-2E49E2B5FEA9","t":"u","conn":"w","tst":1500235088,"alt":10,"_type":"location","tid":"DK"}
20170716-21:58:08 received '{"batt":61,"lon":5.876082340260852,"acc":10,"vel":0,"vac":4,"lat":51.94217903544376,"topic":"owntracks/Henk/41151CB8-4C3B-4A0A-BEA2-2E49E2B5FEA9","t":"u","conn":"w","tst":1500235088,"alt":10,"_type":"location","tid":"DK"}' on 'owntracks/Henk/httpendpoint'
20170716-21:58:08 We have received a location message
20170716-21:58:08 User Henkauthenticated
20170716-21:58:13 handleOwntracksEvents called
20170716-21:58:13 {"batt":61,"lon": balbalbal,"acc":10,"vel":0,"vac":4,"lat":balblabal,"topic":"owntracks/Henk/41151CB8-4C3B-4A0A-BEA2-2E49E2B5FEA9","t":"u","conn":"w","tst":1500235091,"alt":10,"_type":"location","tid":"DK"}
20170716-21:58:13 received '{"batt":61,"lon":balblabla,"acc":10,"vel":0,"vac":4,"lat":lbalbal,"topic":"owntracks/Henk/41151CB8-4C3B-4A0A-BEA2-2E49E2B5FEA9","t":"u","conn":"w","tst":1500235091,"alt":10,"_type":"location","tid":"DK"}' on 'owntracks/Henk/httpendpoint'
20170716-21:58:13 We have received a location message
20170716-21:58:13 Set battery percentage for Henk to 61%
20170716-21:58:13 User Henk authenticated
20170716-21:58:14 handleOwntracksEvents called
```

**Comment by scanno** [comment]
I am the author of the application @DeefK is using, i also added a comment in issue #375.
As mentioned in issue #375, Android users do not have problems. The android owntracks app sends event messages:

```
20170716-22:28:30 {"_type":"transition","tid":"3t","acc":19.503,"desc":"thuis","event":"enter","lat":xx.yyyyyy,"lon":x.yyyyy,"tst":1500236913,"wtst":1500053935,"t":"c"}
20170716-22:28:30 received '{"_type":"transition","tid":"3t","acc":19.503,"desc":"thuis","event":"enter","lat":xx.yyyyyyy,"lon":x.yyyyyyy,"tst":1500236913,"wtst":1500053935,"t":"c"}' on 'owntracks/xxxxxxxxx/httpendpoint'
20170716-22:28:30 Accuracy is within limits
20170716-22:28:30 Fence: thuis changed

```
As this does seems to work in Android, this seems to be something in the iOS app that does not send the transistion message on enter/leave.

**Comment by jpmens** [comment]
Show us, please, how this waypoint was created in iOS; a screenshot of it is fine (you can obliterate lat/lon)

**Comment by Rido** [comment]
I have the same issue, so here's a screenshot of my own:

![al3dwuhtjao9](https://user-images.githubusercontent.com/1889864/28258480-b671a170-6ad1-11e7-9452-d484fccb9f63.png)

**Comment by jpmens** [comment]
Help me understand what's happening: what do @DeefK and @Rido have in common? 

Also, which broker are you using?
Please show pertitnent ACLs

**Comment by Rido** [comment]
We're using the Homey (domotica controller) Owntracks client made by @scanno. This client can trigger domotica flows inside of our controller when arriving or leaving a region.
The problem is that the iOS app won't trigger a transition, so Homey doesn't know that we leave a region (I do receive a notification on iOS when leaving a region).

The broker I'm using is Mosquitto on a Synology NAS with a user that has full access.

**Comment by jpmens** [comment]
The output posted above (I've reformatted) is confusing as it contains two topic-like things, one probably from your Homey the other from OwnTracks.

Please provide proper logs (Mosquitto) and results from `mosquitto_sub` when entering/leaving the waypoint you showed us.

**Comment by scanno** [comment]
@jpmens this issue can be closed. Thanks for the help.

**Comment by jpmens** [comment]
It's polite to tell us what you did to solve the problem or if it was a problem to start with, particularly after we helped you or at least spent time on this issue!
