### ISSUE TITLE
Waypoints/shared location with ibeacon

### ISSUE THREAD

**Issue by x821938** [owntracks/ios#472]
I am using an ibeacon and I have set it up with owntracks. Owntrack detects when i turn on and off the beacon. I get both MQTT events and the IOS push notifications too. 

But....

After full restarting the owntracks app (doubleclick button and slide up to close), It seems to forget sending MQTT evens about waypoints. I still get the IOS push notifications when I turn on and off the beacon. But I dont get any MQTT events published to /owntracks/me/phone/event :(

After jiggeling a little, like turning on and off the sharing of the beacon, I can get it working again.... only until next time I restart the owntracks app.

I hope I explained myself good enough.... besides that I love your app :)

Best regards,
   Alex

**Comment by ckrey** [comment]
Hi Alex,

what you call IOS push notifications are just "Local Notifications by the OwnTracks App".

You only get `.../event` messages when sharing is enabled. Otherwise the app just uses the enter/leave as a trigger to publish the current position. In this case the trigger in the payload indicates this (`"t":"b"` b for beacon).

What you call full restarting the owntracks app is a "brutal kill of the app".
Please note that the changed settings (Sharing, etc.) of a Region are only saved to non-volatile memory when you exit the setup screen (< Regions). If you kill the app while on the setup screen, your last changes are not saved.

If you do save the changes, the app should work as you expect.

**Comment by x821938** [comment]
Hi,

I probably got my terms wrong, so I will try again:

I know that I only get an event when sharing is enabled and saved (by exiting the reqions screen). I also get a mqtt event in the very moment I enable sharing of the beacon.

Owntrack also seems to detect the precense of the beacon very good by always making "local notifications". All this is great :)

The problem is that it often forget to send the mqtt events with ("t": "b"). Could it because my car 
 beacon is in the same location as my home location? See screenshot:

![img_7667](https://user-images.githubusercontent.com/12182986/28517860-37b476d8-7066-11e7-98e8-c36beb6635ff.PNG)

Best regards,
   Alex

**Comment by ckrey** [comment]
Hi Alex,

thank you for the screenshot.

I think you are talking about 2 different things:
a) iBeacons
b) Waypoints

I am not sure what you do expect? Do you expect the app to sent a new event after restart? It doesn't, because iOS remembers the last status (inside or outside a region). The event will only get triggered when you actually move.

**Comment by x821938** [comment]
Hi again,

I am expecting to see some mqtt messages when I turn on and off my beacon. That seem to fail a lot :(
It's like I can get it working for a couple of times and then the mqtt messages stop coming, no matter how many times i restart my beacon.

Best regards,
   Alex

**Comment by x821938** [comment]
Here is an example of the log of my mosquitto server. These are the entries that appear when I turn on my beacon.

```
Jul 24 12:50:10 homeauto mosquitto[12633]: New connection from 192.168.xxx.xxx on port 11111.
Jul 24 12:50:10 homeauto mosquitto[12633]: New client connected from 192.168.xxx.xxx as asjiphone (c1, k60, u'asj').
Jul 24 12:50:10 homeauto mosquitto[12633]: Sending CONNACK to asjiphone (0, 0)
Jul 24 12:50:10 homeauto mosquitto[12633]: Received SUBSCRIBE from asjiphone
Jul 24 12:50:10 homeauto mosquitto[12633]:         owntracks/+/+ (QoS 0)
Jul 24 12:50:10 homeauto mosquitto[12633]: asjiphone 0 owntracks/+/+
Jul 24 12:50:10 homeauto mosquitto[12633]: Sending SUBACK to asjiphone
Jul 24 12:50:10 homeauto mosquitto[12633]: Received SUBSCRIBE from asjiphone
Jul 24 12:50:10 homeauto mosquitto[12633]:         owntracks/+/+/event (QoS 0)
Jul 24 12:50:10 homeauto mosquitto[12633]: asjiphone 0 owntracks/+/+/event
Jul 24 12:50:10 homeauto mosquitto[12633]: Sending SUBACK to asjiphone
Jul 24 12:50:10 homeauto mosquitto[12633]: Received SUBSCRIBE from asjiphone
Jul 24 12:50:10 homeauto mosquitto[12633]:         owntracks/+/+/info (QoS 0)
Jul 24 12:50:10 homeauto mosquitto[12633]: asjiphone 0 owntracks/+/+/info
Jul 24 12:50:10 homeauto mosquitto[12633]: Sending SUBACK to asjiphone
Jul 24 12:50:10 homeauto mosquitto[12633]: Received SUBSCRIBE from asjiphone
Jul 24 12:50:10 homeauto mosquitto[12633]:         owntracks/asj/iphone/cmd (QoS 0)
Jul 24 12:50:10 homeauto mosquitto[12633]: asjiphone 0 owntracks/asj/iphone/cmd
Jul 24 12:50:10 homeauto mosquitto[12633]: Sending SUBACK to asjiphone
Jul 24 12:50:11 homeauto mosquitto[12633]: Received PINGREQ from ot-recorder-homeauto-1328
Jul 24 12:50:11 homeauto mosquitto[12633]: Sending PINGRESP to ot-recorder-homeauto-1328
Jul 24 12:50:13 homeauto mosquitto[12633]: Received DISCONNECT from asjiphone
Jul 24 12:50:13 homeauto mosquitto[12633]: Client asjiphone disconnected.

```
The phone connects via mqtt, but it forgets tu publish anything.

Best regards,
    Alex

**Comment by ckrey** [comment]
Why do you use cleanSession=True?

This erases all your offline data on the client! And the client was offline when the event happened.

**Comment by x821938** [comment]
I have done all the setup in the UI, and I have not set that on purpose.... 
I can't find that setting in the UI?

Best regards,
    Alex

**Comment by ckrey** [comment]
Thank you for helping to track this down.
There is a problem in the UI which does not set the proper default when switching to Private mode.

You can edit all parameters by tapping 3 times on the `Status Info` screen.

**Comment by x821938** [comment]
I changed the setting you mentioned... It still didn't solve the problem.
But now my phone doesn's mqtt subscribe when i turn on the beacon. Now it looks like this in my mosquitto log:
```
Jul 24 15:06:51 homeauto mosquitto[12633]: New connection from 192.168.20.10 on port 58883.
Jul 24 15:06:51 homeauto mosquitto[12633]: Client asjiphone disconnected.
Jul 24 15:06:51 homeauto mosquitto[12633]: New client connected from 192.168.20.10 as asjiphone (c0, k60, u'asj').
Jul 24 15:06:51 homeauto mosquitto[12633]: Sending CONNACK to asjiphone (1, 0)
Jul 24 15:07:06 homeauto mosquitto[12633]: Received DISCONNECT from asjiphone
Jul 24 15:07:06 homeauto mosquitto[12633]: Client asjiphone disconnected.
```

**Comment by ckrey** [comment]
This is normal behaviour, when CONNACK returns (1), then the broker still knows the subscriptions.

Please try again

**Comment by x821938** [comment]
Everything seem to work fine, when my phones display is on and showing owntracks region page (while turning on/off my beacon).... But when I am not inside the owntrack app, I only get the local notification, but no mqtt message.

**Comment by ckrey** [comment]
Please set 
      "pubQos":1,
      "subQos":1,

**Comment by x821938** [comment]
Now it seems to work :)
Thanks for your help :) :) :)

shouldn't pub and sup be true by default?

**Comment by ckrey** [comment]
Yes, they should as the cleansession should have been false
Not your fault. I will put a new version to the app store soon

**Comment by x821938** [comment]
Thanks a lot - have a nice day :)
