### ISSUE TITLE
Geofence - Differentiate between enter and leave

### ISSUE THREAD

**Issue by tomjmul** [owntracks/ios#477]
In the message payload we have "t":"c" to signify that a circular region has been entered/left, though there is no way to know whether it is actually and enter or a leave event. Can an additional property be added to differentiate? Or, perhaps, the value changed depending on whether the region has been entered or left?

**Comment by ckrey** [comment]
The message payload you are referring to is the `location` message.

The information you want is published as `transition` messages described [here](http://owntracks.org/booklet/tech/json/#_typetransition)
