### ISSUE TITLE
Feature request: send back FRIENDS payload in http mode

### ISSUE THREAD

**Issue by tomyvi** [owntracks/ios#478]
In http mode, propose a way to update app with friends location :

when owntracks app sends payload to http client, expect to receive in return a json payload with all friends location to be displayed on the 'friends' screen of the app (with as detailed information as in the MQTT mode)

**Comment by jpmens** [comment]
This is [already implemented and documented](http://owntracks.org/booklet/tech/http/).

**Comment by tomyvi** [comment]
my mistake... good job !!!!!

**Comment by mgmino** [comment]
I can help you with this.  I extended your recorder.php script to return this information.
