### ISSUE TITLE
iOS11 reverse geocoding hangs/fails

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#479]
goto friends list to see the problem

**Comment by ckrey** [comment]
![img_5215](https://user-images.githubusercontent.com/4027289/30641171-5dc0ab4e-9e06-11e7-93dd-358a4ee3e5a7.jpg)
![img_5216](https://user-images.githubusercontent.com/4027289/30641172-5dcc8446-9e06-11e7-94d3-ad9198169438.jpg)

**Comment by jpmens** [comment]
me thinks this is https://github.com/owntracks/ios/issues/440

**Comment by ckrey** [comment]
This was only observed shortly after upgrading to iOS11. The devices seems to have used it's quota of address resolving. Not necessarily by OwnTracks.

Other apps had the same problem.

Next day everything was back to normal
