### ISSUE TITLE
iOS 11 devices hangs

### ISSUE THREAD

**Issue by dineshdatasisar** [owntracks/ios#480]
We are using owntracks in one of our app, till now its working fine, with the recent iOS 11 update, app hangs. When I comment owntrack methods it works fine.

**Comment by jpmens** [comment]
What do you mean by "we are using OwnTracks in one of our apps" ? Which app? Please tell us what you're doing with OwnTracks so we can better help you.

**Comment by dineshdatasisar** [comment]
owntracks is implemented in the app for tracking user locations.

**Comment by dineshdatasisar** [comment]
Owntracks is not working properly in iOS 11, it has some lag. We tried to integrated owntracks to find user location.

**Comment by jpmens** [comment]
@dineshdatasisar you should take some time to explain what you are doing. "is integrated in the app" is definitely not a description. Please elaborate.

**Comment by jpmens** [comment]
@dineshdatasisar Did you just write this email to our support address?

> Downloaded own tracks app from App Store.  I am using iPhone 6s iOS 11. App UI is not responsive. 

I have asked to you EXPLAIN what you are doing. You now have one last chance.

**Comment by ckrey** [comment]
Closing due to no response
