### ISSUE TITLE
iPhone iOS 11.0.1 owntracks, stops publishing in the evening.

### ISSUE THREAD

**Issue by karimmansour** [owntracks/ios#482]
iPhone owntracks, stops publishing in the evening.
iOS: 11.0.1 
App is running in Background
Background App refresh Enabled
Location access set to Always

Am I missing something?

**Comment by jpmens** [comment]
You're going to have to describe better what "stops publishing in the evening" means. Tell us what you do with OwnTracks; tell us what's different in the evening (your network, network location, etc.)

**Comment by karimmansour** [comment]
I use Owntracks to track an iPhone. I keep logs on the MQTT server.

I notice that when the phone is not touched (used) for long time (tested around 5 hrs), not only in the evening, and then I start moving with the phone after the e.g. 5 hours, I see that the MQTT server does not receive any updates. Once I open owntracks app on the iPhone, I find immediately the MQTT server start receiving updates. The App was running in the background, and I am sure it is with App refresh enabled and location access set to always. Also in the Owntracks app Move mode is enabled. But I noticed when I open the app (where the moment it is start publishing to the mqtt server) that the app  looks like it is initializing even if it was running in the background. My judgment looks like it goes to sleep or something, I am not sure. 

Please let me know if I can help more with more data.

**Comment by cmsimike** [comment]
I am experiencing a similar-ish issue. I have noticed that owntracks just doesn't push anything anymore to MQTT. Opening up the app, I tried pressing the "location" button to find me on the map, but it just spins without ever coming back.

Going into iOS settings -> privacy -> location services -> owntracks doesn't give any options for location services. going into the menu and clicking out ends up populating that list, but upon phone restart those settings are lost again and no location tracking happens at all.

**Comment by farstreet** [comment]
Same experience here. The Location

**Comment by farstreet** [comment]
Same experience here.  When going to Settings > Privacy > Location Services and search for Owntracks, I can see something is wrong from the list already.   Next to Owntracks, there is the little symbol, in grey (indicating that the app has used the location in the last 24h), but there is nothing else.  No "Always" (what should be there), but also no "While Using App" or "Never".    When choosing Owntracks, there is only the option "Never" however not selected.   I can select it, go back to the list, choose Owntracks again and then all three options are there.   However, when choosing Always and leaving the Settings to try again, it still doesn't work.   Going back to the Location Services, the same issue is there again.
![img_3129](https://user-images.githubusercontent.com/24705229/31105178-fc0ee5d8-a796-11e7-97d2-ffc7a24eaf9b.PNG)
![img_3130](https://user-images.githubusercontent.com/24705229/31105180-fc37ae96-a796-11e7-81f8-ef9d731841de.PNG)
![img_3131](https://user-images.githubusercontent.com/24705229/31105179-fc3741f4-a796-11e7-9c2b-d44e243f86bf.PNG)
![img_3132](https://user-images.githubusercontent.com/24705229/31105182-fc3c7c82-a796-11e7-8e61-5efad01ec626.PNG)
![img_3133](https://user-images.githubusercontent.com/24705229/31105181-fc3b6aea-a796-11e7-80ae-7cd711b31396.PNG)

**Comment by farstreet** [comment]
Using version 9.7.1/en_US, which seems to be an update released today.   
But so far without luck.

**Comment by cmsimike** [comment]
@farstreet thank you! this is exactly what i am seeing.

**Comment by ckrey** [comment]
@cmsimike and @farstreet: your issue is known, fixed and a new version 9.7.2 is available in the app store. The details were tracked in issue #483.

The problems of @karimmansour are probably different and are related how iOS (11) handles background applications

**Comment by cmsimike** [comment]
@ckrey Sorry I couldn't comment last night but 9.7.2 fixed all my issues! Thank you.

**Comment by jpmens** [comment]
Thanks for reporting back; glad it's all working.
