### ISSUE TITLE
OwnTracks locationsettings are wrong

### ISSUE THREAD

**Issue by thomasmul** [owntracks/ios#483]
I installed today on iPhone 6s with iOS 11. When I start the app it can’t find a gps fix. When I look at location settings there is something weird. I can only chose never, go back and then select always. For a while OwnTracks works but when I leave the app and later return again the location service is messed up. Besides this problem OwnTracks does Burt seem to find my iBeacon??

**Comment by ckrey** [comment]
Yes such things always happen in September when Apple upgrades to a new iOS Version and changes the tools https://mackuba.eu/2017/07/13/changes-to-location-tracking-in-ios-11/

**Comment by ckrey** [comment]
```
2017-09-30 09:34:33.727823+0200 OwnTracks[1296:687830] This app has attempted to access privacy-sensitive data without a usage description. The app's Info.plist must contain both NSLocationAlwaysAndWhenInUseUsageDescription and NSLocationWhenInUseUsageDescription keys with string values explaining to the user how the app uses this data
```

**Comment by bolsen27** [comment]
I just started having this issue on my iPhone today. I see this thread is marked as fixed but I don’t see a new version of owntracks available for download. Am I supposed to fix it another way in some setting?

**Comment by bachya** [comment]
This is still present in 9.7.1/en_US. I’d add that even after correcting location access, some time later, the issue reappears.

**Comment by bachya** [comment]
@bolsen27 This looks like it’s been fixed in 9.7.2; although it hasn’t been released yet, I’m sure it will be shorty.

**Comment by ckrey** [comment]
The fixed version is @apple for review. This usually takes less than a day, but over the weekend we may need a bit more patience

> Von: iTunes Store no_reply@email.apple.com
> Datum: 30. September 2017 um 15:25:10 MESZ
> An: c@ckrey.de
> Betreff: Your app (iOS) status is Waiting For Review

**Comment by bolsen27** [comment]
Thanks! I’ll keep an eye out. :)

Brian Olsen
940-782-2401

**Comment by ajdezigns** [comment]
Do we know how much longer till this update goes through?

**Comment by ckrey** [comment]
I think it is still weekend on the West Coast of the US of A

**Comment by schettada** [comment]
I'm not sure if this issues has to to do with IOS 11. I'm running 11.0 and it was working as expected. Seeing this issue after the owntracks app update to version 9.7.1. I was running ios 11 beta as well last couple of months and didnt see the issue.

**Comment by jpmens** [comment]
Please have some patience, people: @ckrey has done *all* possible to fix this; we now have to wait for Apple. (And no: we do not know how long that will take.)

**Comment by ckrey** [comment]
The following app has been approved and the app status has changed to Ready for Sale:

App Name: OwnTracks
--
App Version Number: 9.7.2

**Comment by lolouk44** [comment]
Fixed for me, thanks for your reactivity guys :)

**Comment by jpmens** [comment]
Good to hear, and thanks for reporting back.

**Comment by bachya** [comment]
Appreciate the quick fix, all! Thank you!
