### ISSUE TITLE
Owntracks doesn't find location on iOS 11

### ISSUE THREAD

**Issue by lolouk44** [owntracks/ios#485]
Owntracks doesn't find location on iOS 11. If I own the app and press the arrow to show my location, I never finds it. If I then go to iOS privacy settings I only have the option "never".
If I select"never" of can then go back a step (show all apps) and select owntracks again when I them have all options and can select "always". From here I can go back to owntracks app and it will show my location while in the app.
If I exit the app then it's back to square one

**Comment by jpmens** [comment]
We’re working on a fix which will be available soon. This issue is being tracked https://github.com/owntracks/ios/issues/483
