### ISSUE TITLE
Owntracks 9.7.1 on iOS 11.0.1 fails to locate, and thus no region entry/exit events

### ISSUE THREAD

**Issue by hlapp** [owntracks/ios#487]
_(I haven't seen this reported here yet, so hoping it's not a duplicate. Apologies if it is.)_

The recent update of Owntracks to v9.7.1 on iOS 11.0.1 appears to have an issue with the Location Services. Specifically, it is unable to locate position of the phone, and when the arrow is tapped that would trigger locating manually, it just keeps spinning busy, never updating or showing its location. 

It appears that this may have to do with an issue with the Location Services permissions. If I pull up the permissions (Settings->Privacy->Location Services), no option (of the possible "Never", "While using the app", "Always") appears, and when tapping Owntracks, only the option "Never" appears, but is not selected. When I select it and then tap "Back", the Owntracks entry shows the option "Never". Tapping the entry again, I now get all three options, with "Never" selected. If I now select "Always" and go back, this is the option that shows, and the color of the arrow  indicates that Owntracks is actively using the Location Services. But if I now return to the Owntracks app, the issue with locating is unchanged, and if I then return to Settings->Privacy->Location Services, the original issue is back (no option shown, tapping shows only "Never" and it isn't selected).

So effectively, Owntracks has stopped working since the latest update, because with no location update it of course never posts any region entry/exit events either. (The Info screen does show that it is "connected" to my MQTT broker.)

**Comment by jpmens** [comment]
We're aware and this has [been fixed](https://github.com/owntracks/ios/issues/483). 9.7.2 should be in the app store momentarily.

**Comment by ckrey** [comment]
see details in #483

**Comment by hlapp** [comment]
Awesome, thank! I should have looked at recently closed issues, too. My bad.

**Comment by sheppy99** [comment]
The new version has arrived down under and it looks like geofencing works again. Thanks @ckrey @jpmens  and anyone else involved for your prompt fix.
