### ISSUE TITLE
Stuck on most recently visited beacon

### ISSUE THREAD

**Issue by roqvist** [owntracks/ios#488]
In version 9.7.2/en_SE when I leave a beacon zone and should enter GPS positioning the most recently visited beacon is still active (red) on the map and no MQTT updates are being sent.

The location seems to change, my icon is moving away from the beacon, but the beacon is shown as active (red) even from 20km+ away.

**Comment by ckrey** [comment]
Please check your Settings/Privacy/Location for Owntracks.

iBeacon enter leave works fine here on iOS11 Owntracks7.9.2 for individual iBeacons or groups (major and/or minor = zero).

**Comment by roqvist** [comment]
Location data for the app is set to 'always'. The beacon eventually released and is no longer active but I have not received any updates on my position. I'll test some more over the weekend and see if I can reproduce it or I'll just call it a one time thing and remove this issue.

**Comment by roqvist** [comment]
My girlfriend got the same thing today, she’s at work now but one of our home beacons are still active (red).

I noticed more people have similar problems with leaving regions so to keep things clean maybe we can reference this issue to #489

**Comment by roqvist** [comment]
Duplicate of #489
