### ISSUE TITLE
Missing event publishes since upgrade to 9.7.2

### ISSUE THREAD

**Issue by ianjenn** [owntracks/ios#489]
ios 11.02 owntracks 9.7.2 iPhone 7
Prior to ios 11 owntracks was brilliant and I am very grateful for the work that goes in to it.
9.7.2 has solved the missing location settings. 
I get updates about location published in mosquito mqtt.
however, there seems to be some sort of issue with regions They seem to take quite along time to update within the owntracks ios app from switching from blue to red. But the main problem is that there is no event sent to mosquito mqtt.

**Comment by jpmens** [comment]
I cannot confirm this for three devices using 9.7.2: enter/leave events work as they always have.

You say no event is received by Mosquitto. May we assume that absolutely no reconfiguration has been done Mosquitto-side since you upgraded the app on iOS? No ACL changes?

**Comment by ckrey** [comment]
Same here, enter/leave events for circular regions and iBeacon regions are detected and transmitted to  owntracks/*user*/*device*/event topic as before OwnTracks9.7.2 and iOS11.0.2

```
owntracks/*user*/*device*/event                   {"t":"c","tst":1507408281,"acc":65,"_type":"transition","event":"enter","lon":6.***,"lat":51.***,"wtst":1506950908,"tid":"SE","desc":"Home"}
```

Please let us know a bit more about your environment.

If you say "it takes longer to switch from blue to red", does that mean you are watching it with OwnTracks in foreground?

**Comment by ianjenn** [comment]
So in ios app I can see myself leave the region and update my position, but then if I select regions on app it is still red. Then after a period of time it switches to blue. After re-entering a region it is the same delay. But if I change the size of the region it seems to force an update.

But nothing comes to mqtt about events. Interestingly changing the size of the region comes through as a waypoint update on mosquitto. I have changed nothing on mosquito and it has worked brilliantly for 2 years. I think my daughters phone which is an iPhone 6 is working fine so it might be just on the 7.

**Comment by roqvist** [comment]
We have the same or similar problem, leaving home beacon zone will sometimes keep the last visited zone active for a long time (5 hours last week) before turning to GPS. But the icon on the map updates correctly. Did not have this before 9.7.2.

iOS 11.0.2 (15A421)

We do have Bluetooth in the car that connects to the phone when we leave our home, not sure if that has anything to do with it but this has worked fine before.

**Comment by roqvist** [comment]
We use iPhones 7 as well and CloudMQTT broker service (they use Mosquitto).

**Comment by ckrey** [comment]
@ianjenn yes, if you change a region (e.g. change the radius), an update is triggered via MQTT if you have choosen to `share`  the waypoint

**Comment by ckrey** [comment]
@roqvist and @iajenn region enter and leave detection is a task of iOS, not of the OwnTracks app.
We could have done this differently, but with a major negative impact on battery life.

Your observation means: Apple has made some changes in iOS which have effects on different iPhone models. They might have introduced a bug, too

If iOS does not trigger the region enter or leave events, the OwnTracks app will not try to publish a message.

**Comment by roqvist** [comment]
Thanks for the info, I'll look around and see if I can find any bug reports regarding the region enter/leave alerts. This link explained quite well the (major) changes in location tracking between iOS 10 and 11: https://mackuba.eu/2017/07/13/changes-to-location-tracking-in-ios-11/

For me everything works as expected 75% of the time so it's not a deal breaker right now.

**Comment by roqvist** [comment]
Indeed there are some posts on Apple dev forums, starting with iOS 10, describing problems with `didExitRegion` and other region specific events.

I never experienced any problems on iOS 10 but perhaps the underlying bug is more evident now in iOS 11.

Some developers targeted different/earlier swift version in their apps and got it working but it seems like a hit-and-miss.

Hopefully enough voices are raised so Apple will investigate and fix it.

**Comment by ianjenn** [comment]
weirdly, after much head scratching yesterday. enter and leave events are now working again!
I have done nothing except get frustrated and having a nights sleep.
I have no idea what was stopping things working yesterday
