### ISSUE TITLE
HTTP error when no signal, does not retry correc

### ISSUE THREAD

**Issue by TonyFeestneus** [owntracks/ios#490]
When using Http, if you go in to a zone where data reception is bad, it ofcourse can't publish location, states http error 500 but does not recover from this when regaining data signal.

Even at home on wifi it keeps giving http error. Would you change the settings completely it will work again, but that is not a viable workaround.

HTTP server is always reachable, but it keeps saying error 500. Which is incorrect.

**Comment by ckrey** [comment]
Dear @TonyFeestneus if you are using HTTP mode, you are probably running an HTTP server. If you are running an HTTP server, you probably have access and error logs of that server. Please have a look there and if you want, share with us.

Here is a hint for you: error 500 does not mean the server is not reachable, but means `internal server error`
[HTTP Status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)

**Comment by TonyFeestneus** [comment]
I know. But when your app says error 500, I can access the url without any issues. So there is no actual internal error, it is just that the app does not recover from it.

I do see this in my server log (Node js express server):
sh: 1: Syntax error: Unterminated quoted string

**Comment by ckrey** [comment]
Correct: It is your server that does not handle the payload correctly

**Comment by TonyFeestneus** [comment]
Mm... why would this only happen if I enter a zone where I have no data? If I set it up again it works flawlessly...

**Comment by jpmens** [comment]
@TonyFeestneus there is no doubt: HTTP 500 is being issued by your backend. 

Furthermore you say "if I set it up again". Set _what_ up? You mean the app config? That makes no sense. Entering app settings simply republishes when you exit. This indicates further that it's your HTTP service backend which is behaving incorrectly.

**Comment by ckrey** [comment]
@TonyFeestneus When you set it up again, the app clears all queued data and does not re-try to send it to the server. This explains why the issues goes away temporarily.

When you are in a `zone where I have no data` (whatever that means) the app may send your HTTP server a slightly different message which you need to handle there (at the HTTP server without exiting with a 500 internal server error).

**Comment by TonyFeestneus** [comment]
Having no data means no wifi, no cellular data connection. So it does not send anything to my server since it has no data. After that it did not pick up.

Do you know what message is sent or queued when signal loss is happening?

**Comment by jpmens** [comment]
There is no specific message when signal loss happens. Do yourself (and us) a favor: write a small HTTP side thing which just collects data in the different occurances you're seeing, then compare the data and react accordingly.

**Comment by TonyFeestneus** [comment]
Thanks for the advice. Tomorrow I will have visited the area again which caused trouble last times.

**Comment by TonyFeestneus** [comment]
Well, problems were over but with nothing changed, new problems are here. My server is perfectly reachable, but it doesn't try according to my server logs. The app states nserrorfailingurlkey

**Comment by jpmens** [comment]
How much work have you invested in querying a search engine what that could mean? What are your findings?

**Comment by TonyFeestneus** [comment]
Let me be wise and not go in to the tone that is being set here as if my problem isn't real and as if your app is the best, faultless app in the world.

I have a running server, now not generating any errors, perfectly reachable, which the app does once in a while, but mostly it still hangs because it caughed on a problematic signal loss. Yes there was also a error by me. Now there is not, since I am pointing the app to a simpel PHP-page only containging <?php echo 'hello'; ?>. Still errors, while any browser can reach the page perfectly fine.

So, of course I will mention this here. Can you be of assistance perhaps?

**Comment by jpmens** [comment]
No. Not with sentences like "since I am pointing the app to a simpel PHP-page only containging". We cannot know what you mean.

Either you show us the code and hope that somebody is willing to glance at it or that's it.

**Comment by TonyFeestneus** [comment]
Open Owntracks iOs App > i-button top left corner > Settings > Mode HTTP > Authentication on, userid and password filled, URL set to my server (which resides at home, and is reachable also from outside).

Click Publish Location icon > go to i-button top left corner > states connecting, after a while comes up with the aforementioned error: The request timed out. NSErrorFailingURLKey = 'keyherewhich is correct'

I made a typo: "since I am pointing the app to a simpel PHP-page only containging", must be "Since I am pointing the app (URL-field) to a simple PHP-page on my server only containing the following code':
`<?php echo 'hello'; ?>`

**Comment by jpmens** [comment]
You have opened this issue with `<?php echo 'hello'; ?>` as your back-end thing? Are you honestly saying that? Have you actually read the Booklet page in which is described what your backend receives and what you should return?

**Comment by TonyFeestneus** [comment]
Can you perhaps write any comment without sounding insulting?

Are you honestly overlooking the fact that it did work for me so perhaps I do know how to write a PHP-page that works? The thing is, the app treats it inconsistently and that is what at least I am trying to fix. Without judging anyone or making anyone feel bad. Lighten up jpmens. Please.

`<?php echo 'hello'; ?>` was an example.

Let 's say:
`<?php echo 'hello';
$response = array();
    # optionally add objects to return to the app (e.g.
    # friends or cards)
    print json_encode($response);
?>`

**Comment by TonyFeestneus** [comment]
Set it up again and is working again. I will see what happens when I enter that zone again. Thanks for your very kind help jpmens, you are a delight.

**Comment by jpmens** [comment]
> you are a delight

It is a pleasure, I'm sure.

**Comment by Matsaki** [comment]
I get error 401 in iOS and I can't go in and edit HTTP like its possible in Android.

**Comment by jpmens** [comment]
@Matsaki this issue was closed two years ago. Please file a new issue and explain exactly what the problem is.
