### ISSUE TITLE
Owntracks is only logging for a short period after region notifications

### ISSUE THREAD

**Issue by rjp** [owntracks/ios#491]
Same problem is back on iOS 11.1 (15B5066f) with Owntracks 9.7.2.

Background App Refresh is on. Location Services are set to always (with hollow arrow - this seems like the wrong one).

Attached: points for the last ~85 hours and both regions.

![img_1352](https://user-images.githubusercontent.com/10793/31332797-b20fbd2e-acdf-11e7-83fa-d8f9596195c0.jpg)

![img_1353](https://user-images.githubusercontent.com/10793/31332798-b21120ec-acdf-11e7-8f01-dc2a3bf0ead4.jpg)

![only-region-points-for-four-days](https://user-images.githubusercontent.com/10793/31332411-32399ecc-acde-11e7-8e92-09d94e54c733.jpg)

**Comment by rjp** [comment]
Having had a quick look at the data, it looks like there's only about 3 minutes of activity after a triggered notification.

**Comment by jpmens** [comment]
Please elaborate and explain what issue you are actually reporting. I am understanding that your app isn't publishing MQTT events after entering/leaving a region; is that so? Show us broker logs please which correlate that.

**Comment by jpmens** [comment]
Above you said
> Attached: points for the last ~85 hours and both regions.

If you submitted by email note that attachments are not added.

**Comment by rjp** [comment]
No, the app is only pushing events for about 3 minutes after a geofence notification. Nothing else arrives at the recorder outside of those windows.

The attachments were the screenshots from the recorder web ui and the two regions; not a dump of the points themselves. Apologies - that could have been clearer.

When you say "broker logs", what do you mean? I'm using the owntracks docker images - where would I find the "broker logs"?

**Comment by ckrey** [comment]
Which monitoring mode (move, significant, manual, quiet) do you use.

And most important: what do you expect to happen?

**Comment by rjp** [comment]
Always "MOVE" mode. And I expect it to log points at the intervals specified in the configuration (currently 120s for time and 100 for distance.)

**Comment by ckrey** [comment]
The pattern you are experiencing is exactly what happens if the app is terminated (swiped out) and is re-activated by entering/leaving a region.

When the app is active (not swiped out) it behaves as you expected. 

Next time you go one of these places, please check if OwnTracks is still active.

What is iOS 11.1?  The most recent one I have is 11.0.3

One other reason for the app to terminate is if it crashes. I don't see any crashes reported through the app store. Do you have your Privacy/Diagnostics&Usage/ShareWithAppDeveloper setting enabled?

**Comment by jpmens** [comment]
@rjp are you swiping the app out?

**Comment by rjp** [comment]
No, I never swipe the app out. I’ve turned on “share analytics with app developers” and hopefully that might help.

I’ve also been logging all the events for the last couple of days with a simple script - maybe those are useful too.

**Comment by rjp** [comment]
11.1 (currently beta 3) is the latest dev build of iOS. (I’d guess it’ll probably drop for everyone around the time of X preorders.)

**Comment by rjp** [comment]
Having just checked my database of location points, I've noticed an odd pattern - after the first 3 11.1 beta updates, I got 2-3 days of what I expect from owntracks (~200 reported points) rather than the "triggered by notifications" updates.

**Comment by ckrey** [comment]
@rjp the current version 9.9.3 addresses a lot of possible crashes. Would you check again with this new version?
Thanks

**Comment by rjp** [comment]
Ok, that is working a lot better (as in how I would expect with my settings) using the new version on iOS 11.4.1.

**Comment by rjp** [comment]
Alas, it's back to being weird - yesterday it did an *excellent* job of tracking me walking around - pretty much a point every 3 minutes (which is ideal.) Today it's got a bunch of points at home then one point at work but nothing for the 2.5 hours between leaving home and the point at work. Can't be a region trigger because I don't have regions for those two places. I'd suspect it of being a WIFI thing but that doesn't explain yesterday's excellent tracking.

Is there any debug version I can run or logging I can enable to help debug this ongoing annoyance?

**Comment by ckrey** [comment]
@rjp what is the current status of your tracking issues?

**Comment by rjp** [comment]
Apologies for the delay - I wanted to give it some time with 12.4ß4 before reporting back.

With iOS 12.4ß4 and OwnTracks 12.0.3, things are looking pretty darned good. Absent the times when signal is patchy (ie on a train) and the odd glitches from the GPS (that affect all tracking apps), Move Mode is working as I'd expect with my settings.

**Comment by ckrey** [comment]
Thanks for the update @rjp
