### ISSUE TITLE
How can I import the .otrc file.

### ISSUE THREAD

**Issue by ElmarSieke** [owntracks/ios#492]
Hello,
I was able to export the file from the settings page.
But I am not able to import the File in an other phone. There exist no import button. If I open the file from my eMail box i can read the JSON content and I can save the file on the phone.

Maybe I missed something. Sorry for this question.

iOS 11.0.3
OT 9.7.2

**Comment by jpmens** [comment]
You should, from say e-mail app, be able to open it in OwnTracks with the "open as" dialog as long as OwnTracks is installed on that other phone.

**Comment by jpmens** [comment]
When you open the .otrc in mail you see the JSON. Then, at the bottom is the share (up-arrow) icon. Click on that, then in the list of apps select OwnTracks.

**Comment by ElmarSieke** [comment]
OwnTrack is not present in that list (Mail, Threema ... is).

**Comment by ElmarSieke** [comment]
By the way thank you for your fast answer!

**Comment by jpmens** [comment]
You might have to add the app to that list by pressing "..."

**Comment by ElmarSieke** [comment]
Also there it is not available.

**Comment by jpmens** [comment]
Look around a bit, please; it ought to be there somewhere as `Copy to OwnTracks`; I see it fine here on 11.0.3 with OwnTracks 9.7.2 installed.

**Comment by ElmarSieke** [comment]
Later on i will try it on another phone! Maybe the phone is restricted. I will inform you as soon as possible!

**Comment by ElmarSieke** [comment]
On the other phone it works as expected! So the **problem is related to my phone**!

Thank you again for your great help!

Maybe it's an idea to add your information to to the documentation? In my case this information was realy helpful.

Have a grat weekend
