### ISSUE TITLE
reportLocation when app is in background

### ISSUE THREAD

**Issue by NightRang3r** [owntracks/ios#494]
Hi,

I am not sure if this is an issue or not, When the app is running in background and i send the following message:

`mosquitto_pub -d -u mosquitto -P password -t "owntracks/user/User" -m '{"_type" : "cmd", "action": "reportLocation"}'`

I get:

```
Client mosqsub/23534-hassbian received PUBLISH (d0, q0, r0, m0, 'owntracks/user/User', ... (45 bytes))
{"_type" : "cmd", "action": "reportLocation"}
```

When the app is in foreground i get the data:

```
Client mosqsub/23534-hassbian received PUBLISH (d0, q0, r0, m0, 'owntracks/user/User', ... (177 bytes))
{"cog":000,"batt":74,"lon":00.000000000,"acc":50,"vel":0,"vac":24,"lat":00.000000000,"t":"r","_cp":1,"conn":"w","tst":1509697485,"alt":11,"_type":"location","tid":"US"}
```

Anyway to allow reportLocation when the app is in background ?

Thanks!

**Comment by ckrey** [comment]
No, because the app is not running in the background, it is suspended. 

You may send the command with QoS > 0, the it will be queued by the broker and executed the next time the app wakes up.

This is not a nee question and has bern discussed at length in other issues and in the docs

**Comment by NightRang3r** [comment]
Thank you and sorry, I couldn't find the answer in the docs :\
