### ISSUE TITLE
What happened to iOS 7 compatibility?

### ISSUE THREAD

**Issue by shymega** [owntracks/ios#497]
I'm trying to setup Owntracks for a close relative of mine who has difficulty remembering things, and we all get worried about her - so I proposed that we used Owntracks on her iPhone 4 (which runs iOS 7.1.2)

I did my research before proposing this idea. The booklet [said][booklet] said that iOS versions **above** or equal to iOS 6.1 _were_ compatible.

I tried to install Owntracks on her iPhone 4 - only to be told we need iOS 8. We can't upgrade her phone's iOS software, nor does she want to upgrade her phone yet - as she's quite happy with it (I strongly think she should, taking into account about security vulns..) - so I said to her I'd look into it.

The App Store states that only iOS versions above 8 are supported, but the boolet is misleading with regards to this. Might need to be updated..

Is there _any_ way to get support for iOS 7 devices, or is this now a non-option? :confused:

After a bit of research, I found [this][htg] article about a "hack" to get iOS 7.1.2 devices running older versions of a Owntracks. Not sure if it would work, but I'm going to do some more research on that.. 

Thanks for any help you can provide 😄 

[booklet]: http://owntracks.org/booklet/features/comparison/
[htg]: https://www.howtogeek.com/263568/how-to-install-older-versions-of-ios-apps-on-an-old-iphone-or-ipad/

**Comment by ckrey** [comment]
@shymega thanks for this hint. We updated the booklet.

Some of the older APIs are deprecated by Apple over the years, so we cannot provide new versions of the App for iOS versions older than 8.0.

The "hack" you mentioned is the standard way to retrieve older versions from the app store, which is a great feature of it

**Comment by shymega** [comment]
@ckrey Hey, no problems, this issue served a dual purpose; I'll admit that freely.

And yeah, I'm not surprised that Apple does that.. but no worries, I totally understand where you're coming from.

I'll use the older version for now, and hopefully - this relative will upgrade her iPhone at some point -- or even move to Android. I'd rather she didn't spend more money on an upgrade, but alas, this is the way Apple work. I don't agree with it, but this is the current state of things.

Loving Owntracks so far though, my family uses it, and we find it very useful!

Thanks for your very quick response man, very much appreciated. :+1:

**Comment by jpmens** [comment]
@shymega you write

> or even move to Android

in terms of running OwnTracks, that's a rather bad idea [at the moment](https://github.com/owntracks/android/issues/520)..

**Comment by shymega** [comment]
@jpmens Damn, I'm afraid I didn't know that.. that is quite unfortunate.

I know a bit about Android programming, so I'll comment in that issue, offer support.

Thanks for letting me know about this. It would explain a lot of the issues that the family have been having with the Android app.. such as not reconnecting. 😟
