### ISSUE TITLE
ios 11.2.1 and owntracks 9.7.2

### ISSUE THREAD

**Issue by grahamhar** [owntracks/ios#499]
After upgrading to owntracks 9.7.2 and then upgrading to ios 11.2.1 the app stops working. The app is showing a red notification bubble, but when the app is started it hangs at the splash screen then exits/crashes.

![img_3124](https://user-images.githubusercontent.com/904991/34034111-0699dfd6-e175-11e7-94be-e23ae6c01860.jpg)
![img_3125](https://user-images.githubusercontent.com/904991/34034115-0a0d731c-e175-11e7-8e15-15bcef7bb0cb.png)

**Comment by ckrey** [comment]
Which OwnTracks version did you have before?
Did you start 9.7.2 before upgrading to iOS 11.2.1?

**Comment by grahamhar** [comment]
Owntracks was installed and configured from previous version (Sorry I can't state what the version was but I do update all apps all the time). I don't open the app, but I can see from my location history on the server side that it was working up to the point ios update happened.

I Just power cycled the device and owntracks has started working again now.
