### ISSUE TITLE
Translation to Polish language

### ISSUE THREAD

**Issue by nxtpl** [owntracks/ios#500]
Hello,
I'd like to make a Polish translation of this app :)

I assume the assets to be translated are located below.
https://github.com/owntracks/ios/tree/master/OwnTracks/OwnTracks/en.lproj

Shall I translate Localizable.strings and Storyboard.strings?

**Comment by ckrey** [comment]
@nxtpl thank you for your support

To be honest, you are the very first user of OwnTracks iOS to undertake the translation.

This means there might be a few strings which are not prepared for Internationalization, but in general
the process is prepared.

There are 5 files to be translated (including the very small ones for Apple Watch and the Today Widget).

```
./OwnTracks WatchKit Extension/pl.lproj/Localizable.strings
./OwnTracksToday/pl.lproj/Localizable.strings
./OwnTracksToday/pl.lproj/MainInterface.strings
./OwnTracks/pl.lproj/Localizable.strings
./OwnTracks/pl.lproj/Storyboard.strings
```

I cleaned up the files for a fresh start in the master branch and created a `pl` version of the files.

Please create a PR for the changed files when you are ready

**Comment by nxtpl** [comment]
Thanks! This app is amazing, it is worth to have more popularity :)
PR created. I will observe the repository, but feel free to call me anytime in case any updates are needed.
I will create the translation for Android version too, but later.

**Comment by ckrey** [comment]
Please have a look at the "Modes_Text" in ./OwnTracks/pl.lproj/Localizable.strings

**Comment by nxtpl** [comment]
Done, PR waiting

**Comment by ckrey** [comment]
Heading for the App Store version >= 9.7.8

**Comment by ckrey** [comment]
@nxtpl Hi, we are moving to a new translation workflow. If you would like to help out with some missing Polish texts:

https://poeditor.com/join/project?hash=Kn8XhUO2yv

And for Android if you use it

**Comment by nxtpl** [comment]
@ckrey

Hello, sure! Just registered but it seems that something needs to be authorized so I can begin.

**Comment by ckrey** [comment]
@nxtpl I just approved you for Polish Language. 
I tried to mark technical terms in the comments. Feedback is welcome.

Example:
![Bildschirmfoto 2021-03-29 um 10 34 30](https://user-images.githubusercontent.com/4027289/112809866-c88c9b80-907a-11eb-8a06-ee914909df2e.png)

**Comment by nxtpl** [comment]
Done, I hope it's good enough :) Some words were difficult to translate as they don't have the exact equivalent in PL.
