### ISSUE TITLE
HTTP: app sending GET requests instead of POST

### ISSUE THREAD

**Issue by Pectojin** [owntracks/ios#503]
I've got an Android and an IOS client sending data to my private server, in HTTP mode, but it appears that the IOS client isn't respecting REST. 

It's sending GET requests instead of POST, while the Android client correctly sends POST.

IOS app version: 9.7.2

Logs:
> 192.168.16.1 - user [05/Jan/2018:22:31:51 +0000] "POST /api/publish HTTP/1.1" 200 57 "-" "okhttp/3.8.0"
192.168.16.1 - user [05/Jan/2018:22:32:25 +0000] "POST /api/publish HTTP/1.1" 200 57 "-" "okhttp/3.8.0"
192.168.16.1 - - [05/Jan/2018:22:32:28 +0000] "GET /api/publish HTTP/1.1" 405 178 "-" "OwnTracks/9.7.2 CFNetwork/894 Darwin/17.4.0"
192.168.16.1 - - [05/Jan/2018:22:35:07 +0000] "GET /api/publish HTTP/1.1" 405 178 "-" "OwnTracks/9.7.2 CFNetwork/894 Darwin/17.4.0"

I can't seem to find any settings in the IOS app that might change this behavior.

**Comment by ckrey** [comment]
@Pectojin the iOS app respects REST as long as you use the right URL

If you specify the wrong url and get a redirect from your backend, it does use GET.

```
127.0.0.1 - - [06/Jan/2018 08:48:19] "POST /wrong/url HTTP/1.1" 303 0
127.0.0.1 - - [06/Jan/2018 08:48:19] "GET /owntracks HTTP/1.1" 200 2
```

Unfortunately the redirect is not in your logs.

The setting you are looking for is `URL`

(The background of your observations is Apple's NSURLSession switches the HTTP method to 'GET'  when it receives a redirect. I am not sure if this is the intended behavior, but it is definitely unexpected.)

**Comment by ckrey** [comment]
[Apple Developer Forums 34834](https://forums.developer.apple.com/message/34834)

**Comment by binarybucks** [comment]
Chiming in here because I saw the same issue before on Android. 
The behavior is neither unexpected nor wrong because that’s what RFC2616 defines for HTTP code 303. 307 should not change the request method though.

**Comment by ckrey** [comment]
Thanks @binarybucks.

I just tested on Android and can confirm: Android is doing the same thing:
```
192.168.79.153 - - [06/Jan/2018 10:30:36] "POST /wrong/url HTTP/1.1" 303 0
192.168.79.153 - - [06/Jan/2018 10:30:36] "GET /owntracks HTTP/1.1" 200 2
```

@Pectojin please update your backend URL!

**Comment by ckrey** [comment]
In one of the next versions you'll see the 303 error in such a case:

<img width="424" alt="bildschirmfoto 2018-01-06 um 10 32 20" src="https://user-images.githubusercontent.com/4027289/34638503-f3792060-f2cc-11e7-8b9b-1f86395a42b2.png">

**Comment by Pectojin** [comment]
I guess I should have mentioned. I'm using a 3rd party backend that expects that POST request at /api/publish. 

There is no 303 redirect to explain the change from POST to GET and as you can see from my logs the Android client is correctly sending POST to the 3rd party backend without getting a 303.

Both apps are configured with the exact same URL.

**Comment by ckrey** [comment]
I don't think it is an app issue because the app works quite well with other backends. Would you share some more details about your "3rd party backend" and the URL via DM with me? I'll have a look

**Comment by Pectojin** [comment]
It seems to have been something on my phone. I reinstalled the app and reconfigured it with same url and now it's coming through as POST.

Thank you for your time. And I guess something good came of the issue with 1c81ceb.
