### ISSUE TITLE
OwnTracks 9.8.3 not start on iOS 10

### ISSUE THREAD

**Issue by djgreg13** [owntracks/ios#504]
Hello,

OwnTracks 9.8.3 crashes at launch on iPhone 6 with iOS 10.3.3

EXC_BAD_ACCESS

**Comment by andrewferrier** [comment]
Updating to iOS 11.x seems to have fixed it (for me at least).

**Comment by brg468** [comment]
Seeing the same on iOS 10

**Comment by djgreg13** [comment]
Cannot upgrade to iOS 11, some of professional applications are not compatible now

**Comment by djgreg13** [comment]
```
locationManager.monitoring = [Settings intForKey:@"monitoring_preference"
                                               inMOC:CoreData.sharedInstance.mainMOC];
```

it crash here (infinite loop)

**Comment by djgreg13** [comment]
I do this : 
```
diff --git a/OwnTracks/OwnTracks/LocationManager.m b/OwnTracks/OwnTracks/LocationManager.m
index aa8cdda..290f3d4 100644
--- a/OwnTracks/OwnTracks/LocationManager.m
+++ b/OwnTracks/OwnTracks/LocationManager.m
@@ -115,7 +115,7 @@ - (void)observeValueForKeyPath:(NSString *)keyPath
     if ([keyPath isEqualToString:@"monitoring"]) {
         NSUserDefaults *shared = object;
         NSInteger monitoring = [shared integerForKey:@"monitoring"];
-        self.monitoring = monitoring;
+        _monitoring = monitoring;
     }
 }
```


i cannot test this because CoreData failed (into iOS 11 too), this application is empty at every start

**Comment by ckrey** [comment]
Thank you so much.

I could reproduce the problem with an iPhone6 iOS 10.3.1 simulator.
Strange, no problems on any other devices or simulators I tested.

Your change does not do what is necessary. This here fixes the problem:
```
--- a/OwnTracks/OwnTracks/LocationManager.m
+++ b/OwnTracks/OwnTracks/LocationManager.m
@@ -115,7 +115,9 @@ - (void)observeValueForKeyPath:(NSString *)keyPath
     if ([keyPath isEqualToString:@"monitoring"]) {
         NSUserDefaults *shared = object;
         NSInteger monitoring = [shared integerForKey:@"monitoring"];
-        self.monitoring = monitoring;
+        if (monitoring != self.monitoring) {
+            self.monitoring = monitoring;
+        }
     }
 }
```

**Comment by ckrey** [comment]
I think the next version of OwnTracks for iOS will be more restricted in terms of supporting devices and old iOS versions:

<img width="297" alt="bildschirmfoto 2018-01-06 um 19 03 52" src="https://user-images.githubusercontent.com/4027289/34642556-f02909e6-f314-11e7-8f98-171cc2ec835d.png">
<img width="133" alt="bildschirmfoto 2018-01-06 um 19 03 00" src="https://user-images.githubusercontent.com/4027289/34642559-f2856298-f314-11e7-9402-afd1f3aefd6f.png">

**Comment by ckrey** [comment]
Fix is waiting for App Store approval (9.8.4)

**Comment by djgreg13** [comment]
Thanks you very much for your fix

Envoyé de mon iPhone

**Comment by djgreg13** [comment]
Hello @ckrey did you send the approval by express process for critical bugs ?
Nothing is out now

Thanks you very much

**Comment by ckrey** [comment]
No I didn't. Usually it takes just a few hours ... except weekends
