### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by Gozaradio** [owntracks/ios#505]
Hello.

Just downloaded latest version of app and opened to try but app fails to open and crashes on launch. Have tried rebooting device and closing all other apps to no avail.

Device is iPhone 6S Plus running iOS 10.3.3

**Comment by ckrey** [comment]
same as #504, please upgrade to iOS 11, or wait until new version is approved

**Comment by Gozaradio** [comment]
Sorry, didn't see that. I'm still fairly new to GitHub interface.
