### ISSUE TITLE
iOS 11.2.2 and OwnTracks 9.8.4

### ISSUE THREAD

**Issue by dwettlaufer** [owntracks/ios#506]
Upgraded iOS version and OwnTracks version yesterday on iPhone 7 and the app no longer starts. I've tried both cycling the device and performing a reboot but facing the same problem.

On opening the app the splash screen loads and the map is displayed but then immediately crashes. The app icon shows 25 pending location uploads and I've verified that the backend service is reachable.

**Comment by nxtpl** [comment]
Tried the same on 6s. Works.
Try deleting and reinstalling the app. I'm not sure if backup is needed, so export your configuration somewhere. In the past it solved similar problems in many apps on different Apple devices.

**Comment by dwettlaufer** [comment]
I think this issue may have been related to the backend service I'm using. After changing my API response to a list of empty json objects (per the documentation) and moving from port 9000 to port 8443 the app is now behaving as expected.
