### ISSUE TITLE
owntracks publishes location every 3 minutes despite config file

### ISSUE THREAD

**Issue by johndsheehan** [owntracks/ios#507]
Hi,
I am using the following config file to publish data every 10 minutes, but messages are still generated every 3, (phone is static on the table)

{
  "updateAddressBook" : true,
  "positions" : 500,
  "locatorDisplacement" : 200,
  "ranging" : false,
  "locked" : false,
  "mode" : 5,
  "_type" : "configuration",
  "ignoreStaleLocations" : 0,
  "watsonOrganization" : "xxx",
  "monitoring" : 2,
  "locatorInterval" : 600,
  "extendedData" : true,
  "waypoints" : [

  ],
  "sub" : false,
  "ignoreInaccurateLocations" : 0,
  "watsonDeviceType" : "xxx",
  "tid" : "",
  "watsonDeviceId" : "xxx",
  "watsonAuthToken" : "xxx"
}

iOS 11.2.2
owntracks 9.8.4

**Comment by ckrey** [comment]
The docs say `locatorInterval` specifies the maximum time between positions updates. This means in move mode (montoring = 2) an update will be created every `locatorInterval` (=600) seconds even if iOS does not present the app with a new position update.

In your case, iOS gives the app a new position every 3 minutes. This time is under control of iOS and may vary.


![bildschirmfoto 2018-01-10 um 19 32 28](https://user-images.githubusercontent.com/4027289/34789062-0f526a1c-f63d-11e7-9118-10c4958fcfef.png)

**Comment by johndsheehan** [comment]
Ah, ok. So there is no way to tell owntracks to publish an mqtt update no more than once every 10 minutes?

**Comment by jpmens** [comment]
@johndsheehan what’s your use-case? Why do you want to limit OwnTracks like that?

**Comment by johndsheehan** [comment]
@jpmens 
- I'm using a 3rd party hosted mqtt broker and tier has limits (Probably won't hit them, but if the phone goes crazy and starts updating every second ...)
- My phone has metered data, so at the end of the month every byte counts
- 10minute granularity is good enough for me, I don't need finer

**Comment by jpmens** [comment]
In that case we recommend you set the device to _Significant Changes_ mode which will publish only when iOS detects a significant change in your location. It’s a trade-off (but saves battery as well!) you might be comfortable with.

**Comment by johndsheehan** [comment]
Ok, thanks for the clarification. Closing this as it mainly stems from my misunderstanding of `locatorInterval`. Great program btw.
