### ISSUE TITLE
Remove the "request friend position"

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#509]
We should consider removing the "request friend's position" round-arrow on a user's blob on the map. It never really works with iOS friends because their devices go to sleep, and it will no longer work with OwnTracks for Android v2 b/c it too will react similarly.

**Comment by ckrey** [comment]
Old:
<img width="215" alt="Screenshot 2019-11-30 at 11 02 53" src="https://user-images.githubusercontent.com/4027289/69899058-6a09bd00-1361-11ea-9471-31611c330754.png">
New:
<img width="224" alt="Screenshot 2019-11-30 at 11 05 46" src="https://user-images.githubusercontent.com/4027289/69899060-6c6c1700-1361-11ea-8b20-128b6149033a.png">

**Comment by jpmens** [comment]
Good show.

**Comment by ckrey** [comment]
Will be in release >= 13.2.0
