### ISSUE TITLE
Feature request - Make topic editable for private mode

### ISSUE THREAD

**Issue by Tau-Pi** [owntracks/ios#510]
Hi there,

I don't understand why the topic is fixed in private mode since you can configure almost everything - but the topic. And it's essential to be able to change it when using it with IoT Services like thingsboard, watson IoT, AWS and so on... They demand a very specific topic structure.

So, please: In private mode, make the topic editable!

**Comment by jpmens** [comment]
The topic is configurable and this is described in our Booklet [remoteconfig](http://owntracks.org/booklet/features/remoteconfig/).

**Comment by Tau-Pi** [comment]
Sorry, but that doesn't help at all.

- owntracks/user/device with _type=location for location updates, and with _type=lwt
- owntracks/user/device/cmd with _type=cmd for remote commands
- owntracks/user/device/event with _type=transition for enter/leave events
- owntracks/user/device/step to report step counter
- owntracks/user/device/beacon for beacon ranging
- owntracks/user/device/dump for config dumps

So if these are the topics available, then you can't use owntracks with the "big" IoT frameworks. And that's pretty poor, I'm sorry to say. Why don't you make the topic **_editable_**?? Like a simple text box? Why these restrictions?

**Comment by ckrey** [comment]
It is editable in expert mode. Tap on status screen 3 times.

OwnTracks does support all known IoT services!

The big IoT services to not support all MQTT features OwnTracks uses (e.g. Watson IoT does not let you use retained messages and does not allow you to subscribe to topic of your friends).

The right thing to do would be to ask the big IoT services to support OwnTracks.

**Comment by Tau-Pi** [comment]
Wow, that's exactly what I needed. Wondering why @jpmens didn't know. Of course, when the topic and the clientID are fully editable, all the IoT services can be used (with some restrictions, as you mentioned). That's really great.
