### ISSUE TITLE
iOS 11.2.5 iphone 6 cannot select private

### ISSUE THREAD

**Issue by hudunak** [owntracks/ios#511]
When I select private or HTTP option, the app freezes. I tried to restart my iPhone and try it again, but the issue continues.

**Comment by ckrey** [comment]
We had a problem with some iPhone models on some iOS versions #504.
I think this has been fixed now. @hudunak can you confirm this?

**Comment by hudunak** [comment]
Hi, the issue is fixed. Thank you
