### ISSUE TITLE
Regions not saved

### ISSUE THREAD

**Issue by vandan380** [owntracks/ios#512]
hi,

i'm a newbie in using owntracks.

i don't know if it is a mistake by me or an issue. 

i try to save a region, but after exiting the app and start it again, the region is not longer available.

i've tried it in public and in private mode.

i am using an iphone se, ios 11.2.5 and owntracks 9.8.4/de_DE.

**Comment by ckrey** [comment]
You are right, the changes are not synched until the next location is published (which may take a few minutes depending on your settings).

What you see only happens when you kill (e.g. swipe out) the app. Any reason why you do this?

**Comment by vandan380** [comment]
thanks, for your fast answer. i'm in the "testing phase" of the app. i want to use it as presence detection. i thought i can define multiple regions, then close the app and the app notifies me through mqtt when i enter or leave a region. does this only work if the app is running?

i use the app in "mqtt mode" and "significant changes mode".

**Comment by jpmens** [comment]
What you propose is exactly what will happen, and no, you do not need to have the app in foreground (that would defeat the purpose a little).

Configure your regions (avoid the bug you discovered yb ensuring a location is published by pressing the up-arrow once) and from then onwards, whenever iOS detects you enter or leave a region an MQTT message on the appropriate topic with a payload (as described in our Booklet) will be published.

**Comment by vandan380** [comment]
cool. it works :D thank you very much. 

may i ask you another question? 

after defining a region (for example my actual location) my own tracking id appears under friends. so far so good. if i delete this entry now, the region is deleted too. why? i don't understand the connection between friends and regions.

**Comment by jpmens** [comment]
You're right in not understanding that: there is no correlation (other than that a friend can be in a particular region).

This may also be an issue related to what @ckrey wrote above.

On a related note: there's no need to delete your own entry in Friends -- it'll re-appear each time your device publishes a location status. In other words you will "always be a Friend" :-)

**Comment by vandan380** [comment]
:-) ah ok. then i will continue testing. i love the app. exactly what I was looking for.

thanks to both of you for your fast answers and support.
