### ISSUE TITLE
OSStatus error 9806 connection to MQTT with TLS

### ISSUE THREAD

**Issue by everwake242** [owntracks/ios#513]
From all my IOS devices when attempting to connect to my Mosquitto MQTT using proper certificates and authentication owntracks fails with " OSStatus error -9806", errordomainkey = 3

ticking options to allow untrusted certificates changes nothing.
using the app Mqtttool from the apple store I can successfully connect and push messages.

what does the error mean?

**Comment by ckrey** [comment]
I don’t knowe MQTT tool but AFAIK it doesn’t do TLS

Show us your connection setting (export config)

**Comment by ckrey** [comment]
The error is an SSL error on OS level

**Comment by otdftr** [comment]
You might like to check out my posting and learnings in https://github.com/owntracks/ios/issues/439 -   to cut that long posting short,
- Check your certs for correct 
 key identifiers
- Check them for wrong or duplicate  certificate extensions
- check for correct Subject alternative name, even the cn has to be mentioned there again
All these helped when I had certificate issues.  The majority of applications didn’t complain about these flaws, but the combination of mosquito and  owntracks actually  did.
 Hope that helps.

**Comment by everwake242** [comment]
The issue was not with owntracks, sorry.
for posterity it was incorrect cafile path specification in mosquitto causing mosquitto to fall back to non-TLS on port 8883, that is why mqttool worked.

even with correct configuration according to the mosquitto manuals I could not get ssl to work properly and many others online seem to have the same issues.

I opted to disable TLS and then owntracks works perfectly.

**Comment by jpmens** [comment]
For the record: OwnTracks for iOS works very well with Mosquitto and TLS, both with self-signed certificates and with certificates of, say, Let's Encrypt! 

If "many others" have the same issues they haven't bothered to take the time and effort to set it up correctly.

FWIW: disabling TLS in the case that you are transporting your private data over the Internet is a horrible idea and we definitely do not reccomend you do that.
