### ISSUE TITLE
how to only use transitions?

### ISSUE THREAD

**Issue by rvorsten** [owntracks/ios#514]
Hi. I am happily using owntracks with my OpenHAB domotica to do presence detection. Running 3 iPhones in private mode, publishing to my own Mosquitto MQTT broker. One the OpenHAB side, as per the manual, I have switches per user defined in a "owntacks.items" file for storing an iPhone's presence in a particular location. So far so good.

I was expecting owntracks to 'only' publish transitions in and out of my three geofences: home/work/school. However, next to that, it also still published position updates. Nice, but I do not necessarily want my daughter to always see where I am... And I'm sure she thinks the same way about her whereabouts, although that is less of a concern to me of course... ;)

Is it possible to have the location updates disabled and still (and only) receive the geofence enter/exit transitions?  

Many thanks,
Ronald

**Comment by ckrey** [comment]
Use "Manual Mode" as described here: http://owntracks.org/booklet/features/location/#location-data

**Comment by krambriw** [comment]
Hello, I am primarily looking to use the Manual mode and forward Region enter/leave events to my other application (Node-RED)
Is there a "minimum" radius suitable for this? My idea is to create a Region with our house in the center and I would like to have those events when leaving/entering
While testing, I have used very small regions, just to try but I guess a larger movement is required to trigger events? Are there any settings in expert mode that could influence this so you could detect smaller movements?
Another test I did was to place two regions with overlap (one larger and one smaller with the same location) trying to use waypoint events instead. But also here I suppose larger regions and larger movements are required 

Kind regards, Walter
