### ISSUE TITLE
iOS UI is at times difficult to understand

### ISSUE THREAD

**Issue by kfdm** [owntracks/ios#515]
![img_7238](https://user-images.githubusercontent.com/89725/36005252-1d40a91e-0d7a-11e8-957f-2d92d912949c.PNG)

The UI is a bit difficult to understand at times and having to refer to the [documentation](http://owntracks.org/booklet/features/location/#location-data) for what the different modes mean each time I accidentally click it is a bit frustrating.

I think one thing that still feels weird is the **i** icon for settings. It seems like the most common symbol used is a gear icon so I think that would indicate functionality much more clearly.

In the far right, the copy/no-copy mode is unclear, and before seeing the comment in #514 directing to the documentation, I hadn't realized what it was for.

The play button for changing the different modes is also unclear without clicking on it, and then the descriptions remain unclear without looking in the [documentation](http://owntracks.org/booklet/features/location/#ios) again. Perhaps an [action sheet](https://developer.apple.com/ios/human-interface-guidelines/views/action-sheets/) or [grouped table view](https://developer.apple.com/ios/human-interface-guidelines/views/tables/) would provide better inline help for what the mode means.

The compass and share icon though work *exactly* as expected though so no complaints there :)

**Comment by jpmens** [comment]
We're very glad you found it all in the documentation.

**Comment by jpmens** [comment]
There's almost always room for improvement.

**Comment by kfdm** [comment]
I apologize. Text only mediums lose a lot of nuance, and I was a bit hasty in my reply. The lack of nuance caused me to take your earlier reply more harshly than you probably intended.

I do hope to see the UI improve to be easier to understand :)

**Comment by CloCkWeRX** [comment]
Might be worth raising a more specific/actionable one (ie Suggestion:
change "i" icon to "gear" as per
https://developer.apple.com/design/resources/)

I'm sure pull requests would be very welcomed

**Comment by kfdm** [comment]
I know a little swift but objectivec is beyond me at this time so it might be difficult to do too many pull requests. An icon fix or two though may be doable.

Even if I did a poor job with this ticket, my initial goal was to start a discussion regarding a UI. In many projects, random pull requests without an initial discussion to determine if it is wanted (or needed) can be considered bad form and may waste a lot of people's time.
