### ISSUE TITLE
Feature request: include orientation

### ISSUE THREAD

**Issue by jeroenvanderschoot** [owntracks/ios#519]
Together with GPS data and battery info send orientation from device if available.

**Comment by jpmens** [comment]
Do you mean course over ground? We already have that in iOS as `cog` (see [Booklet](http://owntracks.org/booklet/tech/json/#_typelocation))

**Comment by ckrey** [comment]
@jeroenvanderschoot what do you mean by orientation?

**Comment by jeroenvanderschoot** [comment]
@ckrey Basically the direction of the compass in degrees. (North-East-South-West in degrees)

**Comment by ckrey** [comment]
as @jpmens already pointed out this is already part of the JSON payload `cog`
