### ISSUE TITLE
LWT - to be or not to be

### ISSUE THREAD

**Issue by krambriw** [owntracks/ios#520]
Hello, great app & solution you have developed!

I have iPhone 7, IOS 11.2.6, Owntracks 9.8.4
For testing purposes, changed keepAlive to 10 seconds

Question regarding LWT:
In Move mode I do get a LWT message from the MQTT broker quickly when entering Flight mode
In Significant location change mode, I do get nothing

Is this normal and expected?

Kind regards, Walter

**Comment by ckrey** [comment]
See #75 

When you are in Significant Change Mode, the MQTT connection is terminated gracefully (no LWT) when you background the app.

In Move Mode, the app tries to keep the MQTT connection open.

**Comment by krambriw** [comment]
OK, thank you, understood
