### ISSUE TITLE
Include desc in _type=beacon messages

### ISSUE THREAD

**Issue by cmsimike** [owntracks/ios#521]
Hi,

Is there a particular reason why desc (the name of the ibeacon defined in owntracks) isn't included in the json for _type=beacon? If not, any chance at all to get this included? It would be of great help to me if Owntracks reported the name of the beacon it is seeing while ranging.

**Comment by ckrey** [comment]
@cmsimike will be part of the next release.

**Comment by cmsimike** [comment]
Thank you @ckrey!

**Comment by cmsimike** [comment]
Thank you so much for this!
