### ISSUE TITLE
Advice for setting up Regions (size, leaving/enter)

### ISSUE THREAD

**Issue by krambriw** [owntracks/ios#522]
Hello, I am primarily looking to use the Manual mode and forward Region enter/leave events to my other application (Node-RED)
Is there a "minimum" radius suitable for this? My idea is to create a Region with our house in the center and I would like to have those events when leaving/entering
While testing, I have used very small regions, just to try but I guess a larger movement is required to trigger events? Are there any settings in expert mode that could influence this so you could detect smaller movements?
Another test I did was to place two regions with overlap (one larger and one smaller with the same location) trying to use waypoint events instead. But also here I suppose larger regions and larger movements are required

Kind regards, Walter

**Comment by ckrey** [comment]
"minimum": setting up a minimum smaller than the typical accurracy for locations does not make sense (you may check the "acc" attribute in our `location` messages). 50 or 100 meters work usually well, but it depends on the accuracy reported in and around your house.

"expert": there are no expert mode settings regarding Region detection. Region enter/leave events are controlled by iOS exclusively and are reported by the application.

**Comment by krambriw** [comment]
OK, understood, thanks!
I have an iBeacon device I have ordered, just arrived today, so I will configure with that device instead. It's an USB powered AKMW-iB005N-SMA (iBeacon and Eddystone)
Thanks for your support,
Kind regards, Walter
