### ISSUE TITLE
Understanding 'setWaypoints'; different information in documentation.

### ISSUE THREAD

**Issue by jamieshaw** [owntracks/ios#524]
I'm looking for a way to have a single controlled source of waypoints/regions between Home Assistant and OwnTracks (via Node-RED).

I'm currently monitoring an MQTT topic in Node-RED and have this spit out a YAML configuration file for Home Assistant — this works fine, but I wish to achieve the reverse to that Home Assistant can publish it's zones as OwnTracks regions for other devices to use, but identification is an issue.

In the [JSON documentation](http://owntracks.org/booklet/tech/json/#_typecmd), it states that the identifying key for these is `desc`. Where as the [waypoint](http://owntracks.org/booklet/features/waypoints/#remote-loading-of-waypoints) and [remoteConfig](http://owntracks.org/booklet/features/remoteconfig/#setwaypoints) documentation pages state that the key is `tst`.

The issue is that when zones are published from iOS, they are *all* given the current timestamp so identification by `tst` is impossible.

Is someone able to clear this up?

**Comment by ckrey** [comment]
The documentation is not correct/consistent.

The key for Regions is `desc`! `tst` is not evaluated when Regions are sent via command or loaded from a settings or waypoints file. If an update is received, the old Region identified by `desc` is deleted and re-created.

The `tst` value in Regions when sent by iOS is the timestamp when the Regions was created either via UI, command, or file.
