### ISSUE TITLE
time stamp (tst) in milliseconds?

### ISSUE THREAD

**Issue by andreklug** [owntracks/ios#530]
Hi,

I have connected the iOS app to MQTT - everything works fine.

Would it be possible to send the timestamp (in the tst field) more precise with milliseconds instead only seconds?

thanks

**Comment by jpmens** [comment]
It'd probably be possible, but all our apps and our back-end programs expect seconds, so we're not bound to change that.

But more interesting: why would you need that granularity?

**Comment by andreklug** [comment]
I just started with Owntracks, my thought is that milliseconds would help being more precise for calculating the speed between two points - it might be possible that this isn't useful at all.

**Comment by jpmens** [comment]
The precision reported by the operating system (iOS) doesn't warrant a millisecond time precision anyway.
