### ISSUE TITLE
How to switch language

### ISSUE THREAD

**Issue by ictcorebiz** [owntracks/ios#531]
Hi,

My iPhone automatically starts the application in Polish localisation. Can you tell me how to switch to English?

Thanks!
Sjoerd

**Comment by ckrey** [comment]
The language is taken from the region and language settings of your iPhone.
The Version and language settings are displayed on the Status Info screen.

![img_6458 kopie](https://user-images.githubusercontent.com/4027289/38563654-af152648-3cdd-11e8-97d5-bf5c8bd3133e.png)


Currently there are only English (default), Polish, and German (incomplete) available.

**Comment by ictcorebiz** [comment]
Thanks for the prompt reply, mine is giving pl_NL, I just found out that I have a PL preference before the EN preference in my regional settings :)
After putting English above Polish, the app indeed uses en_NL!

THANKS!
