### ISSUE TITLE
iOS 11.3.1 and OwnTracks 9.8.4 crashes when zooming map or switching to friends list

### ISSUE THREAD

**Issue by mbirth** [owntracks/ios#533]
Wife just tested OwnTracks 9.8.4 on her iPhone 6S and it - configured to HTTP mode (with an https URL) - was unusable. Zooming into the map to her location (in Berlin, Germany) crashed the app. So did switching to the friends list (she didn't allow address book access, though, but that shouldn't be an issue if you don't want to match people). In those few minutes it was installed, it successfully reported one location to the server (php-owntracks-recorder), though.

Sadly she won't let me have her phone for debugging. But I wanted to report this nevertheless, so you have it on the radar.

**Comment by ckrey** [comment]
What kind of backend do you use?

**Comment by ckrey** [comment]
Anyhow, thanks for reporting!

We did analyze and fix a number of bugs based on crash reports received over iTunes from consenting users.
The iPhone 6(S) seems to have a different timing than other iPhones.
