### ISSUE TITLE
Crashing every time I open the app

### ISSUE THREAD

**Issue by OmgImAlexis** [owntracks/ios#534]
For some reason the app crashes randomly and after that the app won't open. The only way I've managed to get past that is to reinstall the whole app.

Is there anyway I can send in debug logs?

**Comment by ckrey** [comment]
Unfortunately random crashes are not easy to diagnose and fix:

Please enable Settings/Privacy/Analytics/Share with App Developers
Your crash report will then be sent to us.

We see some crashes from other users reported. The most frequent are fixed and the fixes will be available with the next version.

**Comment by ckrey** [comment]
@OmgImAlexis the current version 9.9.3 addresses a lot of possible crashes. Would you check again with this new version?
Thanks

**Comment by OmgImAlexis** [comment]
I haven't had any crashes in a while so it seems to have been fixed.
