### ISSUE TITLE
Requesting StepCount via HTTP-Connection seems not to work

### ISSUE THREAD

**Issue by balu-** [owntracks/ios#535]
I'm tring to get the step count from my ios device, 
but i can't make it work.

**What I'm doing**
My understanding of the docu is that stepcount has to be requested, 
and the http api only allows to submit "requests" if the phone initiated a Http-Request.
So I modified my serverside script to respond to owntracks http requtests with the following content:

       [{ "_type":"cmd", "action":"reportSteps"}]

(I also tried without the array, and with `to`and `from` timestamps)

My expectation was that the device would issue a secound http request, with a stepcount-json payload.
Testing it by pressing the "manual submitt position" button in the app did not cause the expected behavior.
(no step data anywhere)

Am I missunderstanding the doku?

**Comment by ckrey** [comment]
Nice idea, but processing of commands via HTTP feedback is not implemented

**Comment by ckrey** [comment]
Pressing the Manual Submit Button does just sent the current position

**Comment by balu-** [comment]
@ckrey okay, so can you clearify what is ment by the return values?

http://owntracks.org/booklet/tech/http/

    If the HTTP endpoint returns a status code 200 it will typically return an empty JSON payload array []. 
    It may, however, return an array of JSON objects to the OwnTracks device, each of which must be a valid _type as described in JSON. 
    Support for the following _type is implemented: ...

**Comment by ckrey** [comment]
It worked at a time, hence the documentation is correct.
Due to stricter checks `cmd` processing is not performed in HTTP mode anymore.

(for curious persons: `cmd` processing only happens when the `topic` received matches the phone's own topic. In HTTP mode not `topic` is received.)

**Comment by balu-** [comment]
Thank you @ckrey 

(just out of curriosity, how often are appstore releases created)

**Comment by jpmens** [comment]
@balu- they are created by @ckrey after appropriate testing and when he determines that it's safe to do so. There's no specific time frame.

**Comment by balu-** [comment]
@jpmens okay! thanks for the quick replays & solution!

**Comment by balu-** [comment]
I'm sorry that i have to ask again, did I understand it correctly that requesting Steps should work now?

(Cause i can't get it working. I
 tried to take a look at the ios app and debug the client side, but i was not able to build it. Podfile metions "mqttc/MinL" and "mqttc/WebsocketL" with '~/mqttc' as Path, that is not there at my machine, and i don't realy know how to get it. I'm a total ios newbe sorry for that)

**Comment by ckrey** [comment]
@balu there are 3 prerequisites to make `reportSteps` work (all described in [booklet](https://www.owtracks.org/booklet))

1) your backend responds with return code 200
2) your backend returns a JSON payload as `[{"action": "reportSteps", "_type": "cmd"}]`
3) processing of "cmd" is allowed in your app (check settings)

<img width="386" alt="bildschirmfoto 2018-06-07 um 10 26 58" src="https://user-images.githubusercontent.com/4027289/41087575-5cb96da4-6a3d-11e8-8874-df1b0eae064b.png">

**Comment by ckrey** [comment]
@balu we cannot support you building your own OwnTracks version with Xcode

**Comment by balu-** [comment]
@ckrey Thanks, the hint to cmd enabling in the settings did the trick.

For future users, i needed a long while to find the "advanced Settings" seen on the Screenshot:
Touch on "Paremeters" btw. "Status" on the "Status Info" Page got me there (the Settings Button below them only showed "Basic Settings")
