### ISSUE TITLE
Drop Public Mode

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#536]
Please drop Public.

**Comment by ckrey** [comment]
Removed Public mode

and Watson Modes
and Hosted Mode (finally)

Screen shown on app start until the settings have been changed manually or via .otrc file

![simulator screen shot - iphone x - 2018-05-27 at 17 05 23](https://user-images.githubusercontent.com/4027289/40588227-83d520ce-61da-11e8-9cc9-6607a87ee76e.png)

**Comment by ckrey** [comment]
![simulator screen shot - iphone x - 2018-05-27 at 18 28 11](https://user-images.githubusercontent.com/4027289/40588302-c3bcbd54-61db-11e8-972d-b18655d64e76.png)

**Comment by prologic** [comment]
Oh! So there is no "Public" mode now meaning I can't trail the app with a public server between two phones?

**Comment by jpmens** [comment]
Kindly elaborate; theres nothing you can now not do with MQTT. And be advised we strongly recommend you do not use public servers for tracking your location.
