### ISSUE TITLE
New version has dropped support for ios < 11

### ISSUE THREAD

**Issue by jeffrizzo** [owntracks/ios#538]
Version 9.9.3, which looks like was released about a week ago, seems to have dropped support for ios versions before 11, which means I can't use it on my iphone 5c.  :(

Was this intentional?  Is there any way I can get access to version 9.8.4?

**Comment by jpmens** [comment]
This was intentional and is noted in the release notes:

```
[FIX] Drop Support for iOS < 11.0, older iOS versions use old version
```

**Comment by ckrey** [comment]
Yes you can, although Apple made it a bit less comfortable since the last major iTunes upgrade:

https://discussions.apple.com/thread/8075526

**Comment by kirichkov** [comment]
May I point out that this release's release notes also have:

    [FIX] Crash in TodayViewController on iOS 9.3.5 iPhone4S #528

At the same time the app itself does not run on iOS 9.3.5, so technically this bug is still present on iPhone 4s because the release is not compatible with iOS 9.

**Comment by jpmens** [comment]
I don't know whether to laugh or to cry

Please read the release notes from bottom to top, whereupon they make sense. 

And please do not add an issue that we should explain how to read the release notes.

**Comment by kirichkov** [comment]
My bad :-) I see 9.8.6 was released too, which also includes this fix. But when reading the release notes in the App Store this didn't make any sense :-)
