### ISSUE TITLE
Client disconnects from broker

### ISSUE THREAD

**Issue by mabnz** [owntracks/ios#540]
IOS OwnTracks app disconnects from mqtt broker at random periods, usually after a day after confirming the connection and connecting successfully. 

Error is:

Stream error code key: -9829
Stream error domain key: 3

Version 9.9.3. 

After going in and confirming the connection details it will connect again, for about a day. Only seems to happen on some (iOS) clients.

**Comment by ckrey** [comment]
duplicate to #525
