### ISSUE TITLE
Owntracks reports Network is down, when it's not on iPhone 8 iOS 11.4

### ISSUE THREAD

**Issue by mg0536** [owntracks/ios#541]
Network is down {
   "_kCFStreamErrorCodeKey" = 50;
   "_kCFStreamErrorDomainKey" = 1;
   }

However, phone network is up, and WiFi is up.

![network-is-down](https://user-images.githubusercontent.com/40570650/41918202-dd113bc6-7929-11e8-9494-a8423d31936c.PNG)

**Comment by ckrey** [comment]
I have 2 questions:

1. Does the connection work sometimes or does the connect never work?

2. MQTT over Secure Websocket connections add at least one more level of complexity on both the server and client side. Why do you use MQTT over Secure Websockets?

**Comment by ckrey** [comment]
@mg0536 were you able to solve the problem?
