### ISSUE TITLE
Share tab IOS

### ISSUE THREAD

**Issue by nutttz** [owntracks/ios#543]
Not sure if this is the place to,ask this, but I’ve set up,OwnTracks with a private MQTT  broker in a Synology docker. Trying to use it with home assistant for iBeacon registration entry and exit into and out of the home zone.

The OwnTracks program has no issues with the iBeacon region, and is showing alerts in and out of the iBeacon zone, but the entry and exit events are not pushing to the HomeAssistant program.

In all the documentation I’ve read, and suggestions online, people are talking about ensuring the ‘share’button is selected in OwnTracks, but I have not been able to find this button anywhere and there is no reference regarding turning it on or off anywhere I’ve seen (either in the IOS app or in the setting up of the MQTt broker).

I’ve set up OwnTracks users and passwords in MQTT for myself, my wife and also home assistant and the programs all seem to be talking to each other - I am able to publish waypoints from OwnTracks and it shows in the HomeAssistant, but the instances entry and exit are not working, and I can only think this is because the events are not being shared.

Is there a something I am missing here, or does sharing now happen automatically for instances on the same broker (if it does, then my wife’s phone is not push8ngbthem either).

Is there a way to turn on ‘sharing’ why there is no button as published on many of the examples on the internet?

Thanks in advance for any suggestions.

**Comment by ckrey** [comment]
The `Share` button was removed in the last release.
All Regions are now shared.
The `transition` events are published to the topic `owntracks/<user>/<device>/event`.You may want to check your broker‘s acl.

**Comment by nutttz** [comment]
Thanks for clarifying that. I thought that may have been the case, but was starting to wonder if I’d missed something in the iOS app.

You may be right regarding the ACL. I hadn’t set up an ACL as no guides really mentioned it. I may have outsmarted myself by setting up a ‘Homeassistant’ user for the MQTT instance instead of using my name. Having said that, the OwnTracks subscription for home assistant is subscribing to ‘owntracks/#’. The interesting thing is that the home assistant app will pick up the waypoints when I publish them, and also the iBeacon but does not appear to be respecting the transitions. It will update my owntracks status when I have it following me (by not using the event only trigger). It may be a problem with the owntracks component in HASS.

As an aside, and for my own education, in the IOS app when you triple click, the area which allows you subsciptions (subTopics?) has ‘owntracks/+/+....etc’ For this to work properly, wouldn’t it also require the ACL in the MQTT broker to be set up correctly, or is it because owntracks is subscribing to the owntracks topic that it works automatically for all owntracks app/user instances?

Anyway, thanks for your reply. I guess I have some more troubleshooting to do.
