### ISSUE TITLE
Which version of mqtt-client-framework ?

### ISSUE THREAD

**Issue by tomtastic** [owntracks/ios#544]
I'm suffering from a bug which was apparently fixed in MQTT-Client-Framework 0.8.7a (released April 2017), is owntracks for iOS using this or a more recent version?

NB: Specifically when using MQTT mode, Websockets and TLS, I get : 
`CFStreamErrorCodeKey=-9807, CFStreamErrorDomainKey=3`

**Comment by ckrey** [comment]
OwnTracks iOS does not use MQTT-Client-Framework anymore!

It uses a fork taken later than 0.8.7a.

The fix in MQTT-Client-Framework was not related to OwnTracks iOS.

-9807 is a generic TLS handshake error

Which broker do you use? Which Websockets Layer?
Are you using self signed certificates?

Pls share your OwnTracks iOS configuration with us

**Comment by tomtastic** [comment]
Oh!, might want to update the project readme.md then... "OwnTracks uses MQTTClient, a native Objective-C client framework. https://github.com/ckrey/MQTT-Client-Framework"

- As a backend I'm using Mosquitto 1.4.12 listening locally with 'protocol websockets'.
- OwnTracks iOS is set to MQTT mode with Websockets, TLS and Authentication set to enabled. I have no custom security policy options set.
- I am attempting to use Traefik v1.6.0 (traefik.io) to act as a TLS endpoint and reverse-proxy the websocket traffic to mosquitto.
  - Traefik is configured to get a letsencrypt CA-signed TLS cert for my domain (domain as configured in OwnTracks iOS).
  - Traefik is relying on TLS SNI compatible clients and services (which is why I was looking at the client framework in use by OwnTracks iOS).

**Comment by ckrey** [comment]
I updated README.md

We have no experiences with `Traefik`

**Comment by tomtastic** [comment]
Thanks Christoph, can you confirm if the MQTT framework in use supports and uses TLS SNI (https://en.wikipedia.org/wiki/Server_Name_Indication) ?

**Comment by ckrey** [comment]
Websockets are implemented using 
https://github.com/facebook/SocketRocket/blob/master/README.md

They don‘t mention SNI explicitly

**Comment by tomtastic** [comment]
Thanks again, I have looked through the SocketRocket code, and read a little more about CFStream.
Happy to close this ticket, and thanks again for OwnTracks iOS, it's very cool!
