### ISSUE TITLE
Owntracks iOS version not same as App Store

### ISSUE THREAD

**Issue by saykalik** [owntracks/ios#545]
I am using Owntracks on iPad Air and according to the App Store I have the latest version (9.9.3) however, when I am in the app and I go to i/info it says 8.9.4.  The only thing the App Store allows me to do is Open the app and not update it (so it thinks I have the latest).

I think I have the older version because some of the newer features are not in the app.  What might I be missing?

Thanks.

**Comment by ckrey** [comment]
The newest version 9.9.3 runs only on iOS 11.
You may have the latest version supported for your iOS version

**Comment by saykalik** [comment]
My mistake.  Thank you.
