### ISSUE TITLE
Empty tid in waypoint event

### ISSUE THREAD

**Issue by kvanover** [owntracks/ios#547]
tid is missing in the waypoint event

{
  "rad": 10,
  "tst": 1532984679,
  "_type": "waypoint",
  "lon": 4.5352988597047998,
  "topic": "owntracks\/user\/3663815E-DFD3-42FE-B536-3C1D74696B9D\/waypoint",
  "lat": 50.818207478197998,
  "desc": "Here-1532984679"
}

**Comment by ckrey** [comment]
The `tid` is not part of the `waypoint` payload type.

The documentation is a little bit confusing:
![bildschirmfoto 2018-07-31 um 14 36 58](https://user-images.githubusercontent.com/4027289/43459988-8fcbb956-94cf-11e8-8048-2df74e3ff837.png)
and is updated now.
