### ISSUE TITLE
accept Invalid Cert

### ISSUE THREAD

**Issue by swaaws** [owntracks/ios#548]
im using an self signd cert!

the Log ask me "do you want accept the invalid cert" but i cant interact with them.

the switch acceptInvalidCrt is enabled

**Comment by ckrey** [comment]
I am not sure which log / setting you are referring to. Pls attache screenshot

**Comment by swaaws** [comment]
At the start screen press top left the "i".
see the Connection row And than the log "Status"

error Das Zertifikat für diesen Server ist ungültig. Eventuell wird eine Verbindung mit einem Server 
...
NSLocalizedRecoverySuggestion = "Soll die Verbindung zum Server trotzdem hergestellt werden?";
    NSURLErrorFailingURLPeerTrustErrorKey = "<SecTrustRef: 0x1cc1084c0>";
...

**Comment by ckrey** [comment]
Could you show me your TLS setting screen with the enabled "acceptInvalidCrt"?

**Comment by swaaws** [comment]
https://i.imgur.com/m8piAqx.jpg and https://i.imgur.com/cfMV2o7.jpg

**Comment by ckrey** [comment]
sorry, what you show is only part of the detailed settings screen. Either show it complete or better give me the normal setting screens. "acceptInvalidCrt" is only evaluated together with "policy mode":

![simulator screen shot - iphone x - 2018-08-03 at 11 44 51](https://user-images.githubusercontent.com/4027289/43636779-59d4647e-9713-11e8-8bc1-937348bfb38c.png)
![simulator screen shot - iphone x - 2018-08-03 at 11 44 39](https://user-images.githubusercontent.com/4027289/43636783-5b2eada2-9713-11e8-9efe-b1a9db9454ec.png)

**Comment by swaaws** [comment]
https://i.imgur.com/uu75jNc.jpg
https://i.imgur.com/8zZpfsJ.jpg

**Comment by ckrey** [comment]
It is not a dev version, but I was guessing you are using MQTT connection, not HTTP.

You can make your iPhone trust your self signed certificate by navigating to your URL endpoint with Safari and follow the instructions there.

**Comment by ckrey** [comment]
closing due to no more activity
