### ISSUE TITLE
Owntracks will not connect after changing topic path in IOS 11.4.1

### ISSUE THREAD

**Issue by SMLMG** [owntracks/ios#549]
I am using cloudmqtt with owntracks. After configuring the settings I noticed that owntracks did not allow me to specify a topic but rather assigned a topic of owntracks/iphone/iphone. I changed the topic in cloudmqtt to reflect the topic in owntracks and a connection was established. I sent a few test messages just to be sure and everything was working. However, I wanted to have a topic of owntracks/# as I intended to add my wife's and daughter's iPhones to a Home Automation system for presence detection. 

My understanding was to export the settings and change "pubTopicBase" to "owntracks/#". I proceeded to make the change and import the new configuration. The topic was successfully changed to "owntracks/#" but owntracks would no longer connect. I made sure that cloudmqtt reflected the new topic as well. Could someone assist me in pointing out what I did wrong? Thank you in advance for any attention and assistance.

**Comment by ckrey** [comment]
Correct, OwnTracks defaults to a the topic `owntracks/<user>/<device>` for PUBLISHing messages. You may explicitly change the topic if you know what you are doing.
`owntracks/#` is an illegal MQTT `topic`, but rather a `wildcard topic filter`, which you cannot use a `pubTopicBase`, but would use as a SUBSCRIBE topic filter.
OwnTracks defaults `subTopic`(which is a list of whitespace separated topic filters) as `owntracks/+/+ owntracks/+/+/event owntracks/+/+/info owntracks/<user>/<device>/cmd`.
This default allows you to pickup your family member's location and region events. No need to change the defaults

**Comment by SMLMG** [comment]
I read everything I could on these topics. In my particular case the CloudMQTT service is acting as a “broker”, the OwnTracks IOS application is the “Publisher”, and Home Assistant instance is the “Subscriber”. That is why Home Assistant referred to the topic as owntracks/#. Is there a way to send you a private message that is off-topic? It’s business related. Regardless, thank you for your help. RTFM should have come first.

**Comment by ckrey** [comment]
oh yes email to c@ckrey.de
