### ISSUE TITLE
Friends works on one out of the two phones

### ISSUE THREAD

**Issue by fmuntean** [owntracks/ios#551]
I have two phones and one can see both but the other can’t.
I have changed and updated the contacts with the new parameter and nothing.
Even created a new contact and still not showing in the friends tab.

Please reconsider implementation for this feature to be able to add friends manually instead of trying to discover them from the contacts.

**Comment by ckrey** [comment]
I think you have the wrong understanding of how friends work

If you see a friend  (which is only determined by your setup of the apps and the backend) you may link the friend to an entry in your address book to show the name and photo store there.

You cannot add friends on the friends tab!

Which backend do you use, how is it configured and how are your apps configured?

**Comment by jpmens** [comment]
@fmuntean for the future, and in most if not all Open Source projects, it is polite to instead of introducing yourself with _Please reconsider implementation for this feature_ to indicate what you expect the application to do, what you did or did not do to make it happen, and the result that you attained.

For example, you do not give me the impression that you've studied our documentation; if you have, you make no indication thereof. If you believe the documentation is insufficient, then you can indicate so and we will attempt to improve it, time permitting. Of course what's even better is that you provide better documentation.

Thank you.

**Comment by fmuntean** [comment]
What am I saying is that I already did that and is not showing up in the
friend tab under app.

To be mote precise it works on one phone but not the other.

So one phone can see the other as a friend but not the opposite. Both
phones have the custom property set correctly inside the address book.

The difference that I see is that the one that works has a small address
book where the address book on the one that is not working has over a
thousand people in the address book.

So pleas tell me how do I get it to show inside the friends tab? I have
been trying for a long time to make it work with no luck.

Florin

**Comment by ckrey** [comment]
This is how it works: https://owntracks.org/booklet/features/friends/

The use of "updateaddressbook" and the "custom property" in the address book have been removed in the last release for privacy reasons:

<img width="501" alt="bildschirmfoto 2018-09-20 um 09 03 10" src="https://user-images.githubusercontent.com/4027289/45801438-325eaa00-bcb4-11e8-8864-c8e90e6bdf71.png">

**Comment by fmuntean** [comment]
I am sorry but in the documentation is not clear how should I change the
json config file to make it work.

Is not clear how the topics are build up from that config Json

Would be helpful to provide a sample json that help achieve this in the
documentation.

I do not not have topic name root and device name in the json file.

Maybe few samples could help.


For example having a root topic and then a device topic what do I put in
json to make it work?

Example topic will be: root/deviceid

So what properties in json will control the root part and which one the
deviceid?

So the two devices will each have the following topics:

Root/device1/
Root/device2/

Thanks
Florin

**Comment by fmuntean** [comment]
I endup fixing it by reinstalling the app and reapplying the config json
from a working one after changing the ids.
Applying the json before app reinstall did not work.

Florin
