### ISSUE TITLE
"Move mode" versus "Significant changes move mode"

### ISSUE THREAD

**Issue by krambriw** [owntracks/ios#552]
Hi,
Just some questions and thought...

I see that the app seems to buffer messages that hopefully will be transmitted "at some time". And some times, "some time" takes a while it seems. Is there any difference for the various modes in respect to their possibility/priority to transfer messages via the network (WiFi or 4G)? I mean is there any priority difference for them in iOS? Does "Move mode" have higher priority/access rights to transmit?

If so, would it not be possible for the app to change the mode to "Move mode" when a transition happens, send the info to the MQTT broker and then change back to the previous mode?

Or is this not possible at all?

**Comment by theslash** [comment]
it would be great if you could connect to ios shortcuts so we could change the mode e.g. when connecting to the car bluetooth or with siri

**Comment by ckrey** [comment]
Siri shortcuts are available in versions >= 13.3.6
