### ISSUE TITLE
owntrack doesnt subcribe to my broker

### ISSUE THREAD

**Issue by Lanzones** [owntracks/ios#553]
Hi,

I have been trying to integrate this lora gps device to owntrack for quite sometime now and it doesnt seem to work. I hope anyone could help..
I have this GPS lora device publish to my clound mqtt broker and configured owntracks to plot the location of my lora device. Owntracks can publish to my broker but doesnt seem able to subcriber to my broker and update its marker location and time publish by my lora gps device. I have disabled location services on my phone btw.. Please help, there must be something I am not following in the owntrack booklet setting up guide..

topic:
owntracks/test2/gps_coomera 
Payload:
{"_type":"location","id":"gps_coomera","acc":65,"conn":"w","vac":10,"tid":"99","batt":100,"tst":1538313790,"alt":22.2,"lat":-27.8xxxx,"lon":153.yyyy}

**Comment by ckrey** [comment]
@Lanzones would you share your config of the iOS device with us (credentials removed)?

The payload looks fine

**Comment by ckrey** [comment]
@Lanzones and a screeshot of the status screen

**Comment by Lanzones** [comment]
Hi Chris,

thanks for the reply..
this is my cloudmqtt acl I have given permission on any pattern for pub and sub to make it work
![image](https://user-images.githubusercontent.com/43723964/46312418-5c935e80-c608-11e8-9613-9b0c4764cdde.png)

Below is the publish of my lora device and the owntrack app the black mark is my lora because I have force to send a lat and long with pattern.. the blue mark is phone because it is where my phone app is reporting..

![image](https://user-images.githubusercontent.com/43723964/46312150-9152e600-c607-11e8-8c15-4e65518fd558.png)

below are my status and credentials in my phone app..
![image](https://user-images.githubusercontent.com/43723964/46312221-ca8b5600-c607-11e8-8736-bf6e0432add3.png)
![image](https://user-images.githubusercontent.com/43723964/46312374-3b327280-c608-11e8-9d1c-3793bcf36952.png)

Hoping that we could resolve this as I have played around using hometrack with my phones and this is what I really wanted on this project that I am developing for lora devices.. I have look into this hoping to make it work for quite sometime now...

**Comment by ckrey** [comment]
Your problem is that you have the iOS app configured exactly like the GPS device.
`owntracks/test2/gps_coomera` is the topic the iOS app publishes to and the GPS device

The iOS app does not process its "own" messages.

Change the DeviceID of your iOS app to e.g. ("iPhone") and you'll see the position of the GPS device.
If you have more than one GPS device make sure they all publish to different topics.

**Comment by Lanzones** [comment]
Thanks mate.. it actually works..

**Comment by ckrey** [comment]
It is a pleasure to have you in the OwnTracks community. We'd appreciate if you share your experiences the the lora device, how you set it up, what you do with it with us.

**Comment by Lanzones** [comment]
these lora devices are very exciting.. no 3g, low power, long range, no monthly sim plan, you re are the network kind of thing and flexible in term of redirecting the data to the cloud. At this stage Im about to release these GPS tracker prototype that has a battery holdup time of roughly 1.8years updating with an update period of 2hours in a 80x50mm key fob size.. the other device (100x100x33mm) which is basically similar but will have a higher hold up time of 4~5years with 30min update period.. Target will be early next year.
I will be advertising these devices with owntracks that I am making. for sure their will be request of smal customization kind of thing in using the app. I have seen as well integration with home assistant where you could downlink to these devices for command. I havent tried, hoping this part will be vastly supported by owntrack and HA as the devices will be able to support control and monitoring of transducers depending of the application requirement.

**Comment by jpmens** [comment]
@Lanzones It would be good if you could share photos of the devices and further specs if you have them. I imagine that would be interesting to other OwnTracks users as well.

**Comment by Lanzones** [comment]
will keep owntrack community posted as I am preparing the specs/application and lots of photos and presentation for these devices.. Will post it here in this thread first hand.. :)
