### ISSUE TITLE
ibeacon as trigger for location update

### ISSUE THREAD

**Issue by logos37** [owntracks/ios#554]
Dear all

My question is very similar to the one discussed in: https://github.com/owntracks/talk/issues/13. unfortunately I still don‘t get it.

As in above reported issue I have only one iBeacon, which should more precisely and timely detect when I’m entering my home region. I‘m only interested in detection of this home region entering/leaving event (I.e. no tracking required) and i’m looking for the most battery savvy approach to that. The events are transmitted to my Mosquitto server in a Openhab environment. 
I understand that OwnTracks should Track a GPS region approach (circular region) combined with iBeacon region.

Currently my settings in owntracks are: quit mode and a circular region with diameter > 0 and with a uuid for my iBeacon in same region setting tab.

Did I get it right or have the parameters to be set differently?

Any help would be highly appreciated.

Thank you and best regards
Rolf

**Comment by ckrey** [comment]
If you want to monitor a region via an iBeacon, you have to setup a Region with Radius of 0 meters.

If you specify a positive Radius, the app will monitor the Regions based on location (lat/lon) information. If this is done based on GPS, Wifi or Cell Tower finger prints is up to iOS. 

So if you want to combine iBeacon sensing and location based region monitoring, you have to setup to Regions

**Comment by logos37** [comment]
Dear crkey

Thanks a lot for your answer! I still don’t get it fully (sorry for that). Based on the above mentioned talk#13 and especially issue #407 https://github.com/owntracks/ios/issues/407 I had the impression that circular region and iBeacon monitoring could be combined. But apparently this seems not to be case. So, I did misunderstand something?

Thanks a lot for clarifying and time spent on my questions.
