### ISSUE TITLE
Specify a different topic base

### ISSUE THREAD

**Issue by jazztunes** [owntracks/ios#555]
My MQTT provider (io.adafruit.com) needs for me to use a different topic. How can I set pubTopicBase in the iPhone app? I tried downloading and editing the config.otcf file. I'm not sure how to load that config back into the app. I tried opening it from mail and opening from drop box. Both simply display the contents. Any help would be appreciated!

--DH

**Comment by jazztunes** [comment]
Nevermind! I figured it out.  In mail, I was able to long press on the attachment and then choose "copy to owntracks". Hope this helps someone else.

**Comment by ckrey** [comment]
![8983ad32-ce2d-4f5d-a1e4-3eb9614438a5](https://user-images.githubusercontent.com/4027289/46902057-c7714f00-cebe-11e8-804a-6850ab752f2b.jpeg)
Yes, or you use the action button as shown above
