### ISSUE TITLE
Attempt to delete self crashes app

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#556]
OwnTracks version 9.9.3, iOS 12, iPhone 5s

In _Friends_ tab, I swipe on my own entry and tap the _Delete_ button which then appears. This crashes the app.

I realize it's a bit foolish to delete _self_, but I think the app should not crash on the attempt.

**Comment by ckrey** [comment]
mmh, version 9.9.3 nor the current development build crash on iOS 12 on an iPhone SE.

I hope you have opted-in to share your crash logs with the developer ;-)

**Comment by jpmens** [comment]
Done.

**Comment by jpmens** [comment]
I exported my config and wiped (to create a demo for a presentation). After re-importing my original config from `.otrc` including waypoints etc. I cannot reproduce the issue.

I am closing this as "it's probably an artifact from upgrading all the way from version 0.0 without a single wipe". :-)
