### ISSUE TITLE
inregion events for lora device

### ISSUE THREAD

**Issue by Lanzones** [owntracks/ios#557]
would it be possible to generate an inregion/outregion event regardless when the location access was turned off?. I have these lora devices that I am monitoring thru owntracks. I have been simulating devices in and out of the region and I was expecting at least that an event will be automatically published into my broker. These events was never published.

If my location access is turned ON on my phone running the owntrack apps, I can confirm that events are published and my region turns red whenever my iphone is in the region. 

I can do some adjustment on my app which runs collecting and publishing data for these lora devices that whenever they are in the region or out and fire a notification and other stuff, but it would be a lot easier for me to monitor these events published by the owntrack app whenever any of the devices enter or leave a predefined region. 
Any response will be greatly appreciated.. thanks

**Comment by ckrey** [comment]
Hi @Lanzones,

OwnTracks just monitors the location of the phone and generates the corresponding region events.
It does not monitor the location of other devices which are received via MQTT.

If you want to do region checking for other devices, I suggest to run a component at your backend, SUBSCRIBE to the devices' locations and re-publish enter/leave events.

Is your lora app available on GitHub? Which lora devices do you use? Sounds interesting!

**Comment by ckrey** [comment]
@lanzones any updates? Otherwise I will close the issue

**Comment by Lanzones** [comment]
Hey chris sorry i lost track of this.. everything is ok.. thanks
