### ISSUE TITLE
Allow authentication without password

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#559]

**Comment by ckrey** [comment]
https://github.com/owntracks/android/issues/637

**Comment by jpmens** [comment]
we already have auth in config which says do or don't auth. A new `.otrc` flag will be implemented called `pass` and this defaults to `true`:

- if `pass` is `true`, then password is used, even if it an empty string `""` (i.e. `strlen(password) == 0`
- if `pass` is `false`, then no password is used (in Mosquitto lib I would then use `NULL` as the password)

**Comment by jpmens** [comment]
`usePassword` ?

**Comment by binarybucks** [comment]
Ack

**Comment by jpmens** [comment]
@ckrey, @binarybucks I've updated the "documentation" above. :-)

**Comment by binarybucks** [comment]
Implemented on Android with https://github.com/owntracks/android/commit/133745885a12a15c195063270af6d5c91cea0d52

**Comment by ckrey** [comment]
Implemented and tested against beebotte.com account in iOS

**Comment by ckrey** [comment]
version >= 12.0.2
