### ISSUE TITLE
SetWaypoints remotely - Not working iOS

### ISSUE THREAD

**Issue by rdavey228** [owntracks/ios#561]
Hello

I have remote commands enabled and I know remote commands are working by issuing 

`mosquitto_pub -h ***** -p ***** -u ** -P ***** -t "owntracks/phones/iPad/cmd" -m '{"_type":"cmd","action":"reportLocation"}'`

This updates my location when I run this command so I know remote commands are working.

However I am trying to setup waypoints on my devices remotely.

Using the command from the documentation does nothing

`mosquitto_pub -h ***** -p ***** -u ** -P ***** -t "owntracks/phones/iPad/cmd" -m  '{"_type": "cmd","action": "setWaypoints","waypoints": {"waypoints": [{"desc": “WAYPOINT1”,"rad": 50,"lon": -0.163409,"lat": 51.499479,"tst": 1437552714,"_type": "waypoint"}],"_type": "waypoints"}}'`

Can anyone help me with this?

**Comment by jpmens** [comment]
If I take your "json" payload and put it in a file, I get this:

```
$ jq . < /tmp/x
parse error: Invalid numeric literal at line 1, column 94
```

Does that help?  (Hint: are you sure those are proper double-quotes?

**Comment by rdavey228** [comment]
Its the same commands I copied from the documentation....so if they are wrong then surely the documentation needs updating?

I pasted this into JSONLint and says its valid. I have used it in my MQTT command but still nothing gets imported into waypoints on my device 

```
{
	"_type": "cmd",
	"action": "setWaypoints",
	"waypoints": {
		"waypoints": [{
			"desc": "WAYPOINT1",
			"rad": 50,
			"lon": -0.163409,
			"lat": 51.499479,
			"tst": 1437552714,
			"_type": "waypoint"
		}],
		"_type": "waypoints"
	}
}
```

**Comment by rdavey228** [comment]
Can anyone help?

**Comment by rdavey228** [comment]
I dont think its a Qos Issue. I have the device sat right in front of me with the App open on owntracks.

**Comment by jpmens** [comment]
```bash
$ cat /tmp/w.json
{
	"_type": "cmd",
	"action": "setWaypoints",
	"waypoints": {
		"waypoints": [{
			"desc": "WAYPOINT1",
			"rad": 50,
			"lon": -0.163409,
			"lat": 51.499479,
			"tst": 1437552714,
			"_type": "waypoint"
		}],
		"_type": "waypoints"
	}
}

$ mosquitto_pub ... -q 1 -t owntracks/jpm/5s/cmd -m "$(cat /tmp/w.json)"
```

Works for me: I then see the following waypoint in my list of regions.

![img_6941](https://user-images.githubusercontent.com/60706/50343587-c6484800-0527-11e9-8f89-9a49fe9c8702.jpg)

**Comment by jpmens** [comment]
If you have access to your MQTT broker logs, it'll help looking at those (if Mosquitto: `tail -f mosquitto.log`) the moment you've opened your iOS app and while publishing your payload; you may be able to see whether the payload is actually being delivered to the device.

**Comment by rdavey228** [comment]
Ok, I copied and pasted your code into w.json and ran the same command you did and it worked.

I then copied the whole thing into a single command (rather than run from a .json file) which is what I was trying to do before and that worked too. I dont get what I was doing wrong before that stopped it working....
