### ISSUE TITLE
differentiate enter/leave iOS

### ISSUE THREAD

**Issue by Liver64** [owntracks/ios#565]
Hey there, great work so far. I have a question if there are any activities in scope to differentiate enter events by the type of entering like Geofancy does? with iOS you can diff. types like walking/running/driving by car. Specially driving by car would be very nice to control your Smart Home. The use case is to open Garage/Door vs. walking
thanks in advance
Oliver

**Comment by ckrey** [comment]
iOS does not provide information on motion types immediately, but only retrospectively (https://developer.apple.com/documentation/coremotion/cmmotionactivitymanager)

I am not sure how and what `Geofancy` does, but I would suggest you use the `vel` (velocity/speed) provided with each `location` to determine the type of movement

**Comment by Liver64** [comment]
thx for your feedback, you are right. At Point „Topics“ is described the diff. movement types determined by iOS. Of course the vel Info could be used, but after a few weeks testing it does not work properly. 
Question is if this feature could be implemented?
