### ISSUE TITLE
Configuration of Username/Password for HTTP Mode

### ISSUE THREAD

**Issue by knxuf** [owntracks/ios#566]
Hi,

could you please allow the configuration of username and password not only for MQTT mode but also for HTTP mode

https://github.com/owntracks/ios/blob/27881dbf7fe21a193bb414db16a344c359903cb1/OwnTracks/OwnTracks/Settings.m#L123

Thank you for the nice app

**Comment by skarotech** [comment]
Hi, just wondering if this is in the latest version (12.02) , as its still not updating the username and password for me via the config file.

**Comment by ckrey** [comment]
No, the problem was fixed after 12.0.2 was piblished

**Comment by skarotech** [comment]
Hi, thanks for letting me know, any idea when this is going to be released/updated in the iOS app store version ?

**Comment by ckrey** [comment]
Will be available in version 12.0.3
