### ISSUE TITLE
Feature request: Include RSSI in event payload when "t" : "b". 

### ISSUE THREAD

**Issue by oleggold** [owntracks/ios#567]

**Comment by oleggold** [comment]
RSSI values will provide us with an ability to further refine the conditions for triggering actions in Home Assistant automatons.

**Comment by ckrey** [comment]
The RSSI value is not available to the application when the beacon region is detected.

RSSI values are sent when you set the `ranging` parameter. Did you try it out?
see https://owntracks.org/booklet/tech/json/#_typebeacon

**Comment by oleggold** [comment]
Thank you very much for your quick response.

I did try beacon ranging and it works as expected. The problem as it is stated in docs is a phone battery drain.

I just started to work with iBeacons and was trying to find a way to get rid of false positives. I was thinking that I can evaluate a RSSI value and decide if it is too low for hass automation to trigger, but now I see that it would not work anyway.

At what point OwnTracks decides to send a transition event “enter” for beacon only region (radius = 0)?

Maybe that “point” (RSSI/range/power) can be externalized in a OwnTracks config file?

Thank you again,
Oleg

________________________________

**Comment by ckrey** [comment]
OwnTracks does not decide on when to report beacons regions. The information is not available to the app, but fully managemed by iOS.

See https://developer.apple.com/ibeacon/
