### ISSUE TITLE
Is there a way to remove waypoints/regions using setWaypoints?

### ISSUE THREAD

**Issue by BowenMarmot** [owntracks/ios#569]
I am using the remote commands to configure my families devices as well as adjust waypoints/regions.  This is primarily for Home Automation.  The creating and updating of waypoints is working just fine, along with changing configuration.  However I have been unable to figure out how to remove a waypoint that is no longer needed using the remote command.  I know that I can do it manually from the GUI but I am looking to do it centrally.  I have read the booklet and done much experimenting with different variations of the json, all with no luck.  Is this doable? If so, can anyone point me to how?  If not, can this be added?  It would be just fine with having to clear all regions and add the ones I wanted back in.

**Comment by ckrey** [comment]
It is already there:

If you send a waypoint with an invalid lat/long, it will be deleted on the device

https://owntracks.org/booklet/tech/json/#_typecmd

**Comment by BowenMarmot** [comment]
Thanks much for that!  This does work but there seems to be a bug. I will open a new issue for that.
