### ISSUE TITLE
setWaypoints crashes owntracks when removing waypoints

### ISSUE THREAD

**Issue by BowenMarmot** [owntracks/ios#570]
When using the remote cmd of setWaypoints and attempting to remove a waypoint by setting either the lat or long to an invalid value (e.g. "lat:":949.2) owntracks will crash when the waypoint is not the first or last in the waypoints array.  I have been doing a bunch of testing and have iOS analytics set to share with developers so hopefully you get the reports.

I tried to simplify the test cases to three waypoints, however, when I had 5 waypoints there were additional oddities where even creating a new waypoint in one of the middle positions caused a crash.  I haven't chased this down and found a replicable test but, if needed, I can try. 

This is the JSON used to replicate the issue. 
`# Create three waypoints, success
{"_type":"cmd","action":"setWaypoints","waypoints": {"_type":"waypoints","waypoints":[{"_type":"waypoint","tst":1550849281,"lat":49.1,"lon":-123.0,"rad":100,"desc":"Number1"},{"_type":"waypoint","tst":1551019778,"lat":49.2,"lon":-123.4,"rad":500,"desc":"Number2"},{"_type
":"waypoint","tst":1551019778,"lat":49.3,"lon":-123.3,"rad":7500,"desc":"Number3"}]} }

# Remove the first one: success
{"_type":"cmd","action":"setWaypoints","waypoints": {"_type":"waypoints","waypoints":[{"_type":"waypoint","tst":1550849281,"lat":949.1,"lon":-123.0,"rad":100,"desc":"Number1"},{"_type":"waypoint","tst":1551019778,"lat":49.2,"lon":-123.4,"rad":500,"desc":"Number2"},{"_type":"waypoint","tst":1551019778,"lat":49.3,"lon":-123.3,"rad":7500,"desc":"Number3"}]} }

# Recreate three waypoints, success
{"_type":"cmd","action":"setWaypoints","waypoints": {"_type":"waypoints","waypoints":[{"_type":"waypoint","tst":1550849281,"lat":49.1,"lon":-123.0,"rad":100,"desc":"Number1"},{"_type":"waypoint","tst":1551019778,"lat":49.2,"lon":-123.4,"rad":500,"desc":"Number2"},{"_type":"waypoint","tst":1551019778,"lat":49.3,"lon":-123.3,"rad":7500,"desc":"Number3"}]} }

# Remove the second one: owntracks crashes
{"_type":"cmd","action":"setWaypoints","waypoints": {"_type":"waypoints","waypoints":[{"_type":"waypoint","tst":1550849281,"lat":49.1,"lon":-123.0,"rad":100,"desc":"Number1"},{"_type":"waypoint","tst":1551019778,"lat":949.2,"lon":-123.4,"rad":500,"desc":"Number2"},{"_type":"waypoint","tst":1551019778,"lat":49.3,"lon":-123.3,"rad":7500,"desc":"Number3"}]} }

# Remove the third one: success
{"_type":"cmd","action":"setWaypoints","waypoints": {"_type":"waypoints","waypoints":[{"_type":"waypoint","tst":1550849281,"lat":49.1,"lon":-123.0,"rad":100,"desc":"Number1"},{"_type":"waypoint","tst":1551019778,"lat":49.2,"lon":-123.4,"rad":500,"desc":"Number2"},{"_type":"waypoint","tst":1551019778,"lat":949.3,"lon":-123.3,"rad":7500,"desc":"Number3"}]} } 

# Recreate three waypoints, success
{"_type":"cmd","action":"setWaypoints","waypoints": {"_type":"waypoints","waypoints":[{"_type":"waypoint","tst":1550849281,"lat":49.1,"lon":-123.0,"rad":100,"desc":"Number1"},{"_type":"waypoint","tst":1551019778,"lat":49.2,"lon":-123.4,"rad":500,"desc":"Number2"},{"_type":"waypoint","tst":1551019778,"lat":49.3,"lon":-123.3,"rad":7500,"desc":"Number3"}]} }

# Swap the first and second waypoints in the array and attempt to remove "Number 2" now in position 1: success
{"_type":"cmd","action":"setWaypoints","waypoints": {"_type":"waypoints","waypoints":[{"_type":"waypoint","tst":1551019778,"lat":949.2,"lon":-123.4,"rad":500,"desc":"Number2"},{"_type":"waypoint","tst":1550849281,"lat":49.1,"lon":-123.0,"rad":100,"desc":"Number1"},{"_type":"waypoint","tst":1551019778,"lat":49.3,"lon":-123.3,"rad":7500,"desc":"Number3"}]} }
`

**Comment by ckrey** [comment]
The good news is: The crash only happens when watching the Regions tab on the iPhone.
When the phone shows the Map, there is no problem.

Anyway: Thanks for tracking down and documenting the problem. The fix will be part of the next Release

**Comment by BowenMarmot** [comment]
That is great news! Thank you! 

In case it matters, there appears to be a subtle variation on the crash that does not require watching the regions tab, only visiting it at some point. No idea if this is the same bug you have fixed for the next version or a different one.

Adding and removes work perfectly in all cases until you visit the "Regions" tab.  As soon as you visit the "Regions" tab the removal of the middle entry in a waypoints array will crash the App. Even if you have switched back to the Friends or Map tabs prior to the removal.

**Comment by ckrey** [comment]
Will be available in version 12.0.3
