### ISSUE TITLE
Owntracks Support Question: iBeacons

### ISSUE THREAD

**Issue by milad-soufastai** [owntracks/ios#571]
Firstly, Thank you for the owntracks app and the support you guys provide over Github. I hate creating an issue since my "issue" is my own in terms of configuration but it seems to be the preferred method around here.

So about my issue:

- Monitoring entry/exit of my house for my home automation

- Beacons: Front Door, Garage, Kitchen, Upstairs Bedroom, Office

All Beacons are named -House. They have different UUIDs but share the same Major and Minor numbers.

What's happening is that my Owntracks iOS app is constantly switching between beacons and showing me entry/exit notifications

From my understanding I have two options:

- Assign Each UUID to each room instead of -House and Owntracks will report entry/exit into the room (Still might have the issue of overlapping Beacons)
- Assign all the beacons to the same UUID with the same Major/Minor all with the name -House and Owntracks will consider these one Beacon and bouncing between them?

Please let me know if I have my options right, what's the recommended practice, and any toher tips/tricks that you might have!

Thanks

**Comment by ckrey** [comment]
I would suggest you assign the same UUID to all your beacons. Then you give your each of your beacons a different Minor number (or even a different Major number if you want to group them).

Setup the app by specifying the Minor (or both Major and Minor) number = 0. Then iOS will treat all
the beacons with the same UUID (or UUID/Major) as one Region.

Example:

```
Beacon 1: <UUID>:1:1
Beacon 2: <UUID>:1:2
Beacon 3: <UUID>:1:3
```

Setup:
```
Name: -House
UUID: <UUID>
Major: 1
Minor: 0
```

**Comment by milad-soufastai** [comment]
Okay so my beacons are Radbeacons: What I setup is the following:

Each beacon has the same UUID, Same Major, Different Minor Numbers

In Owntracks: 1 region called -House, Same UUID, Same Major, 0 for the minor number.

So far Owntracks is connecting to the region (aka it's turning red) but the location is still showing up as my neighbors house and not my address.

**Comment by milad-soufastai** [comment]
Seems to have resolved my issue of the constant connecting but even when I'm connected via beacons, sometimes owntracks shows me at my neighbors address vs. my own

**Comment by ckrey** [comment]
@milad-soufastai can we close this issue?
