### ISSUE TITLE
crash on successful transmission 

### ISSUE THREAD

**Issue by micdis** [owntracks/ios#572]
when the App is configured right it instantly crashes on successful transmission to the mqtt server.
in airplane mode or with no or wrong credentials it stays on. that way no background updates are happening!?
anyone with the same problem?

**Comment by ckrey** [comment]
@micdis this is not the typical behaviour of the app.

Maybe your MQTT broker sends some messages (OwnTracks subscribes to the topic `owntracks/#` by default) which are misinterpreted by the app.

Would you check the messages retained under the above topic on your MQTT broker?

**Comment by ckrey** [comment]
@micdis did you find some hints to the underlying problem?
