### ISSUE TITLE
I don't detect iBeacons on iPhone 7 Plus

### ISSUE THREAD

**Issue by cavoixanha** [owntracks/ios#573]
I use ibeancons of manufactor
http://www.radioland-china.com/English/Product/2703464627.html
I check some app(iBKS Config Tool), It is dectect exactly is iBeacons

**Comment by ckrey** [comment]
@cavoixanha any news? How did you setup your iBeacon region in OwnTracks? What does your Tool tell you about UUID, major and minor number?

**Comment by cavoixanha** [comment]
I check and I find problem because I select "While Using the App" on allow location, I think app should work when open app, (I don't use always because consumption battery iphone, I think you add feature  increase the time between the number of requests)
Thanks You!
