### ISSUE TITLE
iOS 10 support 

### ISSUE THREAD

**Issue by kngharv** [owntracks/ios#574]
I wanted to use an old iphone (iphone 5) act as an underaged family member tracker. I have noticed that latest version only support iOS11 or newer.

Is there a way to access an older version of Owntracks client?   

Thanks in advance

**Comment by ckrey** [comment]
Sorry for the inconvenience, but we have to limit the support of older iOS versions to keep development, testing and support efforts balanced with our free time we allocate to OwnTracks.

Yes you can access older versions of the app by standard app store features:

https://appleinsider.com/articles/18/02/08/how-to-download-old-versions-of-apps-from-the-app-store-on-an-older-iphone-or-ipad-that-cant-run-ios-11
