### ISSUE TITLE
Project LORA tracker update

### ISSUE THREAD

**Issue by Lanzones** [owntracks/ios#576]
Hi
Just an update on the progress of my Lora + owntrack project I have been tinkering a while back.

Check this out.. it comes in a black enclosure as well.
[915MHZ LORA GPS lightweight tracker assets long battery life, with Panic button](https://www.ebay.com.au/itm/264282935564)

**Comment by jpmens** [comment]
Thank you. If you have a Web site on which you showcase the specs and details we'll gladly add that to the booklet, but I'm closing this advert for a product sale now.

**Comment by Lanzones** [comment]
Hi JPmens,

Below is what the tracker can do.
//*************//
Long range capability, low cost, great GPS accuracy, IP66 enclosure, no cellular fees, off the shelves AAA battery replaceable within half a year, no wonder this device will be the tracker of choice.

- GEOFENCING : Uses Owntracks free app (Iphone and Android) which trigger alerts (twitter). Find out when a tool leaves a building site, when a vehicle leaves a compound, or when a child leaves school.
- HIGH ACCURACY: (10 metres) Allows for recovery of lost objects, including drones, sports equipment. etc.
- COVERAGE: LoRa network, growing in America, Asia, EMEA and Australia). Widespread in Europe
- SECURE AND PRIVATE: Unique device ID, network and application keysLOW-COST: Annual subscription $. *
- CHECK IN TIME: every 2hoursAUTONOMY: Up to 6 to 8 months for Lady-Bug tracker based on 750mAHr battery**
- DURESS PENDANT: A panic button for the lady-bug tracker is provided for quick relay of location.

Note:
** > depending how frequently the panic button is being used and how quickly the GPS locks its location.
