### ISSUE TITLE
Monitoring mode seems to change of its own accord

### ISSUE THREAD

**Issue by spbriggs** [owntracks/ios#579]
I've noticed high battery usage from the app recently. I set significant changes mode but next time I open the app it's back in move mode.

Steps to reproduce:

When I open the app it shows the >> icon for move mode. I tap it and it changes to > for significant changes. If I close the app (double press home button and flick it away), when I re-open it I'm back in >> move mode.

I've exported the config file before and after closing and reopening the app.

Before :   "monitoring" : 1
After :   "monitoring" : 2

**Comment by spbriggs** [comment]
Should add: Owntracks 12.0.3, iOS 12.2, iPhone 6 Plus and the issue is with excessive battery use.

**Comment by jpmens** [comment]
Why do you kill (flick away) the app?what do you intend accomplishing by doing that?

**Comment by spbriggs** [comment]
What I'm intending to accomplish is give instructions on reproducing the behaviour. What happens in practice is : open the app, set significant changes mode, exit app, get on with life, wonder why my phone battery is dying, open battery app on iPhone, see that Owntracks has been using a lot of power in the background, open Owntracks app, see that it is back on move mode without me having set it.

**Comment by spbriggs** [comment]
Having spent my lunch break walking up and down the road while logging the MQTT messages it seems I was mistaken. The tracking mode is staying set properly. I'll see if I can figure out what's causing the battery drain if it's not the tracking mode.

Probably a duplicate of #577 #562 and maybe related to #575
