### ISSUE TITLE
Missing updates in Friends tab after coming back from background

### ISSUE THREAD

**Issue by bakkerv** [owntracks/ios#582]
Hello,

I've setup a mosquitto server (MQTTS) at home and using OwnTracks on iOS and Android. When the iOS application is in the foreground, everything works fine. If I publish location updates, the application handles these updates and the friend locations are updated as expected.
However, if I leave the application, these updates are not handled in the background. This is expected, since the application is not allowed to run in the background in iOS. If I resume the application, I would expect OwnTracks to receive/'request' the latests locations, which it does not. It shows the 'old' location of my friends, i.e. the ones before going to the background.
If I 'close' and open the application, the behaviour is as expected.

Could the application be adjusted to 'refresh' all locations when returning from the background, or is something wrong with my setup?

**Comment by jpmens** [comment]
It sounds as though there's something wrong with your setup; the behaviour you're looking for is in our app.

Are you in quiet mode or something in the app? Does our iOS show a "play" symbol on the top right above the map? If not, then please tap it until it does.

Also, have you modified the QoS settings on any of your clients?

**Comment by BowenMarmot** [comment]
If you are using Mosquitto version 1.6.2 there is a bug that prevents “persistent sessions” from working which causes the exact behaviour you are seeing.  I have the same issue.  It is supposed to be fixed in the current “fixes” branch and included in the 1.6.3 release when that is eventually released.

**Comment by bakkerv** [comment]
@BowenMarmot I'm using 1.6.2, that would explain the current behaviour. Downgrading to 1.5 shows different behaviour in the OwnTracks app (I see a sort of progress bar when starting the app).. Let's hope the new version will fix the issue :) Tnx!
