### ISSUE TITLE
Update mode UI element.

### ISSUE THREAD

**Issue by tomtastic** [owntracks/ios#583]
Could the current 'update mode' button, which toggles between the multiple states be replaced with a flat toolbar like below?
![IMG_4336](https://user-images.githubusercontent.com/302127/58761851-7f339980-8540-11e9-8f82-6212e182c131.jpg)

I think it would help the user determine the current mode and the available options, especially if text was used rather than (or in addition to if space allowed) an icon.
![IMG_4335](https://user-images.githubusercontent.com/302127/58761852-85297a80-8540-11e9-8057-c3e95e290da0.jpg)
_(I do know the above example is not in quiet mode as per the icon, it was just a quick mock up)_
Ref:
https://github.com/owntracks/ios/issues/145

**Comment by ckrey** [comment]
![one](https://user-images.githubusercontent.com/4027289/59273901-80a84480-8c59-11e9-8d03-b09375697708.png)
![two](https://user-images.githubusercontent.com/4027289/59273902-830a9e80-8c59-11e9-9e9a-37efd8edc63a.png)
![three](https://user-images.githubusercontent.com/4027289/59273905-843bcb80-8c59-11e9-8a74-58f3c1ea3502.png)

**Comment by tomtastic** [comment]
I like the 'modes as text' in the last screenshot, I think this should be the always-visible default view, rather than the slightly odd tape-recorder vintage 'fast-forward/play/pause/stop' icons

**Comment by jpmens** [comment]
+1 for _modes as text_ in last screenshot, but I don't know whether 'always visible' is the right thing as it takes away map real estate

**Comment by ckrey** [comment]
I think the best compromise is a semi-translucent, always-visible control.
![IMG_8280](https://user-images.githubusercontent.com/4027289/59349980-42735980-8d1b-11e9-8224-c0c602f8ad2d.jpg)

**Comment by ckrey** [comment]
I will still be using the "slightly odd tape-recorder vintage 'fast-forward/play/pause/stop' icons" in the OwnTracksToday widget and keep the toogle logic:
![IMG_5E56EC66DEA2-1](https://user-images.githubusercontent.com/4027289/59350253-eceb7c80-8d1b-11e9-82dc-17c61a2db66e.jpg)

**Comment by tomtastic** [comment]
Thank you for your interest and development in this request, I think this is a really nice change to the UI.

**Comment by ckrey** [comment]
Will be in 12.0.8
