### ISSUE TITLE
Location not published correctly even when requested

### ISSUE THREAD

**Issue by MoerkyMark** [owntracks/ios#584]
Hi, I have a reoccurring issue with the recent iOS version: Even when the map shows my current position correctly, the manual publishing publishes a way older position. You can see it on my screenshots as as the blue dot indicates my current position (which is measured correctly but the reported position (indicated as letter "M" is far behind. Especially behind the geolocation fence so the trigger for being at home is not correctly. Its also reported a wrong speed as I'm currently sitting not moving - You can also see the different timestamps. Any
![IMG_2205](https://user-images.githubusercontent.com/30433435/59144726-0cf90400-89db-11e9-847e-1d6582b18732.jpg)
![IMG_2204](https://user-images.githubusercontent.com/30433435/59144727-0cf90400-89db-11e9-9930-68e0bf677bd0.jpg)

 help appreciated.

**Comment by ckrey** [comment]
Please let us know what is your "recent iOS version" and iPhone model.
And what is the current monitoring selected (Move, Significant changes, Quiet, or Manual)

**Comment by MoerkyMark** [comment]
iOS 12.3.1, iPhone XR, All Monitoring states used.

The example which is not working was in manual mode with manual update.

 

 

Von: Christoph Krey <notifications@github.com>
Antworten an: owntracks/ios <reply@reply.github.com>
Datum: Dienstag, 11. Juni 2019 um 12:19
An: owntracks/ios <ios@noreply.github.com>
Cc: MoerkyMark <special@schruefer.ch>, Author <author@noreply.github.com>
Betreff: Re: [owntracks/ios] Location not published correctly even when requested (#584)

 

Please let us know what is your "recent iOS version" and iPhone model.
And what is the current monitoring selected (Move, Significant changes, Quiet, or Manual)

**Comment by ckrey** [comment]
Would you check the `ignoreInaccuratePositions`setting, which defaults to 2000 meters.

If your phone does not have a GPS signal, cell tower accuracy is typically reported as 2200 meters.
This means all location publishes are silently ignored and not sent.

To check if this setting causes the problem, change it to a larger value e.g. 10000 meters.

**Comment by MoerkyMark** [comment]
Where can I change this setting?

 

Von: Christoph Krey <notifications@github.com>
Antworten an: owntracks/ios <reply@reply.github.com>
Datum: Freitag, 23. August 2019 um 09:40
An: owntracks/ios <ios@noreply.github.com>
Cc: MoerkyMark <special@schruefer.ch>, Author <author@noreply.github.com>
Betreff: Re: [owntracks/ios] Location not published correctly even when requested (#584)

 

Would you check the ignoreInaccuratePositionssetting, which defaults to 2000 meters.

If your phone does not have a GPS signal, cell tower accuracy is typically reported as 2200 meters.
This means all location publishes are silently ignored and not sent.

To check if this setting causes the problem, change it to a larger value e.g. 10000 meters.

**Comment by ckrey** [comment]
Got to Expert Settings  by tapping 3 times when on Status Info screen

**Comment by MoerkyMark** [comment]
Tested it with setting the ignoreInaccuratePositions to 10000, same problem. Manual update doesn't update the location.

**Comment by ckrey** [comment]
If you share your full configuration with us (direct message, anonymized), I will have a look.

**Comment by MoerkyMark** [comment]
Is there a way how to export this, then I’ll be happy to do so.

 

 

Von: Christoph Krey <notifications@github.com>
Antworten an: owntracks/ios <reply@reply.github.com>
Datum: Freitag, 30. August 2019 um 09:19
An: owntracks/ios <ios@noreply.github.com>
Cc: MoerkyMark <special@schruefer.ch>, Author <author@noreply.github.com>
Betreff: Re: [owntracks/ios] Location not published correctly even when requested (#584)

 

If you share your full configuration with us (direct message, anonymized), I will have a look.

**Comment by ckrey** [comment]
Go to the Status screen, tap on Settings and then on "Export Settings"

**Comment by MoerkyMark** [comment]
Just sent config as requested via mail.

 

 

Von: Christoph Krey <notifications@github.com>
Antworten an: owntracks/ios <reply@reply.github.com>
Datum: Freitag, 30. August 2019 um 12:07
An: owntracks/ios <ios@noreply.github.com>
Cc: MoerkyMark <special@schruefer.ch>, Author <author@noreply.github.com>
Betreff: Re: [owntracks/ios] Location not published correctly even when requested (#584)

 

Go to the Status screen, tap on Settings and then on "Export Settings"

**Comment by ckrey** [comment]
Thanks. The config is ok, settings do not seem to be related to the problem.
Still, I have no idea yet what is causing the problem

**Comment by ckrey** [comment]
@MoerkyMark would you retest the situation with the current iOS version (13.1.4).
It indicates the accuracy of the current location and uses the same location as the map display.

**Comment by MoerkyMark** [comment]
Hi Chris

Tested it with iOS 13.2.3. on iPhone XR and iPhone 7 and as soon as the Location is published (tested manual publishing) the same location as the map display is taken, great! thank you!

> Am 30.11.2019 um 11:17 schrieb Christoph Krey <notifications@github.com>:
> 

﻿
@MoerkyMark would you retest the situation with the current iOS version (13.1.4).
It indicates the accuracy of the current location and uses the same location as the map display.

**Comment by ckrey** [comment]
Fixed in e5bda26
