### ISSUE TITLE
.otrp files cannot be opened in OwnTrack app

### ISSUE THREAD

**Issue by ylexus** [owntracks/ios#585]
Maybe it's the iOS version, but .otrp files (AirDropped or saved to Files app) cannot be opened in OwnTrack app. Default action on these files is to save them to an iOS profile in Settings. "Open In" action on such a file does not list OwnTrack app. Is there any other way in iOS to transfer the .otrp file to the app? iOS 12.3.1.

**Comment by oliviervanroey** [comment]
I had the same issue on iOS. I tried using google drive, icloud and synology file. He could not open the file using OwnTracks. When I tried to open it when it was attached to an e-mail, it opened correctly.

**Comment by ylexus** [comment]
Alright, the problem was actually not the method of delivery, but the fact that iOS hides the extension of the file. The file looked like "file.otrp" in Finder, but it's actually received by iOS as "file.otrp.p12". Force-changed the extension in Finder (cmd+i on the file, change file name there) and now it works, even via AirDrop. I think it's definitely worth mentioning this on the Booklet.

**Comment by jpmens** [comment]
> the file must have a .otrp extension so that it can be opened in OwnTracks

is what the booklet says.
