### ISSUE TITLE
App enters and leaves iBeacon region while phone is stationary on same desk

### ISSUE THREAD

**Issue by ylexus** [owntracks/ios#588]
I have this iBeacon https://www.avvel.co.uk/shop/long-range-ibeacon and a region associated with it in the iOS app v12.0.3. When both the phone and the beacon are lying on the desk 50cm from each other, the app keep popping with enter/leave transition notifications for the beacon’s region, roughly every 5 to 30 mins. What could cause this? In iOS, do you use some kind of a high level iBeacon API that gives you enter/leave events or do you calculate enter/leave status yourself based on the presence/absence of the beacon advertisement? Just trying to understand how to approach the problem.

**Comment by ckrey** [comment]
We are using Apple‘s high level interface to detect entering or leaving a iBeacon region.

There are no parameters other than UUID, major, and minor for the app.

Please check with your beacon provider if the beacon fulfills Apple‘s iBeacon specs

**Comment by ylexus** [comment]
Setting beacon's broadcast period to 1 second helped.
