### ISSUE TITLE
Loading config.otrc crashes an open app

### ISSUE THREAD

**Issue by arturum** [owntracks/ios#591]
When opening config file while app is already running produces a crash (iPhone 6, iOS 12.4 and iPad Air2 iPadOS 13.0 beta). Although all settings and waypoints seem to be imported properly.

Opening file when app is closed properly opens an app and produces "File successfully processed" alert.

Edit: Apparently this behaviour is connected with number of waypoints included (or size of the config file). When it's above 120 app crashes.

**Comment by ckrey** [comment]
Probably caused by trying to setup 120+ regions to be monitored (iOS limits this to 20)
