### ISSUE TITLE
documenting the mqtt topics examples

### ISSUE THREAD

**Issue by fmuntean** [owntracks/ios#592]
I have two phones configured as follow:
Phone1:
 "pubTopicBase" : "prefix/owntracks/phone1"
 "sub" : true,
 "subTopic" : "prefix/owntracks/#",
"cmd" : true,
"remoteConfiguration":true,
"allowRemoteLocation" : true,

Phone2:
 "pubTopicBase" : "prefix/owntracks/phone2"
 "sub" : true,
 "subTopic" : "prefix/owntracks/#",
"cmd" : true,
"remoteConfiguration":true,
"allowRemoteLocation" : true,

The only example I see is the use of topic; owntracks/user/device.
With the configuration above the receiving of published locations works as expected. However the friends feature does not seems to work.

Also it seems that the phones are not responding to messages sent to prefix/owntracks/phone1/cmd or prefix/owntracks/phone2/cmd either.

Is the topic prefix of owntracks/+/+ hardcoded somewhere?

Can somebody explain how can we use a custom prefix please?

**Comment by ckrey** [comment]
No there is no hardcoded prefix.

Would you check if your ACL settings allow the phones to receive messages published under the topics `prefix/owntracks/+/event` `prefix/owntracks/+/cmd` and the other phone's base topic?

Would you check or share your MQTT broker log?

**Comment by fmuntean** [comment]
yes the ACLs are disabled for this debugging.
I am currently using a public cloud for this testing.
From the code it loos that if the subTopic setting is used then there is no subscription to /cmd or anything else just the subTopic list separated by white-space. (so I guess a space in there should be split the topics to subscribe however to keep it simple I only used one.

I know the public mqtt broker is receiving the message correctly as I get a subscription to the same topic and receive the messages I sent back correctly.
Asking for remote location under the /cmd topic results in nothing being sent back, but when I send location from the phone itself I get it with no issue.

So I guess it has to do with the subscription or the way is checking the ownDevice under the OwnTracksAppDelegate when using these settings.:
Not really sure  why these two lines are the same:
        NSArray *baseComponents = [[Settings theGeneralTopicInMOC:CoreData.sharedInstance.queuedMOC] componentsSeparatedByString:@"/"];
        NSArray *topicComponents = [[Settings theGeneralTopicInMOC:CoreData.sharedInstance.queuedMOC] componentsSeparatedByString:@"/"];

**Comment by fmuntean** [comment]
Do i even need to set the sub and subTopic when I have the pubTopicBase set?
My initial understanding was that the subTopic would be used when I need an extra topic to subscribe to; but now looking in the code with my limited knowledge of the app I am not really sure when and why to use the subTopic settings.
Would appreciate more info around this.

**Comment by ckrey** [comment]
All the information is available in https://owntracks.org/booklet and especially here: 
https://owntracks.org/booklet/tech/json/

If you think some more clarifcation is needed, we are happy to accept a PR

When you enter the expert mode (by tapping 3 times on the Status Info screen), you see all parameters and the effective settings for defaults:

![IMG_8548](https://user-images.githubusercontent.com/4027289/64258101-e2a9da80-cf26-11e9-82a0-acb8e954076a.jpg)

Yes, if you want to use a prefix, just change the pubTopicBase!
