### ISSUE TITLE
Step counter on iOS always returns 0 steps

### ISSUE THREAD

**Issue by lostfocus** [owntracks/ios#593]
I'm not too sure what I'm doing wrong - I've allowed the app in the hidden settings panel to accept commands, I've allowed the app to access "Motion & Fitness" data and every time I put a `steps` command with a timeframe in it (and it doesn't matter which timeframe it is) I get all values back as 0. (0 steps, 0 distance, 0 floorsup, 0 floorsdown)
I'm on the latest stable iOS and the latest OwnTrack app.

Is this a known issue and/or is there something I might have missed?

**Comment by ckrey** [comment]
There is no known issue other than the fact that the app accesses historical data from the phone:

https://developer.apple.com/documentation/coremotion/cmpedometer/1613946-querypedometerdata

You may have to wait a while until historical data is available. 

We use to query the steps once a day for the previous day (00:00 to 23:59)

**Comment by ckrey** [comment]
And please check if you did enable Settings/Privacy/Fitness data

**Comment by lostfocus** [comment]
Ah:

> Only the past seven days worth of data is stored and available for you to retrieve. Specifying a start date that is more than seven days in the past returns only the available data.

That is the problem. I wanted to get older data since I knew it was in the Health app and didn't even think to check if more current data is around. 🤦‍♂ Thanks for that link, now I understand better how the app works and that this Fitness data seems to be a different thing than the fitness data in the Health app.
