### ISSUE TITLE
Copy location coordinates to clipboard

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#597]
I wonder whether it would be easily possible to copy coordinate data to the clipboard. There are two different fields for which I've wanted this in the past:

* The `Coordinates` field on the Status Info page, top right
* The `Coordinates` field displayed on a friend's details page

If this is can easily be enabled (without redoing the UI !!!) I think it would be a useful addition.

**Comment by jpmens** [comment]
Thank you! :-)

**Comment by ckrey** [comment]
Will be in 12.0.9

**Comment by jpmens** [comment]
Tested and works very nicely. Thank you.
