### ISSUE TITLE
Review colors for Dark/Light Mode 

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#600]
Optimize for easy readability

**Comment by ckrey** [comment]
Thanks for your alpha-test feedback @jpmens
<img width="398" alt="Bildschirmfoto 2019-09-25 um 15 33 43" src="https://user-images.githubusercontent.com/4027289/65605772-f8507400-dfa9-11e9-97ef-4efc0621a9e0.png">
<img width="402" alt="Bildschirmfoto 2019-09-25 um 15 31 39" src="https://user-images.githubusercontent.com/4027289/65605776-f981a100-dfa9-11e9-91de-63df28fd3e80.png">

**Comment by jpmens** [comment]
Thank you, @ckrey, for addressing this so quickly. From your screenshots I think I see the following changes:

1. Labels at top of page are back to white (light mode), and grey (dark mode). This looks good to me.
2. The border and buttons on the move modes has changed a bit I think, and these look good in both light and dark.

Very nice.

**Comment by ckrey** [comment]
Fix available in App Store versions
