### ISSUE TITLE
Error "Operation not permitted" on otrp import

### ISSUE THREAD

**Issue by marvindv** [owntracks/ios#602]
When I open a otrp file from the Files app the OwnTracks app opens but the following error occurs:

```
openURL

file open error Error
Domain=NSPOSIXErrorDomain Code=1
"Operation not permitted"
UserInfo={_kCFStreamErrorCodeKey=1, _kCFStreamErrorDomainKey=1} 
file:///private/var/mobile/Containers/Shared/AppGroup/<some uuid>/Files%20Provider%20Storage/marvin.otrp
```

The otrp file was created with 

```
$ openssl pkcs12 -export -in marvin.crt -inkey marvin.key -name "marvins cert/key" -out marvin.otrp
```

just like https://owntracks.org/booklet/features/tlscert/#ios recommends. The corresponding CA cert is already installed.

**Comment by ckrey** [comment]
OwnTracks for iOS does not support opening files from the `Files` app yet.

For now, send the file via mail, and open/copy the attachment in OwnTracks.

**Comment by marvindv** [comment]
Got it, thanks!

**Comment by ckrey** [comment]
Default behaviour for iOS 13 changed back to copy files 9cb25d7994e72b5385519f2f7694ba9b99a90e39
