### ISSUE TITLE
Creating a Mac Version of OwnTracks

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#603]
The first step is very simple:
https://developer.apple.com/documentation/xcode/creating_a_mac_version_of_your_ipad_app?language=objc

- Found issues:
    - CLLocationManager
[ ] monitoringDidFailForRegion CLBeaconRegion - no Beacon monitoring

- Solved/Worked Around issues:
    - CLLocationManager
[x] maccatalyst does not support CLLocationManager startRangingBeaconsInRegion and other Beacon ranging methods. Excluded
[x] maccatalyst does support new initializer CLBeaconRegion. Updated
    - UIKit
[x] maccatalyst does not allow to use UIAlertController without actions (and termiation by dismissViewControllerAnimated). Workaround applied
[x] maccatalyst MKMapView does not allow to zoom out. Added Zoom Controls
[x] maccatalyst UITableView does not support left swipe actions. Added Edit/Done Button, another work around is to use 2 fingers to swipe left
[x] maccatalyst does not support UIApplication statusBarStyle. Excluded
    - Miscellaneous
[x] maccatalyst bundles have a different structure than in iOS. Need to use NSBundle URLForResource
[x] SocketRocket needs some #ifdef (about to replace SockeRocket by native Websockets)
[x] error: Today extensions are not available when building for Mac Catalyst. Ignored
[x] maccatalyst does fail in CLLocationManager startUpdatingLocation - needs Wifi!
[x] maccatalyst life cycle is different. Need to re-connect after laptop wakes up from sleep
[x] export Settings/Waypoints does not work --> not yet implemented in Mac Catalyst
[x] AVCaptureDevice *captureDevice = [AVCaptureDevice defaultDeviceWithMediaType:AVMediaTypeVideo]; returns nil, internal QR code reading removed

**Comment by jpmens** [comment]
Fantastic. Tested and working:

- association with address book
- location copy to clipboard
- publish settings
- publish waypoints

**Comment by ckrey** [comment]
macOS version available in App Store: https://jpmens.net/2019/11/29/owntracks-on-macos/
