### ISSUE TITLE
lwt-message: Parameter "tst" is of type string.

### ISSUE THREAD

**Issue by marc-heinlein** [owntracks/ios#604]
According to OwnTracks API definition (https://owntracks.org/booklet/tech/json/#_typelwt) the lwt-message should provide parameter "tst" as type int. Instead the iOS-App sends "tst" as type string.

OwnTracks iOS-App Version: 13.0.2/de_DE

Sample payload:
{"tst":"1571457804","_type":"lwt"}

Maybe this is due to the following implementation in
ios/OwnTracks/OwnTracks/OwnTracksAppDelegate.m, lines 1251..1253:
        NSMutableDictionary *json = [NSMutableDictionary dictionaryWithDictionary:@{
                                                                                    @"tst": **[NSString stringWithFormat:@"%.0f", [NSDate date].timeIntervalSince1970]**,
                                                                                    @"_type": @"lwt"}];

**Comment by ckrey** [comment]
Good catch. That's in for ages

**Comment by ckrey** [comment]
Fix available in App Store versions.
