### ISSUE TITLE
Allow map to be switched between map view and satellite view

### ISSUE THREAD

**Issue by unikitty37** [owntracks/ios#606]
Editing zones on the map is trickier than it needs to be, as you do not have a clear indication of whether the radius you have set encompasses the whole area you wanted (this is especially problematic in more rural areas, where there are fewer cross streets and other reference points than in cities).

Allowing the user to toggle the map into satellite view would greatly help here. However, I can't see how to do it — is this even possible? If not, would it be possible to support it?

**Comment by ckrey** [comment]
Consider it done

<img width="709" alt="Bildschirmfoto 2019-11-08 um 14 16 53" src="https://user-images.githubusercontent.com/4027289/68479398-8323c000-0232-11ea-8625-e643c4ae8437.png">

**Comment by jpmens** [comment]
@unikitty37 thanks for the suggestion. @ckrey thanks for doing that so quickly!

**Comment by ckrey** [comment]
Enhancement available in App Store versions.
