### ISSUE TITLE
end user whose Regions disappear

### ISSUE THREAD

**Issue by JtwoA** [owntracks/ios#608]
I've attempted to add Regions only to have 2/3 of them disappear after closing and opening the app.  I'm using iOS 13.3 -- am I missing a step?  Also, one Region saves with the OwnTracks icon in blue, the other saves with a giant dot (red when I'm at that location but then just a not-red dot when I'm gone from that location.)

Any guidance is appreciated!

**Comment by ckrey** [comment]
If you mean to kill the app / swipe out the app when you say "closing", then this may happen because the database is persisted asynchronously.

Please don't kill the app, no need to to so.

The number of regions the iOS operating system is able to monitor per app is limited to 20.

The status of the regions is shown in the regions list and on the map:
Blue is cold -> you are not in the region
Red is hot -> you are in the region

**Comment by JtwoA** [comment]
So are the missing ones actually still present but not visible or are they just not saved after reporting up to the consuming service I'm beta testing for a friend?

As to closing apps, it's habit.  I have no apps running other than when I'm actually interacting with the phone.

**Comment by jpmens** [comment]
Worth a read: [You Should Not Force Quit Apps on iOS](https://daringfireball.net/2017/07/you_should_not_force_quit_apps)

**Comment by JtwoA** [comment]
Interesting article.  I've heard both sides but this is the first time I've seen anything back up the assertions.  Thanks for this.

**Comment by JtwoA** [comment]
FYI, here is what I'm seeing for icons: 

![image](https://user-images.githubusercontent.com/12992040/68768790-2ee15d00-05f1-11ea-9d04-2dd64267a73d.png)

**Comment by ckrey** [comment]
Yes, here is an example with all possible icons:

OwnTracks Icon: Region not completely set up. No radius or UUID set

Blue or Red Circle: see above

Blue or Red iBeacon symbol: Undetected or detected iBeacon

![IMG_8BDCF9E6A1C4-1](https://user-images.githubusercontent.com/4027289/68770656-daf16b00-0626-11ea-89bb-a6fc472dd575.jpg)

**Comment by JtwoA** [comment]
Ah, 65 did not save the radius.  Very helpful and now corrected.  thanks!

**Comment by JtwoA** [comment]
The ask I still have is "are the missing Regions on my device actually still present somewhere on the device but not visible to me?

**Comment by jpmens** [comment]
If you can't see them they're not there

**Comment by JtwoA** [comment]
Thanks - this means I need to take this up with the implementer of the app I'm beta testing as they keep re-populating there.

**Comment by jpmens** [comment]
The implementor of the OwnTracks app? That is us! 

Where did you download that app from?

**Comment by JtwoA** [comment]
No, the app I'm beta testing that uses data provided by owntracks.  As the data only flows one way, if it's present in your side it appears on his side.  Every time I delete those regions I don't see in the OT app, they reappear on his side when his app updates.  That's why I was asking if it was possible these regions were still somehow stored but not visible - it would certainly make for an easier explanation.

Now I'll go to him with this data and see what's causing it upstream.

**Comment by jpmens** [comment]
Regions are not exported to transmitted by default; locations and events are.

That been said, if you care to precisely explain what you are trying to do (and what "his app" actually is and does) we'd have a chance understand and might even be able to assist you.

**Comment by JtwoA** [comment]
I have a home automation system, VeraSecure.  This gentleman has written a plug-in that pulls from OwnTracks to create "devices" in the system that represent the saved locations in OT.  Using those "devices", one can now trigger events and actions - "when I leave Jimmy's house turn up the heat", "when I leave my house turn down the heat and turn on the lights", "when I get home, open the garage door", etc.

It's a great idea, taking the home automation system's limited geofencing capabilities and blowing it away.

**Comment by ckrey** [comment]
Fix available in App Store versions. Closing Issue
