### ISSUE TITLE
Question about background location tracking

### ISSUE THREAD

**Issue by AnandChowdhary** [owntracks/ios#609]
It seems like [iOS 13 only allows users to use "Allow While Using the App"](https://www.macrumors.com/2019/08/16/app-developers-tracking-restrictions-ios-13/) instead of "Always Allow" for location tracking. However, a user can go into the app's settings and select "Always" (like shown in the article above). So, my question is this:

If I have it set up on "Always", do I still need to keep OwnTracks open in the background to track my location on the "Significant" setting, or will it continue to push my location while the app is closed (via background refresh)? If I don't change the location setting to "Always" and keep "Allow While Using the App", I would assume I will need to keep the app open?

**PS:** OwnTracks is absolutely the best way to track your location on iOS without using third-party services like Google/Apple Maps. Thank you so much for all your hard work, @ckrey!

**Comment by jpmens** [comment]
OwnTracks will continue to track location in "Significant" as you've been used to seeing. However, after a few days (3 IIRC) iOS will ask you if you want to continue letting it track your location in the background; answer 'Yes always', or whatever the exact response is. 

Thank you for your kind words, and the record will show that I too find @ckrey does an amazing job!

**Comment by AnandChowdhary** [comment]
Thanks, @jpmens!

**Comment by jpmens** [comment]
Please don’t hesitate to report back if you notice it doesn’t work for you.
