### ISSUE TITLE
owntracks on iOS stopped receiving positions after eclipse-mosquitto upgrade

### ISSUE THREAD

**Issue by chedxb** [owntracks/ios#611]
Hi there,

I host my own eclipse-mosquitto broker on a docker instance (eclipse-mosquitto:latest) and after an image upgrade on the 4th of December, owntracks stopped working. I see clients are connected to the broker, however on the iOS app, everything has been frozen as of 4th, just before the image upgrade.

What could be the issue?

Best,

Savas

**Comment by luca-angemi** [comment]
Hi guys, after reinstalling I had the same issue and moving sub to True worked. 

Now there is another problem (not sure if it's related). Friends are updating only if I swipe away the app and reopening it. Am I missing something?

Apologies if this isn't the right place to address this issue.

**Comment by jpmens** [comment]
This issue is a  year old ...

If `Sub` is false, you're not subscribing. If you swipe out the app you are effectively killing it; we recommend you don't do that.

How are your friends publishing their data? Which apps, versions?

**Comment by luca-angemi** [comment]
Thanks for the prompt reply.

Both apps are iOS v. 13.3.6 with both Sub set to True.

**Comment by jpmens** [comment]
So, phone1 open on map or Friends list
and phone2 publishes a position (up arrow on map)
and you don't see its position or publishing time change/show on phone1?

**Comment by luca-angemi** [comment]
Correct. I only see the update if I kill the app.

**Comment by jpmens** [comment]
Which MQTT broker are you using? Can you see the publish and the subscribe in its logs and can you show us the logs, please?

**Comment by luca-angemi** [comment]
I'm using mosquitto.

Here the logs of the mentioned test.

1608138960: New connection from 86.127.254.180 on port 1883.
[INFO] found luca on local database
1608138962: New client connected from 86.127.254.180 as lucaiphone (p2, c0, k60, u'luca').
1608138968: Client lucaiphone disconnected.
1608138968: New connection from 86.127.254.180 on port 1883.
1608138968: New client connected from 86.127.254.180 as lucaiphone (p2, c0, k60, u'luca').
1608139013: Client lucaiphone disconnected.
1608139065: New connection from 195.135.248.188 on port 1883.
[INFO] found maca on local database
1608139067: New client connected from 195.135.248.188 as macaiphone (p2, c0, k60, u'maca').
1608139069: Client macaiphone disconnected.

**Comment by luca-angemi** [comment]
Thanks for editing it.

**Comment by jpmens** [comment]
Those logs show connection messages only. Please add `log_type debug` to `mosquitto.conf` and try again after restarting/reloading Mosquitto. I'm looking for `PUBLISH` and `SUBSCRIBE` type messages.

**Comment by luca-angemi** [comment]
I redacted some stuff. I'm not an expert so I tried my best.

```log
$ mosquitto_sub -u username -P password -t '#' -h 'XXX.XXX.XXX.XXX' -v -d
Client mosq-YnjK61DPBHZdyaObrY sending CONNECT
Client mosq-YnjK61DPBHZdyaObrY received CONNACK (0)
Client mosq-YnjK61DPBHZdyaObrY sending SUBSCRIBE (Mid: 1, Topic: #, QoS: 0, Options: 0x00)
Client mosq-YnjK61DPBHZdyaObrY received SUBACK
Subscribed (mid: 1): 0
Client mosq-YnjK61DPBHZdyaObrY received PUBLISH (d0, q0, r1, m0, 'esp/door', ... (3 bytes))
esp/door OFF
Client mosq-YnjK61DPBHZdyaObrY received PUBLISH (d0, q0, r1, m0, 'owntracks/maca/iphone', ... (165 bytes))
owntracks/maca/iphone {"cog":153,"batt":69,"lon":XXXX,"acc":10,"p":93.016,"bs":1,"vel":12,"vac":3,"lat":XXXX,"conn":"m","tst":1608140267,"tid":"ma","_type":"location","alt":722}
Client mosq-YnjK61DPBHZdyaObrY received PUBLISH (d0, q0, r1, m0, 'owntracks/luca/iphone', ... (230 bytes))
owntracks/luca/iphone {"batt":4,"lon":XXXX,"acc":65,"p":93.233,"bs":1,"SSID":"ZZZZZZZZ","BSSID":"YYYYYYYYY","vac":3,"lat":XXXX,"inregions":["Home"],"t":"u","conn":"w","tst":1608140518,"alt":694,"_type":"location","tid":"lu"}
Client mosq-YnjK61DPBHZdyaObrY received PUBLISH (d0, q0, r0, m0, 'owntracks/maca/iphone', ... (164 bytes))
owntracks/maca/iphone {"cog":174,"batt":69,"lon":XXXX,"acc":5,"p":93.061,"bs":1,"vel":12,"vac":3,"lat":XXXX,"conn":"m","tst":1608140568,"tid":"ma","_type":"location","alt":719}
Client mosq-YnjK61DPBHZdyaObrY received PUBLISH (d0, q0, r0, m0, 'owntracks/luca/iphone', ... (230 bytes))
owntracks/luca/iphone {"batt":3,"lon":XXXX,"acc":65,"p":93.233,"bs":1,"SSID":"ZZZZZZZZ","BSSID":"YYYYYYYYY","vac":3,"lat":XXXX,"inregions":["Home"],"t":"u","conn":"w","tst":1608140572,"alt":694,"_type":"location","tid":"lu"}
´´´

**Comment by luca-angemi** [comment]
I think I found something else. I managed to put in debug mode the logs.

```log
[INFO] found maca on local database
1608142071: Will message specified (32 bytes) (r0, q1).
1608142071: 	owntracks/maca/iphone
1608142071: Sending CONNACK to macaiphone (0, 0)
1608142072: Denied PUBLISH from macaiphone (d0, q1, r1, m30, 'owntracks/maca/iphone', ... (154 bytes))
1608142072: Sending PUBACK to macaiphone (m30, rc135)
1608142072: Denied PUBLISH from macaiphone (d0, q1, r1, m31, 'owntracks/maca/iphone', ... (148 bytes))
1608142072: Sending PUBACK to macaiphone (m31, rc135)
1608142072: Denied PUBLISH from macaiphone (d0, q1, r1, m32, 'owntracks/maca/iphone', ... (164 bytes))
1608142072: Sending PUBACK to macaiphone (m32, rc135)
1608142073: Received DISCONNECT from macaiphone
1608142087: Denied PUBLISH from lucaiphone (d0, q1, r1, m7, 'owntracks/luca/iphone', ... (230 bytes))
1608142087: Sending PUBACK to lucaiphone (m7, rc135)

**Comment by luca-angemi** [comment]
Ok, managed to get proper logs.

```log
1608147076: Sending CONNACK to macaiphone (0, 0)
1608147084: Received PUBLISH from macaiphone (d0, q1, r1, m41, 'owntracks/maca/iphone', ... (232 bytes))
1608147084: Sending PUBACK to macaiphone (m41, rc0)
1608147084: Sending PUBLISH to 0e4pnP2KQEYYEB9P5cm3Vu (d0, q1, r0, m7, 'owntracks/maca/iphone', ... (232 bytes))
1608147084: Received PUBACK from 0e4pnP2KQEYYEB9P5cm3Vu (Mid: 7, RC:0)
1608147091: Received PINGREQ from lucaiphone
1608147091: Sending PINGRESP to lucaiphone
1608147105: Received DISCONNECT from lucaiphone
1608147107: Will message specified (32 bytes) (r0, q1).
1608147107: 	owntracks/luca/iphone
1608147107: Sending CONNACK to lucaiphone (0, 0)
1608147107: Received SUBSCRIBE from lucaiphone
1608147107: 	owntracks/+/+ (QoS 1)
1608147107: Sending SUBACK to lucaiphone
1608147107: Sending PUBLISH to lucaiphone (d0, q1, r1, m1, 'owntracks/maca/iphone', ... (232 bytes))
1608147107: Sending PUBLISH to lucaiphone (d0, q1, r1, m2, 'owntracks/luca/iphone', ... (241 bytes))
1608147107: Received SUBSCRIBE from lucaiphone
1608147107: 	owntracks/+/+/event (QoS 1)
1608147107: Sending SUBACK to lucaiphone
1608147107: Received SUBSCRIBE from lucaiphone
1608147107: 	owntracks/+/+/info (QoS 1)
1608147107: Sending SUBACK to lucaiphone
1608147107: Received SUBSCRIBE from lucaiphone
1608147107: 	owntracks/luca/iphone/cmd (QoS 1)
1608147107: Sending SUBACK to lucaiphone
1608147107: Received PUBACK from lucaiphone (Mid: 1, RC:0)
1608147107: Received PUBACK from lucaiphone (Mid: 2, RC:0)

**Comment by jpmens** [comment]
Before you edited the last comment I see in the notification email

```
Denied PUBLISH from macaiphone (d0, q1, r1, m31, 'owntracks/maca/iphone', ... (148 bytes))
```

This indicates ACL problems on your Mosquitto broker.

**Comment by luca-angemi** [comment]
Yes, I had forgotten to add those users to the file. Latest comments are with correct ACL and the iOS app is updated only after a kill.

**Comment by jpmens** [comment]
@luca-angemi we need more info. Show us your Mosquitto ACLs please, and show us logs during which both phones initially connect, subscribe, publish, etc.
