### ISSUE TITLE
Self-signed server certificate not recognized after iOS update

### ISSUE THREAD

**Issue by tedstriker** [owntracks/ios#613]
Setting:
mosquitto with a server certificate derived from a self-signed root certificate. The root certificate is present and trusted on iPhone.
After updating iOS to version 13.3 from (12.x) it seems the self-signed root certificate isn't recognized to validate the server certificate anymore.
The connection is only possible if the TLS settings is set to `Use Custom Security Policy` to `true` and `Allow Untrusted Certificates` to `true` as well.

with iOS 12.x the self-signed certificate wasn't considered untrusted due to installed root certificate.

**Comment by jpmens** [comment]
I think you are being hit by https://github.com/owntracks/ios/issues/612 and request that you follow the progres there, also with an updated `generateTLS.sh` script which I provided a few hours ago which ought to fix the problem; glad for you to test.

I am marking this as duplicate and closing.

**Comment by tedstriker** [comment]
Thank you for pointing out the changed policies. Adjusting properties of the certificate did the trick.
