### ISSUE TITLE
_type=cmd action

### ISSUE THREAD

**Issue by deepakkoirala** [owntracks/ios#614]
I am trying to send a _type=cmd action so that I can open a new tab in iphone app.

var valToSend = JSON.stringify({"action": "action", "url": "http://www.example.com", "_type": "cmd"});
client.publish("owntracks/rdamopvr/deepsiphone/cmd", valToSend);

All the mqqt connection is working fine and the ios is also sending location updates in certain interval of time. There are no errors anywhere.

I am not able to open this url from the JSON payload in the ios tab. Is there something I am missing.

I am following this https://owntracks.org/booklet/tech/json/#_typecmd

**Comment by jpmens** [comment]
Make sure you publish with QoS>0 as the iOS app might be in the background and your publish gets lost. What you want is when the app wakes up for it to receive the message.

I have a bit more [blurb about that here](https://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/).

**Comment by deepakkoirala** [comment]
I am using mqqt.js javascript library to publish the message. I even tried sending QOS 1, 2. And also kept the app opened. It did not work.

https://github.com/mqttjs/MQTT.js

But I am getting location updates.

**Comment by ckrey** [comment]
@deepakkoirala please check if you have `"cmd" = true` and `"sub" = true` in your iPhone's configuration

Check via "Export Settings" or in expert mode (tap 3 times on status screen)

**Comment by deepakkoirala** [comment]
This the export json file currently.


{
  "host": "postman.cloudmqtt.com",
  "locatorDisplacement": 200,
  "subTopic": "",
  "usepolicy": false,
  "validatecertificatechain": false,
  "ignoreStaleLocations": 0,
  "cleanSession": false,
  "locked": false,
  "url": "",
  "usePassword": true,
  "positions": 50,
  "mode": 0,
  "tls": true,
  "willRetain": false,
  "ignoreInaccurateLocations": 0,
  "deviceId": "deepsiphone",
  "extendedData": true,
  "monitoring": 2,
  "_type": "configuration",
  "locatorInterval": 180,
  "maxHistory": 0,
  "waypoints": [
    {
      "_type": "waypoint",
      "tst": 1564414705,
      "lat": 32.898284912109,
      "lon": -96.949188242154,
      "rad": 100,
      "desc": "test1"
    },
    {
      "_type": "waypoint",
      "tst": 1565053780,
      "lat": 32.916403721477,
      "lon": -96.951325875915,
      "rad": 100,
      "desc": "test2"
    }
  ],
  "ws": false,
  "username": "testus",
  "tid": "",
  "policymode": 0,
  "willTopic": "",
  "clientpkcs": "",
  "ranging": false,
  "keepalive": 60,
  "willQos": 1,
  "pubTopicBase": "",
  "auth": true,
  "passphrase": "",
  "allowinvalidcerts": false,
  "port": 24156,
  "clientId": "",
  "mqttProtocolLevel": 4,
  "sub": true,
  "allowRemoteLocation": true,
  "pubQos": 1,
  "password": "_",
  "validatedomainname": false,
  "subQos": 1,
  "servercer": "",
  "cmd": true,
  "pubRetain": true
}

**Comment by jpmens** [comment]
redacted above for privace,but:

```
"sub": true,
"cmd": true,
```

**Comment by deepakkoirala** [comment]
I did not know about this 3 tap option thing. I did enabled these options to true since it was false by default. Now it seems to be working. Thanks a lot.

**Comment by jpmens** [comment]
Glad you got it working; thanks for the feedback.
