### ISSUE TITLE
Add SSID and BSSID

### ISSUE THREAD

**Issue by jpawlowski** [owntracks/ios#615]
I was wondering if you could add SSID and BSSID to the payload in case the device is connected to a wifi?

**Comment by ckrey** [comment]
we could, what's the use case?

**Comment by jpawlowski** [comment]
Primarily I would like balance out available data with other suppliers (e.g. other apps). Currently it is really hard to make apps interchangeably as they don't deliver the same amount of data and data quality. That makes OwnTracks less attractive to be used within lots of (home) automation scenarios.

Furthermore, cars provide wifi and it might be that something should only be triggered while sitting in my own car.

**Comment by sheppy99** [comment]
Did this make it into the main ios app? It could be an easy way for working out if the phone is at home assuming it doesn't disconnect from WiFi when its sleeping

**Comment by ckrey** [comment]
The new app version is not yet ready for the App Store

**Comment by sheppy99** [comment]
Thanks for the prompt reply, I'll keep my eyes open for it as for some strange reason OT has recently stopped updating my closest geofence promptly which I use for presence detection
