### ISSUE TITLE
Add address information from lat+long

### ISSUE THREAD

**Issue by jpawlowski** [owntracks/ios#616]
It would be neat to have the device looking up the address information and have it added to the payload. It will avoid every MQTT consumer will need to do this on their own and will even lead to a consistent result as otherwise consumers may handle it all differently.

I even think there is an API available on iOS devices (not an Apple developer though):
https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/UsingGeocoders/UsingGeocoders.html

**Comment by ckrey** [comment]
This has already been discussed and rejected in owntracks/talk#77
