### ISSUE TITLE
iOS notifications not in Notification Center or lock screen 

### ISSUE THREAD

**Issue by glennorchard** [owntracks/ios#618]
iOS notifications for Waypoint enter/leave only appear as a banner but not in Notification Center or lock screen. Is this by design as I’d like to see them there but disable them in setting if not?

**Comment by ckrey** [comment]
The do appear in Notification Center but will disappear when the app is activated ( see #595 )

**Comment by glennorchard** [comment]
> The do appear in Notification Center but will disappear when the app is activated ( see #595 )

That’s not the experience I have now. There is no sign of the notification in Notification Center even seconds after the banner appears and with the app not being opened?
