### ISSUE TITLE
OwnTracks/Podfile has some hardwired values `=> ~/...`

### ISSUE THREAD

**Issue by mrose17** [owntracks/ios#619]
if i replace:

        pod 'ABStaticTableViewController', :path => '~/ABStaticTableViewController'
        pod 'mqttc/MinL', :path => '~/mqttc'

with:

        pod 'ABStaticTableViewController'
        pod 'mqttc/MinL'

then `AbStaticTableViewController` resolves, but `mqttc/MinL` does not... what should i be using? thanks!

ps: @ckrey - thanks for maintaining OwnTracks. many years ago when i was in the IoT space, i did some work with @binarybucks and @jpmens ... great times! i'm glad to see that this project is still active!

**Comment by ckrey** [comment]
I use a modified version of `ABStaticTableViewController` to avoid Xcode11 warnings. Unfortunately the maintainer of the repo did accept my change request but didn't succeed to 
update in cocoapods. I suggest you clone the repo and use it locally too

https://github.com/k06a/ABStaticTableViewController.git

I do use an MQTT library which is in pod format but not available on cocoapods:

Please clone and use locally:

https://github.com/ckrey/mqttc.git

**Comment by mrose17** [comment]
Winner, thanks! I will submit a PR later today with some additions to the README file.

**Comment by ckrey** [comment]
solved by a46b0f645b8bd34c71c5efd25e43b0646688ba9c
