### ISSUE TITLE
Q: how to set configuration options?

### ISSUE THREAD

**Issue by mrose17** [owntracks/ios#621]
(i'm able to compile and run, thanks!)

so, here's a question: i know how to import an `.otrc` file, but i don't see a way to set an existing configuration option, e.g., `pubTopicBase` ... in the android app, there's a "Preferences > Configuration management > Import" function that lets you enter a keyword/value pair, but i don't see any panel/tab in the iOS application that does that.

am i missing it?

**Comment by ckrey** [comment]
There is no action in the OwnTracks app, but the app registers for the respective file types.

E.g. if you send an .otrc file via email, open it with the action button and select "Copy to OwnTracks".

**Comment by mrose17** [comment]
understood. i've been using "Copy to OwnTracks" quite a bit. thanks!
