### ISSUE TITLE
Question: Expert Mode

### ISSUE THREAD

**Issue by mrose17** [owntracks/ios#623]
This is a follow-up to #621 - i was getting ready to do some coding to support editing two options, `pubTopicBase` and `subTopic`, and noticed that the storyboard already has something called "Expert" mode and that [SettingsTVC.m](https://github.com/owntracks/ios/blob/master/OwnTracks/OwnTracks/SettingsTVC.m) seems to implement it.

However, this isn't present in the [App Store](https://apps.apple.com/us/app/owntracks/id692424691). I've also noticed that the non-expert mode storyboard has an additional option (URL) that isn't in the app store version.

is there an ETA for enabling the Expert mode code and then putting a new release on the app store?

**Comment by ckrey** [comment]
URL is only visible and relevant in HTTP mode.

Expert mode is present in the app store version but hidden. You access it by tapping 3 times on the status screen. This info can be found in a number of issues.

**Comment by mrose17** [comment]
This is _wonderful_. i don't have to code anything!

if i may suggest, perhaps on the "Status info" page, have a little bit of text that says something like this:

        Triple-tap here for expert mode. (As an expert, if you break something, you'll have to fix it yourself!)

i mention this because requiring folks to dig through the code or the issue list is a bit much for folks who just want to download the app and run it! (-;

**Comment by jpmens** [comment]
We removed all the settings on purpose back then and hid them this way. I feel this is, for most users, safer.

Apropos triple-tap, and since you’re so happy: let me indicate that you can single-tap (or tripple-tap) on the Sponsor heart at the top of this page, if you like. :-)

**Comment by mrose17** [comment]
@jpmens - hi!

ok, compromise: put the triple tap note in the README.md...

also, instead of using liberapay, i use Brave ... (well, actually, i've been working there for a while...)

<img width="759" alt="Screen Shot 2020-03-01 at 16 05 25" src="https://user-images.githubusercontent.com/400552/75633921-34ca7080-5bd7-11ea-982c-18d606158656.png">

See the little "pyramid" icon and the "Tip". i clicked on that and sent some BAT to both you and @ckrey ...  if you don't know about the Brave browser and BAT, cf., https://brave.com/faq/#unclaimed-funds

Sorry for the advert!
