### ISSUE TITLE
Consider watchOS version

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#625]

**Comment by ckrey** [comment]
There is a first version available now 16060be8c6cae88caffa68604b85557e01f2d1eb

Open issues:

- no region monitoring available
- no significant changes mode available (need to filter too frequent updates)
- Connectivity only when close to associated iPhone. Wifi or cellular data is not used?
- UI very basic and technical:
![Simulator Screen Shot - Apple Watch Series 5 - 44mm - 2020-04-06 at 08 25 34](https://user-images.githubusercontent.com/4027289/78530041-3ba25f80-77e3-11ea-8a23-ef7097901c7d.png)
![Simulator Screen Shot - Apple Watch Series 5 - 44mm - 2020-04-06 at 08 27 30](https://user-images.githubusercontent.com/4027289/78530051-40ffaa00-77e3-11ea-9285-c803176e7aab.png)
![Simulator Screen Shot - Apple Watch Series 5 - 44mm - 2020-04-06 at 08 26 22](https://user-images.githubusercontent.com/4027289/78530060-44933100-77e3-11ea-85d2-8bae53e53a9f.png)

**Comment by philjubb** [comment]
+1 for this one. I've been using my kid's LTE apple watch to track him when he's on the bus but it required me to have an iphone. I switched to android a while back and would much prefer to connect our OwnTracks to his watch than have to carry an extra iphone.

**Comment by ckrey** [comment]
I couldn't get communications to work on an LTE watch without an iPhone nearby. Giving up for now ...
