### ISSUE TITLE
iOS device does only update initially 

### ISSUE THREAD

**Issue by peterlindeman** [owntracks/ios#628]
Hello,

For an unknown reason one iPhone here only shows the location update once in the app. 
I see updates coming in to my mqtt server but in the app (as well as the local app as a friend's app) I see an old location again. When I remove the friend from the list it will return with a correct location when the location of this friend updates but after a while it then shows the old location n (with old timestamp) again. 

What can be happening here and even better how can it be resolved?

Peter

**Comment by ckrey** [comment]
This seems to be a problem with your MQTT broker / your MQTT configuration (clean session, QoS, retain)
Please share some details about your broker and your configuration file (credentials removed)

**Comment by peterlindeman** [comment]
I have Eclipse Mosquitto running in a docker container. What could be wrong in this setup. Pretty basic setup.

Mosquitto config

log_type all
allow_anonymous false
password_file /mosquitto/config/passwd

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /mosquitto/data

log_dest file /mosquitto/log/mosquitto.log

#include_dir /etc/mosquitto/conf.d

listener 1883

# Enable SSL
listener 8883
cafile /mosquitto/config/DST_Root_CA_X3.pem
certfile /etc/letsencrypt/live/lindeman.nl/fullchain.pem
keyfile /etc/letsencrypt/live/lindeman.nl/privkey.pem
tls_version tlsv1.2

I will try to remove all persistant data from MQTT and start over to see if this makes a difference

**Comment by jpmens** [comment]
@peterlindeman have you per chance "fiddled" with some of the OwnTracks settings on iOS, e.g. changed QoS, retention, etc., either via `.otrc` or in the settings panel? 

Could you please export your iOS settings (Settings, Export) and send them to us? Feel free obviously to remove any credentials. `support@owntracks.org`.

**Comment by peterlindeman** [comment]
Haven't changed anything manually. Have sended the config gile now to the support address. Thanks!

**Comment by ckrey** [comment]
Looking at your config file:

You changed `"cleanSession": false` to `"cleanSession": true`.

This means everytime the app comes into foreground, it asks the broker to purge queued messages and will get the last retained position from the broker.

You wrote in your mail:
```
When I initially send the location it seems correct. I then switch to other applications on the
phone and return to owntracks later. I see "resolving" for a while and then an old location of this
phone. When I now manually send the location I see it coming in to mqtt but not on the owntrack
clients
When I now remove the incorrect friend from the list all the waypoints are deleted as well
```

You are talking about multiple OwnTracks clients. But it is not clear to us what you do on which client.

The last point is correct: If you delete your own entry on your phone, all waypoints are gone

**Comment by peterlindeman** [comment]
Hello,

Could be that I have changed that field when I was looking for a solution. Have set that back to false but that doesn’t change anything.

I’ll try to explain a bit better what I am experiencing.

I have two iPhones with owntracks installed. My personal iPhone and my daughters one. My personal iPhone is sending updates correct and the location on both iPhones in the owntrack app is correct.
Then I can send several location updates from my daughter iPhone to MQTT and I see this immediately on my personal iPhone.
To speed up getting the error is that I now kill the own tracks application on my daughters iPhone.
I then start it again, I now see a counter running in red on the friend button and when I now check the location of my daughters iPhone it has sended an invalid location to mqtt. When I check the timestamp in this message it is in the future. If I now manually send a new location update it has the correct location and timestamp in the message but it is not being shown on the friends tab on both iPhones. Maybe because of the previous message with timestamp in the future but where does that come from??

In the mean time I did a clean install of Mosquitto so I am absolutely sure there are no retained messages there anymore that can ruin things.

Hope this gives some more info of what I am seeing.

Thanks


Met vriendelijke groet, Peter Lindeman

**Comment by peterlindeman** [comment]
I now even removed the app completely from her iPhone. Installed it again from the AppStore, Airdropped the configuration file from my Mac to her iPhone to get the correct configuration in. On MQTT there was not even a retained topic of her location yet and the record with the wrong time does already popped up on her phone.

**Comment by ckrey** [comment]
The app displays the most recent location based on timestamp. This explains why a location with  "wrong" timestamp in the future will never get overwritten by subsequent "correct" location messages.

No, there is no data left behind when the app is removed. 

You may share the location message with the "wrong" timestamp with us, it may contain a hint.

**Comment by ckrey** [comment]
What model of iPhone and iOS version does you daughter use?

**Comment by peterlindeman** [comment]
I will send it to the support email address due to privacy concerns.

Met vriendelijke groet, Peter Lindeman

**Comment by peterlindeman** [comment]
She has an iPhone SE 32Gb with iOS 13.3.1

Met vriendelijke groet, Peter Lindeman

**Comment by ckrey** [comment]
I use an iPhone SE 64Gb with iOS 13.3.1, no problem

**Comment by jpmens** [comment]
@peterlindeman FYI we've not yet received the location message at the support address.

**Comment by peterlindeman** [comment]
@jpmens  I just sended two packages to the support address. Thanks

**Comment by ckrey** [comment]
Would you double check

- under `Settings/Privacy/Locationservices` if access for OwnTracks is set to "Always".
- what is the current time on the device
-  which accuracy is displayed on the device

<img width="411" alt="Screenshot 2020-03-13 at 16 10 04" src="https://user-images.githubusercontent.com/4027289/76633612-47349a80-6545-11ea-9ace-eec65ac75fc7.png">

We have never seen a location timestamp for the future before
`1584118070 translates into, which is hours ahead Fri Mar 13 17:47:50 CET 2020`

The app relies on the operating system delivering correct location data

**Comment by peterlindeman** [comment]
1. Owntracks is set to Always for location services.
2. Current time Friday March 13 16:17 (Amsterdam timezone)
3. I’m now inside the house and it says here +/-10m (blue dot a bit moving on the screen)


I now manually sended the location to mqtt and now I see an updated MQTT record with correct timestamp but it does not reflect in the app. I will send it separate to the support address

**Comment by ckrey** [comment]
Yes, it does not reflect on the UI because the timestamp is older. Please try again after 17:47 today.

And if this does not help, please switch off and re-start the complete iPhone.

**Comment by peterlindeman** [comment]
It seems that the occurred problem is related to the fact that my girl sometimes changes here clock of the iPhone to circumvate screen time. There is a bug in iOS that you can't block a child to update the clock or timezone and through this they can circumvate rules set up on the phone. Reported this already long ago but Apple won't fix it ;-(

It would be nice if an invalid date/time has been used this somehow can be overwritten with the correct one. For some reason the incorrect value is stored somewhere and you have to wait until that time has passed.

**Comment by jpmens** [comment]
Trust me: it's not possible to conquer the cleverness of children which is why I've never even tried to and never limited things like this.

Furthermore it's impossible to tell what a "correct time" is. 

In other words: no. The program works well and we will not invest time in doing this.
