### ISSUE TITLE
Map pins

### ISSUE THREAD

**Issue by Sawadee2u** [owntracks/ios#631]
How to remove map location pins?

**Comment by jpmens** [comment]
Go to the list of regions and swipe left on the region you wish to delete and confirm deletion.

**Comment by Sawadee2u** [comment]
Thank you very much. Driving me nuts.

* * * * * * * * * * * * * * * * * * * * * * *
“Beer is Proof that God Loves Us and Wants Us to Be Happy"  Benjamin Franklin
* * * * * * * * * * * * * * * * * * * * * * *
