### ISSUE TITLE
Friends no longer visible

### ISSUE THREAD

**Issue by FPPMvB** [owntracks/ios#632]
Hi,
I cannot longer see the location ofmy friends and vice versa. We bothatemaking use of the sam cloudmqtt account and can track out iwn location, but cannot share this anymkre with each other.
Regions can only be shared through exporting the waypoints
Any sollution?

**Comment by ckrey** [comment]
If you cannot **longer** see your friends locations **anymore**, you probably changed your setup

**Comment by FPPMvB** [comment]
Thanks for the reply, setup hasn’t changed, only a new iPhone but kept the same setup.
My Homey however is still receiving all the information (friends and regions) so the setup still seens to be ok

**Comment by jpmens** [comment]
Is the old phone still in operation with the same configuration? In that case you would have two phones with identical client IDs; this is not permitted.

**Comment by FPPMvB** [comment]
No old iPhone is completly whiped

**Comment by FPPMvB** [comment]
Also cloud mqtt serms to be working correct so any ideas ? Annybody....?

**Comment by ckrey** [comment]
Did you resolve your cloud mqtt problem?

**Comment by ckrey** [comment]
No reaction
