### ISSUE TITLE
Crash on delete friend

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#635]
Happened twice: crash on swipe left then delete on a friend. 

OwnTracks 13.1.7 on iOS 13.4.1 iPhone 7

**Comment by ckrey** [comment]
I cannot find a corresponding crash log in the app store.

Do you have "Settings/Privacy/Analytics&Improvements/Share Wit App Developers" enabled on your device?

**Comment by jpmens** [comment]
I do yes, but can no longer reproduce. Closing for now.
