### ISSUE TITLE
cloudmqtt smash by owntrack messages

### ISSUE THREAD

**Issue by Lanzones** [owntracks/ios#637]
I have previously updated the ios of my iphonexs. now my cloudmqtt is smash with data coming from my iPhone.. Five messages comes every seconds.. do you guys know what is the reason for this?
![image](https://user-images.githubusercontent.com/43723964/85530521-59000080-b651-11ea-9475-27fb35e8b20f.png)

**Comment by ckrey** [comment]
What kind of update did you do? Seems the connection is interrupted after 7 messages. The app then reconnects and retries to re-send the un-acknowledged messages.

You may want to reboot/re-install owntracks on your phones (save the config before)

**Comment by Lanzones** [comment]
It works.. 🙏🏿
