### ISSUE TITLE
ed25519 certificates

### ISSUE THREAD

**Issue by hanche** [owntracks/ios#639]
Is it possible to use ed25519 certificates with the iOS client?

I ask because I tried it, and couldn't get it to work. If the answer is yes, I'll come back with more details on what I tried; if the answer is no, then I'll just go for rsa keys instead.

Basically, the just tells me “TLS Client Certificate / incorrect file or passphrase” when I try it, which is not specific enough to tell me whether I just made some silly mistake, or if I am trying to do something impossible.

The mosquitto server and accompanying clients handle ed25519 certs (both server and client) just fine.

**Comment by jpmens** [comment]
The `incorrect file` message sounds as though there's no support in iOS for ED25519, but I've not tried it yet. To be honest, I don't have a version of OpenSSL at hand which can even create the keys.

What might be related: please remember that Apple has strongly cut down on the certificate validity -- if your self-signed cert is valid for more than 825 days it won't be accepted by the operating system ([more](https://support.apple.com/en-us/HT210176))

**Comment by jpmens** [comment]
I've created an appropriate certificate:

```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            72:d0:c2:46:cf:f7:5b:31:85:ce:97:e4:82:29:48:c0:a9:58:ed:6b
        Signature Algorithm: ED25519
        Issuer: C = DE, CN = www.example.com
        Validity
            Not Before: Jul 10 16:10:42 2020 GMT
            Not After : Jun 10 16:10:42 2022 GMT
        Subject: C = DE, CN = www.example.com
        Subject Public Key Info:
            Public Key Algorithm: ED25519
                ED25519 Public-Key:
                pub:
                    af:07:34:cf:01:30:7d:96:27:31:bd:8b:00:8c:0a:
                    db:d6:d0:7c:ef:4f:4f:cc:e5:08:75:52:17:d9:c8:
                    78:b4
    Signature Algorithm: ED25519
         d3:66:fb:d6:41:54:4a:62:0a:af:85:49:72:e9:bb:b7:12:a8:
         c6:93:37:82:6a:d2:3f:54:18:02:c5:1c:84:9a:03:ed:64:02:
         85:ad:78:c6:a0:1d:23:45:8a:46:2f:4e:a5:df:5e:19:5d:b8:
         f1:6a:fe:cc:c2:79:e2:e9:3c:07
-----BEGIN CERTIFICATE-----
MIIBCDCBuwIUctDCRs/3WzGFzpfkgilIwKlY7WswBQYDK2VwMCcxCzAJBgNVBAYT
AkRFMRgwFgYDVQQDDA93d3cuZXhhbXBsZS5jb20wHhcNMjAwNzEwMTYxMDQyWhcN
MjIwNjEwMTYxMDQyWjAnMQswCQYDVQQGEwJERTEYMBYGA1UEAwwPd3d3LmV4YW1w
bGUuY29tMCowBQYDK2VwAyEArwc0zwEwfZYnMb2LAIwK29bQfO9PT8zlCHVSF9nI
eLQwBQYDK2VwA0EA02b71kFUSmIKr4VJcum7txKoxpM3gmrSP1QYAsUchJoD7WQC
ha14xqAdI0WKRi9Opd9eGV248Wr+zMJ54uk8Bw==
-----END CERTIFICATE-----
```

and have imported that into the iPhone:

![rabbit-6503](https://user-images.githubusercontent.com/60706/87175871-8dbeb980-c2d9-11ea-8925-1a5874a610e7.png)

so that at least works. I can't actually test this at the moment.

FWIW, I created the certificate as follows:

```bash
$ openssl genpkey -algorithm ED25519 > example.com.key
$ openssl req -new -out example.com.csr -key example.com.key
$ openssl x509 -req -days 700 -in example.com.csr -signkey example.com.key -out example.com.crt
$ cat ex*.crt ex*.key > ex.pem
```

and mailed myself the concatenated PEM file.

**Comment by ckrey** [comment]
The error message “TLS Client Certificate / incorrect file or passphrase” means you are trying to import a client certificate.
The client certificate has to be in PKCS12 format. Please check https://owntracks.org/booklet/features/tlscert/#pkcs12

**Comment by hanche** [comment]
@jpmens Ah, that could be it. I had a longer expiry on my self-signed CA cert. I think it's a bit odd that this did not cause an issue when I imported it, but it could well be the cause of the problem. Also, I note this requirement:

> TLS server certificates must contain an ExtendedKeyUsage (EKU) extension containing the id-kp-serverAuth OID.

Now I have to figure out what _that_ means, and work out how to achieve it before I proceed. There seems to be some good advice here:

http://blog.nashcom.de/nashcomblog.nsf/dx/more-strict-server-certificate-handling-in-ios-13-macos-10.15.htm?opendocument&comments

Also, the certificate you created with a `.pem` extension would be imported into the system, right? But don't you have to give it a `.otrp` extension so that OpenTracks will get it?

@ckrey Yes, I did read that section and created the pkcs12 format file accordingly.

I'll try to figure out how to make a self signed CA cert that iOS will be happy with before testing further.

Thanks to both of you for your quick response!

**Comment by hanche** [comment]
A couple hours later, I have no luck.

I was wrong about cert expiration: It is only my self signed CA certificate that had a long validity, but that shouldn't be a problem. The server cert was fine, except it lacked the required extension. I have fixed that.

FWIW, this is how I do it for the client (some personal info elided, marked by <…>; ⬥ is my shell prompt):

```
⬥ cat hanche.config
[ req ]
prompt = no
distinguished_name = req_distinguished_name

[ req_distinguished_name ]
C   = NO
L   = Trondheim
O   = NTNU
OU  = math
CN  = hanche
emailAddress = <my full email address>
⬥ u = hanche
⬥ openssl req -new -config $u.config -key $u.key -out $u.csr
⬥ openssl x509 -req -days 365 -in $u.csr -CA ca.crt -CAkey ca.key -out $u.crt
Signature ok
subject=C = NO, L = Trondheim, O = NTNU, OU = math, CN = hanche, emailAddress = <my full email address>
Getting CA Private Key
⬥ openssl pkcs12 -export -in $u.crt -inkey $u.key -out $u.otrp
Enter Export Password:
Verifying - Enter Export Password:
```

Then I transfer `hanche.otrp` to the iphone with airdrop, where OwnTracks grabs it and then rejects it.

**Comment by hanche** [comment]
Oops, I forgot to add that I had neglected the extensions. So I did it again:

```
⬥ cat client.config
[ cliext ]
basicConstraints        = critical,CA:false
subjectAltName          = email:copy
nsCertType              = client,email
extendedKeyUsage        = clientAuth,emailProtection
keyUsage                = digitalSignature, keyEncipherment, keyAgreement
nsComment               = "Client Broker Certificate"
subjectKeyIdentifier    = hash
authorityKeyIdentifier  = keyid,issuer:always
⬥ openssl x509 -req -days 365 -in $u.csr -CA ca.crt -CAkey ca.key -extfile client.config -extensions cliext -out $u.crt
```

after which I ran `openssl x509 …` once more. That did not help.

**Comment by ckrey** [comment]
I can confirm OwnTracks is not able to open PKCS12 files with ED25519 keys.

Your config files with RSA keys do work.

OwnTracks uses the following library function:
https://developer.apple.com/documentation/security/1396915-secpkcs12import

No Idea what the problem is or when and how this can be solved.

**Comment by hanche** [comment]
@ckrey Thanks for clearing that up! RSA keys it is, then. Until you find a way to support ed25519 key, if possible. But I understand if it's a relatively low priority. I wanted it primarily to save on bandwidth, but I suppose the bandwidth requirements are modest even with RSA.
