### ISSUE TITLE
Can't get OwnTracks to show up in Home Assistant after reinstall

### ISSUE THREAD

**Issue by unikitty37** [owntracks/ios#640]
I had to reinstall Home Assistant, and am currently reconfiguring it, but I can't get owntracks to show up.

I've installed the OwnTracks integration, and set the iOS app in HTTP mode, with the URL of my HA instance, the encryption key, my username, and a long-lived access token (as I'm using 2FA on HA).

The status in OwnTracks is "idle", but it doesn't show up in HA using the default dashboard.

I tried uninstalling and reinstalling OwnTracks, thinking it might still be holding on to some old config, but repeating the process didn't help at all.

Additionally, if I now go to Integrations in HA, instead of the expected "1 device and 1 entity" against OwnTracks, I see "2 devices and 2 entities". The first device has the wrong entity_id (and is presumably from before I uninstalled/reinstalled the app) but HA won't let me delete or disable it.

Please could somebody show me how I can get Home Assistant to successfully show OwnTracks iOS as a device tracker? Has something changed in HA recently that's causing problems?

**Comment by jpmens** [comment]
Closing as duplicate of https://github.com/owntracks/talk/issues/95

**Comment by unikitty37** [comment]
This isn't a duplicate — Home Assistant has shown the popup with the details, and I have entered the details into the iOS app. In the referenced issue, the OP wasn't getting that popup at all.

What *isn't* happening here is any data from OwnTracks appearing in Home Assistant.

**Comment by jpmens** [comment]
Nevertheless this seems to be a Home Assistant issue. The only way we can help you is if you configure an MQTT or HTTP endpoint you control and can demonstrate to us with the configuration that your data is not leaving the device.

I think you rightly ask 

> Has something changed in HA recently that's causing problems?

which indicates the issue is not on the OwnTracks app side.

**Comment by unikitty37** [comment]
Thanks — it looks like the Home Assistant integration is provided by the Home Assistant folks, so I'll head on over there…

**Comment by jpmens** [comment]
Good luck, and if you do find a solution, you might like to add this here for posterity.
