### ISSUE TITLE
sending old timesttamp in location messages

### ISSUE THREAD

**Issue by sanjeshpathak** [owntracks/ios#641]
I am running it on iPhone 6 and owntracks version 13.1.7.

My phone is not moving and stationery. Owntracks occasionally sends the location message, but it sends with the same old timestamp. Looks like it is not updating the timestamp to the current time when sending the location message in this scenario.

**Comment by jpmens** [comment]
This was [changed quite a while ago](https://github.com/owntracks/ios/issues/197) to include current timestamp (`tst`) on publishes. Can  you please indicate the JSON's `t` for which you are seeing that?

**Comment by sanjeshpathak** [comment]
The JSON's t  value is t.

**Comment by sanjeshpathak** [comment]
Here is some additional information I found:

1) Owntracks is sending JSONs with t's value as t with old/same timestamp
2) Once in a while it sends JSON with t value as p with a new timestamp. I did not check the accuracy of the timestamp but can confirm that this timestamp is greater than what is sent in 1) and also the timestamp value is increasing with each subsequent messages with t's value as p

**Comment by sanjeshpathak** [comment]
jpmens,

Any update on this?

I have owntracks installed on an Android phone. It is working fine. Although on rare occasions I do see a subsequent message come with same timestamp as a previous message. It happens, but rare. But it is ok.

I am storing the location data into a database and tst value is one of the primary keys. So in the case of iOS devices I am constantly getting primary key violation error from my database. That is the problem for me.

Sanjesh
[https://mygps.co.in](https://mygps.co.in)

**Comment by jpmens** [comment]
Using `tst` as a primary key is maybe not the best idea as in theory more than one publishes can be transmitted within a second.

**Comment by sanjeshpathak** [comment]
In that case tst should be sent in milliseconds.

**Comment by jpmens** [comment]
We have no reason to change that.

**Comment by sanjeshpathak** [comment]
I am not asking you change that. All I am asking is to send the correct timestamp.

**Comment by jpmens** [comment]
> should be sent in milliseconds

That sounded different to me. I must have misunderstood.

As to the actual issue you reported you'll have to wait until we can investigate this more closely.

**Comment by sanjeshpathak** [comment]
I can wait. Thank you very much.

**Comment by ckrey** [comment]
As the [booklet](https://owntracks.org/booklet/tech/json/) says, 

> `tst` UNIX epoch timestamp in seconds of the location fix

If the operating system does not deliver a new location to the app, `tst` will not change. But in Move Mode, a new location will be transmitted with `"t": "t"`.

**Comment by sanjeshpathak** [comment]
That's fine.
