### ISSUE TITLE
NSOSStatusErrorDomain -9829

### ISSUE THREAD

**Issue by hanche** [owntracks/ios#642]
It seems that every time I leave home, work, or some other place with wifi access (or possibly everytime my network connection changes), OwnTracks loses its connection to the server, a badge count starts going up on the app icon, and the status is shown as:

`idle NSOSStatusErrorDomain -9829 The operation couldn't be completed. (OSStatus error -9829.) { "_kCFStreamErrorCodeKey" = "-9829";
`

Merely going into Settings, not even touching anything there, cures the problem temporarily.

Here is a typical excerpt from the mosquitto log (IP address elided). Most new connections seem to end this way, but as I stated, when I go into Settings, it connects successfully.

```
20200822_094325: New connection from IP on port 8883.
20200822_094325: OpenSSL Error: error:1417C0C7:SSL routines:tls_process_client_certificate:peer did not return a certificate
20200822_094325: Socket error on client <unknown>, disconnecting.
```
I am running the latest OwnTracks (13.1.7, 8 months old?) in MQTT mode with TLS enabled.
Exported config file attached (hostname faked and waypoints removed, otherwise, it is the real thing).

[config.otrc.txt](https://github.com/owntracks/ios/files/5112130/config.otrc.txt)

Any ideas what could be wrong?

**Comment by ckrey** [comment]
This is an already known problem #605, which will be probably be solved in the upcoming version (minimum OS requirement is iOS 13). I will send you @hanche an invite to pre-test this version.

Closing this issue
