### ISSUE TITLE
Occasional connection issues introduced with 13.3.5?

### ISSUE THREAD

**Issue by brummbrum** [owntracks/ios#643]
Coming from 13.1.7 using TLS. Connections worked robustly, using trusted CA certificate & server certificate in compliance with Apple requirements as per https://support.apple.com/en-us/HT210176
My server certificate has a validity of 824 days and was issued before Sept 1, 2020.

However, in the new app 13.3.5 there are occasionally connection problems. Status is shown as "connecting". This can be resolved by going into the app settings which seemingly triggers a new sequence of connection attempts, which then succeed to connect. I have not found a way to reliably reproduce the issue - it happens occasionally and I never noticed the problem with 13.1.7.

=> Wondering if anybody else has run into this with the latest update?

PS: I doubt that it is related to this latest Apple requirements https://support.apple.com/en-us/HT211025 which requires server certificates to have a validity of max 398 days as it would only apply to those signed by with iOS pre-installed root CAs (not the case here - we are using our own CA) and server certificates issued after Sep 1.

**Comment by ckrey** [comment]
The network layer was completely replaces by Apple's NSURLSession in 13.3.5

To clarify: Are you using a self-signed certificate and you installed and trusted the CA cert on your phone? Do you use client certificates?

**Comment by brummbrum** [comment]
Hi Christoph,

To your questions:
Yes, self signed certificate, installed and trusted.
No client certificate (just server which is compliant with Apple's requirements).

However, I have a hunch it is actually unrelated to the whole TLS setup.

While I have not been able to reliably reproduce the problem it happens from time to time with a particular iPhone. Another iPhone does not show the problem so far. They use different cellular carriers. My impression is that it happens when the carrier coverage is weak in an area and the phone cannot connect or while the connection is established the cell coverage breaks. In these instances it seems that the app is not able to recover the connection by itself in the background, i.e. when cellular coverage is good again (or even when returning to the home base with Wifi available) the app still does not reconnect by itself in the background. It takes the user to bring the app into the foreground and fiddle with the settings. Then it immediately reconnects and published all the positions that have been waiting in queue. But obviously this does not solve the problem that live tracking does not work when the connection breaks and the user does not even know.

It seems that the app somehow gets stuck in the background once the connection gets lost. Again, it still records and queues the positions locally on the phone but does not publish them to the broker while running in the background. It is almost as if it stayed in an endless "connecting" loop rather than trying to fully reconnect as it does when you bring the app into the foreground and got to settings.

**Comment by ckrey** [comment]
Good news: I was able to reproduce the problem. It occurs if the broker/server does not respond to the CONNACK message and does not close the connection either.
I added a connect timeout which solves the problem.
@brummbrum if you drop me your email, I will invite you to beta test in TestFlight

**Comment by brummbrum** [comment]
Thanks, just shot you an email.

**Comment by ckrey** [comment]
fixed in versions >= 13.3.6
