### ISSUE TITLE
iPhone X reports with very bad accuracy

### ISSUE THREAD

**Issue by sknsean** [owntracks/ios#644]
My iPhone X is reporting location updates with very low accuracy:
`{"cog":0,"batt":97,"lon":10.000000,"acc":2500,"p":101.587,"bs":1,"vel":0,"SSID":"xxxx","BSSID":"fc:ec:dd:15:d0:38","vac":2,"lat":56.300000,"conn":"w","tst":1600185158,"alt":55,"_type":"location","tid":"er"}`
It's fixed at 2500m

It have been working fine for a very long time:) Wife's iPhone XR with seemingly the same settings reports with maximum accuracy of around 200-400m.

Am I missing something?

**Comment by ckrey** [comment]
are you running iOS 14? Do you have limited location accuracy? Please check Settings/Privacy/Location/Owntracks

**Comment by sknsean** [comment]
iOS 13.7
Owntracks is set to `Always`

**Comment by ckrey** [comment]
OwnTracks displays the current accuracy reported by iOS in the top right. Please check the accuracy with the Maps app or Google Maps.
Check which accuracy you get when you switch off Wifi. Did you exchange your Wifi Access Point and it is not yet in the Wifi Location Database (iOS uses GPS, Wifi, or Cell Towers to determine location)?


<img width="109" alt="Screenshot 2020-09-16 at 12 16 16" src="https://user-images.githubusercontent.com/4027289/93324637-77bc0080-f816-11ea-991a-f2f45e606188.png">

**Comment by sknsean** [comment]
Accuracy is hovering +-7m - +-65 m :) So it's fine when the app is open...
Same with WiFi off...
No i havn't changed anything in my setup.
I had a 20km trip where I did leave the phone on the dash with the screen off, every update had a accuracy of 2500m

**Comment by sknsean** [comment]
Updated to iOS 14 last night...
`{"batt":34,"lon":10.000000,"acc":65,"bs":1,"p":102.195,"vac":10,"lat":56.00000,"conn":"m","tst":1600000949,"alt":57,"_type":"location","tid":"sn"}`
Looking much better today

**Comment by sknsean** [comment]
Guess it have been a bug in 13.7... It just have been working for since updating.

**Comment by ckrey** [comment]
Thanks for the feedback
