### ISSUE TITLE
Location stops updating after changing between cellular and WiFi

### ISSUE THREAD

**Issue by BBaoVanC** [owntracks/ios#645]
When switching from cellular to WiFi, OwnTracks stops publishing location to my MQTT broker, until I manually request an update (by publishing settings). This doesn't happen the other direction, when switching from WiFi to cellular.

**Comment by BBaoVanC** [comment]
By the way, the MQTT host I have set is accessible on the internet, through a host name I have. I'm using TLS and port 8883, websocket mode disabled n

**Comment by ckrey** [comment]
@BBaoVanC which monitoring mode do you use (Significant or Move)?

When an iPhone enters Wifi, iOS uses the Wifi fingerprint to determine the location. Then it will not change anymore while you are in Wifi.

Is this a possible explanation of your problem?
