### ISSUE TITLE
Flaky connection with 13.3.6

### ISSUE THREAD

**Issue by jue89** [owntracks/ios#647]
Thank you very much for your great tool! :)

Since version 13.3.6 I am observing flaky connections. The connection to the Broker is established via websockets/TLS protected by a valid Let's Encrypt certificate. I am authenticating myself with username and password.

The status is jumping between "Idle" and "Connecting" within seconds. The broker statistics show that the count of sent CONNECT and CONNACK is increasing but no DISCONNECT packets are sent.

Is someone observing the same effect? Can I do something to support debugging?

**Comment by ckrey** [comment]
@jue we don't see any problems with mosquitto 1.6.12 behind apache2 proxy. What is your broker toolchain?

**Comment by jue89** [comment]
Im using EMQ as broker and the NodeJS module [http-proxy](https://www.npmjs.com/package/http-proxy) together with the NodeJS built-in HTTPS server.

The problems arose after updating to 13.3.6. Could it be an interference with #643?

**Comment by ckrey** [comment]
The timeout introduced in #643 is the same as the Keepalive interval. Do you use a non-default Keepalive interval (default = 60)?

**Comment by jue89** [comment]
No, I'm using the default timeout. I haven't touched my setting during the last two years ;)

**Comment by ckrey** [comment]
@jue89 did you resolve the problem? Otherwise, do you have a broker log?

**Comment by jue89** [comment]
I switched to HTTPS und build a HTTP to MQTT bridge. That works flawlessly.

The broker log wasn't really helpful. It just reported that my iPhone was connecting and disconnecting over and over again.
