### ISSUE TITLE
How to remove a client certificate?

### ISSUE THREAD

**Issue by windsource** [owntracks/ios#648]
I was using the owntrack ios app with client certificates before. Now I switched to TLS with user and password authentication so I do not need the client certificate anymore.
In the list of client certificates I was able to remove it but in the "Settings" View it still shows "Filename: client-owntrack2.otrp" but the file does not exist anymore.
Now the app shows the error message "TLS Client Certificate, incorrect file or passphrase". The app is able to connect to my MQTT broker using user and password but the error message is a little bit anoying. Is it possible to tell the app that it should not use or look for a client certificate anymore?

**Comment by jpmens** [comment]
@windsource can you not backspace it away in the Settings panel?

**Comment by windsource** [comment]
I tried lots of methods and did not find a working one. In the view with "Filename, Passphrase, Allow Untrusted Certificates" the Filename still shows the file. When I click on that entry I see the next screen with the list of client certificates but it is empty now. So I cannot select from an empty list. And the error is shown with every action.

**Comment by jpmens** [comment]
What will likely work but is a bit hacky is to export your settings, edit out those particular settings from the `.OTRC` file and re-import. If you feel comfortable doing that, go ahead. Otherwise we'll have to wait see what idea @ckrey has for this.

**Comment by ckrey** [comment]
correct, you can unselect a certificate file while it is still there.
If you deleted the file, you cannot unselect it.

Either follow the suggestion by @jpmens  or delete the app and setup the parameters from scratch.

**Comment by windsource** [comment]
Thanks, I have exported the settings and imported the modfied settings and it worked well.

**Comment by jpmens** [comment]
Glad you got it fixed; thanks for reporting back!

**Comment by ckrey** [comment]
find a way in the UI to remove client certificate setting if the certificate is no longer installed

**Comment by ckrey** [comment]
![IMG_55FA017CC000-1](https://user-images.githubusercontent.com/4027289/146927842-0a415b96-d5bc-455b-8ab6-e30e162a9ed3.jpeg)
