### ISSUE TITLE
OT dos/can not push data to NAS broker...

### ISSUE THREAD

**Issue by backslashgithub** [owntracks/ios#651]
Hi , i'am using OT on my iPhone 7 ios 14.0.1 (always location on)  and mqtt broker Mosquitto 1.6.12.-11 on my syn. NAS to publish to Homey ( domotica) when i enter en leave waypoints. The problem is that OT dos not push the date when i'm on move and iphone sleeps. When i do it myzelf and push for publish then it works and sends data to broker and Homey (domotica) en works the flow to send message with Telegram back to my iPhone. edit: last lini does not always works. Yesterday i was driving in my car and de iphone was all of the time in a wake. The regions in OT collered from blue to red. but it was not pusched to the broker and Homey app :-(

Edit; i changed the broker i'm using. replacing mosquitto broker synology with MQTT Broker for Homey. Testing if this made a diverance and how ios tells OT that it is moving in sleep state. Later i test it with the MQTT Broker for Homey again.

**Comment by ckrey** [comment]
Please tell us which move mode you use

<img width="346" alt="Screenshot 2020-10-25 at 14 42 30" src="https://user-images.githubusercontent.com/4027289/97108831-55988680-16d0-11eb-98b2-0e2ebfd9203d.png">

**Comment by backslashgithub** [comment]
Hey ckrey, i use the Quiet mode, i read about it it is saving the battery

**Comment by jpmens** [comment]
@backslashgithub if you look at [our Booklet](https://owntracks.org/booklet/features/location/) you will see that in `Quiet` mode no publishes are emitted by default:

> The user has to publish the current location explicitly via the UI.

that is the reason you're not getting data.

I recommend you set the app to _Significant changes_ whereupon I think you'll see it does what you need.

**Comment by ckrey** [comment]
If you use Quiet mode, you should not be surprised if you receive no automatic updates.

Please read: https://owntracks.org/booklet/features/location/

And try Significant mode.

**Comment by backslashgithub** [comment]
thanks for the quick respons, changed to significant mode. thats why it is in the Quiet mode easy for the battery :-)

want to test the new setting mode, but i can test it thrue pressing the UI button on the top right of the screen and make a flow that takes this up en let it send a message.

**Comment by backslashgithub** [comment]
> If you use Quiet mode, you should not be surprised if you receive no automatic updates.
> 
> Please read: https://owntracks.org/booklet/features/location/
> 
> And try Significant mode.

Yeah maybee better i read it now entirely :-) i already see there is a difrance between ios and android

**Comment by jpmens** [comment]
There should  be no functional difference between our Android and iOS apps with regard to this setting; users have to hit the _publish_ button on both platforms in Quiet mode.

**Comment by growse** [comment]
*Wondering if there's a lurking difference between Android and iOS that's actually a bug somewhere*

> > If you use Quiet mode, you should not be surprised if you receive no automatic updates.
> > Please read: https://owntracks.org/booklet/features/location/
> > And try Significant mode.
> 
> Yeah maybee better i read it now entirely :-) i already see there is a difrance between ios and android

Do you see Android behaving differently in quiet mode?

**Comment by backslashgithub** [comment]
> Do you see Android behaving differently in quiet mode?

I'm using only ios, i ment diverance  in the manual ios vs Android

**Comment by ckrey** [comment]
I assume this question to be answered
