### ISSUE TITLE
Anyway not to send Lon,lat if ibeacon?

### ISSUE THREAD

**Issue by goldriver2** [owntracks/ios#652]
Anyway not to send Lon,lat on ibeacon change on iOS ?

**Comment by ckrey** [comment]
The whole idea of monitoring iBeacons in the OwnTracks iOS app is to trigger location data to be sent. 
I think I don't understand your use case or problem?

**Comment by goldriver2** [comment]
Le lun. 16 nov. 2020 à 11:11, Christoph Krey <notifications@github.com> a
écrit :

**Comment by goldriver2** [comment]
I am using OwnTracks to send my iPhone presence detection when I enter a
room. On my automated system all I need to know is the uuid minor major to
know in which room I am.

I am using the location (long,lat) only to know if I am away from home

Le lun. 16 nov. 2020 à 11:11, Christoph Krey <notifications@github.com> a
écrit :

**Comment by jpmens** [comment]
When we publish a change or a regios or a transition we publish the latitude and longitude with it; that's one of the main features of OwnTracks, and we don't think it is at all necessary to change this.

If, as in this case, you are not interested in lat/lon, then please just ignore it for your application. 

Closing with "it works as designed".
