### ISSUE TITLE
Publish queued on user request

### ISSUE THREAD

**Issue by thedoctor535** [owntracks/ios#653]
Hi has anybody had the issue when you push your location. You get a
“Publish queued on user request” notification. And nothing gets sent to the MQTT broker

**Comment by jpmens** [comment]
Yes.

How about you tell us a bit more so that we can help you? Which broker and version? What have you done to debug the issue? What do your broker logs say when you push a location? Does the configuration on your iPhone match that of the broker? What ACLs do you have on the broker?

**Comment by thedoctor535** [comment]
I’m using MQTTCloud and 13.3.6. It was working fine about two days ago

**Comment by jpmens** [comment]
It's likely the broker side. See if you can obtain logs for that (unlikely I assume), but maybe you'll be lucky.

**Comment by thedoctor535** [comment]
![Uploading AD8C2B70-E4BA-4646-A13C-BC72E05B0057.png…]()

**Comment by thedoctor535** [comment]
![Uploading 45D5E561-CC0E-4E47-A00B-DC202BD45A67.jpeg…]()

**Comment by ckrey** [comment]
Will you share your "Status Info" screen with us? It may show error codes

**Comment by thedoctor535** [comment]
![Uploading C7787C45-64E9-4947-ABE4-794789A5A642.jpeg…]()

**Comment by ckrey** [comment]
„connected“ is the status you are looking for. Please have a look st your broker log

**Comment by ckrey** [comment]
@thedoctor535 did you resolve your issue?

**Comment by thedoctor535** [comment]
Hi, 

To be honest I have scraped the project I was working on so due to a nine connected issue. I might pick up this project I. The new year

Kind Regards

Martin Norman
