### ISSUE TITLE
iOS Owntracks - loading a pem file

### ISSUE THREAD

**Issue by feyazbek** [owntracks/ios#655]
Hello, 

I would like to use Owntracks with MQTT. I am trying to load a certificate file that I have uploaded to my iPhone. For some reason, Owtracks app does not see it! 

![image](https://user-images.githubusercontent.com/58607338/102214030-ef620000-3ed7-11eb-9e22-1dc90516c283.png)

Can you please tell me what to do? 

Thanks, 
Emmanuel

**Comment by ckrey** [comment]
How did you upload the file? Did you open it with OwnTracks App?

**Comment by feyazbek** [comment]
Hello,

I have put the file in the “files” on my iphone. See the screenshot:

[cid:image001.png@01D6D45B.FA4A15C0]

But when opening Owntracks, Status info, settings, proto 4 TLS, Client Certificate, Filename I see no files….

So how to locate the file from Owntracks to be able to open it in the app?

Regards,
Emmanuel

_________________________________________________
 Emmanuel Yazbeck | Partner
 M: +32-485-668333
www: https://www.smcconsulting.be

**Comment by ckrey** [comment]
@feyazbek If you reply via mail, images are not shown here. Please upload the file in a browser.
- You have to "Open" the file.
- If it is a Client Certificate, it needs to have the extension `.otrp`and you will open it with OwnTracks

**Comment by ckrey** [comment]
@feyazbek did you resolve your issue?

**Comment by or-dodson** [comment]
Yes it did.
