### ISSUE TITLE
share waypoints with ios devices

### ISSUE THREAD

**Issue by stefan90403** [owntracks/ios#656]
Hello,

i want to share waypoints between my devices.
when i create a waypoint on my iphone and press "Publish Waypoints" in the settings, i can see these in the broker under 
owntracks/stefan/iphone/waypoints

But i'm not able to see these waypoints on my ipad. 
I have tried to subscribe in the settings

owntracks/#
owntracks/+/+/waypoints

beside the standard Topics. 
Is there anything i miss or did not understand? 

Regards, Stefan

**Comment by jpmens** [comment]
That’s an interesting use case; I don’t think it’s ever occurred to us. :-) 

The waypoints you publish are in configuration file format (`.otrc` file), and I don’t think our apps will actually process them unless they arrive in a [setWaypoints](https://owntracks.org/booklet/features/remoteconfig/ ) configuration command. 

As a short-term workaround, and if you are able to, a small subscriber which takes the `waypoints` payload rewraps it and publishes it back to the broker might do the trick.

**Comment by jpmens** [comment]
Alternatively you can export the waypoints into a `config.otrw` file and import that on your other devices. This is a manual operation, of course, and I have understood you’d like to automate it — just pointing it out as a matter of course.

**Comment by stefan90403** [comment]
Hi, when i publish waypoints, these are published in json format under for example 
/owntracks/stefan/iphone/waypoints

```
{
  "_type" : "waypoints",
  "waypoints" : [ {
    "_type" : "waypoint",
    "tst" : 1609972906,
    "lat" : 49.457622529824164,
    "lon" : 11.076585282877444,
    "rad" : 0,
    "desc" : "Center-1609972906"
  } ]
}
```

When i publish exactly this to 
/owntracks/stefan/ipad/waypoints
i would like to see these waypoints on my ipad..

**Comment by stefan90403** [comment]
In the docu there is a use case 

> Share your favorite places with your friends ("Best Sushi in Town")

And i did not understand how to do this only with the ios apps.

**Comment by jpmens** [comment]
> When i publish exactly this to `/owntracks/stefan/ipad/waypoints` i would like to see these waypoints on my ipad

As explained above, this is not possible out of the box because the JSON used during publish differs from what we expect when importing the data.

**Comment by jpmens** [comment]
If you are comfortable experimenting a bit, this code might do what you're seeking to do. The premise is we're going to subscribe via MQTT to the data published by your iPhone, modify it accordingly, and republish to your iPad.

You'll have to tweak the _topic_ names in `repubwaypoints.py` accordingly. Look for the string `jpm` and I think you'll see what to do.

I recommend you first set up a "virtual" Python environment:

```console
$ python3 -mvenv venv
$ source venv/bin/activate
(venv) $ pip install paho-mqtt
(venv) $ ./repubwaypoints.py
```

The program `repubwaypoints.py` itself:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import paho.mqtt.client as paho   # pip install paho-mqtt
import socket
import json
import os
import sys
import time

to_topic = "owntracks/jpm/s8/cmd"  # topic to publish _to_
hostname = "127.0.0.1"
auth = {
    "username" : "<username>",
    "password" : "<secret>"
}

def on_connect(mosq, userdata, flags, rc):
    # subscribe to iPhone waypoints topic; add as many as required
    mqttc.subscribe("owntracks/jpm/5s/waypoints", 0)

def on_message(mosq, userdata, msg):

    data = json.loads(msg.payload)
    wp_list = data["waypoints"]

    # workaround for an issue we're currently (2020-01-07) investigating ...
    new_list = []
    for wp in wp_list:
        if not wp["desc"].startswith("-*") and not wp["desc"] == "+forwardme":
            wp["tst"] = int(time.time())
            print("{tst} {desc} {lat} {lon}".format(**wp))
            time.sleep(1)
            new_list.append(wp)

    wp = {
        "_type"         : "cmd",
        "action"        : "setWaypoints",
        "waypoints"     : {
                "_type"     : "waypoints",
                "waypoints" : new_list,
            }
        }

    payload = json.dumps(wp)
    mqttc.publish(to_topic, payload, qos=1, retain=False)

def on_disconnect(mosq, userdata, rc):

    reasons = {
       '0' : 'Connection Accepted',
       '1' : 'Connection Refused: unacceptable protocol version',
       '2' : 'Connection Refused: identifier rejected',
       '3' : 'Connection Refused: server unavailable',
       '4' : 'Connection Refused: bad user name or password',
       '5' : 'Connection Refused: not authorized',
    }
    reason = reasons.get(rc, "code=%s" % rc)
    logging.debug("Disconnected: ", reason)

PROGRAM = os.path.basename(sys.argv[0]).split('.')[0]

mqttc = paho.Client(PROGRAM, clean_session=True, userdata=None, protocol=paho.MQTTv311)
mqttc.on_connect = on_connect
mqttc.on_disconnect = on_disconnect
mqttc.on_message = on_message

mqttc.username_pw_set(auth["username"], auth["password"])

mqttc.connect(hostname, 1883, 60)

while True:
    try:
        mqttc.loop_forever()
    except socket.error:
        print("MQTT server disconnected; sleeping")
        time.sleep(5)
    except KeyboardInterrupt:
        mqttc.disconnect()
        sys.exit(0)
    except:
        raise
```

**Comment by stefan90403** [comment]
@jpmens thanks! that helps a lot!!!!

**Comment by jpmens** [comment]
Please note that this behavior is about to change slightly. In order to uniquely identify a region created on the device, the JSON will have a region ID (`rid`) set on it. We've [documented the new behavior](https://owntracks.org/booklet/features/waypoints/), but it's not yet in the released apps. (For iOS this will likely be in our next version, on Android it might be a jiffy longer.)

**Comment by kfdm** [comment]
It took me a bit to find it in the docs here https://github.com/owntracks/booklet/commit/73fc311d82dcfa762fbf65edb7b141598e2a6830 though the docs say
```
`rid` Region ID _(iOS/Android, after January 2021)_
```

Is that going to be a UID? or some kind of hash? or something else ?

**Comment by jpmens** [comment]
It will be a kind of hash, the exact formula to be defined by the respective authors of our Android and iOS apps. If you intend publishing your own, you can use a GUUID or whatever you please.

**Comment by rossbates** [comment]
I know this issue is closed but it seems the most appropriate thread to ask. Is there any way to import waypoints other than `setConfiguration` on an mqqt endpoint?

https://owntracks.org/booklet/features/remoteconfig/

My backend is http and want to know if I can backup/restore waypoints in the iOS app. Thanks!

**Comment by jpmens** [comment]
It is generally NOT appropriate to ask a question on a thread which has been closed for three years...

Import via setCofniguration. export via "export" in the settings.

**Comment by jpmens** [comment]
cmd/setWaypoints (not setconfig)

**Comment by rossbates** [comment]
Apologies for resurrecting an old thread. The alternative would have been opening a new issue, which linked to this issue, the result being 2 separate issues talking about the same thing.

You had previously mentioned `cmd/setWaypoints` as a way of sending waypoints to a client, the reason for my question was to find out if there was an https equivalent in the app to _get_ waypoints. It's not mentioned in the documentation, so at this point I'll assume it's not possible.

While the export function works to create a `config.otrw`, the app no longer appears to be able act as a handler for .otrc or .otrw files. Also, `Publish Waypoints` works over https to receive waypoints from a client. Getting waypoints out is not an issue, there just doesn't appear to be a way to get them back in other then MQQT.

Appreciate your response. I'll look for other workarounds.
