### ISSUE TITLE
regions are changing - is this a bug ?

### ISSUE THREAD

**Issue by steuerzentrale** [owntracks/ios#657]
Hi community

First of all many thanks for this app! I am trying to setup presence detecion with Owntracks and iBeacons in conjunction with Home Assistant.

**What I have done so far in Owntracks**
- created a region called -home
-  added UUID of my iBeacons to the region
-  circular region -1 which sends location updates to HASS
- location updates via webhook (not MQTT)

The app recognizes entries/leaves very reliable once I connect or disconnect with the beacons.

**the issues**
- the longitude and latitude of the regions are changing

**detailed explanation**
I created a region with a longitude of 48.518976 and latitude 9.549859 (just an example) and Owntracks changed them to
48.518865 and 9.549767 after a while.

Is this behaviour intended or maybe a bug? I expect that the regions longitude and latitude should stay as I have entered the coordinates. I know its not a big change but I want to understand the behaviour and make sure that it works well my home zone I have created in Home Assistant.

Kind regards from Switzerland

Andrew

**Comment by ckrey** [comment]
This is the intended behavior see https://owntracks.org/booklet/features/beacons/#ibeacons

If you dont‘t want the coordinate to be updated, use 0 (zero) for radius on iBeacons

**Comment by steuerzentrale** [comment]
many thanks for your quick reply, really appreciate that. Maybe I am misunderstanding something. My goal is to define a region (with **fixed coordinates**) with the beacons where Owntracks **sends updates** once I left the region. As per my understanding I have to define this behaviour with the radius set to -1 rather than 0. I could not find any info in the Owntracks booklet.

could you please explain how (if) I can achieve to have entry/leave updates but the region is fixed. sorry for repeated question.

**Comment by steuerzentrale** [comment]
just checked it with radius 0 and it sends updates. please ignore my recent question and again, many thanks!
