### ISSUE TITLE
Disable export settings

### ISSUE THREAD

**Issue by RogierQ** [owntracks/ios#658]
Is it possible to disable the export settings function?
I want to make a simple game with it but now the players can see / read my mqtt credentials.
Tried the "lock" to true but the i button then still show the screen with settings and options

Is it possible to disable more functionality? Controlled by the configuration file?

But most important, amazing app with great documentation!! Thanks!!

**Comment by jpmens** [comment]
That is currently not possible. 

But do tell us more about your "game"? What does it do and how does it work?

**Comment by jpmens** [comment]
As discussed privately, this is not possible. 
Closing.
