### ISSUE TITLE
Steps reporting topic changed?

### ISSUE THREAD

**Issue by martinlindjarv** [owntracks/ios#660]
I can't be sure but it might be that update changed steps reporting topic...

But last /steps topic got logged in 24.01 and after that it's not reported to steps topic ...

Jan 23 13:56:17 owntracks/home_mosquitto/martin_phone/step {"from":1611266400,"tst":1611402977,"steps
Jan 24 00:34:45 owntracks/home_mosquitto/martin_phone/step {"from":1611352800,"tst":1611441285,"steps
Jan 25 13:21:44 owntracks/home_mosquitto/martin_phone {"from":1611439200,"tst":1611573704,"steps":180
Jan 25 17:41:00 owntracks/home_mosquitto/martin_phone {"from":1611525600,"tst":1611589261,"steps":122
Jan 25 17:44:24 owntracks/home_mosquitto/martin_phone {"from":1611525600,"tst":1611589464,"steps":122

I coudn't find anything from "what's new" that could change behavior ...

Do i have to chenge my code or it qualifies as bug?

**Comment by jpmens** [comment]
Well spotted: I think you're right, I see the same when checking my logs.

**Comment by martinlindjarv** [comment]
As i was forced to rewrite my "steps counter" in hopenhab from mqtt1 -> mqtt2 i got an idea how to "temporarily overcome this problem" :)
As mqtt2 uses channels i defined new channel that finds word "steps" from topic and then takes steps from json :)

I did have to define secondary channel like and got it working until bugfix get's into app:
Type number : yesterday_steps_temp    [ stateTopic="owntracks/home_mosquitto/martin_phone", transformationPattern="REGEX:(.*steps.*)∩JSONPATH:$.steps" ]

**Comment by martinlindjarv** [comment]
> Well spotted: I think you're right, I see the same when checking my logs.

If you plan to make same kind of workaround to mqttwarn - i'd be happy if you can share it :)

**Comment by ckrey** [comment]
Oh! Never change a running system...

**Comment by ckrey** [comment]
Will be fixed in 14.0.3

**Comment by jpmens** [comment]
@ckrey on line 1192 in that patch I see the string "/step" (singular); shouldn't that be "/steps" (plural)?

**Comment by martinlindjarv** [comment]
@jpmens i think it should be step. As i saw from my first comment. At least mine was working from /step not /steps topic.

**Comment by jpmens** [comment]
Now I’m completely confused, also because you report above:

> after that it's not reported to steps topic 

Our Recorder uses `steps` (plural)

https://github.com/owntracks/recorder/blob/e2ce1904811786c140818a034610f8bf86beaddb/recorder.c#L674

It’s `cmd=reportSteps`, it’s `_type=steps`, but the Booklet does say topic = `../step`.

**Comment by jpmens** [comment]
The topic branch name changed in March 2015 from “steps” to “step”, judging by iOS repo. I stand corrected. I must have been out that day. ;-)
