### ISSUE TITLE
Version 14.0.2 crashes on MacOS Catalina 10.15 

### ISSUE THREAD

**Issue by dcj** [owntracks/ios#661]
I updated via App Store app, afterwards OwnTracks app crashes on launch.
I restored to the previous version via TimeMachine Version 13.3.7 (13.3.7), and it runs again.
I run Catalina 10.15.7 (19H114)

**Comment by ckrey** [comment]
I cannot reproduce here, my machines are all on MacOS Big Sur 11.1.

Do you have "Share with App Developers" enabled in Settings/Security&Privacy/Privacy ? If so, I should see your crash report

**Comment by jpmens** [comment]
Catalina 10.15.7 running here as well, and crash confirmed, @dcj 
I will correspond with @ckrey on this issue; no need for you to yet. :-)

**Comment by ckrey** [comment]
We have an error message, thanks to @jpmens 
```
*** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named _MKModernCompassView because no class named _MKModernCompassView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target)'
terminating with uncaught exception of type NSException
```

**Comment by ckrey** [comment]
And we are not the only one:
https://developer.apple.com/forums/thread/667557

**Comment by ckrey** [comment]
Unfortunately `Turning off the compass property seems to avoid this crash on Catalina.` doesn't help

**Comment by ckrey** [comment]
I did open a ticket with Apple, but didn't receive any useful response.

**Comment by jpmens** [comment]
>I did open a ticket with Apple, but didn't receive any useful response.

Thank you, @ckrey. I think we should probably abandon the thought. It's probably time to upgrade to Big Sur anyway.

**Comment by ckrey** [comment]
I got no response from Apple, and macOS Catalina is probably obsolete by now. Closing issue
