### ISSUE TITLE
Consider informing user and/or dropping HTTP POSTs on 4xx errors

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#665]
As shortly discussed and reported in https://github.com/owntracks/ios/issues/663 we might consider informing the user of HTTP `4xx` codes upon HTTP POST requests, and optionally dropping the payload completely until the client and server have solved the issue.

As seen in the case of our client with a Traccar server, not deleting a `_type: dump` request will basically disable the client forever.

Note that this affects HTTP only.

**Comment by ckrey** [comment]
If HTTP `4xx` codes are returned, the user is informed and the message is discarded.

This happens e.g. if the backend is `traccar` and the device is not known to traccar or if e.g. a non-location message is sent on user request (see #663)

![IMG_2656](https://user-images.githubusercontent.com/4027289/108603510-936c9980-73a8-11eb-9b69-a4ca7c7fda6d.PNG)

**Comment by jpmens** [comment]
Excellent. Thank you.
