### ISSUE TITLE
place attribut not updated via MQTT on leaving a zone/region 

### ISSUE THREAD

**Issue by Albatros2** [owntracks/ios#670]
When leaving a zone the update over mqtt does not contain the place attribute. So it is not possible to detect if the device is still in this region. Maybe the update should include an empty place string if the device is leaving a zone, or is currently not i a zone ?

currently using
Iphone 12
IOS 14.4
OwnTracks App 14.0.3
Mode "Significant"

**Comment by jpmens** [comment]
We don't have a `place` attribute in the JSON payloads. Which attribute do you mean exactly?

**Comment by Albatros2** [comment]
sorry. i take a closer look at the mqtt message itself. I mean the "inregions" attribute. looking at the mqtt messages this attribute is only distributed if the device is currently in a region. if the device is not in a region this attribute is missing. 
So far this make sense. and the error take place in the fhem modul witch is interpret this messages.
inregions":["home"],

Sorry for the misunderstanding and thank you for the fast response and this great project !
I will have a look in the FHEM module (98_livetracking.pm)

**Comment by jpmens** [comment]
So, if the `inregions` element is not available the device is not in a region; that is accurate.

If _fhem_ causes an error on that, I think they need to address that there, but judging by [this line](https://github.com/mhop/fhem-mirror/blob/master/fhem/FHEM/98_livetracking.pm#L1110) that actually is checked, so I don't know why it's throwing an error for youi.

**Comment by Albatros2** [comment]
Thank you for this hint. i tried to configure the zones and it works fine. 
![image](https://user-images.githubusercontent.com/80961653/111865289-7ce53e00-8966-11eb-985d-cfe49cb242a9.png)

the place attribute i used before seems to be for another usecase.

**Comment by jpmens** [comment]
Glad it's working for you.
