### ISSUE TITLE
Region Monitoring +follow

### ISSUE THREAD

**Issue by mbrackjr** [owntracks/ios#675]
It seems this (great!) feature is currently hard-coded to auto-create a new geozone with radius set to distance over past 30 seconds.  Is there any way to set this interval to something custom-set (i'd like to test with 60 seconds)?

**Comment by ckrey** [comment]
The current implementation uses a default and minimum radius of 50m.
If the current speed is higher, it uses the distance which will be travelled within 30 seconds. This value is not configurable at the moment.
Typically iOS reports a region `leave` event when the device is more 1.5 times the radius away from the center.

Please share your thoughts with us why you think the value should be configurable (describe the use case).

Examples:

- You drive with 50 km/h, which is about 14 m/s: The new radius will be set to 4200 meters.
- Cycling with 18 km/h, which is about 5 m/s: The new radius will be set to 150 meters.
- Walking with less than 6 km/h or not moving: The new radius will be set to 50 meters.

**Comment by mbrackjr** [comment]
I've witnessed that my owntracks client is suffering from what i believe is some sort of Apple IOS protection scheme to restrict amount of geofence-based 'triggers'.  When I'm driving (local or highway, phone actively powered and showing my navigation app) I usually see 4 or 5 consecutive owntracks registrations of locations, after which the client seems to 'stall' or stop reporting. It usually picks up again after some time (or distance?) and repeats the same pattern.  
I'd like to experiment having slightly less granular 'follow' logic by increasing the radius based on 60 second travelled distance to see if it maintains a continuous stream of location updates.

**Comment by mbrackjr** [comment]
Is the usecase clear, or do you like to have more feedback?  Thanks again for great app and hope you can help me get an even better experience.

**Comment by ckrey** [comment]
see https://owntracks.org/booklet/features/ios/
<img width="729" alt="Screenshot 2021-12-19 at 17 31 17" src="https://user-images.githubusercontent.com/4027289/146682782-d674b22e-ddaf-4a3d-b88b-188a19286eb1.png">

**Comment by mbrackjr** [comment]
Looking forward to test this out once I get the 15 release. Thanks!

**Comment by ckrey** [comment]
@mbrackjr drop me your email if you want to become a Beta-Tester

**Comment by ckrey** [comment]
https://github.com/owntracks/ios/issues/683
