### ISSUE TITLE
How long can ownTracks (iOS) be offline/in airplane mode (=how much data will be buffered)?

### ISSUE THREAD

**Issue by segdy** [owntracks/ios#679]
... and is there a way to see:

- When was the last successful transfer?
- How much data (#points, time etc.) is in the local buffer?
- Does the buffer survive reboots etc.?
- Does ownTracks still track location in airplane mode?

**Comment by jpmens** [comment]
(moved to iOS because iOS specific)

**Comment by jpmens** [comment]
We store an unlimited (well, limited by iOS resources only) number of points in an SQLite database on the device, so it survives device reboots, etc. Other than a badge on the application icon there is no information on the content of the cache, and the last transfer can be seen server-side only (on publish the data point has an associated timestamp).

**Comment by segdy** [comment]
> We store an unlimited (well, limited by iOS resources only) number of points in an SQLite database on the device, so it survives device reboots, etc.

This is good to know.

> Other than a badge on the application icon

Yes, I was wondering already what the badge means. For me the number is 30 and is like this forever.
What does it mean?

> [...] there is no information on the content of the cache, and the last transfer can be seen server-side only (on publish the data point has an associated timestamp).

I have set up owntracks on my iPhone Oct 16, 2020 (so long time ago). I never found the time to install the ot-recorder (and the hurdle with MQTT complexity was one reason).

In the meantime I have traveled the world and moved from one place of the world to the other.

Does this mean the local SQlite database still contains all these traces and once I set up my ot-recorder via HTTP POST, I can recover all my tracks?

(Is there anything I should be careful to maximize the chance to recover my past half year of move data?)

**Comment by segdy** [comment]
PS: I'm not sure if this is relevant but I tried "Export Waypoints" in the Settings.
The resulting otrw file is just 400 bytes and contains two "waypoint" entries. Is this supposed to include all locally cached ones?

**Comment by jpmens** [comment]
>I tried "Export Waypoints" in the Settings.

That export contains the regions (waypoints) set up on the device. It is 
not possible to export the positions that way. Positions are sent of via 
MQTT or HTTP depending on your configured end-point.

**Comment by ckrey** [comment]
If you have never configured a backend (either HTTP or MQTT) before, your data will be erased when you change the configuration for privacy reasons.

If the badge on the app icon says "30", then  only 30 locations are stored, probably because you swiped out the app (killed it).

**Comment by segdy** [comment]
> If you have never configured a backend (either HTTP or MQTT) before, your data will be erased when you change the configuration for privacy reasons.

Good to know, thank you. But if I never configured a backend and never changed the config, all my traces should be there, right?
Which brings me to:

> If the badge on the app icon says "30", then only 30 locations are stored, probably because you swiped out the app (killed it).

What do you mean by "swiped out"?
My owntracks app is installed on my phone since last November.
Of course, I rebooted the phone hundreds of times.
Location is set to "Always", "Precise Location" is enabled as well as Background App Refresh.

Shouldn't this app have colleced thousands of waypoints over the past months?

What could be the reason that this is not the case, and that there are only 30? (Note, the 30 badge was there pretty much from the beginning and never increased. I also just started ownTracks randomly in between...)
