### ISSUE TITLE
ownTracks on iOS does not collect any data and does not transfer any data via MQTT

### ISSUE THREAD

**Issue by segdy** [owntracks/ios#680]
I am debugging straight at the source if MQTT messages are received:

`mosquitto_sub -t 'owntracks/#' -u miphone -P XXXXX`

ownTracks says "Status Connected", so connection is definitely working.

But there is no data arriving. 

- Location Access is set to "Always"
- Precise Location is Enabled
- Notifications are enabled
- Background App Refresh is Enavled
- Cellular Data is Enabled

Today I even walked a few miles outside. Nothing.

Now I thought maybe I need to start from scratch. Removed ownTracks, re-installed and reconfigured.
Nothing.

If I explicitely push "Publish Waypoints" I only get 

`{"_type":"waypoints","waypoints":[]}`

I think something on the iOS app is broken.

Any further ideas?

**Comment by jpmens** [comment]
How is mode set (the horizontal menu `Quiet`, `Manual`, ...)?

I think I've already explained what Waypoints are to you in https://github.com/owntracks/ios/issues/679#issuecomment-853710149

Those are not the positions; they'll be published as `_type: location`

**Comment by ckrey** [comment]
`Publish Waypoints` publishes the defined Regions (AKA Waypoints).
If you want to force publish of your current location, hit the action button  in the top right corner of the map screen.
![IMG_336B4209F7EB-1](https://user-images.githubusercontent.com/4027289/121483971-11dc5e00-c9cf-11eb-8e90-adf217b35bfe.jpeg)

**Comment by ckrey** [comment]
Did you successfully manage to publish a location by pressing the indicated button above?
