### ISSUE TITLE
Problemas de conexión 

### ISSUE THREAD

**Issue by Au67** [owntracks/ios#682]
It supports ios owntracks with myqtthub, my ios device can't connect, but my android device connects smoothly.

**Comment by ckrey** [comment]
I think you are referring to [MyQttHub](myqtthub.com) and especially [Cómo configurar el cliente ownTracks para que use MyQttHub.com](https://support.asplhosting.com/t/como-configurar-el-cliente-owntracks-para-que-use-myqtthub-com/148)

What is the error message you see on the status screen? Which are the setting you use?

**Comment by ckrey** [comment]
I just tried with MyQttHub and it works fine.

In Settings, you have to enter the credentials in the fields:
- `Host`
- `Port`
- `UserID`
- `Password`
- `clientId`
- enable TLS
- enable Authentication
- enable Password

**Comment by Au67** [comment]
Thank you very much for your help, it is already working, ClientId was missing, I was confusing it with DeviceID, as ClienId appears in the Ecpert Mode section it seems that it is not necessary to touch an initial configuration.
Thank you very much
