### ISSUE TITLE
Why did ownTracks/iOS not track my flight?

### ISSUE THREAD

**Issue by segdy** [owntracks/ios#685]
It is suggested here #679 that ownTracks in airplane mode captures an infinite amount of data points and buffers them until there is connection to the server. As I have mentioned, tracking during airplane mode is somewhat crucial because that happens quite a bit for traveling, hiking in the wilderness etc.

I am still struggling to ensure all of my data points are tracked. I do not understand why half a year of tracking (Oct 16, 2020 to May 2021, as per #679) is lost.

Sometimes I feel I am missing places where I have been (even an extended period). Now I have a similar issue where I am sure I am missing data: Last week I was flying from San Francisco to Munich and from Frankfurt back to San Francisco. That's more than 12 hours of flight, yet not a single point was captured -- for both flights. I used the device quite a bit 

Why?
Thanks!

**Comment by gordolio** [comment]
I’ve never worked on this project, I’ve just discovered it. But I believe that while iOS is in airplane mode, location services may appear enabled but will only provide the last known location and may not register a “location change”.

I’m interested in this project though. Seems like a good open source alternative to Life360.

**Comment by segdy** [comment]
Unfortunately that can’t be it (at least not entirely). I regularly use it when hiking in airplane mode and there are always some points captured. Just not on the airplane. It’s really strange.

**Comment by hajoscher** [comment]
Maybe there was no GPS lock in the airplane. I tried this many times, and I only get a GPS lock while flying, when I hold the phone directly to the window.  And then not even always.

**Comment by ckrey** [comment]
I can confirm from recent experience/test OwnTracks does not get location Updates when in Airplane Mode after a while. This is independent of the mode used (significant, move, etc.).
This behaviour is the same in Apple's Maps App, Google Maps, or other apps using location services in iOS.

If OwnTracks is just off-line, location updates are queued and transmitted as soon as the connection to the backend is re-established.
