### ISSUE TITLE
Help - iBeacon zone exit - IOS App + Home Assistant + MQTT - HA does not set tracker to "not_home"

### ISSUE THREAD

**Issue by bleitchhk** [owntracks/ios#686]
First and most important, I really like owntracks and have it generally working quite well with my home assistant.  I think it is a great piece of software.  I am trying to perfect its use as a presence input for automation and security system use cases.  I have one thing I cant quite get working right.

The question below is for sure more related to Home Assistant, but this is the best forum I feel to ask this question.

I am using owntracks with Home Assistant as follows:
- Owntracks IOS APP on Iphone 10
- Home Assistant as Home Automation platform on PI 4b
- MQTT setup is using Mosquitto add-on to Home Assistant
- Configured owntracks to use MQTT from app to Mosquitto broker
- using iBeacons at home to create a home zone accurately
-      - home region in IOS app set to same name as home zone (region) in home assistant
-      - home region in IOS app set with Radius of 0 and using Ibeacon UUID
- not using waypoints or way point imports (false on waypoints config in Home Assistant)
- am using region mapping - name to name exactly Owntracks to Home Assistant (zone names) - names, radius, and GPS co-ordinates align with Home Assistant radius slightly less as recommended
- I am not using yaml mapping in home assistant config, I am just manually setting regions and zones the same in both IOS App and Home assistant
- have set Home Assistant to use entry/exit events only

My problem is when I leave home.  I can not get Home Assistant to set my zone on the associated device tracker to "not_home".  The exact behaviour and debugging is:

- owntracks correctly detects beacon is no longer present and the beacon in owntracks goes from red to blue
- owntracks sends both a transition message and location message when this happens
- I can see both MQTT messages arrive at my home assistant in MQTT listening debugging my listening on "owntracks/#"
- the transition message reports existing home zone
- 1-2 location messages arrive, 1 to report changing from home wifi to mobile and 2nd reporting actual location, it is sometimes 1 and sometimes 2 messages
- so, MQTT messages are 100% for sure arriving at Home Assistant
- home assistant will not change the device tracker from "home" to "not_home"

When I come home, the "_transition" message of entering home comes immediately and Home Assistant sets me as home.  In  fact it happens impressively fast at about 3-4 seconds before my door sensor detects opening.

How do I make home assistant set me to "away" or "not_home" as soon as the beacon connectivity is lost when I leave home ?

Thanks;

Brendan

  *** Before filing an issue: Is this an issue specifically for Android or iOS?
  *** Please then, visit either https://github.com/owntracks/android/issues
  *** or https://github.com/owntracks/ios/issues

-->

**Comment by ckrey** [comment]
@bleitchhk sorry, if the OwnTracks iOS app sends the MQTT messages there is nothing more we can do from here to  make HA recognize the correct status.

You may open a ticket in HA or look in their forum for a solution or hint
