### ISSUE TITLE
iOS app no longer seems to respond to remote cmds

### ISSUE THREAD

**Issue by RealGandy** [owntracks/ios#687]
Recently I have been trying to update some waypoints for my family phones, but have noticed that they no longer appear to respond to any owntracks/<name>/<device>/cmd messages. 

I also no longer get family member (friends) updates on my device.
[subTopic on device shows owntracks/+/+, owntracks/+/+/event, owntracks/+/+/info and owntracks/<name>/<device>/cmd as expected]

I publish messages on the MQTT broker and see them in other MQTT clients connected as the same users as used by the devices, but the devices do not action anything.

The devices continue to send significant location change events and waypoint enter/exit events as expected.
MQTT ACLs allow all messages to be seen by all clients

Any advice on how to work out what's going on and how to fix please?

OwnTracks latest version is installed on devices (14.2.2)

**Comment by jpmens** [comment]
Are you publishing messages to your iOS device with QoS>0 ?

**Comment by RealGandy** [comment]
I’ve tried with QoS of 0,1 and 2 without success.

**Comment by ckrey** [comment]
Would you please check if the relevant toggle switches in "Settings/Expert Mode" are "on":

`sub` controls if an subscriptions are made
`cmd` controls if any remote commands are executed
`subQos` sets the maximum Qos accepted by the device (even if you publish with a higher Qos)

**Comment by RealGandy** [comment]
sub was off - now on
cmd was on
subQos set to 1

The turning on of 'sub' seems to have resolved my issue - was this a new setting in a recent version as it's not been an issue in the past.

**Comment by ckrey** [comment]
We had a problem with a wrong default for `sub` in the past ( see #610), sorry

**Comment by RealGandy** [comment]
Gosh! That long ago! Thanks for help, I’ll set about updating devices now, shame I can’t do it remotely ;)

**Comment by ckrey** [comment]
@felho001, please do not comment on a closed topic

If you have an MQTT setup problem please open a new issue with the details regarding your MQTT broker
