### ISSUE TITLE
No locations sent in "significant"-mode from iPhone

### ISSUE THREAD

**Issue by rallyeaon** [owntracks/ios#689]
Hello ! IWe (my family & I) were using owntracks on Android mobiles with almost no/minor issues. Recently (2 weeks ago) we changed to iPhone 12 (2x pro, 1x max) running IOS 15.1.1 with owntracks 14.2.2/de_AT
The phones are clients to an MQTT-Server (MQTT2 in FHEM home automation).
Requesting a manual transmission of the phone's location results in an location update on the server of the respective phone. However, in neither "significant" mode, nor "move" mode any update is sent. This is true regardless of owntracks in the foreground or in the background.
A couple of days ago new locations were sent occasionally however, since a while only manual mode ist working. I'm not sure wether update of IOS had an impact.
For your convenience I have uploaded my exported configuration (anonymized somewhat) and appended a ".txt" to comply to the upload-rules.

Any help is highly appreciated. In case this is not the right place to post my issue please point me to the right address.

Thank you very much

rallye

[config.otrc.txt](https://github.com/owntracks/ios/files/7635485/config.otrc.txt)

**Comment by jpmens** [comment]
I see from your configuration you have TLS disabled but are trying to transmit to port 8883 which is typically the TLS port on an MQTT broker. Is the port offering plain MQTT?

(Though you say manual publishes are possible which contradicts my question somewhat ...)

**Comment by ckrey** [comment]
@rallyeaon we have seen problems after iOS updates in the past. Would you shutdown and restart the iPhone(s) and check if reporting restarts? 
And please check under Settings/Privacy/Location if Owntracks is allowed to use location services in background mode

**Comment by rallyeaon** [comment]
> I see from your configuration you have TLS disabled but are trying to transmit to port 8883 which is typically the TLS port on an MQTT broker. Is the port offering plain MQTT?
> 
> (Though you say manual publishes are possible which contradicts my question somewhat ...)

Thank you. Yes, this port is plain MQTT. It worked with disabled TLS under Android too.

**Comment by rallyeaon** [comment]
> @rallyeaon we have seen problems after iOS updates in the past. Would you shutdown and restart the iPhone(s) and check if reporting restarts?
> And please check under Settings/Privacy/Location if Owntracks is allowed to use location services in background mode

Thank you for your suggestion ! We will do as proposed by you but I can test only on Friday. I’ll come back wit my results during the weekend. 
Refs from Vienna

**Comment by rallyeaon** [comment]
> @rallyeaon we have seen problems after iOS updates in the past. Would you shutdown and restart the iPhone(s) and check if reporting restarts? And please check under Settings/Privacy/Location if Owntracks is allowed to use location services in background mode

Unexpectedly 2 members of my family left home today. Seems the iPhone reboot solved the problem. I'll keep you posted.

Thank you for the time being

Regs rallyeaon

**Comment by rallyeaon** [comment]
Thank you for your patience ! Going back and forth from home I found the reboot of the devices after upgrading IOS helped a lot. In fact, moving around on a daily basis keeps the tracking "alive". However, if owntracks is inactive (no significant movement) for ~3 days it doesn't send updated locations until it's called to the foreground.

Bottom line it works with the minor restriction described above.

Thank you for your suggestions !

Regs rallyeaon

**Comment by ckrey** [comment]
@rallyeaon thanks for testing
