### ISSUE TITLE
Cannot add certificate on iPhone 13 mini

### ISSUE THREAD

**Issue by or-dodson** [owntracks/ios#693]
When trying to add a certificate that's already trusted on my iphone. The screens where I should be able to add the certificates look like the following on my device:

![IMG_0199](https://user-images.githubusercontent.com/48970011/147306387-49536887-c165-4d32-a0ec-938e2fc6f53d.PNG)
![IMG_0199 2](https://user-images.githubusercontent.com/48970011/147306389-984605d8-9d20-4bce-a922-dcb7ea61d4cc.PNG)

**Comment by ckrey** [comment]
@or-dodson you need to follow the instructions:

https://owntracks.org/booklet/features/tlscert/

- create the Client Certificate an Key
- package it als a pkcs11 file
- send it as an .otrp file to the phone and open it with the OwnTracks app
- then you can select it on the screens you showed

**Comment by ckrey** [comment]
@or-dodson were you successful?

**Comment by or-dodson** [comment]
@ckrey I was able to add it with your instructions. Maybe it would be useful to update the interface to guide the user to the online instructions instead of presenting screen that is not intuitive to new users.
