### ISSUE TITLE
Feature Request: Publish current monitoring mode on location updates

### ISSUE THREAD

**Issue by AndLindemann** [owntracks/ios#694]
Would it be feasible to publish the currently selected monitoring mode (significant, move, etc) as part of the regular location update messages to MQTT?

Background: I have Owntracks connected through my Home Automation setup and I've fiddled around with automatically switching the monitoring mode between "significant" and "move" by evaluating charging (bs) and battery levels in my automation setup and depending on this, sending config commands to switch between significant and move modes. That way I can automatically switch Owntracks to Move mode while driving by car for example, if the phone is being charged by the car or if the battery level is high enough, which is a nice and seamless way for me to get more accuracy out of it.
However as the current monitoring mode is not included in location updates, there's no feedback available to the automation to check whether the setting is actually applied or not (and to take appropriate action on it), unless I send a separate dump command to get and parse the whole config from the device, which is a bit cumbersome to handle.

I'm aware this would mean the size of the location update message increases a bit to include the additional field, so not sure if that'd be a counter argument, or a reason to include it as a toggle-able feature for those who want to use it or not?

**Comment by jpmens** [comment]
This isn't a bad idea at all and might help others knowing under what circumstances (which mode) a particular location publish occurred.

**Comment by ckrey** [comment]
Changing monitoring modes while the app is in the background is not possible #683 and #659.
I doubt you will be able to switch between modes by a command without opening the app. We will try to see if it actually works.

Your idea of including the current monitoring mode in the json payload is fine. It will be 
```
{"_type":"location", "m":<monitoring mode>, ...}
```

A separate issue how to control the extra data element is opened here #695

**Comment by AndLindemann** [comment]
I'm somewhat certain I've seen it happening that the app switches the mode while in background and that it works, though I'll admit I would have to run some tests to verify it. Looking at my tracks making me believe it works, but unsure whether that was because I may have opened the app at some point or not. 
I'll try and run some tests over the next days to see if changes are being picked up or not.
