### ISSUE TITLE
Granular control for `extendedData` 

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#695]
Today, a minimal `location` message contains

```
{
    "_type":"location", 
    "tst":1640875336
    "lat":55.123456, 
    "lon":-6.663311, 
    "acc":8,
    "tid":"SE", 
    "t":"u", 
    "batt":31,
    "bs":1, 
    "inregions":["Home"], 
    "inrids":["66ffddee"], 
}
```

If the `extendedData` configuration parameter is `true`, the following attributes are added:
``` 
    "alt":41,
    "vac":7,
    "vel":1,
    "cog":93,
    "conn":"w",
    "SSID":"MyWifi"
    "BSSID":"66:88:22:11:33:66",
    "p":101.059,
```

With new enhancements, do we need to control the content and size of the `location` message on more granular level or is storage and mobile bandwith not a major issue anymore?

**Comment by jpmens** [comment]
I was very concerned with the issue of bandwidth when we originally started with OwnTracks, as you will recall, but I would say that is no longer really an issue for very many people, as mobile operators tend to offer more bang for the buck.
