### ISSUE TITLE
Ask for permission to use Apple's reverse geocoder and map

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#696]
![EFE272EE-58F8-4401-9E19-5339301D1CF7](https://user-images.githubusercontent.com/4027289/148758783-2822006f-54d8-4c45-9e98-b64f97ede42c.png)

**Comment by ckrey** [comment]
Permission is currently asked only to "Send your location to a server of your choice".

The reverse geocoder in iOS is not protected by the Privacy Settings of the device. So we may have to make it configurable (see Android).

The map starts with a view extending to the country you used in device settings. As soon as you select a friend (or yourself) in Friends view, the map is zooming to the friend's location.

Both may give hints to Apple's services where I am or my friends are.

**Comment by jpmens** [comment]
My initial reaction on seeing that review was "that's inaccurate", as what the user describes only occurs after I've configured a target, i.e. I've given consent.

But, ok, after rereading several times I get the point.

What is to happen if user doesn't give consent for revgeo or for using the map? Basically the map would need to be completely disabled, right? And what about Friends: do we need consent for them as well?

**Comment by ckrey** [comment]
![IMG_2D7D4E7AE8D4-1](https://user-images.githubusercontent.com/4027289/149513013-fb4fda90-845b-4ab7-934a-b7e6638c1f07.jpeg)

**Comment by ckrey** [comment]
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-01-14 at 13 43 31](https://user-images.githubusercontent.com/4027289/149518245-482ed905-55bb-4892-850b-a04ab5774923.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-01-14 at 13 43 41](https://user-images.githubusercontent.com/4027289/149518255-3c3ae76b-a4f0-4639-a124-1c6b89554952.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-01-14 at 13 52 32](https://user-images.githubusercontent.com/4027289/149518421-e5ba1d15-2404-489f-9ee7-fd496253fdd8.png)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2022-01-14 at 13 52 52](https://user-images.githubusercontent.com/4027289/149518600-a2302e67-d965-4219-85c3-6b7871769cf7.png)

**Comment by jpmens** [comment]
Looks good to me.

**Comment by growse** [comment]
I'm wondering what the equivalent functionality we'd want on Android so that our privacy stance is consistent between Android/iOS. Right now, the Android app prompts for permission on loading the map to use the device location permission, but the default geocoder (on the Google Play version) is set to Google by default. On OSS, the default geocoder is "none", so the user has to explicitly ask for it.

I guess no services are called unless the user grants access to location, but wondered if there's anything else we'd want to do there?

**Comment by ckrey** [comment]
The problem is that the user allows access to location to send the data to his "own" server, not to the geocoder of Google (in the Google Play version).
Same is true for accessing tile data

**Comment by growse** [comment]
Ah, so if I understand you right, when the user clicks "allow location permission", they don't think they're giving permission to send their data to Google?

On a device with Google Play Services installed, Google has root on the device anyway, so this feels like a bit of a weird thing to worry about. We could default the Geocoder to "none" (or at least show a prompt asking the user whether they want geocoding or not), but that doesn't solve the tile issue. 

For any map implementation (Google, OSM etc.), if you allow the app to know your location, it's going to then fetch the map tiles around that location from somehwere, which will leak your approximate location to that tile provider.

**Comment by jpmens** [comment]
So if the map has no idea where the device is, we wouldn't be leaking data, also not when obtaining new tiles from the map server. 

If permission to use device location also means permission to use the Google Play geocoder is given, we probably need to split that out.

**Comment by jpmens** [comment]
![IMG_2019](https://user-images.githubusercontent.com/60706/149528374-04e4cdcc-e778-430a-afaa-5c00aff0adfe.jpg)

This is very elegantly done! (Click on the "folded map" icon to have the app ask for permission again.)
