### ISSUE TITLE
iBeacon not updating upon entering/exiting

### ISSUE THREAD

**Issue by goldriver2** [owntracks/ios#697]
Hi, can someone help with this problem 

I have been using OwnTracks for about 15 months now without issues. Starting last’’few days ago, suddenly OwnTracks does not update the iBeacon status anymore. The only way for them to update, I have to launch another application « Locate » from Radius that upon starting it detects iBeacon, then OwnTracks updates it’s status BUT if the phone fall asleep, if I reopen OwnTracks ALL iBeacon regions are once again « off » even if I am in the middle of 3 of them

I can’t certify the fact but it seems to have stop working sometime around the same time I updated from iOS 15.1 to 15.2

I made sure « location » was set to always in the settings, I even try to deactivate and activate the location to « always » without luck

using 14.2.2 en_ca version on iOS 15.2

**Comment by ckrey** [comment]
In the past we saw a lot of problems after updating iOS. Usually all is back to normal after you completely shutdown and restart your iPhone

**Comment by motoxsgb** [comment]
I will confirm this issue, and shutting down and restarting ios does not resolve. This is occurring on 8 devices all on IOS 15.2 They will not respond to: {"_type":"cmd","action":"reportLocation"} request (cmd is enabled on all). As soon as OwnTracks is put to the background (device locked or unlocked) it no longer responds. 
The only device that operates properly is running IOS 15.1

**Comment by goldriver2** [comment]
I did restart the device twice and the problem persist. As soon as OwnTracks goes asleep nothing is updating

**Comment by goldriver2** [comment]
I tested 2 other iPhone with my setting, one on 15.1 (everything work as expected) a second one on 15.2 (this one have the same problem)

**Comment by goldriver2** [comment]
Not sure exactly where the problem sits as I tried with a 3rd iPhone also on 15.2 and on this one it is working

What I have observe yet with the device on 15.2 where OwnTracks seems to loose track of my iBeacons 
1- if I open the owtrack, there are none of my iBeacons on. Even if I come close to a beacon, owtracks does not detect them.
2- if I open radius "locate" application, immediately I have the notification from OwnTracks saying it detected the beacon wherw I am
3- if i put OwnTracks in background's to work with another application and stay exactly where i physically was, after about 40 seconds, I have notifications saying that I left the beacon area which is false ( I am still right beside the iBeacon)
4- if i open OwnTracks again, once again OwnTracks shows no sign of me being right aside a beacon even if I am right beside, again, if I open "Locate", owtracks immediately sends me notification saying I am near

**Comment by ckrey** [comment]
@goldriver2 thanks for your detailed description

I can confirm your observation. Seems Apple changed the handling of iBeacon monitoring in background with regards to Privacy settings:

In former versions of iOS it was sufficient to give OwnTracks "When in use" to get updates when entering/leaving iBeacon regions.

Since 15.2 you need to give OwnTracks "Always" access to Location services. I will try to find the respective release note as a reference

**Comment by ckrey** [comment]
@motoxsgb your remark is a different topic. I opened a separate issue #699

**Comment by goldriver2** [comment]
Changing location to "Always" definitly fixed my issue on the devices on 15.2 
Thanks for this

I suppose the installation process will be modified to include "always" in the location options.

**Comment by ckrey** [comment]
It is not possible to include the option in the first step, but after a short while, iOS prompts for the upgrade.

Step 1:
![IMG_9705](https://user-images.githubusercontent.com/4027289/149337139-4e769358-3716-47f4-a93e-174c8b1a2e88.PNG)

Step 2:

![IMG_9706](https://user-images.githubusercontent.com/4027289/149337160-31825af4-fd87-4638-898f-833322cff5f5.PNG)

**Comment by ckrey** [comment]
Let's hope for the best with iOS 15.3
