### ISSUE TITLE
No response to "cmd" "reportLocation" in iOS 15.2

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#699]
I will confirm this issue, and shutting down and restarting ios does not resolve. This is occurring on 8 devices all on IOS 15.2 They will not respond to: {"_type":"cmd","action":"reportLocation"} request (cmd is enabled on all, and background app refresh). As soon as OwnTracks is put to the background (device locked or unlocked) it no longer responds. 
The only device that operates properly is running IOS 15.1

_Originally posted by @motoxsgb in https://github.com/owntracks/ios/issues/697#issuecomment-1011055317_

**Comment by motoxsgb** [comment]
Adding to this issue: The main problem is that OwnTracks is not reporting position on iOS 15.2 when open in the background. Additionally it does not respond to position requests sent via mqtt as I described above. As soon as the application is brought to the front it works. I have one device running iOS 15.1 and another running iOS 14.8.1 that are operating properly. I also applied the iOS 15.2.1 update to one device and it has the same problem as iOS 15.2

**Comment by jpmens** [comment]
Are you publishing your `cmd` requests to the broker with `QoS>0`?

**Comment by motoxsgb** [comment]
I have tried publishing cmd requests with Qos 0,1, & 2 with no luck
Privacy Setting has been confirmed on all devices and are set to "Always On"
Background App Refresh confirmed on all devices to enabled

**Comment by ckrey** [comment]
@motoxsgb unless you are using "Move Mode", the app is sleeping in the background and disconnects from the MQTT broker.

It will eventually pick up MQTT messages sent with QoS>0 when it wakes up by either
- the user opening it
- getting an location update when entering or leaving a region
- getting an location update once in a while when in Significant Mode
- or when being woken up by iOS to do a Background Fetch

If you are expecting the "reportLocation" command to trigger the app immediately, you are wrong.

The downside of using "Move Mode" is the high battery consumption.

Our tests show "reportLocation" works on iOS 15.2 devices with the limitations explained above

**Comment by motoxsgb** [comment]
Thank you for the detailed operational explanation of the reporting modes and how the app responds while in the background. My troubleshooting was not thorough enough and I zeroed in on the different iOS versions as the cause not noting what reporting mode the devices were in. I appreciate the quick responses and overall support from this volunteer community!
