### ISSUE TITLE
Moving updates received, but with stale fields (appears not to move)

### ISSUE THREAD

**Issue by bitmonkey0** [owntracks/ios#700]
Hey everyone,  thank you for creating this project.  I love the effort and the spirit of the project.

I am trying to use the iOS app to share positions with relatively high frequency during certain periods.  Since we are paying for those high resolution fixes with lots of battery usage, I want to make sure that the data generated can be used.  

In my iOS config, I set 

```
...
        "locatorDisplacement": 100,
        "locatorInterval": 10,
...
```

thinking that would give me sufficiently high resolution.

dumping the MQTT stream, I see that my device is sending data every 10s, but the data in the json payload is stale.

(I removed the lat/long from the file -- but the positions were changing with each sample and when watching the map on the app, I could see the blue dot following my location)

```
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","p":95.945,"tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628069,"p":95.944,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628079,"p":95.939,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628089,"p":95.937,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628099,"p":95.942,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628109,"p":95.944,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628119,"p":95.946,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628129,"p":95.949,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628139,"p":95.937,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628149,"p":95.921,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":555,"batt":79,"bs":1,"cog":192,"conn":"m","created_at":1642628159,"p":95.91,"t":"t","tid":"CR","tst":1642628067,"vac":3,"vel":3}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":79,"bs":1,"cog":240,"conn":"m","p":95.9,"tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":79,"bs":1,"cog":240,"conn":"m","created_at":1642628169,"p":95.895,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":79,"bs":1,"cog":240,"conn":"m","created_at":1642628179,"p":95.88,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":78,"bs":1,"cog":240,"conn":"m","created_at":1642628189,"p":95.867,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":78,"bs":1,"cog":240,"conn":"m","created_at":1642628199,"p":95.873,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":78,"bs":1,"cog":240,"conn":"m","created_at":1642628209,"p":95.875,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":78,"bs":1,"cog":240,"conn":"m","created_at":1642628219,"p":95.883,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":78,"bs":1,"cog":240,"conn":"m","created_at":1642628229,"p":95.887,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":78,"bs":1,"cog":240,"conn":"m","created_at":1642628239,"p":95.893,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
owntracks/xxx/iPhone {"_type":"location","acc":5,"alt":561,"batt":78,"bs":1,"cog":240,"conn":"m","created_at":1642628249,"p":95.893,"t":"t","tid":"CR","tst":1642628166,"vac":3,"vel":4}
```

Full dump from walk [mobile_no_loc.txt](https://github.com/owntracks/ios/files/7903893/mobile_no_loc.txt)

Is there something wrong here?  The created_at fields are correct, but tst is stale.  Is there something wrong with my GPS?  

When I set the same settings on the android app, I get the high resolution I am seeking.

I'm using version 14.2.2 with iOS 15.2 on an iPhone Xr

Thanks for your support,
bitmonkey0

**Comment by ckrey** [comment]
@bitmonkey0 thanks for reporting.

The location services in iOS and Android work different. This is why the Monitoring Modes are different:
- https://owntracks.org/booklet/features/location/#ios
- https://owntracks.org/booklet/features/location/#android

Move Mode in iOS works as follows:
- controlled by `locatorInterval` it sends the last position delivered by iOS, regardless if the position actually changed or if iOS delivered an updated position.
- controlled by `locatorDisplacement` iOS will deliver position updates only when the relative position changed more than `locatorDisplacement` meters. Set to 0 to receive all position updates.

In your log you see the continuous messages with `"t":"t"` created by the timer and the occasional messages without `"t":` triggered by an actual new position delivered by iOS.

For similar results as in Android, try to set `locatorDisplacement=0`

**Comment by bitmonkey0** [comment]
Thanks @ckrey for the unexpectedly quick response!

I will shortly go for another walk and will test out the new setting of `"locatorDisplacement": 0`  Assuming that works, I will close the issue.

Kind regards,
bitmonkey0

**Comment by bitmonkey0** [comment]
It worked exactly as you described it.  Thanks for the support.
