### ISSUE TITLE
owntracks did not detect my movement today

### ISSUE THREAD

**Issue by alangrafu** [owntracks/ios#703]
I moved today in my car for 5 KM but owntracks did not recorded those changes. This is strange, since usually owntracks detects even smaller displacements (my configuration shows `locatorDisplacement` =30 and `locatorInterval` = 60.

Not sure how to debug this issue? Thanks!

**Comment by ckrey** [comment]
@alangrafu 
- Did you upgrade to the new release 16.1.3? If so, please check if your phone is still in "Move Mode". Two new features may affect "Move Mode" (#683 and #426).
- Did you upgrade iOS recently. Sometimes the phone needs to be restarted to setup the location setting again.

If you have, it would be helpful to see the MQTT messages sent before, during and after the trip with your car.

**Comment by alangrafu** [comment]
Thanks! I have auto update for the apps. I restarted the phone, maybe it was a glitch due to the update itself since it was working perfectly a few days ago.

i use http on the server not sure if it useful for you
