### ISSUE TITLE
Receiving empty packets and that is all for some time (hours)

### ISSUE THREAD

**Issue by Wildbill-Z** [owntracks/ios#704]
Hi, me and my wife are running latest version 16.1.3de_DE out of Appstore (I stopped using the testflight version and did a install from Appstore). My Iphone 12 is running just fine without any problems. The Iphone 12 of my wife has problems: After leaving a waypoint her Owntracks app is sending 3-4 packets (about 3-5 minutes) and then sends a last "empty" packet (see below) and then stops sending new packets, sometimes for hours. After a new waypoint event (entering a waypoint) it just starts over to send everything correctly again ( but only after this event, there are no buffered data),  sometimes it "repairs" itself and is sending new data after a few hours. It also starts again if she is opening the app by herself on the Iphone.
In Owntracks frontend, recorder and in MQTT-Explorer I can see, that there are no new packets after this last empty packet. Timestamps don't change, position in recorder and frontend stay at the last known position. When I look into Apples Where is-App (Wo-Ist in german) I can see her actual position, so localisation on the Iphone just seems to work, it's only Owntracks stopping to do its work.
What I checked so far: All app settings are exactly the same as on my Iphone (besides the user name). All settings in Iphone who could affect Owntracks are exactly the same. I even uninstalled the app on her phone including the settings and did a fresh install (app, not whole Iphone) without success. The log of the MQTT-broker (mosquitto) is not showing any suspects, its just showing the connection changes when leaving WIFI and entering mobile net (new IPs).
We both have the same waypoints (all with the new feature of automatic mode change with |1|2) and one waypoint +follow, as recommended in the documentation. Mine is just working, besides of positions without mobile connection. Her seems to stop sending, when automatic mode change occurs (just a suggestion without exact testing). When looking into her app, the mode change between significant and move and backwards works, I also get the correct mode in the MQTT-Packet, as long as it is working.
Here is a screenshot out of iobroker with the data of one of those "last empty packets", where I can see all of the data which was sent to my MQTT-broker (mosquitto). As you can see, most of the data is empty (null):

![grafik](https://user-images.githubusercontent.com/35911150/155845885-39ef8a17-db6b-4d6e-b28c-445d61890a01.png)

**Comment by ckrey** [comment]
The problem is known and described in #683

I don't see a way to eliminate the problem: When switching to "Move Mode" in background, the app is not allowed to run indefinitely (as it is when switching to "Move Mode" in foreground). The result is it is killed by iOS after a few minutes. The result is an "empty" will message triggered by the keepAlive timeout on the broker.

@Wildbill-Z you say on your  Iphone 12 it is running without problems. Do you use other settings (Background Fetch, Location always) or other apps than on your wife's? Do you use Automation for OwnTracks in parallel?

**Comment by Wildbill-Z** [comment]
@ckrey You are right, it seems to be like something, that it is killed by iOS. But, today, it is working nearly fine, as long as I can see. In Owntracks frontend I can see nearly all positions my wife is, sometimes interrupted by a "empty" message. But after a few minutes it goes on and I can see her new position. Conveniently, she is working as a supplier, so she is on the road the whole day. :-) In iobroker I can see, that Owntracks switched automatically to move mode, so that one worked. After an empty message I get the new lat/lon with all the other data and a new timestamp.
As far as I can see, we both use the exactly same settings in iOS (Background fetch, Location always) and in Owntracks. Only automation (for both of us) is telling the smartphone when we leave home through the Apple home app (automation in shortcuts app), which sends this to Yahka (an adapter for iobroker which connects to Apple home). This is working just fine for both of us and always. No other automation, especially for Owntracks, no other tracking apps. The only difference is, that my wife uses her iPhone for some other apps and games, which I don't use. Maybe these stay open in background (although I didn't see them in background settings in iOS) and use some memory so that iOS stops some other processes like Owntracks due to memory optimization?!

**Comment by Wildbill-Z** [comment]
@ckrey Something strange happened. Without doing anything for the last two days and today Owntracks on my wife's iPhone seems just to work without problems. I see nearly all positions. Sometimes there is one of those "empty messages" with payload (null) but after some minutes (obviously after driving along a few hundred metres) I get the next message which contains all data.
iOS is sometimes weird, but not as much as Android. With Android we had a lot more problems, not just belonging to Owntracks.
Does it make sense to close this issue as I think, you can't fix anything here anyway? Or should I leave it open in the hope, someone has that one sparkling idea to fix it without the need that Apple will change something in iOS?

**Comment by Wildbill-Z** [comment]
I'll close this issue for now as the problem nearly seems to be solved by itself. Sometimes I get one of these strange empty data (even sometimes from my iPhone which seems to work. bit more reliable), but over the hole Owntracks is nearly doing a perfect job. I don't know why it seem to "repair" itself, but for now I'm satisfied just the way it is.
