### ISSUE TITLE
Feature request: Allow owntracks to define "tags" (e.g., walking, bycicle, car)

### ISSUE THREAD

**Issue by alangrafu** [owntracks/ios#705]
Apologies if this is supported, but I couldn't find in the app how to do it: It would be great to have a way to identify different means of transportation (car, walking, bike) and add them as different topics (in an automatic/semi-automatic way). For example, I could create a shortcut where every time I start a biking workout, the topic in the owntracks app switches to `alangrafu/iphone/bicycle` and when I connect to CarPlay, it switches to `alangrafu/iphone/car`.

**Comment by ckrey** [comment]
@alangrafu good idea. Though, we would suggest not to change the topic a lot of downstream processing and the processing of `faces`, `commands`, etc. rely on the base topic.

We can thing of an additional `"tag": "walking"` as part of the payload.

You may either evaluate the payload directly or choose to re-publish the payload to a different topic in your backend.

Setting up an automation to control the tag is a good idea too. You could trigger it using CarPlay connection, Wifi Connection, NFC Tags, etc.

**Comment by ckrey** [comment]
It is implemented since #705
