### ISSUE TITLE
Owntracks for ios stops updating ibeacons after a while when in background

### ISSUE THREAD

**Issue by goldriver2** [owntracks/ios#706]
This issue was raised few months ago, the app when going in background mode stops sending ibeacons activity.

I made sure that notifications are set to always on

when the application stops working, even if I open the app and go in the beacon section, the application does NOT detect any beacon even if i move away and come back in the room.

The only way to restart the detection is toi open another ibeacon locator, this seems to reactivate the beacon detection.

Then, as soon as the app goes back in background mode, the app stops responding to beacon presence.

I don't think the problem is related to the ios release as I tried another beacon app :Geofency  and this one is working in the background

**Comment by goldriver2** [comment]
Yes I am reffering to this issue raised few months ago.
 
I am attaching a screen video of what is happening. I recorded my iphone screen right after taking it out of sleep.

https://user-images.githubusercontent.com/7215561/157954467-440c9e94-77a0-4883-8937-411e10285453.mp4

1- I opened Owtrack, you can see that no ibeacons are ON
2- Without moving in the room, I then open the "Locate" application from radbeacon wich detects any local beacons
3- Right after opening the Locate App and without moving , I then switch back to the Owntrack App, you can see the beacons being detected 

It looks like the Owntrack app loose the link with the bluetooth when the phone goes in sleep mode. Owntrack "Location" parameters in setting is set to "Always"

Using an iphone 12 Pro on 15.3.1

My wife use the exact same configuration (shared via export-import) on an iphone 13 Pro and does not have this issue.

I tried erasing the app and re-installing, sometimes, the app does detect beacon for a few hours even if the phone goes in sleep mode and after a while, it stops. When it stops, there is nothing I have been able to do to fix the issue other than removing and re-installing the app.

Are there any traces that can be turned on to try understand when and why the App stops working ?

**Comment by ckrey** [comment]
There are now accessible log files available on the status screen. But, the app itself does not interface with bluetooth directly. It uses the iBeacon monitoring handled by iOS and is notified only if iOS detects an iBeacon or looses connection to an iBeacon. 
Do you still use the problem with recent iOS releases?

**Comment by ckrey** [comment]
@goldriver2 does your problem still exist? We are now on iOS 17.x.x. 

Which monitoring mode (Quiet, Manual, Significant, Move) do you use in the OwnTracks app?
Do you have location services allowed for the OwnTracks app = "always"?
