### ISSUE TITLE
LOCK does not disable Friend association

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#707]
When OwnTracks (16.1.3) on iOS is locked via an OTRC import (`"locked" : true`), it is still possible for a user to associate a contact from the device's address book with an OwnTracks topic.

Case in point is an elderly user who has a device which should be locked (so as to not be able to change settings), but this user also manages to rename random entries in Friends list, causing a lot of confusion. As an example, Jane Jolie, now in Hamburg, is suddenly called Fritz Friendly, and the OwnTracks user is surprised that their old friend Fritz is in Hamburg. 😀

I'm wondering whether we ought to include locking the contact association in the LOCK feature, seeing as it is possible to provision a CARD via MQTT.

Assuming a savvy user who is able to provision a device for someone, I don't think disabling contact association would be a big limitation.

**Comment by jpmens** [comment]
Maybe we could use more than a boolean:
> Feature Request : Lock the Map-Settings if requested as well (i.e. Significant Move, Standard-Map) because users (elderly people) tend to klick around not knowing what they do.

**Comment by ckrey** [comment]
`locked` are now
- regions tab
- create region by long press on map
- Mode selection on map screen
- Map screen authorizations
- Address book associations
- Card Button and Shares Button on Settings screen

**Comment by ckrey** [comment]
Will be fixed in the upcoming 16.2.5 iOS app release
