### ISSUE TITLE
Home Assistant: Duplicate User and a user missing!

### ISSUE THREAD

**Issue by EagleDTW** [owntracks/ios#709]
Hi,

I have OwnTracks setup on an HA instance and have each device (3) configured in the iOS apps. 2/3 apps have only 2 devices, except 1 - it’s the missing one from the others, but has all the devices in the topic.

Thank you,
Daniel

**Comment by ckrey** [comment]
The integration with Home Assistant done by HA is a bit incomplete. Please have a look at #701. There is a related issue opened with HA

**Comment by ckrey** [comment]
Please check your Home Assistant Setup as shown in issue #701

**Comment by ckrey** [comment]
No news for more than a year, closing issue
