### ISSUE TITLE
send webhook on regular basis if near beacon

### ISSUE THREAD

**Issue by josh-m-sharpe** [owntracks/ios#712]
I'm attempting to use an ibeacon to track that I'm in my car.  

Issue is: The "entered" webhook may fail for any one if a bazillion internet reasons.

Feature Request:  If near a beacon, send an event to the webhook at a (configureable?) interval.

This way if the entered request fails, there is a guarantee of some event in the near future.

Thanks!

**Comment by jpmens** [comment]
The apps send the notifications as "events" which, as you rightly indicate, could get lost when using HTTP. (Using MQTT had a QoS>0 is typically quite reliable.)

I fear the fact a device has entered or left a particular location (in this case beacon) would be misinterpreted if we continuously published the event.

**Comment by josh-m-sharpe** [comment]
For this use case (tracking mobile ibeacon) using mqtt isn't an option I don't think as it would require exposing it publicly, which isn't really ideal.

I wasn't suggesting re-using `entered`.  Any other name would do... `present`, `nearby` - whatever folks thinks makes sense.

**Comment by ckrey** [comment]
@josh-m-sharpe the „normal“ `location` message already includes the array `inRegions`, which indicates all present circular or iBeacon regions. The `location` message is made persistent if you use MQTT.

I don‘t understand why you think MQTT means public? If you use your own instance the protocol can be encrypted with TLS snd you don‘t expose any data or metadata.

There is no way to update the status at a certain interval without using Move mode. Move mode consumes your battery quickly, so for your use case I would recommend looking at the `inRegions` array.

If I understand you correctly, you are using mobile iBeacons. If you specify a negative value for radius, the position of the beacon will be updated everytimr you enter it‘s perimeter. The location of the iBeacon region is sent persistent with each update.

**Comment by ckrey** [comment]
@josh-m-sharpe does my answer help?

**Comment by josh-m-sharpe** [comment]
This fell off my priority list a bit, but I'll be testing it soon.  I'll post back here - I still want this thing to work for me.  Thanks!

**Comment by josh-m-sharpe** [comment]
I opened up mqtt publicly, and I do get updates from the app.
