### ISSUE TITLE
Does move mode only works in foreground?

### ISSUE THREAD

**Issue by philipb232** [owntracks/ios#713]
Does the following, from the iOS move mode documentation, mean that the move mode only works when the app is in foreground or does it mean that if the app is in foreground it always is in move mode?

"Please note, move mode is active when the app is active (a.k.a in foreground)."

**Comment by jpmens** [comment]
The app is only in move mode if you switch it to move mode; this doesn't occur automatically. As such it means move mode works when the app is in the foreground, if move mode is enabled.

**Comment by ckrey** [comment]
@philipb232 you are right: The sentence from the booklet you refer is a bit unclear.

> "Please note, move mode is active when the app is active (a.k.a in foreground)."

The answers to your questions are:

- No, Move Mode works in background and foreground
- No, even if the app is in foreground, the Mode remains as selected

When in foreground displaying the map, the map view itself uses high frequency location updates.
