### ISSUE TITLE
Sharing location to people who don't have OwnTracks?

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#714]
Over in [Talk](https://github.com/owntracks/talk/issues/146) we've posted a question we'd appreciate your feedback on.

**Comment by jpmens** [comment]
Recorder 0.9.1 and corresponding Docker image have been released and include WITH_TOURS support.

**Comment by lostfocus** [comment]
Woohoo! This is so neat, thanks!  
A small bug/information: it only seems to work in http-mode when "cmd" is enabled in expert mode. Otherwise it will say that it received an empty tour list.

**Comment by jpmens** [comment]
Enabled cmd is required.

**Comment by lostfocus** [comment]
Yes, sorry, that's what I was trying to say 😅  
I was trying to add the new function to my simple little php endpoint and was wondering why I didn't get the tour list. After I toggled the cmd switch everything works fine. Thanks again! Such a useful feature.
