### ISSUE TITLE
iOS app not reporting region changes?

### ISSUE THREAD

**Issue by jimxbob** [owntracks/ios#719]
I may well be doing something wrong....
I have the OT app set up on 2 iPhones and on an Android phone. I'm using them in HTTP mode to report region changes. Android seems to work OK.
On iOS, it's reporting lat & long OK, but the Regions do not update. They stay coloured with a red circle in the app even when I've walked well outside of the region, and waited long enough (I've reduced "locatorinterval" to 60 and "LocatorDisplacement" to 15), and done a forced location push.
If I alter the lat/long of the region, so that I'm outside it, then it does change the circle to blue, and transmits the correct inregions list over HTTP.
I.e. - if I alter the region so that I fall outside it, it works as it should. If I move the phone so that we're outside the region, it fails to update the region status.
I can't find the logs in iOS to investigate further - help!

**Comment by ckrey** [comment]
Region monitorin in the iOS app is done by iOS. Typically a region exit is triggered when you move away more than 50% of the region radius. 

What is your region radius setting?

**Comment by jimxbob** [comment]
25 metres. I'm pretty sure I was well clear of the region, and that the location was reporting OK - I looked on the map view.... I was also trying this on two iPhones.
I might try again tomorrow setting the region radius even lower......

**Comment by ckrey** [comment]
You will not get better results by reducing the radius. Region monitoring works reliable with regions with 50 or 100 meters

**Comment by jpmens** [comment]
Closing as stale
