### ISSUE TITLE
Crash when saving card with no image

### ISSUE THREAD

**Issue by sjpickup** [owntracks/ios#723]
Running version 16.2.5/en_GB, if I "Create Card", then enter a name and press Save, the app crashes.

If I add a photo before saving, it seems to work fine.

**Comment by ckrey** [comment]
Thanks for the hint. A card w/o a photo doesn't make sense. Will block the save button if no photo is selected yet in the next version.

**Comment by ckrey** [comment]
Version 16.3.2 is on its way into the App Store
