### ISSUE TITLE
Is rectangle or polygon possible for waypoints

### ISSUE THREAD

**Issue by Wildbill-Z** [owntracks/ios#725]
Hi, would it be possible to use waypoints which are not just circles with a defined radius but maybe rectangles or polygons?
The company I work at has a size of about 3km*0.5km. If I just use the "middle" and set radius to 1.5km I will be shown in "company" even if I just drive aside. Also automatic change of move mode is toggled in the wrong way. If I set the waypoint to near my bureau (where I am 90% of the time at work) and radius to about 300m, Owntracks shows me leaving the company if I have to go to different buildings or the other end of the company.
Am I getting problems, when I use two different waypoints which overlap? Or will it even be possible to use two or more different waypoints which overlap and have the same name (I just didn't test this)?

Greetings, Jürgen

**Comment by jpmens** [comment]
There should be no problem in using overlapping regions, but you might run into trouble giving them the same names. Even so, if it's enough for you to have regions `Company-01` and `Company-02` and the prefix `"Company-"` is sufficient to recognize where you are, that ought to work.

We do not have rectangles or polygons, and I'm not even sure iOS and Android would support that.

**Comment by Wildbill-Z** [comment]
Thanks for your fast reply. And thanks, I just didn't think about using just a prefix and a number, I think I thought to complicated. 👍 
About shape of waypoints. I just had a look to traccar (no, I won't switch) and it seems, that traccar allows geofencing with circles, rectangles and polygons. And it has a iOS-app, so I thought iOS would make this possible. But having a closer look it seems, that it is the traccar server which handles geofencing without the use of region monitoring in iOS (or Android or whatever)?!
So, Owntracks just is the better solution (for me) and I'll keep it using. And I will try just one or two more waypoints for the company.
Thanks a lot.

Greetings, Jürgen

**Comment by jpmens** [comment]
It is indeed Traccar which does the geofencing and not iOS. You might be interested to know that we actually created the Traccar device interface to OwnTracks and you can use OwnTracks on iOS to publish to Traccar and use the features it provides. 

Our Booklet [describes this](https://owntracks.org/booklet/features/traccar/)

**Comment by Wildbill-Z** [comment]
Thanks, I knew about sending data from Owntracks-App to traccar. But, I'm just happy with owntracks-recorder and frontend and having the data also in iobroker. So I won't set up a traccar server. I first thought if traccar-app has more features, but at  closer look, it just seems to be a dumb location client which send data in an definable interval. and the server is doing all the work. So Owntracks-app seems to provide just more features and I don't see any reason to change something.
I'll close this issue as it seems to be iOS itself limiting to circular regions.
Many thanks.

Greetings, Jürgen
