### ISSUE TITLE
Where does the iOS app derive it label

### ISSUE THREAD

**Issue by captcurrent** [owntracks/ios#730]
I am running OwnTracks in conjunction (well I should say I am trying ).  In the OwnTracks app. It assign a so 42 as an icon.  Where is this derived from?

**Comment by jpmens** [comment]
That id the TID which defaults to the last two letters of the device name. Configure it in settings if you want to change it.

**Comment by captcurrent** [comment]
Thanks for the quick response I had it working with home assurance but that crashed and I am trying with much effort to reviveOn Dec 31, 2022, at 4:18 PM, Jan-Piet Mens ***@***.***> wrote:﻿
That id the TID which defaults to the last two letters of the device name. Configure it in settings if you want to change it.
