### ISSUE TITLE
Home Assistant: Unknown friend with backend

### ISSUE THREAD

**Issue by captcurrent** [owntracks/ios#731]
I have my owntracks configured as user “jh”. But I am also getting a friend “j”. I can’t delete thoughts !
![84274844-8A50-442C-AA7E-27131812C907](https://user-images.githubusercontent.com/67183495/210235907-ac513d43-c17d-4e6d-b045-520fd7141761.png)

**Comment by jpmens** [comment]
What protocol (MQTT/HTTP) are you using?
Do you share with friends?
Have you (recently) reconfigured and have a space at the end of the `topic` in settings?

**Comment by captcurrent** [comment]
Sorry   HTTP I have not shared with anyone I have reconfigured and reinstalled several times as I am trying unsuccessfully to get this to work with home assistantI have no idea and cannot find “topic” in settingOn Jan 2, 2023, at 9:13 AM, Jan-Piet Mens ***@***.***> wrote:﻿
What protocol (MQTT/HTTP) are you using?
Do you share with friends?
Have you (recently) reconfigured and have a space at the end of the topic in settings?

**Comment by ckrey** [comment]
Did you try to swipe left the “j” row? This is how to delete a friend.

**Comment by captcurrent** [comment]
Yep and it keeps coming backOn Jan 2, 2023, at 9:30 AM, Christoph Krey ***@***.***> wrote:﻿
Did you try to swipe left the “j” row? This is how to delete a friend.

**Comment by captcurrent** [comment]
That sort of explains the color rings but not that unknown users..


Very buggy app

**Comment by jpmens** [comment]
If you feel the app is so buggy, we recommend you delete it and no longer use it.

**Comment by captcurrent** [comment]
It would be as buggy if there was one documentation


Where except in the issue is the meaning behind the border colors discussed?

**Comment by captcurrent** [comment]
Based on your response.    I sort of understand the color borders

I am running Http: mode as it appears simpler for someone having problems like me
I remain fairly confused as to the settings  on the iOS apps




DeviceID: not quite sure what this is supposed to be.  I have tried my phone id which is jay-phone 

UserId;  I assign.  Only the last three letters appear oin the map. So keep it short my case

Authenticationj is ON

Password:  Not too sure what is correct .   I am using my user password from Home Aiistant

Seretr Encryption:    copied from the integration   as is the HTTP following it




And a blue circle around owntrack/jh/Jay-phone (using the "one “ sd the map ID

There is nothing on the Homeassistant map from owntracks

In the past I was able to get the tracking and icon and waypoints from owntracks on the Homeassistant Map


I am 90% sure my problem is with homeassitant.  That community openly admits their documentation if outdated by several years.



Any thoughts work be appreciated.. 6 months ago I had this working and loved it


Jason

**Comment by captcurrent** [comment]
I seem to pretty much havw OwnTracks working back to level where I had it before my virtual machine had to be rebuilt.  The remaining question I have is that I have a friend in myself  Based on the link you provided green circle contact are derived from home assitant.   I don’t have a “J”.  My device is “Jay-phone”. On Jan 3, 2023, at 9:35 AM, jason hirsh ***@***.***> wrote:﻿It would be as buggy if there was one documentationWhere except in the issue is the meaning behind the border colors discussed?On Jan 3, 2023, at 7:47 AM, Jan-Piet Mens ***@***.***> wrote:If you feel the app is so buggy, we recommend you delete it and no longer use it.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ckrey** [comment]
No news for more than a year, closing issue
