### ISSUE TITLE
Do the Move mode settings outlined in the documentation exist?

### ISSUE THREAD

**Issue by mckennajones** [owntracks/ios#732]
In the documentation there is mention of `x` and `t` settings to tweak the meter and second values for move mode location reporting: https://owntracks.org/booklet/features/location/#move-mode

Looking at the settings page of the iOS app I see no such settings. Am I missing them?

**Comment by ckrey** [comment]
@mckennajones thanks for spotting this. The two parameters were renamed to match the Android version:
- `x` is `locatorDisplacement`
- `t` is `locatorInterval`

The documentation in the booklet is now updated

**Comment by mckennajones** [comment]
Perfect thanks @ckrey!
