### ISSUE TITLE
Is it possible to configure OwnTracks iOS application to start on startup in background?

### ISSUE THREAD

**Issue by demokedes** [owntracks/ios#733]
I have configured owntracks to send my location to my mqtt server. I am satisfied with how it works. The only thing that botheres me is the fact that owntracks app has to run in in the background. That is a problem especially after each restart of the device. It is not realistic for me, to remember to turn  it on after each restart. Is it possible to configure it, to run in background automatically? Thank you for your answers/ideas in advance!

**Comment by jpmens** [comment]
OwnTracks on iOS starts up in the background automatically, and continues working if the app is set to "Significant" changes. (This does not work in "Move" mode which would also drain the battery pretty quickly.)

If this is not working for you, are you swiping the app out when closing it? That's something which isn't necessary.

**Comment by demokedes** [comment]
Hey jpmens,
I just tested it, and you're right. When it is set as significant, it is started automatically. The only think, that I have to be carefull is to  not close it by swipping it up, when closing it. Thank you!

**Comment by demokedes** [comment]
ALthough In theory it looks fine, in practice after few fays of usage it is not woking as expected. After day or two, owntracks on ios is not sending data, although I am doing significant moves. I check whether it is running and I see it under application running in the background. If I open it, to become active, than it is sending again....but not forever. What might be the reason for that?
