### ISSUE TITLE
503 errors last few days

### ISSUE THREAD

**Issue by lorenzothurman** [owntracks/ios#734]
I’ve been getting 503 errors for the last few days. Updated have been backing up and I have over 600 pending updates. When I first noticed, I took my iPhone 13 Pro off Wi-Fi, and the pending updates went out. But that has not worked since. Any ideas, beyond a complete restart, which I’ve tried?

**Comment by jpmens** [comment]
>I’ve been getting 503 errors for the last few days. 

You're not saying which backend you are using nor which protocol, but if it is HTTP, the 503 indicates that the service is not available, so I assume that whatever you're using has 'died' and is therefore not accepting the device location posts.

**Comment by lorenzothurman** [comment]
"My Break-Dancing days are over, but there's always the Funky Chicken" -- The Full MontyOn Jan 26, 2023, at 1:48 PM, Jan-Piet Mens ***@***.***> wrote:﻿
>I’ve been getting 503 errors for the last few days. 

You're not saying which backend you are using nor which protocol, but if it is HTTP, the 503 indicates that the service is not available, so I assume that whatever you're using has 'died' and is therefore not accepting the device location posts.



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
I’m using the OwnTracks integration with home assistant configured for http. I’ll go back through my configuration and make sure it’s all still good. Nothings changed in months, so I assumed the problem was elsewhere. I’ll followup after I’ve backtracked.

**Comment by lorenzothurman** [comment]
I went back over the setup instructions and everything looked correct. But updates still weren’t being pushed…until late last night. About 1am, the backlog of updates started clearing up. I still have no pending updates. Not sure where the break was, but things seem to be fine right now and my webhooks are firing again. "My Break-Dancing days are over, but there's always the Funky Chicken" -- The Full MontyOn Jan 26, 2023, at 1:48 PM, Jan-Piet Mens ***@***.***> wrote:﻿
>I’ve been getting 503 errors for the last few days. 

You're not saying which backend you are using nor which protocol, but if it is HTTP, the 503 indicates that the service is not available, so I assume that whatever you're using has 'died' and is therefore not accepting the device location posts.

**Comment by jpmens** [comment]
It is to be assumed that the backend was down for a while. 
Glad it's working again.
