### ISSUE TITLE
Altitude

### ISSUE THREAD

**Issue by VanDeStouwe** [owntracks/ios#735]
I'm using the Openhab GPSTrackerbinding. I notice that the location heigth is not updated. Is there anyway that Owntracks IOS sends Heigths?

**Comment by jpmens** [comment]
OwnTracks on iOS sends the height as a number in the "alt" element of the published JSON location type.

**Comment by VanDeStouwe** [comment]
With trace on the binding I found indeed the altitude under "alt" see:
`Post message received from OwnTracks tracker: {"batt":81,"lon":4.6459339999999996,"acc":18,"bs":1,"p":102.06699999999999,"BSSID":"64:d1:a3:43:64:19","SSID":"Bateleur_5GHz","vac":20,"lat":52.421568000000001,"topic":"owntracks\/sidney@vandestouwe.com\/2C45AD11-C37A-49E3-9719-62F194D7C466","conn":"w","m":2,"tst":1675352004,"alt":3,"_type":"location","tid":"66"}`

It turns out that this is not added to the location channel
