### ISSUE TITLE
16.3.2

### ISSUE THREAD

**Issue by luckman212** [owntracks/ios#736]
Hello 👋 

I was wondering: is the only way to get v16.3.2 on your device to compile it yourself with Xcode and sideload it? Last version in the US AppStore is 16.2.5 currently. (Thank you for the project)

**Comment by ckrey** [comment]
When I find some time for the upload and approval process, update the docs, etc., I will publish the recent version to the app store. Probably this month

**Comment by luckman212** [comment]
Okay, I am behind on a lot of projects myself so believe me I know how busy things can get. No rush at all I was just asking. Thank you again

**Comment by ckrey** [comment]
@luckman212 16.3.2 is on its way into the appstore
