### ISSUE TITLE
Mode change option on app icon press (on iOS)?

### ISSUE THREAD

**Issue by ionos** [owntracks/ios#737]
Feature idea: Allow users to change the recording mode via the pop-up menu that shows up when pressing the app icon a bit longer (sorry, not sure what the proper name is).

Thank you!

**Comment by jpmens** [comment]
I think they are called _Home Screen quick actions_.

**Comment by ckrey** [comment]
You already have the option to change monitoring mode via the
- OwnTracksToday Widget
and you may create an Siri Shortcut to change monitoring mode and place it on your Home Screen

**Comment by ionos** [comment]
Thank you for pointing that out, @ckrey . These are good fallback options. The quick actions tend to be my personal favourite, 's all. If it can't be implemented, the fallbacks will do. Thank you!

**Comment by ckrey** [comment]
Will be in the next release >= 16.4.0

**Comment by ckrey** [comment]
Will be available as 16.4.1 in the App Store soon
