### ISSUE TITLE
Multiple "Move" modes?

### ISSUE THREAD

**Issue by ionos** [owntracks/ios#738]
Feature idea: Allow for multiple "Move" modes with different time/distance settings.

This would allow users to quickly change between modes optimized for different activities (walking vs. driving, one would probably set different min. distances).

Would go nicely with #737.

Background: I use OwnTracks for personal location history recording, e.g. to tag photos etc. The "Significant Move" mode tends to be too coarse for many use cases. E.g. we drive, stop at a certain point of interest, walk around for a while (just a few meters), keep driving - this won't be reflected at all in the published locations, as the walking around did not cover enough distance to trigger another location update - I'd have preferred to have a "time expired OR distance travelled" settings as a default. With a single configuration setting, however, it's tricky to find a setting that works for every use case.

OS: iOS 16.3.1
App: 16.3.2

P.S: Apologies if this is a duplicate, I did not see any existing issue for this request.

**Comment by jpmens** [comment]
This would necessitate a lot of UI interaction and would likely also mean lots of confusion when debugging. Not sure this is a good idea.

**Comment by ionos** [comment]
> #737 is implemented already. Does this work for you?

The intent of this feature idea, IIRC, was to have multiple user-customizable modes. #737 rather deals with activating (the hardcoded) modes.

**Comment by ckrey** [comment]
We are not planning to implement multiple Move Mode settings
