### ISSUE TITLE
iOS app zoom

### ISSUE THREAD

**Issue by jevans10** [owntracks/ios#744]
My iOS app is stuck on a view of the US. I can’t find how to zoom in at all. I’ve added a region, Double taped, pinched with my fingers, clicked on my friends. You feel like I’m missing something.

**Comment by jpmens** [comment]
The usual pinch and un-pinch should do the trick; I wonder if it's 'frozen'. Can you please try to swipe-out the app and relaunch?

**Comment by jevans10** [comment]
This worked for me, thank you!Sent from my iPadOn Aug 1, 2023, at 11:01 AM, Christoph Krey ***@***.***> wrote:﻿
You did select “no” for map interaction during setup for privacy reasons.
Please press the map symbol on the top level to change the setting

**Comment by jevans10** [comment]
I force quit the app and reinstalled it. The issue persisted.Then I change the interaction settings and it worked. Thank you!Sent from my iPadOn Aug 1, 2023, at 10:43 AM, Jan-Piet Mens ***@***.***> wrote:﻿
The usual pinch and un-pinch should do the trick; I wonder if it's 'frozen'. Can you please try to swipe-out the app and relaunch?
