### ISSUE TITLE
Remove all friends via UI

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#746]
From the Friends list, add a button to remove all entries except your own.

As requested by Chad:
On Fri, 11 Aug 2023, at 12:12 AM, Chad Gibeaut wrote:
Hello!

I see there is a "clear" option for a specific client,  but I really wish there was a way to clear all existing clients.  I currently have a couple hundred stale locations on the map, and going through one by one to remove them is pretty tedious....  guess I could just Uninstall and start over...

**Comment by jpmens** [comment]
> a couple hundred stale locations on the map

How does that occur? Doubtful to me that a button on the UI will solve the issue, particularly as you wrote the OP that it’s also an ACL problem with regard to the broker.

**Comment by ckrey** [comment]
Von: "c@ckrey.de" <c@ckrey.de>
Betreff: Aw: OwnTracks removing friends
Datum: 29. August 2023 um 18:37:13 MESZ
An: Chad Gibeaut <chad.gibeaut@gmail.com>
Kopie: support@owntracks.org

Hi Chad,

are you talking about the stale locations you see on the mobile clients (Android/iOS)?

If so where do all those stale clients come from? What is your environment?

If we delete on the clients, we can only remove them from the client’s database and try to delete them on the backend (broker).
Deleting on the broker will only succeed if we have sufficient access rights. Otherwise the other clients will reappear even if
deleted locally when they do their next update.

Awaiting your thoughts.

Cheers,
   Christoph

**Comment by ckrey** [comment]
Not implemented!
