### ISSUE TITLE
Latest version for iOS crashes on loop with 17494 locations cached to publish

### ISSUE THREAD

**Issue by synedu** [owntracks/ios#747]
I've been using owntracks without issue for years now, terrific app. I have a docker containers with a complicated set up that ultimately consumes the mqtt messages from the owntracks app (looks like an MQTT server from the client point of view). Anyway, it stopped receiving messages, and I thought, no problem, I will fix this whenever, but now GPS points aren't increasing, and the app crashes when I try to open it after 5-10 seconds.

Do I have any recourse here? Any way to debug?

**Comment by ckrey** [comment]
you may check if there is a meaningful error message on the info screen

Otherwise: do you have a log on the broker side?

**Comment by ckrey** [comment]
Or, change the connection parameters to “cleansession=on”. This will clear the cache on client and broker side

**Comment by ckrey** [comment]
make sure you have enabled “Settings/Analytics/Share wit Developer“ so I will see your crash log eventually

**Comment by synedu** [comment]
It crashed immediately upon loading again and again, then suddenly it is fine again and showing it is getting a connection refused from my broker. So now I think I am back in business. I'll check that it will send you the log. There may be some kind of issue when there are too many GPS points that have not been sent but I doubt many users will run into it.

I am a donor by the way, thanks for the great software! I will close this.

**Comment by jpmens** [comment]
@synedu thank you for being a donor and for the kind words.
