### ISSUE TITLE
Deleting friend deletes waypoints? No map search?

### ISSUE THREAD

**Issue by strunker** [owntracks/ios#749]
2part question comment.
1) Recently i established a bunch of waypoints. Which seems to chain back to a friend? right now I have one friend, which is really myself, and all my waypoints are attached to that one friend? Seems like a weird design, unless Im not understanding something? 
my goal with way points is to establish known locations and have those get passed to the back end.
2) The map has no search feature I have been able to find? It would be nice to be able to search in advance and establish waypoints for known places without having to physically be there to do it, or without having to swipe through the map to locate things.

Thanks.

**Comment by ckrey** [comment]
1. Yes, regions (a.k.a. waypoints) are linked to friends. In the friends list, your own "friend" is marked with a blue border. Your waypoints are linked to that "friend". This may seem "weird", but was an early design decision. Originally we planned to store/show regions of friends too.

2. Correct, there is no map search feature
