### ISSUE TITLE
Background updates

### ISSUE THREAD

**Issue by fig2k4** [owntracks/ios#751]
I get that ios has restrictions for GPS updates, but I don't get why there's no updates for the battery level or the "ping" mentioned in the documentation.

"Note, however, that the app will publish a ping-type message once in a while."

I need this ping to tell if the phone is still in the current location.  For all I know, the battery is dead and it will never report the location again.

Is there a reason why the battery level isn't being reported when it changes?

**Comment by ckrey** [comment]
Sorry, there is no way to report battery changes in iOS when the app is not running actively. And the only way to keep OwnTracks running actively is to use "Move" mode which on the downside consumes a lot of battery.

The best practice is to setup a ["follow" region](https://owntracks.org/booklet/features/ios/#region-monitoring-with-follow). This works very reliable as long as the phone is not dead. If you don't get an update you can assume the phone is close to it's last reported location.
