### ISSUE TITLE
App sends everything except for location data

### ISSUE THREAD

**Issue by jpcastberg** [owntracks/ios#757]
Hey - I have set up a mosquitto server, the owntracks recorder, and the app set up on iphone (app has "always" access to location).

Everything seems to talk to each other okay - the phone app shows as being connected to the MQTT server via TLS+websocket, and the recorder is subscribed to `/owntracks` publishes. I know that this flow works because I have been able to publish a card and publish my settings from the app, which are both picked up and saved by the recorder.

The problem is that the app doesn't seem to be sending any location data. I have verbose logging turned on in mosquitto so I can see all incoming publishes. I went on a long walk, and there were no location updates. The documentation says that there is a way to manually publish location from the app, but I am not seeing that anywhere. Hoping to get some guidance for how to debug this. Below is my app configuration json, please let me know if any more information is needed.

```json
{
	"_type": "configuration",
	"allowinvalidcerts": false,
	"allowRemoteLocation": true,
	"auth": true,
	"cleanSession": false,
	"clientId": "",
	"clientpkcs": "",
	"cmd": false,
	"deviceId": "iphone",
	"downgrade": 0,
	"extendedData": true,
	"host": "my.domain.com",
	"ignoreInaccurateLocations": 0,
	"ignoreStaleLocations": 0,
	"keepalive": 60,
	"locatorDisplacement": 200,
	"locatorInterval": 180,
	"locked": false,
	"maxHistory": 0,
	"mode": 0,
	"monitoring": 0,
	"mqttProtocolLevel": 4,
	"passphrase": "",
	"password": "fake_password",
	"port": 443,
	"positions": 50,
	"pubQos": 1,
	"pubRetain": true,
	"pubTopicBase": "",
	"ranging": false,
	"sub": true,
	"subQos": 1,
	"subTopic": "",
	"tid": "JC",
	"tls": true,
	"url": "",
	"usePassword": true,
	"username": "abstraktion",
	"waypoints": [],
	"willQos": 1,
	"willRetain": false,
	"willTopic": "",
	"ws": true
}
```
![IMG_C4DE7BA89E59-1](https://github.com/owntracks/ios/assets/37011196/26ac9be5-9861-4b4d-b5be-efaf91f50372)

![image](https://github.com/owntracks/ios/assets/37011196/0c4aa7af-ca75-4338-83f1-fdcc585cda84)

**Comment by ckrey** [comment]
The default publish topic is `owntracks/<user>/<device>` (without the `/` prefix). The recorder should be subscribing to `owntracks/#`.

You have ser monitoring mode (selection on the top of the map). This means the app does not send any locations unless you use the action button on top right in the navigation bar. 

You may want to use `significant` or `move` mode.
![IMG_9808](https://github.com/owntracks/ios/assets/4027289/402b3f1a-4f38-4b47-b7e1-5698adffce84)

**Comment by jpcastberg** [comment]
Thank you - yes, my problem was an issue of using the wrong mode. It was on quiet mode and I did not yet understand what that meant. A link for anyone that may stumble on this thread in the future: https://owntracks.org/booklet/features/location

I have a follow up question - I do not seem to have an option to use the icon in the action bar. Is there a setting to enable it? Notice in the video it is greyed out, it does not respond to any tap action. Thank you again for your prompt response.

https://github.com/owntracks/ios/assets/37011196/2ea594bb-4974-45c8-840b-f8e6ee335d6f

**Comment by ckrey** [comment]
It is greyed out as long as your phone does not have a location available. The dash in front of the action button will show the current accuracy of your position if available. 
Please check "Settings/Privacy/Location" settings for OwnTracks. It should be "always" or "when in use". Do you see the position indicator on the map?

**Comment by jpcastberg** [comment]
Hm, seems like my phone is having trouble getting a location when I am at home, so likely an issue at the device level, not the app level. I'll go ahead and close this. Thank you so much for your help!!
