### ISSUE TITLE
Stale location not sending in background

### ISSUE THREAD

**Issue by debugger24** [owntracks/ios#758]
Hi all,

First of all thanks for this awesome project. I recently started using it and have few questions/issues.

I had installed the app few months back but didn't get chance to set recorder. Now when I set recorder (using HTTP) I can see stale locations are being published.

1. Stale locations are being published only when the app is in the foreground, in the background it is not being published. Is this expected?
2. In the app can we see the progress of how much stale data backlog is pending?
3. The configuration `ignoreStaleLocations` is not set by default, what is the meaning of the null value here? Infinite?

Here is the config export for my iOS App

```
{
  "username": "debugger24",
  "maxHistory": 0,
  "positions": 50,
  "sub": true,
  "locked": false,
  "deviceId": "",
  "ranging": false,
  "monitoring": 1,
  "cmd": false,
  "tid": "01",
  "allowRemoteLocation": true,
  "_type": "configuration",
  "url": "https://www.example.com",
  "ignoreStaleLocations": 0,
  "waypoints": [],
  "allowinvalidcerts": false,
  "usePassword": false,
  "auth": false,
  "locatorInterval": 180,
  "extendedData": true,
  "ignoreInaccurateLocations": 0,
  "locatorDisplacement": 200,
  "mode": 3,
  "password": "pass",
  "downgrade": 0
}
```

Few questions regarding app settings.
1. When I am in HTTP mode, I still see all the MQTT configurations like topic, client, pub, etc any specific reason for showing these even in HTTP mode?
2. There is a location displacement setting, in the docs it was mentioned in Significant Mode displacement required in 500m, does setting `locationDisplacement` override 500m in Significant Mode or is this `locationDisplacement` for specific mode only (like move mode).

**Comment by ckrey** [comment]
> When I am in HTTP mode, I still see all the MQTT configurations like topic, client, pub, etc any specific reason for showing these even in HTTP mode?

The display in settings changes when toggling between MQTT and HTTP mode in the upper section of the settings screen.

The configuration settings you refer to are all in the "Expert Mode" section which you may ignore. We may consider making the "Expert Mode" section depending on MQTT/HTTP mode too

**Comment by ckrey** [comment]
> There is a location displacement setting, in the docs it was mentioned in Significant Mode displacement required in 500m, does setting locationDisplacement override 500m in Significant Mode or is this locationDisplacement for specific mode only (like move mode).

No, the two settings only apply to "Move mode" https://owntracks.org/booklet/features/location/#move-mode

**Comment by ckrey** [comment]
> The configuration ignoreStaleLocations is not set by default, what is the meaning of the null value here? Infinite?

Maybe this is a language thing. Stale locations are locations sent by "friends". If their last location update is older than "ignoreStaleLocations"  seconds, they are not shown on the map. If "ignoreStaleLocations" is set to 0, no filtering happens. We may add this to the booklet https://owntracks.org/booklet/tech/json/#_typeconfiguration

**Comment by ckrey** [comment]
> Stale locations are being published only when the app is in the foreground, in the background it is not being published. Is this expected?
In the app can we see the progress of how much stale data backlog is pending?

There is no backlog for something like "stale" locations. 

Not sure what you expect. I can see you are in "Significant Changes" mode ("monitoring": 1). In this mode the app will not publish anything unless you move at least 500 meters and will not push more than once in 5 minutes in background.
https://owntracks.org/booklet/features/location/#significant-location-change-mode

If you want the app to publish more accurately when you e.g. enter or leave your home, Please set a region 
https://owntracks.org/booklet/features/waypoints/
Regions trigger in "Significant Changes", "Manual" and "Move" mode and are quite reliable in Background

**Comment by debugger24** [comment]
So currently my iOS device is continuously publishing locations when app in forground and I am not moving.

And these are 3-4 months old data being sent to recorder sequentially since I installed app.

The timestamp and locations makes sense to me, it is 3-4 months old as expected.

So I am assuming owntracks kept all those data in storage/kept retrying till my recorder came online (i.e. today).

**Comment by debugger24** [comment]
So I wanted more visibility and configuration on this older data backfilling.

**Comment by debugger24** [comment]
Thank you.

1. So can we say the recommended way to send this backlog is to change the mode to Move temporarily so that it can quickly complete the backlog in the background and later change back to Significant mode?

2. Can we implement something to send this data in bulk instead of individual API calls?

3. Also, can we prioritize current location data over backlog so live data is available for others.

**Comment by ckrey** [comment]
There are no plans to change the app, recorder etc. to bulk mode HTTP uploads. MQTT handles backlogs a lot more elegant. 

We will not change the order of delivery.

**Comment by debugger24** [comment]
Thank you, @ckrey. I will explore the MQTT implementation at a later time.
