### ISSUE TITLE
Question: Is it possible to configure the iOS app to send custom http headers?

### ISSUE THREAD

**Issue by marceloaf** [owntracks/ios#761]
Hi. Hope this finds you well.

My Home Assistant installation is behind Cloudflare with Service Token. When I access the webhook url in my HA I need to pass the clientid and clientsecret as headers. Is it possible to configure the iOS app to use such custom http headers?

Thanks in advance,
Marcelo

**Comment by jpmens** [comment]
This is currently not possible, but is probably a good idea, as custom HTTP headers can be useful in a multitude of situations.

**Comment by ckrey** [comment]
Text settings parameter contains extra HTTP headers.
- `<field-name>:<field-content>`
- multiple fields separated by `\n` in text or '\\n' in JSON
- Example in configuration JSON: 
>   ...
"httpHeaders": "CF-Access-Client-Id: bd2744144725d2651d39363df6807599.access.owntracks.org\\nCF-Access-Client-Secret: 3e2c2ad371b00777a443f0c639c103687e4fcf73e0c3371cb1cbd6"
...

**Comment by ckrey** [comment]
@marceloaf here is the link to a public beta of the new version. It would be highly appreciated if you test to connect to your backend via Cloudflare and leave your feedback here.

https://testflight.apple.com/join/k2iqRtjH

**Comment by marceloaf** [comment]
Very cool guys! Apparently, it's working perfectly! ☺ 

Just sent a manual update at 16:19 my time and HA received it correctly! I'll leave now to do some errands and to do some further tests. Thank you very much! 

I had done a small donation earlier today, but as I was not used to the platform it apparently split the value throughout the year... :-( My intent was to do it immediately! Anyways...

![Owntracks update](https://github.com/owntracks/ios/assets/11551691/68627b39-8e02-4e61-89f0-770bb7fb52e6)

<img width="597" alt="image" src="https://github.com/owntracks/ios/assets/11551691/ecedb8c3-06ac-49a3-b4f3-1ea966b987ef">

**Comment by jpmens** [comment]
Much appreciated, thank you!

**Comment by Jaconah** [comment]
@marceloaf  Long shot, but do you any advice on how you originally get this configured?  I have created a service auth in my cloudflare zero trust portal and set it up similar to the example listed just with my values

"CF-Access-Client-Id: bd2744144725d2651d39363df6807599.access\nCF-Access-Client-Secret: 3e2c2ad371b00777a443f0c639c103687e4fcf73e0c3371cb1cbd6"

However every time it attempts to send I get a 301 error.

**Comment by marceloaf** [comment]
Hello Ryan! Hope this finds you well.

I apologize for not answering before. Things went crazy these past days as my iPhone was robbed and I was pretty busy trying to get things up and running again. The own tracks configuration was on this this phone so I couldn't answer before.

Mine is pretty much like the example you gave without the initial and final double quotes.

Hope this helps.

Regards
Marcelo

Obter o Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Ryan ***@***.***>
Enviado: Tuesday, November 12, 2024 7:33:29 PM
Para: owntracks/ios ***@***.***>
Cc: marceloaf ***@***.***>; Mention ***@***.***>
Assunto: Re: [owntracks/ios] Question: Is it possible to configure the iOS app to send custom http headers? (Issue #761)


@marceloaf<https://github.com/marceloaf> Long shot, but do you any advice on how you originally get this configured? I have created a service auth in my cloudflare zero trust portal and set it up similar to the example listed just with my values

"CF-Access-Client-Id: bd2744144725d2651d39363df6807599.access\nCF-Access-Client-Secret: 3e2c2ad371b00777a443f0c639c103687e4fcf73e0c3371cb1cbd6"

However every time it attempts to send I get a 301 error.

**Comment by jpmens** [comment]
(OP deleted 2nd to last comment; I deleted response by mail to deleted comment as it made no sense.)
