### ISSUE TITLE
Non funziona in gsm ma solo in Wi-Fi in background!!

### ISSUE THREAD

**Issue by Aleks2399** [owntracks/ios#762]
IOS- La modalità Move o meglio tutte, inviano in background solo in Wi-Fi, mentre in gsm non funziona più dopo qualche aggiornamento o iOS o di OWN, prima funzionava ed era famstastica, così sinceramente per l’uso che ne faccio per la domotica non mi serve più a nulla!! Ed è un peccato perché era la migliore ****

**Comment by jpmens** [comment]
Closing as stale.
