### ISSUE TITLE
Imperial Units in iOS UI

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#765]
As submitted in https://github.com/owntracks/android/issues/1573 and discussed in https://github.com/owntracks/android/discussions/1571, there is an enhancement idea to have the UI present data in Imperial units? Feet, miles, mph, etc.

I'd assume a toggle in settings which defaults to metric.

In favor of feature parity between the apps, I link this here.

**Comment by ckrey** [comment]
In iOS, the user can use "Settings/General/Language&Region/Measurement System" to select the system.
<img width="347" alt="Bildschirmfoto 2024-01-10 um 19 23 25" src="https://github.com/owntracks/ios/assets/4027289/d9f924f9-8536-463c-9141-d29f5cca1ec3">

**Comment by ckrey** [comment]
Will use 
- feet (ft) for altitudes and accuracy
- miles per hour (mph) for speed
- yards (yd) for short distances (less than a mile)
- miles (mi) for long distances
- 

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-10 at 20 39 59](https://github.com/owntracks/ios/assets/4027289/f4e2f942-1c00-4239-a5f4-08005956d3d7)

**Comment by jpmens** [comment]
Looks good to me!

**Comment by ckrey** [comment]
Using Apple Foundation's NSMeasurementFormatter now:

> ... Representations of measurements are reduced and converted into a more convenient unit, when possible. For example, a quantity of 12000 meters would be represented as 12 kilometers.

**Comment by ckrey** [comment]
Use `Region` to change settings! Changes to `Measurement System` affects Apple Maps only!

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-01-15 at 14 52 52](https://github.com/owntracks/ios/assets/4027289/b051bf52-3132-43c1-8246-49f75ac571e9)

**Comment by ckrey** [comment]
Available since version 17.1.1
