### ISSUE TITLE
"Change Monitoring Mode" doesn't work if the app is on the settings page

### ISSUE THREAD

**Issue by hepcat72** [owntracks/ios#768]
I sat down to do some more testing and I had written a simple shortcut to open the app (although I didn't test if that was necessary) and change the monitoring mode (to "move", though I tried multiple settings).

## Steps to Reproduce

1. I was on the OwnTracks settings page and the monitoring value was `1`.
2. I switched to Shortcuts and ran the shortcut to change the mode to "move".  It opened OwnTracks, but the setting didn't change.
3. I backed out to the map view (still set to "significant")
4. I switched to the Shortcuts app again and ran it again.  This time it worked and switched to "move".

I repeated this multiple times.  Apparently, you can't leave the OwnTracks app on the settings page and expect the shortcut action to work.

## Notes

I also tried the "Send Now" while on the Owntracks settings screen, and that works. It sends my location despite being on the settings screen.

**Comment by ckrey** [comment]
Included in 17.2.5
