### ISSUE TITLE
Revisit Address publishing?

### ISSUE THREAD

**Issue by lnjustin** [owntracks/ios#769]
I see in the closed issues that, about 3-4 years ago, others requested publishing of the reverse geocode address results. At the time, it was decided not to publish this information, in the interest of keeping data transfer low. Has anything changed in the last few years to justify a different decision now? I would kindly request reconsideration if so, as it seems the address information would be quite useful to some. Thanks for your work on this open-source project!

(refers to #616)

**Comment by ckrey** [comment]
In addition reverse geocoding is rate limited on the iPhone. Therefore we do not use it for all sent locations, but only when a location is displayed on user request.

This is in line with [CLGeoCoder | Apple Developer Documentation](https://developer.apple.com/documentation/corelocation/clgeocoder?language=objc)

We will therefore not publish address from the iOS app
