### ISSUE TITLE
URL config requires disconnect / connect

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#770]
When clicking on a link with [URL config](https://owntracks.org/booklet/features/remoteconfig/) or inline configuration, the configuration is loaded, but the app doesn’t reflect it.

Only after swipe out / launch is the new configuration used.

**Comment by ckrey** [comment]
fixed in e47d842c499c84d30a7d62d48d111025b50b4c94

**Comment by jpmens** [comment]
Thank.
