### ISSUE TITLE
Tour submission (cmd) isn't encrypted in payload

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#773]
I'm not sure this is a bug, more like a discussion point:

I notice that creating and submitting a Tour causes an MQTT publish with a clear-text payload in spite of secret key encryption being enabled on iOS / Recorder.

I tend to think we should encrypt these payloads as well.

**Comment by ckrey** [comment]
All messages from the app are encrypted if the encryption key is set.
The encryption key cannot be set remotely (via .otrc, inline url, or `cmd`)

**Comment by jpmens** [comment]
```
+++++ [owntracks/jip/iPad/request (plen=239, r=0) [{"_type":"encrypted","data":"pFlC...
+++++ [Key for jip-ipad is [...
+++++ [START DECRYPT. clen==155]
+++++ [DECRYPTED: {"_type":"request","request":"tour","tour":{"from":"2024-02-...
+++++ [owntracks/jip/iPad/request (plen=115, r=0) [{"_type":"request","request":"tour","tour":{"fro
```
