### ISSUE TITLE
Make encryptionKey for payload encryption configurable over .otrc

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#774]
We discussed internally that we are changing our minds as to the configurability of `encryptionKey` for nacl payload encryption. First of all, our Android app has provision for doing so, and second of all our original fears of being able to "lock" a device.

In par with Android, the .OTRC setting will be `encryptionKey`.

**Comment by jpmens** [comment]
I confirm working:
- publish of settings contains `encryptionKey` ✅ 
- otrc config (also URL) loads `encryptionKey` ✅ 

However, loading of otrc config **without** an encryption key doesn't clear the field:
- length of previous value still visible in settings UI
- export Settings (via mail) contains previous value

I'm not saying this is a bug, but in terms of https://github.com/owntracks/ios/issues/771 we might wish to fix this.

**Comment by ckrey** [comment]
Included in 17.2.5
