### ISSUE TITLE
remote cmd in background ios17.2

### ISSUE THREAD

**Issue by killah78** [owntracks/ios#777]
Hi, 
I just give it a try and ask you for help. 
I use owntracks in combination with fhem to report locations. Broker is the fhem internal mqtt2server. 
owntracks is the ios version all needed settings are turned on. 
TLS not used. 

the "normal" reporting in significant mode works fine, but I got no responses on remote commands(in background) and I have no clue why. When app is open in foregound immediate responses are sent. 
I checked the settings for remote commands, as well as settings for gps and background services. all is set correctly. 
I don't expect a realtime response (in background), as I read it's not possible with iphone, but I get no response at all. 
No location reporting, no waypoints, no config. I send with qos 0,1 and 2. No change. 

I have no problems with Android, there the answer comes in realtime after the request. 

So, is it really working with owntracks on ios 17.2? Can somebody confirm that? Then I could go on searching for a solution. Or is it generally not possible in background to request locations?

Thanks

**Comment by jpmens** [comment]
Have you published your cmd with QoS > 0? The app goes to sleep in iOS and is only woken up periodically after which it will see the cmd. That's the reason you see immediate effect when the app is open.

**Comment by killah78** [comment]
Yes, same behavior with qos 0,1,2. But there is no response at all when the app is in background. If there was an answer for example after 5 mins, that would be ok. but there is no  answer at all in background. Background service in ios is on for owntracks. 
But in general it should work that owntracks answer in background on remote commands? not in realtime but with some delay?
I mean I guess this is the normal use case. The app will be always in the background normally. And with remote cmd i request a location, or switch to move mode..... Is there a kind of log in the app, where I can see if the remote cmd arrived?

**Comment by ckrey** [comment]
Yes there is a log accessible via the status screen (the „i“ button top left).

The iOS app is not connected while in background. 

It connects if it gets an location update or is woken up to do a background fetch. Don‘t expect this to happen regulary or within minutes. 

If you send a command with QoS>0 it will executed eventually. 

When you move the device with will send location updates and pick up commands. Im Significant Mode you can increase the number of updated by setting up Regions and a +follow region especially http://owntracks.org/features/ios/
