### ISSUE TITLE
Value of atmospheric pressure missing on settings

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#779]
![IMG_7142](https://github.com/owntracks/ios/assets/60706/eb1f4bca-56dd-4b50-b7bb-811969fc66a5)

As recently discusse, iPhone 13 mini, OwnTracks 17.1.3.

Pressure is being reported in JSON on location publish:

```json
{
  "_type": "location",
  "acc": 35,
  "alt": 110,
  "batt": 68,
  "bs": 1,
  "conn": "w",
  "created_at": 1708331250,
  "m": 1,
  "p": 101.12,
  "t": "u",
  "tid": "jp",
  "tst": 1708331248,
  "vac": 16
}
```

**Comment by ckrey** [comment]
Please tell me your iOS version, language, and region settings

I am running iOS 17.3.1, German or English and the region settings below and get the expected result:

![IMG_9991](https://github.com/owntracks/ios/assets/4027289/f7d36641-02fb-41c0-a773-8a17e0061572)

![IMG_9992](https://github.com/owntracks/ios/assets/4027289/06324c68-76c5-4a6f-9745-50d3b448a253)

**Comment by jpmens** [comment]
iOS 16.7.2
Language English
Region Germany

Temperature C
Measurement system Metric

**Comment by ckrey** [comment]
It may be a layout issue... If you turn your iPhone to Landscape and back, does the pressure value appear?
Other than that it may be an iOS 16.7.2 issue. The methods used are available in iOS>=10.0

**Comment by jpmens** [comment]
Pressure doesn't appear in landscape mode either, also not after a republish.

Let's ignore this for now.

**Comment by ckrey** [comment]
I found an old Xcode 14.2 with an iPhone Simulator 16.2:

The problem you reported is visible in 16.2

**Comment by jpmens** [comment]
Thanks for checking, @ckrey, which means the problem is historic, so I will now close this.

**Comment by jpmens** [comment]
After upgrading iOS to 17.3.1 I see pressure displayed. 

![image](https://github.com/owntracks/ios/assets/60706/06fc14c6-483d-4a6e-b3e2-2d9095488841)
