### ISSUE TITLE
Drop MQTT will related settings parameters

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#780]
Instead as in the Android app:

- always use will
- willTopic is the same as pubTopicBase after User/Device replacements
- willQos is the same as pubQos
- willRetain is always false

**Comment by ckrey** [comment]
otherwise, we will have to add to the docs:
<img width="596" alt="Bildschirmfoto 2024-02-19 um 19 03 30" src="https://github.com/owntracks/ios/assets/4027289/216d0ea3-25cd-492a-9352-8606bd84deef">

**Comment by jpmens** [comment]
I'm for standardizing on these four settings and removing their 'configurability' from the app.

**Comment by ckrey** [comment]
Included in 17.2.5
