### ISSUE TITLE
Delete / Remove POI location

### ISSUE THREAD

**Issue by whmoorejr** [owntracks/ios#782]
Once POIs are created from the iOS app, how are they deleted?

**Comment by jpmens** [comment]
>Once POIs are created from the iOS app, how are they deleted?

POIs aren't deleted. They're part of the history in the app (there's a maximum number of entries configured in settings), and POI are part of the data which is stored for the particular location in the .rec files by Recorder.

Your next question might be: how can I visualize POIs? :-) There's currently only one supported mechanism, which is to use the Recorder API to return GeoJSON with the POI setting. (That's documented.)

There's an enhancement request to add POI display to Frontend, but that's pending.

**Comment by whmoorejr** [comment]
Thank you again.

**Comment by jpmens** [comment]
Closing as answered.
