### ISSUE TITLE
iOS: Change subscriptions $ cmd for monitoring mode change

### ISSUE THREAD

**Issue by whmoorejr** [owntracks/ios#784]
Two questions that I couldn't find documentation on....
For my children's devices, I want them to be subscribed to owntracks/++/++ for locations of other devices.  And subscribed to /++/++/cmd for remote managment, but **not** ++/++/events.  My guess is I need to edit the settings page, first line under "Expert Mode"... but I'm not sure what exactly to put there and I don't want to mess anything up.

Second question.... I've been collecting all the cmd options... is there a command to change the monitoring mode of a device?, i.e., {"_type":"cmd", "action":"setMonitoring", "monitoring":"move"}   I see where you can do this (I think) with remote configuration, but that looks to be only an android thing.

**Comment by jpmens** [comment]
`++` is not a valid MQTT topic; the correct syntax for one level is `+`

That said, I recommend not tweaking the settings on the iOS app, as we're actually talking about simplifying them whereupon they would no longer be supported. Instead look at [Friend-specific MQTT ACLs](https://owntracks.org/booklet/features/qs-config/) during Quicksetup. The default ACL for a user currently is

```
user jane
topic readwrite owntracks/jane/#
topic read owntracks/+/+
topic read owntracks/+/+/event
topic read owntracks/+/+/info
```

I do not see a mention of `setMonitoring` in the Booklet.

**Comment by ckrey** [comment]
You can use setConfiguration in iOS with only the monitoring to be changed.
But remember that you have to publish the message wit QoS > 0 and that it will only be received by the app when it connects next (to transmit a new event or location)

```
{
	"_type" : "cmd",
	"action":"setConfiguration",
	"configuration": {
		"_type" : "configuration",
		"monitoring": 1
	}
}
```

**Comment by whmoorejr** [comment]
As allways, thank you guys very much for your support!  I'm having a lot of fun with owntracks and very impressed with what all it can do.

**Comment by whmoorejr** [comment]
Questions answered.  :-)
