### ISSUE TITLE
What to do when Contact Cards disappear?

### ISSUE THREAD

**Issue by whmoorejr** [owntracks/ios#789]
I have one device (bill) that stopped showing the contact cards for all friends.  I double checked the other friend devices... they all are showing contact cards fine.  I thought that maybe if I re-configure the phone, that might do the trick when it re-loads all the friends.  That did not work.  From another device, I re-saved the contact card, now I have that one friend's card (cisa) on my iPhone13.

Is there a short cut way to re-publish all the contact cards?
Any idea why they disapeard and why they didn't populate after re-configuring the phone?

**Comment by jpmens** [comment]
If cards are published with a qos>0 and with a _retained_ flag set, they should not "disappear".  You can check by subscribing from the command line to `owntracks/+/+/info` to see which cards are on the broker.

If you didn't remove the persistence db of Mosquitto, and didn't remove the cards themselves they should still be there, and your device will pick them up when OwnTracks starts.

**Comment by whmoorejr** [comment]
Got it.  I think I know where I messed up.  I was experimenting with the different publish options.... like URLs, and I published a notification message and selected "retain".... Now everytime I opened owntracks I'd get the pop-up notification.... so I went into MQTT Explorer and started deleting all the retained messages.... oops.

This one was totally on me.  I'm still learing the basics of MQTT.
