### ISSUE TITLE
OwnTracks not providing notifications

### ISSUE THREAD

**Issue by dhitchenor** [owntracks/ios#795]
Hi @ckrey 

First  things, first; nice work on the app, I saw the FLOSS weekly talk with @jpmens and I believe his praises were certainly justified.

I've been toying with OwnTracks and Mosquitto, I personally use android which seems to be working fine, however, there is user that uses my infrastructure whom uses the OwnTracks iOS app.
Their issue is that OwnTracks does not provide any notifications; all their other apps do. Notifications, like entering and exiting regions are fairly important to this user.

They are using the latest version of the iOS app, the server runs Mosquitto 2.0.18, (without TLS for now.. for testing), Mosquitto runs dynamic security, and an ACL file, both of which seem to be working fine. Notifications for the OwnTracks app are turned on, in the settings locally on their phone.

What are you're thoughts?

**Comment by ckrey** [comment]
@dhitchenor thanks for reporting
Notifications used to work well for a long time but there seems to be an issue wirh the latest iOS update. Need to investigate.

Would you be so kind the enable the history tab by setting “maxHistory” to a value > zero, e.g. 100

The you can check if the events are not received at all or if just the notifications did not work.

**Comment by jpmens** [comment]
I thought lack of notifications was on my iPhone only (13 mini, iOS 17.4.1)...

History is enabled here, and you'll recognize this last notification I got:

```
07.06.24 22:42:49  XX enters SP34
```

**Comment by jpmens** [comment]
and of course (how could it be different with computers), moments after writing the above, I see

![rabbit-11046](https://github.com/owntracks/ios/assets/60706/a6648827-bcce-4afe-af59-6b20248fbcde)

**Comment by ckrey** [comment]
But the latter is Pushover, not OwnTracks

**Comment by jpmens** [comment]
The icon is blue; is there a difference? 🤦 
Sorry for the noise.

**Comment by jpmens** [comment]
![image](https://github.com/owntracks/ios/assets/60706/e2f3cbb4-3248-4abf-9b85-3168d58f13b7)

Here's one.

**Comment by dhitchenor** [comment]
> I thought lack of notifications was on my iPhone only (13 mini, iOS 17.4.1)...
> 
> History is enabled here, and you'll recognize this last notification I got:
> 
> ```
> 07.06.24 22:42:49  XX enters SP34
> ```

Hi @jpmens,
I appreciate your reply; its good to know that this isn't a localised issue.


> @dhitchenor thanks for reporting Notifications used to work well for a long time but there seems to be an issue wirh the latest iOS update. Need to investigate.
> 
> Would you be so kind the enable the history tab by setting “maxHistory” to a value > zero, e.g. 100
> 
> The you can check if the events are not received at all or if just the notifications did not work.

Hi @ckrey,

I'll update you, once I've had the opportunity to follow your instructions.

**Comment by dhitchenor** [comment]
Hi @ckrey,

We've turned on history, the history tab appeared.

It remains blank, and we've been moving in and out of a region.

I'll check the logs soon.

**Comment by ckrey** [comment]
iOS does not detect your regions, probably because you specified a radius which is too small. Region detection usually works well with a radius of 50 or 100 meters

**Comment by ckrey** [comment]
When you enter or exit a region, please check on the regions tab if the color of the region changes from blue (cold=outside) to red (hot=inside) accordingly. When the color changes, iOS has detected the transition

**Comment by dhitchenor** [comment]
Ahh I see. Thank you for the reply, @ckrey.

The user and I, have identical regions on our android and iOS devices (respectively), and it seems to work fairly well on the android device; the ranges are between ~10 - ~20 metres, as you are most likely aware.

Not to 'nitpick' here, but a radius of ~50+ metres is much too large. Almost unreasonable (IMO), especially for users within a major city.

> When you enter or exit a region, please check on the regions tab if the color of the region changes from blue (cold=outside) to red (hot=inside) accordingly. When the color changes, iOS has detected the transition

As requested though, I'll double check the colour of the regions, when the user is available, and get back to you.

**Comment by ckrey** [comment]
Thanks for checking the region colors. For detection in Background we rely on the algorithms implemented in iOS. It is not documented, but from experience they seem to use the distance between the center of the region and the reported location plus the accuracy of the location.
In your example I see accuracies of 5 m (best) to 16 meters.

**Comment by dhitchenor** [comment]
We've done some testing with the regions, and the colours, and they work as you describe. That seems to be working well.

Would you like me to check anything else?

**Comment by ckrey** [comment]
Thanks. 
Can you confirm that notifications are send and recorded in history when you see the colors change. Those 3 things should go together or none of them because they all depend on the region enter/leave detection.

**Comment by dhitchenor** [comment]
Definitely confirmed. The history has always been and remains accurate. I've checked it, personally

**Comment by dhitchenor** [comment]
Hi @ckrey, how is it going? Did you end up finding the root of the issue?

**Comment by ckrey** [comment]
@dhitchenor unfortunately not yet

one more clarifcation: Are you missing the notifications of the iPhone itself entering/leaving regions, or the notifications about other mobile phones entering/leaving regions?

**Comment by dhitchenor** [comment]
hi @ckrey,

Notifications do not appear for anything, (almost) at all..
the history within the app is fine, but getting notifications from OwnTracks, in general, seems impossible on iOS, given the current circumstance.

On an unfortunate, but related point, that user has actually stopped using OwnTracks due to this issue, so I won't be able to provide you any further testing/information, regarding iOS.

My apologies @ckrey.. I appreciate your insight, nonetheless


I hope this finds you well

**Comment by ckrey** [comment]
Cannot reproduce here. Region detection and Notifications work well when app is not swiped out, location authorization is given „always“ and Notifications are not limited by user (Focus mode, etc.)
Notification of other users entering regions is by design only given next when app connects to backend the next time.

**Comment by jpmens** [comment]
I was also going to add: @dhitchenor are you quite sure the user isn't swiping out (up) the OwnTracks app? Some users wrongly believe the fairy tale that swiping out apps saves memory or whatnot, and doing that on OwnTracks obviously means it's then not there for a while which could well describe the behaviour you are seeing.

**Comment by dhitchenor** [comment]
Hi @jpmens,
Thank you for your reply, however as I mentioned earllier, they have since moved on; so (to be absolutely honest) I couldn't say for sure.
