### ISSUE TITLE
OwnTracks iOS app not detecting leaving region

### ISSUE THREAD

**Issue by mattogodoy** [owntracks/ios#796]
Hi folks!

First of all, thank you for this awesome project. I'm trying to de-google as much as possible, and this is by far the best open-source alternative to Google Timeline.

I'm having a strange issue: I have the latest version of OwnTracks for iOS installed and I've created a POI for my home with the name `Home|0|2`. This is because I want the mode to be **Manual** when I'm at home, and change it to **Move** when I go out.
What happens is that leaving the region is not detected, the mode is never changed and of course I don't get the notification. If I manually open the app, everything starts working as expected, and it detects that I left the region, changes the mode and shows the notification.
The strange part is that when I get back home, it does change automatically! So it detects entering the region, but not leaving it.

I have an iPhone 15 Pro Max, with iOS 17.5.1. The app has location permissions set to "Always".

Maybe I have something wrong in my configuration? Any hints?
Thanks!

**Comment by ckrey** [comment]
Sorry, switching back to Move mode does not work reliably in Background. Still the detection of leaving the region should work.

You may try to `Home|1|2`, which has the same battery saving effect and should not generate any updates while at home.

**Comment by mattogodoy** [comment]
Thanks for your reply! I did try `Home|1|2` just in case, but unfortunately I get the same results.

I will try creating an Apple Shortcuts automation that changes the modes when I leave and return to home as a temporary solution. Something like:
![telegram-cloud-photo-size-4-5996886407194460991-y](https://github.com/owntracks/ios/assets/1627178/b9cba45d-643f-4922-8456-fb53388ac4fe)

I'll report back with the results :)

**Comment by mattogodoy** [comment]
After some testing, I can confirm that this approach works very reliably 🎉 

The only issue I've noticed is that the "Move" mode is only accurate if I'm in my car using some map navigation app. It greatly reduces accuracy otherwise. Is it possible to always have great accuracy without having a Maps app running in the background? I don't care much about battery life because I usually have more than enough.

**Comment by ckrey** [comment]
Thanks for testing.

What you experience is that the app does not successfully switches back to move move automatically. It does happen the next time you open the app.
Until then, the app remains in "Significant Changes" mode. In this mode the app profits from other apps (e.g. navigation) requesting higher frequency location updates.

I tried more than once how to make the app perform the switch, but without success...

**Comment by mattogodoy** [comment]
This is very useful information. I'm closing the issue now.
Thank you!
