### ISSUE TITLE
location history

### ISSUE THREAD

**Issue by rithask** [owntracks/ios#798]
previously the iOS app used to show the history of locations i visited but it stopped for some reason. how do i get it working again? 

i've set the mode to 'Significant'

![image](https://github.com/owntracks/ios/assets/74851056/47a3f4cd-7e95-4f70-a2e8-aa87ff5161f5)

**Comment by ckrey** [comment]
I guess you mean the history of enter/leave events to regions, which you can access with the rightmost tab "History" on your screen.

Please check if your regions are still defined on the "Regions" tab.

Did you accidentally change the "ignoreInaccurateLocation" value to 100?. The default is zero, or typically 2000 (meters) to filter out bad location data

**Comment by rithask** [comment]
no, that's working perfectly.

what i meant was, the map in the iOS app used to show the locations I've visited by drawing a line on the map. it's not showing anymore.

is 2000 the recommended value? the readings went crazy one day. so, I set it to 100

**Comment by ckrey** [comment]
It stills draws a line on the map when you select a device on the map. The line disappears when you unselect a device (click somewhere else on the map) or when a new location is added. OwnTracks stores the last "positions" (1000 in your case) locations.

If 100  works well for you in "ignoreInaccurateLocation", that's fine. If this value is small it may cause no locations to be published/recorded when you are in an area with poor GPS quality (indoors, tunnel, etc.)

**Comment by rithask** [comment]
oh, so that's how it works. thanks.

another thing i want to ask is, does owntracks respect 'locatorDisplacement' and 'locatorInterval' when the mode is set to 'Significant'?

**Comment by ckrey** [comment]
No, `locatorDisplacement` and `locatorInterval` are only used in `Move` mode.

**Comment by rithask** [comment]
great. thanks for the help.

**Comment by rithask** [comment]
great. thanks for the help.
