### ISSUE TITLE
Friend not shown in iOS app, running in HTTP mode

### ISSUE THREAD

**Issue by SathyaBhat** [owntracks/ios#799]
Hi,

I'm running owntracks on my NAS, with the clients connecting to the recorder in HTTP mode. Me & My wife talk to the same http endpoint for owntracks, but the iOS Apps on our phones cannot find each other. 

I've manually setup Friends per https://github.com/owntracks/recorder/issues/297#issuecomment-477470597 and the dump shows 

```
/ # ocat --dump=friends
sathyasdevice ["sathya/sathyasdevice", "jo/josdevice"]
```
I also have owntracks frontend installed, which however, correctly shows each other on the map. Any ideas on we can't find each other on the iOS app?

**Comment by SathyaBhat** [comment]
Ooh went back to the source and read it correctly

https://github.com/owntracks/recorder?tab=readme-ov-file#friends

modified the file to 

```
jo-josdevice ["sathya/sathyasdevice"]
sathya-sathyasdevice["jo/josdevice "]
```

load the file

```
ocat --load=friends < friends-sathya
```

published on each device, and now we can see each other. thanks for being the 🦆

**Comment by jpmens** [comment]
I was just going to respond in kind. Glad you got it sorted.

**Comment by SathyaBhat** [comment]
Thank you :)
