### ISSUE TITLE
Deprecation: macOS app 

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#801]
The installs of the macOS app are less than 1% of the total installs.
On modern Macs with Apple Silicon, the iOS version can be installed natively. At the time of Intel Macs a specific version was necessary.
If nobody objects or can convince us we will deprecate the Mac version

**Comment by jpmens** [comment]
I think I was one of its few users, and since quite a while I've not been installing it as I've an M1. 
As far as I'm concerned, we can remove it.

**Comment by ckrey** [comment]
17.3.1 was the last version for macOS (Catalyst)
