### ISSUE TITLE
Suggestion: rename "Publish" in Settings

### ISSUE THREAD

**Issue by jpmens** [owntracks/ios#803]
The "Publish" knob in Settings is causing confusion: we've just had the second user this week assume that it publishes location. ([Here](https://github.com/owntracks/docker-recorder/issues/83) and [here](https://github.com/owntracks/recorder/issues/481)).

![rabbit-11202](https://github.com/user-attachments/assets/06615497-9ee9-48b3-9d5f-972ac98ab2b0)

I suggest we rename it, the question is: what to?

Would either of these fit in the UI?

- Send status
- Give report
- Don't touch everthing explodes
an icon along the lines of 

![rabbit-11203](https://github.com/user-attachments/assets/219e6878-5783-4be0-9038-85a2017614db)

**Comment by whalecoiner** [comment]
As one of those users in question: I would gratefully request something that makes it clear what it does. If it sends debug info then "Publish device debug data".

**Comment by ckrey** [comment]
I am convinced that PUBLISH on the status screen might be misunderstood

<img width="359" alt="Bildschirmfoto 2024-08-02 um 16 59 28" src="https://github.com/user-attachments/assets/8d5d9e77-9dfb-4cc3-beb3-66aaf2e2fa48">

**Comment by jpmens** [comment]
`Send Debug Status` is good, and clearly implements what @whalecoiner suggested!

**Comment by ckrey** [comment]
Available in version 18.0.1
