### ISSUE TITLE
OwnTracks does not respond to command from Shortcuts to change mode

### ISSUE THREAD

**Issue by jbrepogmailcom** [owntracks/ios#804]
Hello. From what I found on internet, the app can get killed by iOS when running in background, after some time. It is then woken up by iOS when significant move is detected.

I have set up automation that when I connect the phone to charger, it switches from Significant mode to Move mode. But it almost never works. I think it is because the app gets killed by iOS and then it does not respond directive from Shortcuts to change mode, because it is not running. My understanding is that it is only possible to send command to apps by Shortcuts when these apps or are in background. Sending command by Shortcuts does not wake the app if it is not in background.

Can you advise how to activate Move mode by automation if OwnTracks is in background for long time and therefore may have been killed by iOS? Thanks very much, Jan

**Comment by ckrey** [comment]
it does not work! Correctly observed

**Comment by jbrepogmailcom** [comment]
Thanks for quick response on all my comments, your are great!
