### ISSUE TITLE
Bye bye OwnTracksToday widget (Deprecated API)

### ISSUE THREAD

**Issue by ckrey** [owntracks/ios#812]
9 years ago (2015) we implemented a Today widget for OwnTracks. The widget could be added to the today widget display on request and implemented the following functions:

- Display icon name, distance, address and last update of selected friends
- Display and change the monitoring mode (move, significant, ...)

The API for today widgets was deprecated in iOS with iOS 14, but was still available.
With iOS 17.4 and iOS 18, the depecrated API is now ignored. Thus we will remove the code.

We never documented the feature in the booklet and we assume not a lot of users have actually activated it (based on no comments or issues received).

![Simulator Screenshot - iPhone SE 17 0 - 2024-09-17 at 09 03 22](https://github.com/user-attachments/assets/eeef07f9-7e83-4fa0-9919-0ca30215b9bc)

<img width="364" alt="Bildschirmfoto 2024-09-17 um 09 05 20" src="https://github.com/user-attachments/assets/3e3cdfed-9ba2-4149-a146-7468e50ce82b">

**Comment by ckrey** [comment]
https://9to5mac.com/2024/07/23/psa-ios-18-is-going-to-disable-your-old-today-view-widgets/

**Comment by jpmens** [comment]
It's sad to see all the effort you put into it wasted, but I agree: hardly anybody used it (I didn't either!)

**Comment by ckrey** [comment]
Removed in version 18.0.1
