### ISSUE TITLE
iBeacon Region Not Posting Updates to MQTT

### ISSUE THREAD

**Issue by jamesgoodhouse** [owntracks/ios#820]
I'm having zero luck getting iBeacons and regions working with Owntracks on my iPhone. Here's the gist:

* I have multiple [FeasyBeacon iBeacons](https://www.feasycom.net/beacon/usb-beacon/bluetooth-beacon-usb-ble-4-0.html) at my home with the same UUID
* I have a region configured in Owntracks with a radius of `0` and the same UUID as configured for the iBeacons
* In the settings for Owntracks i have `ranging` enabled
* I have Owntracks configured `Location` setting in iOS set to `Always`

What else am I missing? When I create the new region I see a new topic type `waypoint`, but I do not see any information sent along with the `location` topic type for my phone, nor any transition events. I'm testing this by plugging and unplugging the USB iBeacon with next to where the phone is. I've also tried a complete wipe of Owntracks and re-install with no luck.

Owntracks Version: `18.0.4/en_US`
iOS Version: `17.6.1`

**Comment by jamesgoodhouse** [comment]
Argh. So apparently the UUID **_MUST_** fit the following format: `XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX`.

**Comment by ckrey** [comment]
Glad you got it working. Do you have a retail quantity source for FeasyBeacon iBeacons ?

**Comment by jpmens** [comment]
![rabbit-11400](https://github.com/user-attachments/assets/dd01d333-de2a-4ebd-961a-2d64d7883c83)
