### ISSUE TITLE
Owntracks ios address resolver disabled

### ISSUE THREAD

**Issue by Raffypoipoi** [owntracks/ios#825]
Hi
Any suggestion to solve question about address resolver disabled? 
here mqtt perfectly connetted and tested
Thanks in advance
Regards 
Raffaele

**Comment by Raffypoipoi** [comment]
I got tat type of error (address resolver disabled) so owntracks dors not update location and in conseguence i cannot have my automation in homeassistant!ThanksInviato da iPhoneIl giorno 29 nov 2024, alle ore 19:30, Jan-Piet Mens ***@***.***> ha scritto:﻿
what's your question?

**Comment by jpmens** [comment]
![image](https://github.com/user-attachments/assets/1fb9079c-d1ad-42b0-9744-e6e98120d819)

Tap on the map symbol and answer yes to both questions

**Comment by Raffypoipoi** [comment]
Many thanks SirJust solved the caseBest regardsRaffaele Inviato da iPhoneIl giorno 30 nov 2024, alle ore 00:04, Jan-Piet Mens ***@***.***> ha scritto:﻿
3889A648-C6F1-4AAE-89CA-C8B6E7C2B2E4.jpeg (view on web)
Tap on the map symbol and answer yes to both questions
