### ISSUE TITLE
trying to use address book with friends crashes

### ISSUE THREAD

**Issue by brunkj** [owntracks/ios#92]
For the last few versions I have been unable to get the address book feature to work.  The moment I hit the address book icon the app dies.

**Comment by jpmens** [comment]
@brunkj have you been able to resolve this using local address book?

**Comment by brunkj** [comment]
Without being able to tell it to use local address book only I have 
not.  As soon as I click the address book icon on a friend it crashes.  
So i don't even get to tell it what address book to use.


On 1/10/15 7:44 AM, JP Mens wrote:
>
> @brunkj <https://github.com/brunkj> have you been able to resolve this 
> using local address book?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/owntracks/ios/issues/92#issuecomment-69454566>.
>

-- 

Jason Brunk
jason.brunk@gmail.com

**Comment by ckrey** [comment]
duplicate #115
